qgis/QGIS-Documentation

source/docs/pyqgis_developer_cookbook/composer.rst
=> Adds how to export atlas using PyQGIS

source/docs/user_manual/processing/scripts.rst
Move some comments out of the code.  Fixes #3894.
Goal:
Ticket: #3894
=> Move some comments out of the code in processing script chapter

source/docs/pyqgis_developer_cookbook/composer.rst
* Adds how to export atlas using PyQGIS
* Fix build and add suggestions from review
Goal:
Ticket: #
=> Adds how to export atlas using PyQGIS (#3974) Backport to 3.4

source/docs/pyqgis_developer_cookbook/composer.rst
=> Fix export settings class for image outputs

source/docs/user_manual/working_with_vector/attribute_table.rst
Users shall be able to browse through the feature list in form view and highlight a feature as well as zoom to the feature.
Goal: Precise information about using the new functions of the attribute table form view
Ticket: #3746 
Ticket: #9992
=> description of the new toolbar in the attribute table

source/docs/developers_guide/codingstandards.rst, source/docs/developers_guide/git.rst, source/docs/developers_guide/ogcconformancetesting.rst, source/docs/developers_guide/unittesting.rst
Include the diff texts from the [dev guidelines on QGIS-website](https://qgis.org/en/site/getinvolved/development/qgisdevelopersguide/index.html)
Hope that i caught them all.
Ticket: refs #1566 and https://github.com/qgis/QGIS-Website/pull/406
=> Update the developers guidelines

source/docs/documentation_guidelines/writing.rst
=> Misc changes to screenshots guidelines

source/docs/pyqgis_developer_cookbook/authentication.rst
Removed two duplicated brackets from a code example.
Goal:
Ticket: #
=> Update minor typos

source/docs/developers_guide/git.rst, source/docs/developers_guide/ogcconformancetesting.rst, source/docs/documentation_guidelines/writing.rst, source/docs/pyqgis_developer_cookbook/intro.rst, source/docs/pyqgis_developer_cookbook/plugins/plugins.rst, source/docs/training_manual/create_vector_data/forms.rst, source/docs/training_manual/database_concepts/data_model.rst, source/docs/training_manual/qgis_server/install.rst, source/docs/training_manual/spatial_databases/spatial_functions.rst, source/docs/user_manual/working_with_gps/live_GPS_tracking.rst, source/docs/user_manual/working_with_ogc/server/getting_started.rst, source/docs/user_manual/working_with_ogc/server/plugins.rst
=> Replace apt-get with apt

source/docs/user_manual/processing_algs/qgis/networkanalysis.rst
=> Fix travel cost units for service area algorithms

source/docs/training_manual/qgis_plugins/fetching_plugins.rst, source/docs/training_manual/qgis_plugins/plugin_examples.rst
and fix some description
Ticket: #
=> [TM] Move the "Install plugins" lesson to numbered list 

source/docs/user_manual/processing/history.rst
I'm not really satisfied with this description. Something I don't know is if this feature is only intended to feed the QGIS project or if it can be used as test framework by the user for his own algorithms (more interesting for the user - I know it sounds a bit selfish but what do you want...). If someone can shed some light or help to improve the description(not sure the process is clear enough to people not used to do PR)... @m-kuhn @luipir @nyalldawson ?
Ticket: #
=> Add information on Processing test creation from history tab

source/docs/documentation_guidelines/writing.rst, source/docs/pyqgis_developer_cookbook/cheat_sheet.rst
=> Adding an example about running a Processing algorithm

source/docs/developers_guide/index.rst
The proposed sequencing is:
1. learn our coding styles and HIG,
2. learn how to checkout the source code,
3. learn how to build the application (with qtcreator),
4. and then learn how to create tests (desktop then server)
Goal:
Ticket: #
=> [dev_guides] Order developer's guide table of content

source/docs/developers_guide/unittesting.rst
I think this chapter is a bit old (it mentions as **recent** an issue report that is 10 years old) and it could be nice that devs go through it again to ensure that it describes the current process and gives up-to-date information.
Here, I only focus on formatting, line length, initializing toc (i think it would deserve to be split in more easily identifiable sections) and some obvious changes.
Also move from 'I' to 'we', imho more inclusive since this is a community material
=> [dev_guides] Initial review of the unit test creation guidelines

source/docs/user_manual/print_composer/composer_items/composer_label.rst
and reduce the indentation for a better rendering in html
Goal:
Ticket: #
=> Better explain the expression purpose

source/docs/pyqgis_developer_cookbook/cheat_sheet.rst
We started a new section for snnipets "Composer" section.
Goal:
Ticket: #
=> Start new Composer section 

source/docs/pyqgis_developer_cookbook/index.rst, source/docs/pyqgis_developer_cookbook/legend.rst
Adds an entire new section of `QgsLayerTreeLayer` & co on how to manage the TOC with pyqgis. Inspired by @wonder-sk: I put references in the chapter to the original material, but I'd like to have your bless here :)
=> pyqgis add TOC managing

source/docs/pyqgis_developer_cookbook/vector.rst
Goal: The code example for creating custom renderers did not work anymore because it used the old style `connect`-mechanism and did not take into account the thread checks present in current QGIS debug versions. This PR updates the code to work with current versions of QGIS. It also fixes an error in the logic by adding a second symbol. Before, all features were drawn with the same symbol.
Ticket: fix #4079
=> Fixes #4079: Update the "Creating Custom Renderers" example

source/docs/user_manual/introduction/project_files.rst
=> Add automatic changes from the find_set_subst.py script

source/docs/training_manual/forestry/map_georeferencing.rst
Correct "georeferentiate".
Goal:
Ticket: #
=> Update map_georeferencing.rst (georeferentiate)

source/docs/training_manual/forestry/map_georeferencing.rst
Update wording based on input from Jared Morgan (save control points).
Goal:
Ticket: #
=> Update map_georeferencing.rst (save control point - wording)

source/docs/training_manual/forestry/map_georeferencing.rst
Updating the text in "In conclusion".  Based on input from Jared Morgan.
Goal:
Ticket: #
=> Update map_georeferencing.rst (in conclusion)

source/docs/user_manual/processing_algs/qgis/database.rst
https://docs.qgis.org/3.4/en/docs/user_manual/processing_algs/qgis/database.html#id3
Ticket: #
=> Fix parameter description indentation

readme.rst
Page https://github.com/qgis/QGIS-Documentation/blob/master/readme.rst#qgis-documentation
Some sections were not shown in the TOC at the top of the page.
Also remove outdated list of contributors and structure of community team at 
New TOC would be
Goal:
Ticket: #
=> Update the readme structure

themes/qgis-theme/languageswitch.html, themes/qgis-theme/page.html
Months that I'm getting insane due to the translation "fix me" button never bring me to the correct page while everything **seemed** OK. Joyful, joyful...
Ticket: fixes #3558
=> Fix me transifex

themes/qgis-theme/languageswitch.html, themes/qgis-theme/page.html
For the posterity and in order to close #3558
Ticket: #
=> Fix me transifex master

source/docs/user_manual/working_with_ogc/ogc_client_support.rst
=> :guilabel: does not display menu arrow

source/docs/user_manual/processing_algs/qgis/vectorselection.rst
showing that each "extract by..." algorithm has its "select by..." alter ego
Ticket: #
=> Add links between "select by" and "extract by" algorithms

themes/qgis-theme/languageswitch.html
=> Fix page generation for Transifex

source/docs/user_manual/processing_algs/qgis/vectortable.rst
=> Add "Extract binary field" algorithm

source/docs/user_manual/processing_algs/qgis/vectorgeneral.rst
=> Split vector does not output a folder

source/docs/user_manual/working_with_vector/vector_properties.rst
=> Alias are not editable in the Source Fields tab

source/docs/user_manual/preamble/contributors.rst
This PR is simply add me as the author of the PyQGIS cheat sheet,in short, author of a section
Regarding the translations, I have been translating QGIS desktop to Spanish as well as the QGIS documentation and website in my free time. My transifex profile is All4Gis.
Goal:
Ticket: #
=> Added myself as a contributor

source/docs/user_manual/processing/scripts.rst
=> Fix typo and blank lines

source/docs/user_manual/processing/scripts.rst
=> Fix typos and trailing spaces

source/docs/user_manual/processing_algs/qgis/qgis_algs_include.rst, source/docs/user_manual/processing_algs/qgis/vectorselection.rst
algorithm, using an include file to avoid duplication
Goal:
Ticket: #
=> Apply the geometric predicates description to extract by location

source/docs/user_manual/working_with_vector/expression.rst
I wish these were picked by beginners at the hackfest but... let's reduce issues queue
Fixes #3902, fix #3703, fix #3662, fix #3647, fix #3375, fix #3338, fix #3279, fix #3266, fix #3134
Most of the new functions are tagged with their release number so don't trust the diff size (mainly due to the table formatting)
=> Add new functions and groups to lists

source/docs/documentation_guidelines/writing.rst
and remove some statements that i'm not sure are relevant today
Ticket: #
=> No, not only Ubuntu is allowed for screenshots

readme.rst
with setting code language (for result, see https://github.com/DelazJ/QGIS-Documentation/tree/readmeCodeSample#qgis-documentation)
Goal:
Ticket(s): #
=> Add a bit of coloring and legibility to code samples in readme

source/conf.py, source/docs/developers_guide/codingstandards.rst, source/docs/developers_guide/ogcconformancetesting.rst, source/docs/developers_guide/processingtesting.rst, source/docs/documentation_guidelines/substitutions.rst, source/docs/pyqgis_developer_cookbook/authentication.rst, source/docs/pyqgis_developer_cookbook/cheat_sheet.rst, source/docs/pyqgis_developer_cookbook/geometry.rst, source/docs/pyqgis_developer_cookbook/intro.rst, source/docs/pyqgis_developer_cookbook/network_analysis.rst, source/docs/pyqgis_developer_cookbook/processing.rst, source/docs/pyqgis_developer_cookbook/server.rst, source/docs/user_manual/plugins/python_console.rst, source/docs/user_manual/processing/history.rst, source/docs/user_manual/processing/scripts.rst
Manual application of #4238 to 3.4
=>  Keep our external links synced with the doc release

source/docs/pyqgis_developer_cookbook/cheat_sheet.rst, source/docs/user_manual/processing/console.rst, source/docs/user_manual/processing/scripts.rst
Goal: use qgis namespace to import processing
Ticket: #3600
=> use qgis namespace to import processing fix #3600

source/docs/pyqgis_developer_cookbook/expressions.rst
I add explanation to the code
Goal:
Ticket(s): #3895 
Part of the training in FOSS4G UK with @nickbearman
=> updating basic code sample for expression #3895

source/docs/user_manual/working_with_vector/expression.rst
fix #4173
Goal: add expression function in documentation
Ticket(s): #4173
=> added "collect_geometry" expression function

readme.rst
This is a minor spelling checker fix of the README file.
=> Minor fixes detected on README by english spell checker

source/docs/documentation_guidelines/first_contribution.rst
Because the code sample can not be automatically synced with current version, it looks confusing. Better remove it and rely on a more generic description.
Also add details and more comments
Goal:
Ticket(s): #
=> Update git instructions for contribution

source/conf.py, themes/qgis-theme/layout.html, themes/qgis-theme/page.html, themes/qgis-theme/static/qgis-style.css, themes/qgis-theme/static/qgis-style.less
It's outdated. So long. And thanks for all the fish.
=> Backport 4274 to release 2.18

readme.rst
and since it's sexier than the live... let's reuse it
Still no PDF though
=> The old documentation link is working again

source/docs/user_manual/processing_algs/taudem/specialized_grid_analysis_tools.rst, source/docs/user_manual/processing_algs/taudem/stream_network_analysis_tools.rst
I fixed some mistakes and hope this time I'm the right way
Goal:
Ticket(s): #
=> Fixed some mistakes

source/docs/developers_guide/git.rst, source/docs/developers_guide/unittesting.rst, source/docs/documentation_guidelines/do_translations.rst, source/docs/gentle_gis_introduction/vector_data.rst, source/docs/user_manual/introduction/qgis_configuration.rst, source/docs/user_manual/processing_algs/taudem/stream_network_analysis_tools.rst, source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst
=> Some spell fixes

readme.rst
Goal:
To describe how to build locally the QGIS documentation (html) in Windows. 
The idea is to test this minimum setting to guide Windows users and hopefully gain more documenters
=> Building windows

source/docs/user_manual/processing_algs/qgis/cartography.rst
Fixes #3971, fixes #3969, fixes #3964, fixes #3566
=> Add some cartography algorithms

source/docs/pyqgis_developer_cookbook/vector.rst
Move the shapefile comment next to the code sample and fix language highlighting error due to encoding error
backports #4320
=> Improve vector creation file in Cookbook

source/docs/user_manual/working_with_vector/style_library.rst
=> Mention SVG version requirement

source/docs/training_manual/processing/more_backends.rst
Fixes #4326
Goal:
Ticket(s): #4326
=> Update the description of the R processing provider

source/docs/pyqgis_developer_cookbook/cheat_sheet.rst
Updating the example to find groups and nodes to work with nested groups. The proposed change uses a recursive function to get all child groups.
=> Update advanced TOC section to work with nested groups

source/docs/pyqgis_developer_cookbook/processing.rst
Goal:
Trying myself to follow these steps for creating a processing plugin, I needed to do this small change for my plugin to be able to find the Provider class.
Not sure if this is the correct way to do it but... I decided to start this PR to discuss it and fix whatever is necessary.
Great work by @Gustry by the way!
Ticket(s): #
=> Fixes processing example

source/docs/user_manual/style_library/symbol_selector.rst, source/docs/user_manual/working_with_vector/expression.rst
Ticket(s): #4173 (follow-up #4271 )
=> Add details for the collect_geometries function

source/docs/user_manual/print_composer/composer_items/composer_image.rst, source/docs/user_manual/print_composer/overview_composer.rst
=> Add details on Layout North arrow button

source/docs/user_manual/print_composer/create_output.rst
This is a proposal for the description of the Javascript setFeature function which includes a full unstructured GeoJSON object.
In the GeoJSON object we work with parent and child features from the project defined relations and create a HTML object.
During atlas creation QGIS iterates over the parent features and builds a bullet list of the related child features.
Goal:
Ticket: #
- [x ] Backport to LTR documentation is required
=> section about atlas setFeature function

source/docs/user_manual/working_with_vector/vector_properties.rst
from https://github.com/qgis/QGIS/pull/32015
=> Vector layer properties -> init form python function -> allow URL

source/docs/user_manual/working_with_vector/vector_properties.rst
=> Fix terminology

source/docs/user_manual/processing_algs/qgis/rasteranalysis.rst
Documenting algorithms "Raster Surface volume" and "Raster layer zonal statistics" 
Fix #3294, Fix #3383
=> Fixing need docs #3294 and #3383

source/docs/user_manual/working_with_ogc/server/services.rst
=> Server OAPIF: add datetime and properties docs

source/docs/user_manual/managing_data_source/opening_data.rst
=> Add tip on MSSQL features selection

source/docs/user_manual/processing/modeler.rst
Fixes: #3424
Goal:
Ticket(s): #
=> Add information about exporting models to processing algorithms

source/docs/user_manual/processing_algs/qgis/vectorgeneral.rst
Fixes: #3438
Goal:
Ticket(s): #
=> Updating the description of the "find projection" algorithm

source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
Fixes #3135.
Goal:
Ticket(s): #
=> Add "force right hand rule for polygon" algorithm

source/docs/user_manual/processing_algs/gdal/rastermiscellaneous.rst
Fixes: #3388.
Also updated according to #2745.
Goal:
Ticket(s): #
=> Add missing srcnodata to the build virtual raster algorithm

source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
Fixes  #3218.
Goal:
Ticket(s): #
=> Add description of the "Split lines by maximum length" algorithm

source/docs/user_manual/processing_algs/qgis/vectorselection.rst
Fixes #3116. Fixes #3253.  Input and output described according to #2745.
Goal:
Ticket(s): #
=> Add description of the "Delete duplicates by attribute" algorithm

source/docs/user_manual/processing_algs/qgis/vectorgeneral.rst
Fixes #3637.
Goal:
Ticket(s): #
=> Add description of the "Join attributes by nearest" algorithm

source/docs/user_manual/processing_algs/qgis/vectoroverlay.rst
See #3767. The figures have not yet been updated.
Goal:
Ticket(s): #
=> Optional prefix in overlay algorithms - update

source/docs/user_manual/processing_algs/qgis/vectortable.rst
Fixes: #3577
Goal:
Ticket(s): #
=> Add description of the native "Add X/Y fields to layer" algorithm

source/docs/user_manual/processing_algs/qgis/vectoranalysis.rst
Fixes:  #3736
Goal:
Ticket(s): #
=> Add description of the "Overlap analysis" algorithm

source/docs/user_manual/processing_algs/gdal/vectorgeoprocessing.rst
Backport of #4412 to 3.4
Goal:
Ticket(s): #
=> Update vectorgeoprocessing.rst (backport to 3.4)

source/docs/user_manual/processing_algs/qgis/vectortable.rst
Fixes: #2533.  Using the suggested table format for the parameters.
Goal:
Ticket(s): #
=> Add description of the Feature filter algorithm

source/docs/user_manual/processing_algs/qgis/vectortable.rst
See  #4408.
Goal:
Ticket(s): #
=> Add description of the Feature filter algorithm  (backport to 3.4)

source/docs/user_manual/appendices/appendices.rst, source/docs/user_manual/managing_data_source/opening_data.rst
=> Update QLR documentation according to review

source/docs/user_manual/processing_algs/qgis/vectoranalysis.rst
To prepare for updating the processing algorithm example in the document writer docs.
On the table format: #2770
Goal:
Ticket(s): #
=> Update the points in polygons with table format for the parameters

source/docs/training_manual/create_vector_data/create_new_vector.rst, source/docs/training_manual/create_vector_data/topo_editing.rst, source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst
=> Rename "node tool" to "vertex tool" in the training manual

source/docs/training_manual/create_vector_data/topo_editing.rst, source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst
Backport of #4433
Goal:
Ticket(s): #2400
=> Rename "node tool" to "vertex tool" in the training manual (backport to 3.4)

source/docs/user_manual/introduction/project_files.rst, source/docs/user_manual/print_composer/create_output.rst
Goal:
Ticket(s): 
Fixes: #1892
Fixes: #3241
Fixes: #4083
Fixes: #4084
Fixes: #4092
Fixes: #4093
Fixes: #4096
Fixes: #4099
Fixes: #4104
Fixes: #4105
Fixes: #4112
=> Manual backport of #4437 (GeoPDF export) to 3.4

source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
Goal: see bug fix at https://github.com/qgis/QGIS/pull/32945
Ticket(s): #
=> Fix wording

source/docs/user_manual/processing_algs/qgis/vectoranalysis.rst
See #2770 and #4429.
Goal:
Ticket(s): #
=> Reformat to use tables for parameter description - vector analysis

source/docs/user_manual/processing_algs/qgis/vectoranalysis.rst
Backport of #4428 to 3.4
Goal:
Ticket(s): #
=> Reformat to use tables for parameter description - vector analysis - Backport to 3.4

source/docs/user_manual/processing_algs/gdal/rasteranalysis.rst, source/docs/user_manual/processing_algs/qgis/cartography.rst, source/docs/user_manual/processing_algs/qgis/database.rst, source/docs/user_manual/processing_algs/qgis/vectoranalysis.rst, source/docs/user_manual/processing_algs/qgis/vectorcreation.rst, source/docs/user_manual/processing_algs/qgis/vectorgeneral.rst, source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst, source/docs/user_manual/processing_algs/qgis/vectoroverlay.rst, source/docs/user_manual/processing_algs/qgis/vectorselection.rst, source/docs/user_manual/processing_algs/taudem/stream_network_analysis_tools.rst
at the end of the alg introduction and put it in a ".. seealso::" directive (as suggested in a previous PR)
=> Place the "see also other algs" section

source/docs/documentation_guidelines/writing.rst
=> Update the writing guidelines with the new table format for QGIS algorithm parameters

source/docs/documentation_guidelines/writing.rst
=> Backport to 3.4 of #4426 (Update the writing guidelines with the new table format for QGIS algorithm parameters)

source/docs/user_manual/processing_algs/qgis/vectorgeneral.rst
=> Fix some seealso placement

source/docs/training_manual/foreword/foreword.rst, source/docs/training_manual/introduction/intro.rst
=> Supplement / reorganise the introduction to the training manual

source/docs/user_manual/processing_algs/gdal/rasterextraction.rst
=> Update the documentation of GDAL algs, raster extraction, to use the proposed table format for parameters

source/docs/user_manual/processing_algs/gdal/rasterextraction.rst
Trivial fixes to the table formatting
Ticket(s): #
=> GDAL raster extraction algs - fix table formatting

source/docs/user_manual/processing_algs/gdal/vectorconversion.rst
Goal: Update the GDAL vector conversion file to use tables for the parameters (#4429).
=> Update the GDAL vector conversion file to use tables for the parameters

source/docs/user_manual/processing_algs/qgis/rastertools.rst, source/docs/user_manual/processing_algs/qgis/vectorgeneral.rst, source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
=> Add more connections between algorithms

source/docs/user_manual/processing_algs/gdal/rasterprojections.rst
=> Update to table format for alg parameters - GDAL raster projection

source/docs/user_manual/processing_algs/gdal/rasterprojections.rst
=> Small fixes for GDAL raster projection algorithms

source/docs/user_manual/processing_algs/gdal/rasterextraction.rst
=> Backport of GDAL raster extraction algorithm to 3.4 (#4461)

source/docs/user_manual/processing_algs/gdal/rastermiscellaneous.rst
Goal:
Ticket(s): #4429 
Fixes: #3763
=> Tables for parameters, GDAL raster misc

source/docs/user_manual/processing_algs/gdal/rastermiscellaneous.rst
Formatting updates
Goal:
Ticket(s): Fixes after review of #4474
=> Table format for parameters - GDAL raster misc - fixes after review in #4474

source/docs/user_manual/processing_algs/gdal/rastermiscellaneous.rst
Goal:
Ticket(s): #4429. Backport of #4474
=> Backport to 3.4 of table format for alg paramters - GDAL raster misc

source/docs/user_manual/processing_algs/qgis/filetools.rst
=> Format alg parameters using tables - QGIS File tools

source/docs/user_manual/processing_algs/qgis/filetools.rst
Goal:
Ticket(s): Backport of #4493. #4429
=> Backport of #4493 (Format alg parameters using tables - QGIS File tools)

source/docs/user_manual/processing_algs/qgis/vectortable.rst
=> Table format for alg parameters - QGIS Vector table

source/docs/user_manual/working_with_vector/expression.rst
=> Add alternative make_line function with an example

source/docs/user_manual/processing_algs/qgis/vectortable.rst
Goal:
Ticket(s): Backport of #4489. #4429.
=> Backport of #4489 (Table format for alg parameters - QGIS Vector table)

source/docs/user_manual/processing_algs/qgis/vectoroverlay.rst
=> Format alg parameters using tables - QGIS Vector overlay

source/docs/user_manual/processing_algs/qgis/vectoroverlay.rst
Goal:
Ticket(s): #4429. Backport of #4491.
=> Backport to 3.4 of #4491 (Format alg parameters using tables - QGIS Vector overlay)

source/docs/user_manual/processing_algs/qgis/vectoroverlay.rst
Goal:
Ticket(s): #4429 (backport of #4491)
=> Backport of #4491 (Format alg parameters using tables - QGIS Vector overlay)

source/docs/user_manual/working_with_vector/vector_properties.rst
using a step-like structure and add some details
ref #4230, ref #4056, Fixes #3334, ref #1896
=> Update the categorized renderer description

source/docs/user_manual/processing_algs/gdal/rasterconversion.rst
=> GDAL Raster conversion algs, table format for parameters

source/docs/pyqgis_developer_cookbook/processing.rst
As a Python noob who has recently need to follow these instructions (thanks to writers), I felt some separation might help beginners.
Mostly indentation changes!
=> Structure the writing Processing plugins instructions as steps

source/docs/user_manual/processing_algs/qgis/rasteranalysis.rst
=> QGIS Raster analysis algs, table format for parameters, 3.4

source/docs/user_manual/processing_algs/qgis/rasteranalysis.rst
Goal:
Ticket(s): #4429. (3.4 version of this: #4504)
=> Tables for parameters - Raster analysis (port of #4504 to master)

readme.rst
And promote the "latest"-based url. Also remove the individual pdf links (already in main pages).
For people who don't know what QGIS is (if any there are) and reach this repository, it could be nice to tell them a bit of it.
=> Introduce QGIS in the readme

source/docs/user_manual/processing_algs/qgis/vectoroverlay.rst
suggestions of reformulation welcome
=> Add details to overlay algorithms

source/docs/user_manual/processing_algs/qgis/rasteranalysis.rst
some cosmetics
Goal:
Ticket(s): #
=> Fix url display

source/docs/user_manual/working_with_vector/vector_properties.rst
to follow the dialog structure and using a step-like introduction
=> Reorganize the Join properties dialog description

source/docs/user_manual/processing_algs/qgis/rastertools.rst
=> QGIS Raster tools algs table for parameters

source/docs/user_manual/processing_algs/qgis/rastertools.rst
Goal:
Ticket(s): #4429    Backport of #4511
=> Backport of #4511(QGIS Raster tools algs table for parameters)

source/docs/user_manual/processing_algs/gdal/rasterconversion.rst
Trying again...
Goal:
Ticket(s): #4429  (#4508)
=> GDAL raster conversion table for alg params update - second attempt

source/docs/user_manual/processing_algs/qgis/vectorselection.rst
=> QGIS Vector selection algs table for parameters - 3.4

source/docs/user_manual/processing_algs/qgis/vectorselection.rst
Porting of #4513 (QGIS Vector selection algs table for parameters) to master.
Goal:
Ticket(s): #4429. Port of #4513 to master.
=> Table for parameters - QGIS Vector selection

source/docs/user_manual/print_composer/create_output.rst
=> "ESRI World File" - explain some more (in print composer - create output)

source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
=> Tables for alg param - QGIS Vector geometry

source/docs/developers_guide/unittesting.rst
@strk your recent comments made me look into this.
=> Add more information for running individual unit tests

source/docs/user_manual/processing_algs/qgis/cartography.rst
=> Table for alg param - QGIS Cartography

source/docs/user_manual/processing_algs/qgis/cartography.rst
Goal:
Ticket(s): #4429 (backport of #4528)
=> Backport of #4528 (Table for alg param - QGIS Cartography)

source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
=> Fix collect geometries (table format for parameters)

source/docs/documentation_guidelines/writing.rst
Goal: Add new parameter types for the documentation of algorithms.
``file`` is for ``QgsProcessingParameterFileDestination``
``matrix`` is for ``QgsProcessingParameterMatrix``
Ticket(s): Fixes: #4505
=> Add parameter types for file, matrix and layer (raster or vector)

source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
=> New algorithms "Extract Z values" and "Extract m values"

source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
Goal:
Ticket(s): #3862, #3863, #4429
=> Create layer from point - fix table format for parameters, and move

source/docs/pyqgis_developer_cookbook/plugins/plugins.rst
=> Some cleanups and updates to the Plugins creation instructions

source/docs/user_manual/introduction/general_tools.rst, source/docs/user_manual/introduction/qgis_configuration.rst
=> Update behavior with project color shortcut entry in DD button

source/docs/gentle_gis_introduction/coordinate_reference_systems.rst
Goal: Just a quick update for some of the wording in the start of the CRS tutorial for clarity.
Ticket(s): #
=> Fix grammar in coordinate_reference_systems intro

source/docs/user_manual/working_with_raster/raster_properties.rst
otherwise we self-reference the section
Goal:
Ticket(s): #
=> Use guilabel instead of ref

source/docs/user_manual/processing_algs/qgis/layertools.rst
=> Tables for algorithm parameters - QGIS Layer tools

source/docs/user_manual/processing_algs/qgis/layertools.rst
Goal:
Ticket(s): Backport of #4546.  #4429.
=> Backport of #4546 (Tables for algorithm parameters - QGIS Layer tools)

source/docs/user_manual/print_composer/composer_items/composer_map.rst
=> Add detail on map item grid

source/docs/user_manual/print_composer/create_output.rst
=> Create output - explaining current behaviour (georeferencing) and some reformatting / cleaning

source/docs/user_manual/introduction/qgis_gui.rst, source/docs/user_manual/print_composer/create_reports.rst, source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst
The first commit is simply a table reformatting, embedded list in a cell is easier to edit in a list-table than in a csv-table
=> Update main menu entries

source/docs/user_manual/working_with_vector/vector_properties.rst
Fix #3468 (but this is mainly a move to steps-like description)
=> Show steps for drag and drop designer

source/docs/user_manual/introduction/general_tools.rst
=> Add symbol widget description

source/docs/user_manual/processing_algs/qgis/database.rst
=> Tables for alg params - QGIS Database

source/docs/user_manual/managing_data_source/opening_data.rst
=> Mesh layer description

source/docs/user_manual/style_library/symbol_selector.rst
=> Move symbol layer properties to its section

source/docs/user_manual/managing_data_source/opening_data.rst
=> Move back the csv anchor next to its section

source/docs/user_manual/processing_algs/qgis/interpolation.rst
=> QGIS Interpolation - Table format for alg params

source/docs/user_manual/processing_algs/qgis/interpolation.rst
Goal:
Ticket(s): #4429, #4556.
=> QGIS Interpolation algs - table for params (cleanup)

source/docs/user_manual/processing_algs/qgis/interpolation.rst
Goal:
Ticket(s): Backport of #4556. #4429.
=> Backport of #4556 (QGIS Interpolation - Table format for alg params)

source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst
=> Fixing some long lines and some language reltated things

source/docs/user_manual/processing_algs/gdal/vectorconversion.rst, source/docs/user_manual/processing_algs/gdal/vectorgeoprocessing.rst, source/docs/user_manual/processing_algs/qgis/modelertools.rst, source/docs/user_manual/processing_algs/qgis/vectoranalysis.rst, source/docs/user_manual/processing_algs/qgis/vectorgeneral.rst, source/docs/user_manual/processing_algs/qgis/vectortable.rst
=> Switching some [vector: any] to [same as input].. but not only

source/docs/user_manual/processing_algs/qgis/vectorcreation.rst
=> Tables for alg params - QGIS vector create

source/docs/user_manual/processing_algs/qgis/vectorcreation.rst
Goal:
Ticket(s): #4429. Backport of #4582.
=> Backport of #4582 (Tables for alg params - QGIS vector create)

source/docs/user_manual/processing_algs/qgis/graphics.rst
=> QGIS vector graphics - tables for algorithm parameters

source/docs/user_manual/processing_algs/qgis/vectoranalysis.rst
=> Add geodesic mode for the "Join by Lines (Hub lines)" algorithm

source/docs/user_manual/processing_algs/qgis/rasterterrainanalysis.rst
=> QGIS Raster terrain analysis - tables for alg params

source/docs/user_manual/processing_algs/qgis/rasterterrainanalysis.rst
Goal:
Ticket(s): #4429.  Backport of #4597
=> Backport to 3.4 of #4597 (QGIS Raster terrain analysis - tables for alg params)

source/docs/user_manual/print_composer/composer_items/composer_scale_bar.rst, source/docs/user_manual/working_with_vector/expression.rst
and an example of use (Fixes #4016)
=> Add scale_value expression

source/docs/user_manual/processing_algs/qgis/qgis_algs_include.rst
to avoid losing them in the future or ensure they are updated accordingly
Goal:
Ticket(s): #
=> Move list of concerned algs comment under the included section

source/docs/user_manual/processing_algs/qgis/networkanalysis.rst
=> Test of include. Separate table before the output table (network advanced parameters)

source/docs/user_manual/processing_algs/qgis/networkanalysis.rst
Goal:
Ticket(s): #4429. Backport of #4594.
=> Backport to 3.4 of #4594 (QGIS Network analysis - tables for alg parameters)

source/docs/user_manual/processing_algs/qgis/qgis_algs_include.rst
Goal:
Ticket(s): #4610 (should have been included there...)
=> Use of include for parameter tables necessary update of the include file

source/docs/user_manual/processing_algs/gdal/vectormiscellaneous.rst
=> GDAL Vector misc - Tables for alg parameters

source/docs/user_manual/processing_algs/gdal/rasteranalysis.rst
=> GDAL Raster analysis - tables for alg parameters

source/docs/documentation_guidelines/writing.rst
and small other fixes (space and blank lines -- not a single word change)
Goal:
Ticket(s): #
=> Avoid wordwrap in code-block for a better legibility

source/docs/user_manual/processing_algs/gdal/rasteranalysis.rst
Goal:
Trivial changes (removing blanks, fix some long lines). Will merge as soon as travis is happy.
Ticket(s): #
=> Fix long lines and remove blanks - GDAL raster analysis

source/docs/user_manual/processing_algs/gdal/rasteranalysis.rst
Goal:
Ticket(s):  #4429.   Backport of #4616
=> Backport to 3.4 of #4616 (Fix long lines and remove blanks - GDAL raster analysis)

source/docs/user_manual/working_with_ogc/server/getting_started.rst, source/docs/user_manual/working_with_vector/vector_properties.rst
=> Replace "Properties" with "Layer properties"

source/docs/user_manual/processing_algs/qgis/vectortable.rst
=> Fix typos in vector table

source/docs/user_manual/processing_algs/qgis/vectortable.rst
=> Add a link to information about HStore (the QGIS Explode HStore Field algorithm)

source/docs/user_manual/processing_algs/qgis/vectortable.rst
@havatv Just follow up after your last commits about HStore.
=> fix wrong description about hstore algo

source/docs/user_manual/processing_algs/qgis/networkanalysis.rst, source/docs/user_manual/processing_algs/qgis/qgis_algs_include.rst
We are considering if using `.. include` is a good idea when algorithms have a group of
parameters in common. Two approaches (suggested earlier) are shown here.
1) "Pasting" tables together. Demonstrated in "Service area (from layer)".
2) Placing the "repeating" group of parameters in a separate table. Demonstrated for the Advanced parameters in the "Service area (from point)" algorithm.
To help the users, it would be nice to have the "Advanced parameters" group exposed in the parameter tables. Three approaches:
1) Adding a row in the table before and after the Advanced parameters group, as demonstrated in the "Shortest path (layer to point)" algorithm.
2) Including "Advanced" in one of the existing columns. In the "Shortest path (point to layer)" algorithm, it is included in the Label …
=> Using includes for common groups of algorithm parameters

.github/workflows/html.yml
Github build action: every time one pushes a commit a zip with the documentation build will be automatically prepared.
@SrNetoChan HTML build: https://github.com/elpaso/QGIS-Documentation/actions
=> GitHub build

.github/workflows/backport.yml
=> Add back the backport bot

source/docs/user_manual/processing_algs/qgis/vectorgeneral.rst
Goal: Change to tables for algorithm parameters - QGIS Vector general algorithms.
Also document some new algorithms (convert to/from bookmarks - #4206 and split features by character - #4214).
Ticket(s): #4429. Fixes: #4214. fixes: #4206.
=> QGIS Vector general - tables for alg parameters

source/docs/user_manual/processing_algs/gdal/rasteranalysis.rst
=> Removed some left-overs

source/docs/user_manual/processing_algs/gdal/rasteranalysis.rst
Goal:
Ticket(s): #4429  Backport of #4603
=> Backport of #4603 (GDAL Raster analysis - tables for alg parameters)

source/docs/user_manual/processing_algs/qgis/vectorgeneral.rst
Goal:
Ticket(s): #4429.  Backport of #4620
=> Backport to 3.4 of #4620 (QGIS Vector general - tables for alg parameters

source/docs/user_manual/processing_algs/qgis/vectorgeneral.rst
=> Removed the field prefix parameter from join attributes by location (summary)

source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
Goal: Use tables for the algorithm parameters.
The algorithms from the start to (and including "Promote to multipart") .
=> QGIS Vector geometry - tables for alg parameters (part two)

source/docs/user_manual/processing_algs/lidartools/lastools.rst
Goal:  Lastools-> las2txt - table for algorithm parameters.
=> Lastools - tables for alg parameters (las2txt)

source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
=> upper case for M/Z

source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
=> Label extract M and Z values with 3.6

source/docs/user_manual/processing_algs/gdal/vectormiscellaneous.rst
=> Fix link to "Export to PostgreSQL (available connections)"

source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
follow-up #4629 
Goal:
Ticket(s): #
=> Some fixes to vector geometry chapter

source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
where some apply on points and some do not
Opening a separate PR because of https://github.com/qgis/QGIS/issues/33502
=> Add 'extract vertices ...' algorithms

source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
Goal:
Ticket(s): Review of #4629
=> Updates of the vectorgeometry algorithms after review

source/docs/user_manual/introduction/qgis_gui.rst
=> Remove duplicate link

source/docs/gentle_gis_introduction/coordinate_reference_systems.rst, source/docs/training_manual/forestry/map_georeferencing.rst, source/docs/training_manual/forestry/updating_stands.rst, source/docs/user_manual/introduction/qgis_gui.rst, source/docs/user_manual/plugins/core_plugins/plugins_coordinate_capture.rst, source/docs/user_manual/working_with_projections/working_with_projections.rst, source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst
long live the automatic reprojection
Goal:
Ticket(s): #
=> "Enable on the fly reprojection" checkbox is dead

source/docs/user_manual/processing_algs/gdal/rastermiscellaneous.rst
=> Add the gdal2tile algorithm (GDAL, Raster misc)

source/docs/user_manual/processing_algs/qgis/rastertools.rst
=> Change section level for output - set style for raster layer (QGIS Raster tools algorithms)

source/docs/user_manual/processing_algs/qgis/vectoranalysis.rst
=> Include version added for climb along line

.github/workflows/html.yml
Goal:
Change the command used by the HTML Build action
This allows faster check, with no internacionalization
It also does not build in nitpick mode, allowing the build to
complete even if there are some warnings. This allows documenters
to see all errors at once, and not just the first one.
Ticket(s): #
=> HTML Build action uses fasthtml

source/docs/user_manual/processing_algs/gdal/rastermiscellaneous.rst
Goal:
Ticket(s): https://github.com/qgis/QGIS/pull/1906
=> Add documentation for the GDAL raster calculator (GDAL misc)

source/docs/user_manual/processing_algs/gdal/rastermiscellaneous.rst
=> Add the gdal retile algorithm

source/docs/user_manual/processing_algs/gdal/rastermiscellaneous.rst
Goal:
Ticket(s): Backport of #4711
=> Backport of #4711 (Add documentation for the GDAL raster calculator, GDAL misc) to 3.4

source/docs/user_manual/processing_algs/gdal/rastermiscellaneous.rst
=> GDAL Retile alg, remove the mention of ESRI Shapefile format output

source/docs/user_manual/processing_algs/qgis/vectoranalysis.rst
based on field type
Also adds some tweaks to basic statistics
=> Reorganize in a table the different stats output by the "statistics by categories" alg

source/docs/gentle_gis_introduction/coordinate_reference_systems.rst
Fix #3357 (actually it does not fix that particular issue since we wrote nothing about the QgsDistanceArea class but the issue rings some bells...)
=> Use antimeridian instead of international date line

source/docs/user_manual/print_composer/composer_items/composer_map.rst
Fixes #3225 fixes #3224, fixes #3223
=> Add more properties of the map item grid frame

source/docs/user_manual/print_composer/composer_items/composer_map.rst
=> Layout map item overviews position can be tweaked

source/docs/user_manual/style_library/label_settings.rst
=> Mention that labels properties are (all) data-definable

source/docs/gentle_gis_introduction/coordinate_reference_systems.rst, source/docs/user_manual/introduction/qgis_configuration.rst, source/docs/user_manual/managing_data_source/opening_data.rst, source/docs/user_manual/print_composer/composer_items/composer_legend.rst, source/docs/user_manual/processing_algs/gdal/rasterextraction.rst, source/docs/user_manual/processing_algs/gdal/rastermiscellaneous.rst, source/docs/user_manual/processing_algs/qgis/interpolation.rst, source/docs/user_manual/processing_algs/qgis/rastertools.rst, source/docs/user_manual/processing_algs/qgis/vectorgeneral.rst, source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst, source/docs/user_manual/working_with_projections/working_with_projections.rst, source/docs/user_manual/working_with_vector/attribute_table.rst, source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst
=> Automatic update of substitutions list in files

source/docs/user_manual/processing_algs/lidartools/lastools.rst
Goal: Use table for the lastools algorithms parameters. Only formatting, no fixing of the
descriptions or correcting of errors.
=> Tables for alg params - lastools

source/docs/user_manual/managing_data_source/supported_data.rst
Goal:
Ticket(s): Fixes: #2292 and #3495
Fixes: #3308 (?)
=> Add a short description of the GeoPackage format

source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
=> Fixing some minor line length and other issues

source/docs/user_manual/processing_algs/qgis/img/geos_dupl_rings.png, source/docs/user_manual/processing_algs/qgis/img/qgis_seg_line_int.png, source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
=> Backport to 3.4 of table formatting for alg parameters for QGIS vector geometry algs

source/docs/user_manual/processing/3rdParty.rst
=> Add information about LAStools to 3rdParty

source/docs/user_manual/processing_algs/taudem/basic_grid_analysis_tools.rst
Goal: Change to tables for the Basic grid analysis group of TauDEM.
Should not require review, as these are external algorithms, and the
changes are formatting only + adding parameter names.
=> TauDEM Basic grid analysis - Tables for parameters

source/docs/user_manual/introduction/general_tools.rst
=> Update the ordering of the pulldown menu in select features by value (general_tools)

source/docs/user_manual/introduction/qgis_configuration.rst
refs https://github.com/qgis/QGIS/pull/30952 (no report in this repo nor in changelog - I came across this writing #4694 )
@nyalldawson @m-kuhn I would appreciate your review here since I'm not sure I understand the purpose, neither from your discussion in the implementation PR nor through my testing (which led to https://github.com/qgis/QGIS/issues/33528). Maybe did I miss some key points?
=> Describe the "planimetric measurements" option

source/docs/user_manual/introduction/qgis_configuration.rst, source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
Fixes #1605, fixes #3994, fixes #4004, fixes #4053
=> Various updates in Settings --> Options dialog

source/docs/user_manual/processing/3rdParty.rst, source/docs/user_manual/processing_algs/qgis/cartography.rst, source/docs/user_manual/processing_algs/qgis/database.rst, source/docs/user_manual/processing_algs/qgis/layertools.rst, source/docs/user_manual/processing_algs/qgis/modelertools.rst, source/docs/user_manual/processing_algs/qgis/networkanalysis.rst, source/docs/user_manual/processing_algs/qgis/rasteranalysis.rst, source/docs/user_manual/processing_algs/qgis/vectoranalysis.rst, source/docs/user_manual/processing_algs/qgis/vectorcreation.rst, source/docs/user_manual/processing_algs/qgis/vectorgeneral.rst, source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst, source/docs/user_manual/processing_algs/qgis/vectortable.rst, source/docs/user_manual/working_with_raster/raster_properties.rst, source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst
contains some review feedback I couldn't make on time and some typo I found on the road
=> Misc review fixes

source/docs/user_manual/working_with_ogc/server/services.rst
Only available starting from QGIS 3.12
=> [server] Add NO_MTEXT and FORCE_2D dxf export parameters

source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
dropped during parameters refactoring
=> Add missing algs

source/docs/user_manual/working_with_vector/expression.rst
Goal: Fix sorting. Trivial. Will merge as soon as Travis is happy.
Ticket(s): #
=> Fix some issues with the sorting of geometry functions (expressions)

source/docs/user_manual/managing_data_source/opening_data.rst
=> Update the description of the preview of XYZ Tiles in the browser after review

source/docs/pyqgis_developer_cookbook/cheat_sheet.rst
=> fix decorators copyright

source/docs/user_manual/working_with_raster/raster_properties.rst
=> Update after review of #4834 (Document contextual menu for changing symbol properties for paletted and singleband pseudocolor)

source/docs/user_manual/managing_data_source/opening_data.rst
Goal:
Ticket(s): Fixes:  #2864
=> Inital description of the context menu for Browser panel entries

source/docs/user_manual/managing_data_source/opening_data.rst
Goal:
Ticket(s):
Fixes: #2270.
=> Rename and remove favorites

source/docs/user_manual/managing_data_source/supported_data.rst
Goal:
Ticket(s): Fixes: #3010.
=> Include GeoPackage as a suitable container for raster data

source/docs/user_manual/working_with_raster/raster_properties.rst
Goal:
Ticket(s):
Fixes #1583
Fixes #1594
=> Document the "dynamic stretching" option for raster layers

source/docs/user_manual/working_with_raster/raster_properties.rst
=> Documenting "Saving paletted raster renderer color tables"

source/docs/user_manual/managing_data_source/opening_data.rst
=> Exploration of QGS project file contents in the browser

source/docs/user_manual/processing/scripts.rst
=> Fix column width in PDF - script parameters

source/docs/pyqgis_developer_cookbook/canvas.rst, source/docs/pyqgis_developer_cookbook/settings.rst
Avoid text split at the end of the code frame
Fix mixture of two and four spaces indentation in the same frame
=> Fix some formatting issues and make code snippets more legible

source/docs/developers_guide/unittesting.rst
=> cdash updates (unit testing, developers guide)

source/docs/developers_guide/unittesting.rst
=> Fixing cdash updates (unit testing, developers guide)

source/docs/pyqgis_developer_cookbook/settings.rst
=> Fix incomplete sentence

source/docs/pyqgis_developer_cookbook/plugins/plugins.rst
Add some pygments coloring for preview in Github
Also fix long line in code sample
=> Some tweaks to improve code legibility

source/docs/user_manual/plugins/core_plugins/plugins_metasearch.rst
typo fix, list items for readability, removal of old QGIS mention
Goal:
Ticket(s): #
=> Review and cleanup of Metasearch chapter

source/docs/user_manual/working_with_vector/expression.rst
=> Add elevation to project expression

source/docs/user_manual/managing_data_source/opening_data.rst
=> Add details on variety of supported online protocols data opening

source/docs/user_manual/working_with_vector/vector_properties.rst
from https://github.com/qgis/QGIS/pull/34411 https://github.com/qgis/QGIS/pull/34433 and https://github.com/qgis/QGIS/pull/34479
=> drag and drop improvements

source/docs/user_manual/managing_data_source/opening_data.rst
to make the steps clearer, easy to follow and complete. Also mention file as not the only option for raster addition
https://docs.qgis.org/testing/en/docs/user_manual/managing_data_source/opening_data.html#loading-a-layer-from-a-file
=> Modularize the "loading a layer from a file" section

source/docs/user_manual/processing_algs/qgis/vectorgeneral.rst
=> Change the name of the QGIS "Define layer projection" algorithm

.github/workflows/backport.yml
@3nids may I have your go (or no) here please? I keep getting backport bot fail with merge operation
=> Use master branch of backport bot

source/docs/user_manual/managing_data_source/opening_data.rst
and make the description less linux-centric
=> Adds some details and aerate the browser panel description

source/docs/pyqgis_developer_cookbook/tasks.rst
=> Fix typo in task code

source/docs/user_manual/plugins/core_plugins/plugins_db_manager.rst, source/docs/user_manual/working_with_vector/attribute_table.rst
=> Add substitutions missing in the "footer"

source/docs/pyqgis_developer_cookbook/tasks.rst
=> Fix typo task code

source/docs/user_manual/introduction/general_tools.rst, source/docs/user_manual/introduction/qgis_gui.rst, source/docs/user_manual/plugins/index.rst
Remove unrelated and redundant references (see eg [View](https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_gui.html#view), [vector](https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_gui.html#vector)
Also fix some typos
=> Use more accurate reference sections

source/docs/user_manual/working_with_vector/vector_properties.rst
Co-Authored-By: Håvard Tveite <havard.tveite@nmbu.no>
See #4983
=> Apply suggestions from review

source/docs/user_manual/working_with_mesh/mesh_properties.rst
and avoid collision because of "rendering" being a tab and a subtab (convenient when opening doc from the application - https://github.com/qgis/QGIS/pull/35013 )
Goal:
Ticket(s): #
=> Reword mesh properties tabs section title to make them unique

source/docs/user_manual/processing/scripts.rst
=> Add the QgsProcessingParameterScale procesing parameter type

conf.py
Goal:
Sets a Canonical URL to use on all pages of the documentation. This allows the search engines to always provide the latest documentation search results at the top.
Ticket(s): #
=> Adds canonical link

docs/user_manual/processing_algs/qgis/vectorgeometry.rst
=> change :guilabel; to :guilabel:

conf.py, docs/pyqgis_developer_cookbook/server.rst, docs/training_manual/qgis_server/install.rst, docs/training_manual/qgis_server/wms.rst, venv.mk
and update of some settings
Ticket(s): #
=> Some fixes to html build warnings

conf.py, docs_conf.yml, themes/rtd_qgis/versions.html
that's an early attempt to add correct links to the current read the doc theme documentation. 
cc @rduivenvoorde @DelazJ
=> first attempts to add correct links for github, edit on github and transifex

docs/user_manual/introduction/qgis_gui.rst
Fix reference after update.
Goal:
Ticket(s): #5026
=> Fixed reference

docs/documentation_guidelines/writing.rst
Goal: Describe some more parameter types used for processing algorithms.
Ticket(s): Contains the "above the line" parameters from #4558
Fixes #3540 (scale).
Fixes #3925 (color).
Fixes #3536 (layout).
Fixes: #3252 (authconfig)
=> Add processing parameter types

docs/user_manual/processing/scripts.rst
Goal: Include recently added processing algorithm parameters in the documentation.
Ticket(s): Replaces #5012
Fixes: #4739
Fixes: #4935
Fixes: #4995
Fixes: #5010
Fixes: #5011
=> Include some more Processing Parameters (for processing scripts)

docs/user_manual/processing_algs/qgis/vectorgeometry.rst
=> Update the remove null geometries algorithm (include the remove empty option)

README.rst
and add some coloring to code samples and text fixes
=>  Indicate that doc build is possible on macOS 

docs/pyqgis_developer_cookbook/server.rst
Fix Access control filter example usage
Goal:
Ticket(s): #
- [ x] Backport to LTR documentation is required
=> Fix Access control plugin example

conf.py, docs/pyqgis_developer_cookbook/authentication.rst, docs/pyqgis_developer_cookbook/cheat_sheet.rst
Revision and doctests for authmanager section of the cookbook
Funded by: QGIS.org
=> Cookbook revision: authmanager

docs/pyqgis_developer_cookbook/authentication.rst
=> Fix indentation of GUI auth widgets list

conf.py, themes/rtd_qgis/layout.html
(cherry picked from commit dea60425dd5f2f3ae89e519b9f6f7065128bf7e9)
Goal:
Ticket(s): #
=> Fix redirection link to the latest docs

conf.py, docs_conf.yml, themes/rtd_qgis/layout.html, themes/rtd_qgis/versions.html
=> Configuration backports to 3.4

conf.py, docs_conf.yml, themes/rtd_qgis/layout.html, themes/rtd_qgis/versions.html
=> Configuration backports to 3.10

docs/pyqgis_developer_cookbook/geometry.rst
=> Cookbook revision: geometry

docs/pyqgis_developer_cookbook/composer.rst
=> Cookbook revision: composer

docs/pyqgis_developer_cookbook/communicating.rst, docs/pyqgis_developer_cookbook/composer.rst, docs/pyqgis_developer_cookbook/expressions.rst, docs/pyqgis_developer_cookbook/geometry.rst, docs/pyqgis_developer_cookbook/intro.rst
to homogenize the highligh of code.
=> Cookbook revision: small tweaks

conf.py, docs/pyqgis_developer_cookbook/legend.rst
=> Cookbook revision: legend

conf.py, docs/pyqgis_developer_cookbook/processing.rst, testdata/processing/processing_provider/example_processing_algorithm.py, testdata/processing/processing_provider/provider.py
=> Cookbook revision: processing

conf.py, docs/pyqgis_developer_cookbook/tasks.rst
=> Cookbook revision tasks

docs/user_manual/processing_algs/qgis/vectortable.rst
Reverts qgis/QGIS-Documentation#5146
=> Revert "[Backport release_3.4] Typo corrected"

docs/user_manual/introduction/qgis_gui.rst
=> Revert removal of vector core Plugins from QGIS GUI list

docs/pyqgis_developer_cookbook/settings.rst, docs/user_manual/introduction/qgis_configuration.rst
=> Cookbook revision: settings

Makefile, conf.py, docs/user_manual/processing/scripts.rst
Eg, neither #5141 nor #5047 should have passed 
This PR is expected to fail because I want to test the setting and let an error (fixed in #5150)
Part of this needs manual backport to other releases.
=> Make the build less permissive and catch errors

Makefile, conf.py
(cherry picked from commit 194fa9c7c6ba62ec016a684bf6b404bb95e26f2e)
backports #5152
=> [Backport 3.10] Make the build less permissive and catch errors

docs/pyqgis_developer_cookbook/plugins/plugins.rst
Goal: update plugin metadata item
=> update plugin metadata item

README.rst
We shouldn't assume - and I know what I'm talking about ;) - that Linux users know what a venv is or how it works so let's share some details (prerequisite install, explanation..) provided in the Windows section with them. Also, try to use the same steps for all OS.
=> Harmonize instructions to build docs within OS

docs/user_manual/working_with_projections/working_with_projections.rst
=> Use :guilabel: and not **[]**

docs/user_manual/introduction/qgis_gui.rst
introducing the navigation widget tools, tweaking/harmonizing descriptions and mentioning the easiest alternatives first
=> Update and detail interaction with 3D map view

conf.py, docs_conf.yml, themes/rtd_qgis/theme.conf, themes/rtd_qgis/versions.html
(cherry picked from commit ea08993b49fe09df6de2743a32714255b85a4069)
Backports #5096
=> [backport 3.4]Fix links for pages in the bottom bar

conf.py, docs_conf.yml, themes/rtd_qgis/theme.conf, themes/rtd_qgis/versions.html
(cherry picked from commit ea08993b49fe09df6de2743a32714255b85a4069)
Backports #5096
=> [Backport 3.10] Fix links for pages in the bottom bar

docs/developers_guide/unittesting.rst, docs/documentation_guidelines/writing.rst, docs/pyqgis_developer_cookbook/plugins/plugins.rst, docs/pyqgis_developer_cookbook/vector.rst, docs/user_manual/introduction/general_tools.rst, docs/user_manual/introduction/qgis_gui.rst, docs/user_manual/processing/scripts.rst, docs/user_manual/processing_algs/qgis/vectoranalysis.rst, docs/user_manual/processing_algs/qgis/vectorgeometry.rst, docs/user_manual/working_with_mesh/mesh_properties.rst, docs/user_manual/working_with_ogc/server/services.rst, docs/user_manual/working_with_vector/expression.rst, docs/user_manual/working_with_vector/vector_properties.rst
The readthedocs default template css already handles this nicely.
=> Remove blank line added below tables to increase bottom margin

docs/training_manual/qgis_server/install.rst
changed 'accompagning' to 'accompanying'
Goal:
Ticket(s): #
=> corrected typo in line 31 of install.rst

docs/pyqgis_developer_cookbook/authentication.rst, docs/pyqgis_developer_cookbook/canvas.rst, docs/pyqgis_developer_cookbook/network_analysis.rst, docs/pyqgis_developer_cookbook/raster.rst, docs/pyqgis_developer_cookbook/settings.rst, docs/user_manual/appendices/GNU_FDL.rst, docs/user_manual/appendices/GNU_GPL.rst, docs/user_manual/appendices/index.rst, docs/user_manual/appendices/qgis_file_formats.rst, docs/user_manual/appendices/qgis_r_syntax.rst, docs/user_manual/print_composer/create_reports.rst
and clean substitutions list in Cookbook
=> Fix Appendices chapter table of content

docs/user_manual/processing_algs/qgis/vectorcreation.rst
Goal: version added for the *Random points on lines* algorithm.
Ticket(s): #
=> Version added for random points on lines

docs/user_manual/working_with_ogc/server/config.rst
=> Document QGIS_SERVER_IGNORE_BAD_LAYERS

docs/pyqgis_developer_cookbook/server.rst
(cherry picked from commit ea7feea71b3e4be80202da2a8871b05c128f8b1d)
Backport #5288 @elpaso?
=> Small server code tweaks

docs/user_manual/working_with_ogc/server/services.rst
see https://docs.qgis.org/3.10/en/docs/user_manual/working_with_ogc/server/services.html#getmap
btw the description will follow the others' style
Goal:
Ticket(s): #
=> Better table display for getmap extra parameters

docs/user_manual/working_with_ogc/server/development_server.rst, docs/user_manual/working_with_ogc/server/index.rst
=> Document QGIS Development Server standalone application

docs/user_manual/working_with_vector/expression.rst
=> Specify that trigonometric functions expect radians

docs/user_manual/working_with_gps/plugins_gps.rst
=> Remove stray unicode character U+200B from plugins_gps

docs/pyqgis_developer_cookbook/network_analysis.rst
=> Change cyrillic A and T to A and T

docs/user_manual/introduction/general_tools.rst
=> Map themes can be renamed

docs/user_manual/style_library/symbol_selector.rst
=> Add random fill symbol layer type

docs/user_manual/working_with_ogc/server/getting_started.rst
=> Misc tweaks and fixes to server getting started

docs/pyqgis_developer_cookbook/loadlayer.rst
Changed the text to add the vector layer to the project after creating it.
Goal:
Ticket(s): #
=> vector layer is made but not added to project

docs/user_manual/working_with_vector/vector_properties.rst
=> Mention single and rule-based symbols of 3D rendering

docs/user_manual/processing_algs/qgis/rasteranalysis.rst
I found some algorithms that had not been updated to use tables for parameters.
Goal:
=> Update the QGIS raster analysis algorithms - table for parameters

docs/user_manual/working_with_vector/expression.rst
refs https://github.com/qgis/QGIS/pull/33436
=> Expose field values list in Expression builder dialog

docs/user_manual/working_with_vector/expression.rst
=> Expression output preview is available for all the features

docs/pyqgis_developer_cookbook/loadlayer.rst
=> Removed provider_options transform_context

docs/user_manual/processing/3rdParty.rst
Goal: Update information about QGIS SAGA integration.
Ticket(s): Fix #1917
=> SAGA can only be run if it is shipped with QGIS

docs/user_manual/working_with_vector/editing_geometry_attributes.rst, qgis-projects/user_manual/working_with_vector_02.qgs
Goal:
Document the rest of the tools available on Shape digitizing toolbar
Ticket(s): Fix #4038
Fix #2179
Fix #3172
=> Document Shape Digitizing tools

docs/training_manual/basic_map/vector_data.rst
Goal: Make text correspond to screenshots - Working with vector data (training manual)
Ticket(s): #
=> Fix error (wrong layer) in Working with vector data (training manual)

themes/rtd_qgis/versions.html
Backport f271eae66a96991ae9a27d2e978b1bf05514b9b8 from #5458
=> [Backport release_3.10] Fix "Translate page" link URL

docs/user_manual/introduction/qgis_gui.rst
particularly for online dataset used as terrain (fixes #3576)
also makes room for newer types.
=> Add details on 3D terrain types

docs/user_manual/style_library/label_settings.rst
=> Add the callout label anchor point

docs/training_manual/complete_analysis/analysis_exercise.rst
Avoid download from the (removed) dropbox folder.
Goal:
Ticket(s): #
=> TM: Update the supplementary exercise to use the training manual data

docs/user_manual/introduction/qgis_gui.rst
=> Introduce mesh dataset as possible elevation terrain

docs/pyqgis_developer_cookbook/loadlayer.rst
Goal: To fill a gap in the 3.10 documentation regarding adding PostGIS rasters.
Ticket(s): #
=> add PostGIS raster layer using GDAL provider

docs/user_manual/working_with_vector/expression.rst
Fixes #5424, fixes #5382, fixes #5359, fixes #5316, fixes #5155, fixes #5064, fixes #4986, fixes #4712, fixes #4637, fixes #4466, fixes #4436, fixes #4357
=> Add some recent expression functions

docs/user_manual/preamble/contributors.rst
=> Fix language's name

docs/user_manual/introduction/qgis_gui.rst
Simplify reference to sub-menus (same as general tools chapter)
Add/fix some url references
Add icons (they add colors :smile: and make things easier to find in these long lists)
=> Various improvements to GUI items lists

docs/pyqgis_developer_cookbook/intro.rst
Goal: Mention processing algorithms and expression functions as possible uses of Python in the QGIS context.
Ticket(s): Fixes #5323
=> Include processing algorithms and expression functions as possible uses of Python

docs/pyqgis_developer_cookbook/authentication.rst, docs/user_manual/auth_system/auth_overview.rst
Remove qt4 references, 
Mention new auth methods (refs #3081)
Fixes code and references display
@elpaso ?
=> Various fixes to the authentication chapter in cookbook

docs/user_manual/introduction/qgis_gui.rst
=> Fix paste to temporary scratch layer shortcut

docs/user_manual/introduction/general_tools.rst, docs/user_manual/introduction/qgis_gui.rst
=> Refer to the "Selection toolbar" for selection tools

conf.py, themes/rtd_qgis/static/css/qgis_topbar.css
Backport a7a560d77b8ecca0476e4994fd81122ed4ae248c from #5496
=> [Backport release_3.10] Fix top bar for testing and outdated versions

conf.py, themes/rtd_qgis/static/css/qgis_topbar.css
Backport a7a560d77b8ecca0476e4994fd81122ed4ae248c from #5496
=> [Backport release_3.4] Fix top bar for testing and outdated versions

docs/user_manual/style_library/symbol_selector.rst
=> Use percentage to size raster image in symbols

docs/user_manual/processing_algs/qgis/index.rst, docs/user_manual/processing_algs/qgis/plots.rst
=> rename Graphics to Plots (fix #5419)

docs_conf.yml
=> List all the released versions of docs

docs/user_manual/preamble/help_and_support.rst
Goal:
Replace the old Redmine bugtracker link https://issues.qgis.org/projects/qgis/issues with the new bugtracker link on GitHub https://github.com/qgis/QGIS/issues in the "[Help and Support](https://docs.qgis.org/testing/en/docs/user_manual/preamble/help_and_support.html#bugtracker
)" page of the User Guide/Manual for the sentence:
> While the qgis-users mailing list is useful for general 'How do I do XYZ in QGIS?'-type questions, you may wish to notify us about bugs in QGIS. You can submit bug reports using the QGIS bug tracker at https://issues.qgis.org/projects/qgis/issues..
The following sentences should be updated too or removed:
> If you have found a bug and fixed it yourself, you can submit either a Pull Request on the Github QGIS Project (prefered) or a patch also. The lovely …
=> Update QGIS BugTracker link

docs/user_manual/working_with_projections/working_with_projections.rst
=> Fix wrong link in projection

docs/user_manual/introduction/qgis_gui.rst
refs https://github.com/qgis/QGIS/pull/36726
=> Arrows are incompatible with 3D mesh terrain

Makefile, docs/user_manual/processing_algs/qgis/qgis_algs_include.rst, docs/user_manual/processing_algs/qgis/vectorgeometry.rst
Goal: Provide a common "Python code" section for all processing algorithm through an include.
Inspired by https://github.com/qgis/QGIS-Enhancement-Proposals/issues/178.
We could also consider adding the algorithm ID in the algorithm documentation.
What to call the "Python code" section is yet to be decided, and the same goes for the contents and structure.
Ticket(s): #
=> Use include to add a Python code section to all processing algorithms

docs/user_manual/processing_algs/qgis/rasteranalysis.rst
Line 1685 :  format for table output is missing.  Added
=> Missing format table for output

docs/user_manual/processing_algs/qgis/rasteranalysis.rst
Goal: Add code include for QGIS raster analysis algorithms.
Also did some line length adjustments.
=> Add code include for QGIS raster analysis algorithms

docs/user_manual/managing_data_source/create_layers.rst
Fixes #5415 and add temporary layer's missing field type (fixes #3152)
=> Allow geometryless shapefile creation

docs/user_manual/style_library/symbol_selector.rst
Fixes #5556, fixes #5087, fixes #5074, fixes #4805, fixes #4631, fixes #3715, fixes #3714
=> Various fixes to symbol types properties

docs/user_manual/introduction/qgis_gui.rst
with their names, sorted alphabetically to match the GUI
Remove mention of the User Input panel, no more a panel and the associated link was not that relevant
Goal:
Ticket(s): #
=> Update list of panels

docs/user_manual/style_library/label_settings.rst
=> Move Obstacles settings from Rendering to Placement tab

docs/user_manual/working_with_ogc/ogc_client_support.rst, docs/user_manual/working_with_ogc/server/services.rst
=> Update of wfs/wfs3 loading section

docs/user_manual/introduction/qgis_configuration.rst
refs https://github.com/qgis/QGIS/pull/36922
=> Tweaks qgs vs qgz difference

docs/training_manual/databases/db_manager.rst, docs/training_manual/databases/index.rst, docs/training_manual/databases/spatialite.rst
Goal: Make sure that SpatiaLite is used throughout the documentation (and some updates to the spatialite document - numbered lists, line length adjustments).
Trivial updates - no need for review.
Ticket(s): #
=> Change to SpatiaLite

docs/user_manual/processing_algs/qgis/cartography.rst
Goal: Add code section to QGIS cartography algs
=> Add code section to QGIS cartography algs

docs/user_manual/processing_algs/gdal/rasteranalysis.rst
Goal: Add code section to GDAL raster analysis algs
=> Add code section to GDAL raster analysis algs

docs/user_manual/processing_algs/qgis/database.rst
Goal: Add code section to QGIS database algs
=> Add code section to QGIS database algs

docs/user_manual/processing_algs/qgis/filetools.rst
Goal: Add code section to QGIS file tools algs
=> Add code section to QGIS file tools algs

docs/user_manual/processing_algs/qgis/plots.rst
Goal: Add code section to QGIS plot algs
=> Add code section to QGIS plot algs

docs/user_manual/processing_algs/qgis/interpolation.rst
Goal: Add code section to QGIS interpolation algs
=> Add code section to QGIS interpolation algs

docs/user_manual/processing_algs/qgis/layertools.rst
Goal: Add code section to QGIS layer tools algs
=> Add code section to QGIS layer tools algs

docs/user_manual/processing_algs/qgis/modelertools.rst
Goal: Add code section to QGIS modeller tools algs
=> Add code section to QGIS modeller tools algs

docs/user_manual/processing_algs/qgis/networkanalysis.rst
Goal: Add code section to QGIS network analysis algs
=> Add code section to QGIS network analysis algs

docs/user_manual/processing_algs/qgis/rasterterrainanalysis.rst
Goal: Add code section to QGIS raster terrain analysis algs
=> Add code section to QGIS raster terrain analysis algs

docs/user_manual/processing_algs/qgis/rastertools.rst
Goal: Add code section to QGIS raster tools algs
=> Add code section to QGIS raster tools algs

docs/user_manual/processing_algs/qgis/vectoranalysis.rst
Goal: Add code section to QGIS vector analysis algs
=> Add code section to QGIS vector analysis algs

docs/user_manual/processing_algs/qgis/vectorcreation.rst
Goal: Add code section to QGIS vector creation algs
=> Add code section to QGIS vector creation algs

docs/user_manual/processing_algs/qgis/vectorgeneral.rst
Goal: Add code section to QGIS vector general algs
=> Add code section to QGIS vector general algs

docs/user_manual/processing_algs/qgis/vectoroverlay.rst
Goal: Add code section to QGIS vector overlay algs
=> Add code section to QGIS vector overlay algs

docs/user_manual/processing_algs/qgis/vectorselection.rst
Goal: Add code section to QGIS vector selection algs
=> Add code section to QGIS vector selection algs

docs/user_manual/processing_algs/qgis/vectortable.rst
Goal: Add code section to QGIS vector table algs
=> Add code section to QGIS vector table algs

docs/user_manual/introduction/qgis_configuration.rst
=> Registry for localized data paths

docs/user_manual/processing_algs/gdal/rasterconversion.rst, docs/user_manual/processing_algs/gdal/rasterextraction.rst, docs/user_manual/processing_algs/gdal/rastermiscellaneous.rst, docs/user_manual/processing_algs/gdal/rasterprojections.rst
Goal: Add code sections to the GDAL raster algorithms
=> Add code sections to the GDAL raster algorithms

docs/user_manual/processing_algs/gdal/vectorconversion.rst, docs/user_manual/processing_algs/gdal/vectorgeoprocessing.rst, docs/user_manual/processing_algs/gdal/vectormiscellaneous.rst
Goal: Add code sections to the GDAL vector algorithms
=> Add code sections to the GDAL vector algorithms

docs/user_manual/processing_algs/lidartools/lastools.rst
Goal: Add code section to lastools algs
=> Add code section to lastools algs

docs/developers_guide/unittesting.rst
Goal: Backport #4873 to 3.10
Ticket(s): #4873
=> Update unittesting.rst (backport #4873 to 3.10)

docs/user_manual/processing_algs/qgis/vectorgeneral.rst
Fix bullet list indentation
Goal:
Ticket(s): #
=> Update vectorgeneral.rst (fix bullet list indentation)

docs/training_manual/map_composer/map_composer.rst
=> Adjusting a few too long lines (clean-up after #5669)

docs/user_manual/processing/intro.rst
Fix https://github.com/qgis/QGIS/issues/37117
=> Indicate how to enable Processing

docs/user_manual/appendices/qgis_r_syntax.rst, docs/user_manual/processing/3rdParty.rst
Goal: I found some spelling mistakes.  Have corrected these. I also added some index entries.
Ticket(s): #
=> Third party section - spell checking and adding index entries

docs/training_manual/introduction/mapviewnavigation.rst
Some minor edits.
Goal: 
Ticket(s): #
=> Minor updates to mapviewnavigation

docs/training_manual/map_composer/dynamic_layout.rst
Goal: Training manual dynamic layout lesson update
Ticket(s): #4349
=> Training manual dynamic layout lesson update

docs/user_manual/introduction/qgis_gui.rst
because people often think that these are new layers... (and assuming that I get the subtleties, myself)
=> A bit more details on "Duplicate layers" and "Copy layers" tools

docs/training_manual/vector_analysis/reproject_transform.rst
Goal: Update the TM reprojecting and transforming data lesson (7.1)
Ticket(s): #2441
=> Update the TM reprojecting and transforming data lesson

docs/training_manual/rasters/terrain_analysis.rst
Goal: Update PR 5737 after review
Ticket(s): #5737
=> Update PR 5737 after review

docs/training_manual/rasters/terrain_analysis.rst
Goal: Manual backport of 5743 (TM, terrain analysis, review)
Ticket(s): #5743
=> Manual backport of 5743 (TM, terrain analysis, review)

docs/training_manual/introduction/mapviewnavigation.rst
Goal: Manual backport of 5748 - TM, shp2gpkg
Ticket(s): #5748
=> Manual backport of 5748 - TM, shp2gpkg

.github/workflows/backport.yml
hopefully it will help with rebased PRs
=> try with new version of backport bot

docs/user_manual/introduction/general_tools.rst, docs/user_manual/print_composer/composer_items/composer_legend.rst, docs/user_manual/working_with_vector/expression.rst
Goal: TM: Update title expresssions - variables
Ticket(s): #5753
=> TM: Update title expresssions - variables

docs/user_manual/working_with_vector/expression.rst
Goal: Update expression variables: sorting, text adjustments
Ticket(s): #
=> Expression variables, sorting, text adjustments

docs/user_manual/working_with_ogc/server/services.rst
Fixes: https://github.com/qgis/QGIS-Documentation/issues/5764
=> Document WFS3 sorting

docs/user_manual/working_with_ogc/server/services.rst
Goal: Add version information for WFS feature sorting
Ticket(s): #5765
=> Add version information for WFS feature sorting

docs/user_manual/processing_algs/gdal/rasteranalysis.rst, docs/user_manual/processing_algs/gdal/rasterconversion.rst, docs/user_manual/processing_algs/gdal/rasterextraction.rst, docs/user_manual/processing_algs/gdal/rastermiscellaneous.rst, docs/user_manual/processing_algs/gdal/rasterprojections.rst, docs/user_manual/processing_algs/gdal/vectorconversion.rst, docs/user_manual/processing_algs/gdal/vectorgeoprocessing.rst, docs/user_manual/processing_algs/gdal/vectormiscellaneous.rst, docs/user_manual/processing_algs/lidartools/lastools.rst, docs/user_manual/processing_algs/qgis/cartography.rst, docs/user_manual/processing_algs/qgis/database.rst, docs/user_manual/processing_algs/qgis/filetools.rst, docs/user_manual/processing_algs/qgis/interpolation.rst, docs/user_manual/processing_algs/qgis/layertools.rst, docs/user_manual/processing_algs/qgis/modelertools.rst, docs/user_manual/processing_algs/qgis/networkanalysis.rst, docs/user_manual/processing_algs/qgis/plots.rst, docs/user_manual/processing_algs/qgis/qgis_algs_include.rst, docs/user_manual/processing_algs/qgis/rasteranalysis.rst, docs/user_manual/processing_algs/qgis/rasterterrainanalysis.rst, docs/user_manual/processing_algs/qgis/rastertools.rst, docs/user_manual/processing_algs/qgis/vectoranalysis.rst, docs/user_manual/processing_algs/qgis/vectorcreation.rst, docs/user_manual/processing_algs/qgis/vectorgeneral.rst, docs/user_manual/processing_algs/qgis/vectorgeometry.rst, docs/user_manual/processing_algs/qgis/vectoroverlay.rst, docs/user_manual/processing_algs/qgis/vectorselection.rst, docs/user_manual/processing_algs/qgis/vectortable.rst
=> Move the algorithm ID under the python code section

docs/user_manual/processing_algs/taudem/basic_grid_analysis_tools.rst
Goal: Update TauDEM basic grid analysis algorithms
=> Update TauDEM basic grid analysis algorithms

docs/user_manual/processing_algs/taudem/specialized_grid_analysis_tools.rst
Goal: Update the TauDEM specialised grid analysis algs
=> Update the TauDEM specialised grid analysis algs

docs/user_manual/processing_algs/taudem/stream_network_analysis_tools.rst
Goal: Update the TauDEM stream network analysis algs
=> Update the TauDEM stream network analysis algs

docs/user_manual/working_with_vector/attribute_table.rst
=> Correct invalid statement that virtual fields cannot be edited after creation

docs/user_manual/processing/history.rst
Fix some minor issues
Goal:
Ticket(s): #
=> Fix some minor issues in processing history.rst

docs/user_manual/preamble/features.rst
Goal: Update the QGIS features part (with features added up until QGIS 3.10)
Ticket(s): FIx #2286
=> Update the QGIS features, part I

docs/user_manual/preamble/features.rst
Goal: Add to the features list
Ticket(s): #2286
=> Add to the features list

docs/user_manual/preamble/features.rst
Goal: More feature updates, including graphical modeller, authentication and locator
Ticket(s): #2286
=> More feature updates, including graphical modeller, authentication and locator

docs/user_manual/introduction/browser.rst
Goal: Remove >3.10 browser panel features
Ticket(s): #5440, #5827
=> Remove >3.10 browser panel features

docs/user_manual/preamble/features.rst
Goal: Update QGIS features with information about spreadsheet support
Ticket(s): #2286
=> Update QGIS features with information about spreadsheet support

docs/user_manual/processing_algs/qgis/vectorgeneral.rst, docs/user_manual/processing_algs/qgis/vectorgeometry.rst
and clean some backport artefacts
=> Restore the "Drop geometries" algorithm

docs/pyqgis_developer_cookbook/loadlayer.rst, docs/pyqgis_developer_cookbook/plugins/snippets.rst
due to unavailable or corrupted(?) wfs layer
=> Fix documentation build

docs/user_manual/print_composer/composer_items/composer_image.rst
Goal: Document drag and drop of images to layouts (and some minor updates)
Ticket(s): Fix #4507
=> Document drag and drop of images to layouts (and some minor updates)

docs/user_manual/print_composer/composer_items/composer_image.rst
=> Trivial pursuit

docs/training_manual/basic_map/mapviewnavigation.rst, docs/training_manual/create_vector_data/actions.rst, docs/training_manual/create_vector_data/create_new_vector.rst, docs/training_manual/create_vector_data/topo_editing.rst, docs/training_manual/map_composer/map_composer.rst, docs/training_manual/rasters/changing_symbology.rst, docs/training_manual/vector_analysis/basic_analysis.rst, docs/training_manual/vector_classification/attribute_data.rst, docs/user_manual/processing_algs/qgis/vectorgeneral.rst, docs/user_manual/style_library/label_settings.rst, docs/user_manual/working_with_vector/vector_properties.rst
=> Missing version tags for new algorithms

themes/rtd_qgis/layout.html
Goal: Add a link to the documentation index in the documentation sidebar. The link is placed at the bottom of the sidebar title (under the "search the docs" field).
Ticket(s): Fix #5543
=> Add a link to the documentation index in the documentation sidebar

docs/documentation_guidelines/first_contribution.rst
=> No more "fix me" link

conf.py
Goal: Provide a more detailed TOC in the PDFs
Ticket(s): Fix #1432
=> More detailed TOC in the PDFs

docs/user_manual/managing_data_source/supported_data.rst
Goal: Some fixes to the ESRI Shapefile format description
Ticket(s): #5873
=> Some fixes to the ESRI Shapefile format description

docs/documentation_guidelines/first_contribution.rst
refs https://github.com/qgis/QGIS-Documentation/pull/5870#pullrequestreview-448414763
=> Detail issue reports page

docs/user_manual/processing/3rdParty.rst, docs/user_manual/processing_algs/index.rst, docs/user_manual/processing_algs/otb.rst
Goal: Backport OTB updates to 3.10
Ticket(s): #5783
=> Backport OTB updates to 3.10

.tx/config, Makefile, README.rst, conf.py
Goal:
Backport #5761 and small fix on PDF
Ticket(s): #
=> Backport 5761

conf.py
Goal: Better PDF rendering of minutes and seconds in dms
Ticket(s): #
=> Better PDF rendering of minutes and seconds in dms

docs/user_manual/introduction/general_tools.rst
Goal: Users shall be able to find the new copy and paste style function which is implement into the right-click for the layers.
Ticket(s): fix #4055
=> Copy paste style

docs/user_manual/working_with_vector/attribute_table.rst
Also move the multiple pairing suggestion to a note to avoid confusion since we stated earlier that a single pair is to be used with the example dataset
=> Add details on the "Discover relation" entry

docs/training_manual/answers/answers.rst, docs/training_manual/complete_analysis/analysis_combination.rst
fixing :kbd: misuse
moving from bulleted list to numbered list
=> Some formatting fixes in analysis combination lesson

docs/developers_guide/qtcreator.rst, docs/user_manual/introduction/getting_started.rst
Goal: Update link to INSTALL
Ticket(s): Fix #5947
=> Update link to INSTALL

Makefile
Goal:
- Separate PDF creation from HTML, allowing it to fail without risking HTML build
- Make Latex less verbose and ignore errors
Ticket(s): #
=> Fix pdf creation

Makefile
Goal:
Backport #5956 
Ticket(s): #
=> Backport 5956

Makefile
Goal:
Port #5961 to master branch. It was tested and worked well
Ticket(s): #
=> Allows PDF creation to fail softly without breaking the build

docs/user_manual/processing/console.rst, docs/user_manual/processing/modeler.rst
Small changes:
* adding `Mesh Layer` as Modeler Input
* removing a lonely sentence in the console
=> Processing inputs minor changes

docs/user_manual/introduction/qgis_gui.rst, docs/user_manual/print_composer/composer_items/composer_attribute_table.rst, docs/user_manual/print_composer/composer_items/composer_map3d.rst, docs/user_manual/print_composer/create_output.rst, docs/user_manual/working_with_mesh/mesh_properties.rst, docs/user_manual/working_with_ogc/ogc_client_support.rst, docs/user_manual/working_with_vector/attribute_table.rst, docs/user_manual/working_with_vector/vector_properties.rst
Goal: Change to numref for figure references in the user manual
Ticket(s): #
=> Change to numref for figure references in the user manual

docs/user_manual/working_with_vector/expression.rst
Deleting duplicate example, already provided by the function. PR for some in code repo at https://github.com/qgis/QGIS/pull/38090.
Moving some generic examples to the introductory part.
=> Reorganize examples of expression now that they are fetched from code repo

Makefile
Goal:
Make sure to clean up the build folder before you synchronize the site and the PDFs, otherwise files from 
Older build may be sent to the server. This happens when you build master and release 3.10, for example.
Ticket(s): #
=> Force spring clean job before running the all task

docs/user_manual/preamble/conventions.rst
=> No icon to indicate the OS screenshots are taken from

docs/user_manual/introduction/qgis_configuration.rst, docs/user_manual/working_with_mesh/mesh_properties.rst, docs/user_manual/working_with_vector/expression.rst
in order to add specific comments and link to other functions or parts of the docs
@SrNetoChan this is somehow what I had in mind while asking the "fake anchors" -- now that I use it, I realize that one would have probably been enough ;(  Thanks
Completes #5954
=> Split the imported expression functions help

docs/pyqgis_developer_cookbook/loadproject.rst
Goal: add the pyqgis description for the bad layer source handler. All credits goes to @nyalldawson (not only for the code, also for the description :).
Not sure if some additional description is needed, I'm available to add it!
Ticket(s): fixes #4027
=> [pyqgis] Add broken path handling with QgsPathResolver

docs/user_manual/introduction/qgis_configuration.rst
=> Fix Windows file path display

docs/pyqgis_developer_cookbook/plugins/snippets.rst
Goal: tries to fix #1743. Target section is a custom code snippet (I couldn't find any other suitable places). @elpaso do you have a chance to make a small review of the code?
Ticket(s): fixes #1743
=> [pyqgis] add a code snippet specific for plugins

docs/user_manual/processing/console.rst, docs/user_manual/processing/modeler.rst
Goal: as discussed in #5896 this is a backport of Processing Model inputs available in 3.10
=> Processing Inputs backport for 3_10

docs/user_manual/introduction/general_tools.rst
refs https://github.com/qgis/QGIS/pull/35434
=> Update available statistics

docs/user_manual/processing_algs/qgis/vectoranalysis.rst
same as what is available in the GUI
Move the Z-score output explanation to where it's mentioned (refs https://github.com/qgis/QGIS-Documentation/pull/5963#issuecomment-669513724)
=> Add a generic description to the alg

docs/user_manual/auth_system/auth_overview.rst
=> Update the location of qgis-auth.db

docs/user_manual/working_with_vector/expression.rst
I usually see people trying to write "select...from..."-like expressions in order to select/update values and there have been requests in lists to provide explanation on how the expression engine works.
This is an attempt to fill the gap; If any expression guru is around I would appreciate feedback.
note: only the first commit introduces the writing description. Others are adding titles/moving sections around to have a smooth reading.
=> Writing expressions

docs/pyqgis_developer_cookbook/crs.rst, docs/pyqgis_developer_cookbook/geometry.rst, docs/pyqgis_developer_cookbook/settings.rst, qgis-projects/python_cookbook/01_project.qgs
fixes some of the "obvious" warnings of travis (I don't know where the actual data are but let's trust travis...)
Also fixes some settings methods.
=> Let's expect same result as travis claims

docs/user_manual/working_with_ogc/server/config.rst, docs/user_manual/working_with_ogc/server/services.rst
Goal: Backport of #5936
Ticket(s): #
=> Backport of #5936

docs/training_manual/vector_classification/classification.rst
Fixes incorrect word use in vector classification
=> Fixed typo picked up by Ed Parsons

docs/training_manual/forestry/forest_maps.rst, docs/user_manual/introduction/general_tools.rst, docs/user_manual/print_composer/composer_items/composer_html_frame.rst, docs/user_manual/print_composer/composer_items/composer_label.rst, docs/user_manual/print_composer/create_reports.rst
=> 'Insert an Expression' button also edits

docs/server_manual/config.rst
Follows #5936 to fix PR comments and insert 2 new variable in the new table
=> Follows add missing env var

docs/user_manual/working_with_ogc/server/config.rst
Goal: Backport of the relevant parts of #6069 to 3.10 (remove the description of DISPLAY, update the description of QGIS_SERVER_API_RESOURCES_DIRECTORY).
Ticket(s): #6071 6069
=> Backport of #6069 to 3.10

docs/server_manual/index.rst
=> Add numbering to Server manual

docs/developers_guide/codingstandards.rst
Today I had a little trouble using the SIP documentation and I later realized it was not complete and a bit outdated. Here we go with an updated version.
=> SIPify documentation update

docs/user_manual/processing_algs/qgis/rasteranalysis.rst
=> Update zonal statistics algorithm

docs/server_manual/config.rst
and highlight the deprecation of QGIS_SERVER_LOG_FILE
=> use anchors to environment variables

docs/server_manual/services.rst
=> Fix security error message in wms filter

docs/server_manual/containerized_deployment.rst
https://docs.qgis.org/testing/en/docs/server_manual/containerized_deployment.html#first-try last code block now renders as below
=> Make sample results fully visible without the need for scrolling

docs/user_manual/working_with_vector/expression_help/Conditionals.rst, docs/user_manual/working_with_vector/expression_help/GeometryGroup.rst, docs/user_manual/working_with_vector/expression_help/String.rst
=> Add new expression functions

docs/server_manual/services.rst
…e specification
Goal: Move the SLD parameters to the standard WMS getmap parameters, and provide link to the SLD specification
Ticket(s): Fix #6104
=> Move the SLD parameters to the standard WMS getmap parameters, and provide link to the SLD specification

docs/user_manual/working_with_ogc/server/services.rst
=> Backport of #6106

docs/user_manual/introduction/qgis_gui.rst
=> Add Annotation entries to Edit menu

Makefile, docs/pyqgis_developer_cookbook/composer.rst, docs/pyqgis_developer_cookbook/index.rst, docs/pyqgis_developer_cookbook/loadlayer.rst, docs/pyqgis_developer_cookbook/tasks.rst, docs/pyqgis_developer_cookbook/vector.rst, docs/user_manual/processing/scripts.rst
This is an attempt to fix a few random crashes in the doctests.
=> Fix segfault on gdalclosewrapper

docs/user_manual/introduction/qgis_configuration.rst
Goal: add a small note to OpenCL support. I think #2842 is already documented but maybe this note can be a little bit more helpful
Ticket(s): fix #2842
=> Add a note to OpenCL

docs/user_manual/processing/3rdParty.rst
Goal: Minor grammatical and style change to first sentence in the section on SAGA.
=> Update first sentence on SAGA

docs/documentation_guidelines/first_contribution.rst
`Propose file change` -> `Propose changes`
https://docs.qgis.org/3.10/en/docs/documentation_guidelines/first_contribution.html#alternative-1-use-the-edit-on-github-shortcut
Update the label text of the page opened when clicking on the `Edit on GitHub` link
=> Update the label text of GitHub

docs/user_manual/working_with_vector/editing_geometry_attributes.rst
and fix build (we should avoid blind backports, without checking files or wait for travis run)
=> Fix wrong backport

docs/pyqgis_developer_cookbook/geometry.rst
Goal:
the output of 1 and 3 for point and polygon are present as a comment, the output of 2 is not. It should be, otherwise it may confuse the reader.
Ticket(s):
=> add explanatory comment

docs/documentation_guidelines/first_contribution.rst
and avoid the use of |CURRENT| that becomes outdated at some point
Also adds some misc fixes
=> Make dynamic the reference to the released version

docs/user_manual/working_with_vector/functions_list.rst
and add reference to related functions or algorithms
Reinstate 3c42278 accidentally removed by 09023a4
=>  Split the imported expression functions help

docs/developers_guide/ogcconformancetesting.rst, docs/pyqgis_developer_cookbook/tasks.rst, docs/pyqgis_developer_cookbook/vector.rst, docs/training_manual/basic_map/mapviewnavigation.rst, docs/training_manual/basic_map/overview.rst, docs/training_manual/basic_map/preparation.rst, docs/training_manual/complete_analysis/analysis_exercise.rst, docs/training_manual/databases/db_browser.rst, docs/training_manual/processing/batch_conversion.rst, docs/training_manual/processing/extents.rst, docs/training_manual/processing/john_snow.rst, docs/training_manual/qgis_plugins/fetching_plugins.rst, docs/training_manual/qgis_server/install.rst
=> Fix misspelling errors

docs/user_manual/working_with_vector/functions_list.rst
=> Connect overlapping functions (and alg) together

.travis.yml
This is already covered by the GitHub action
=> Remove HTML build from travis check

docs/pyqgis_developer_cookbook/geometry.rst
Get rid of "imaginary" countries and expect actual and existing ones (I always wondered where does this dataset come from...)
=> Make travis green again

docs/user_manual/processing_algs/qgis/vectorgeneral.rst
=> Add operation parameter to Reproject layer algorithm

README.md
=> Add a badge that points to the published doc

docs/pyqgis_developer_cookbook/communicating.rst
shortening lines and fixing indentation in code sample
=> Some formatting cleanup

docs/pyqgis_developer_cookbook/communicating.rst
=> Update communicating with various methods

docs/server_manual/containerized_deployment.rst
Just an update of the QGIS gpg key
=> fixes instructions for QGIS install in dockerfile

docs/training_manual/vector_analysis/basic_analysis.rst
=> Fix NULL comparison

README.md
to avoid unaware people needlessly run this "lengthy" command
=> Add comments for code sample

docs/user_manual/managing_data_source/opening_data.rst
Use numref for references
Goal:Use numref for references
Ticket(s): #
=> Update opening_data.rst (numref)

docs/server_manual/services.rst
Goal: hopefully fixes #2124. Not sure if this is the correct place where to put this small description.
Ticket(s): #2124
=> GetProjectSettings legend group

docs/user_manual/processing_algs/qgis/vectortable.rst
fix #4786 
- [ x] Backport to LTR documentation is required
=> rename vector field

docs/user_manual/processing_algs/qgis/vectorcreation.rst
and fix output directory parameter name (backports part of #6220)
=> [3.16] Add close_path parameter to points to path alg

README.md
=> Point to the Actions page from the badges in readme

docs/user_manual/processing_algs/qgis/vectorcreation.rst, substitutions.txt
Fixes #6217 and a previous unreported feature
=> Update Points to path algorithm

docs/user_manual/processing/index.rst, docs/user_manual/processing/standalone.rst
Closes https://github.com/qgis/QGIS-Documentation/issues/6192
=> Add some basic usage information about qgis_process

docs/user_manual/introduction/qgis_configuration.rst, docs/user_manual/working_with_vector/expression.rst, docs/user_manual/working_with_vector/functions_list.rst
and a reference to the functions list - refs #6231
=> Add the "Relations" group in Expressions dialog

docs/user_manual/processing_algs/gdal/rasterextraction.rst
a merely copy-paste of gdal_contour while fixing description in that alg parameters (fixes #6204)
=> Add gdal contour_polygon algorithm

docs/pyqgis_developer_cookbook/vector.rst
Goal: add a section of the `QgsVectorLayerUtils` class. I think it deserves a whole section where we can add also more methods in the future.
A small code sample has been added
Ticket(s): fixes #1525
=> QgsVectorLayerUtils class

.github/workflows/auto-label.yml
Remove unmaintained versions and add future ones
=> Update list of versions to auto-label issue reports

docs/pyqgis_developer_cookbook/vector.rst
Reverts qgis/QGIS-Documentation#6040
=> Revert "[pyqgis] add a small QgsSpatialIndexKDBush description"

docs/user_manual/working_with_vector/functions_list.rst
to help people manipulate the output
=> Connect the array functions to the overlay-* functions

docs/user_manual/print_composer/composer_items/composer_label.rst
=> Add examples of expressions to display layer values

docs/training_manual/complete_analysis/analysis_exercise.rst
Two more renaming file
Line 367 :  Added capital R to name of file "rainfall30" as this file should be named "Rainfall30" like in the rest of the exercise
Line 451 :  Added capital R to name of file "rainfall30" as this file should be named "Rainfall30" like in the rest of the exercise
Ticket(s): #
=> Two more renaming fil;e (adding capital R)

docs/user_manual/processing_algs/qgis/rasteranalysis.rst
=> Update zonal statistics algorithm ID to use help button efficiently

docs/pyqgis_developer_cookbook/vector.rst, docs/user_manual/managing_data_source/supported_data.rst, docs/user_manual/processing_algs/gdal/rasteranalysis.rst, docs/user_manual/processing_algs/gdal/rasterconversion.rst, docs/user_manual/processing_algs/gdal/rasterextraction.rst, docs/user_manual/processing_algs/gdal/rastermiscellaneous.rst, docs/user_manual/processing_algs/gdal/rasterprojections.rst, docs/user_manual/processing_algs/gdal/vectorconversion.rst, docs/user_manual/processing_algs/gdal/vectorgeoprocessing.rst, docs/user_manual/processing_algs/gdal/vectormiscellaneous.rst
=> Update url of gdal programs

docs/training_manual/complete_analysis/analysis_exercise.rst
Clarify and reorganize some steps (eg really load all the layers in first step)
Remove some unnecessary instructions
Highlight use of IN operator over = in SQL expression
Goal:
Ticket(s): #
=> [TM] Some cleanup to analysis exercise

docs/user_manual/style_library/label_settings.rst
that are included in #6262
Fix #5849, fix #6111
=> Various changes on label settings

docs/user_manual/style_library/label_settings.rst
Sort the placement modes to match the GUI
Fix labels and description (fix #5390, fix #5389, fix #5388, refs #6024)
=> Update polygon labels placement

docs/user_manual/style_library/label_settings.rst
Modularize the point labels placement  to easily identify how properties relate to each others (and ease further changes)
Some tweaks to reflect the GUI
refs #6024
=> Update point labels placement

docs/user_manual/processing_algs/gdal/rasterextraction.rst
=> Complete description of clip raster by mask layer parameters

docs/user_manual/processing_algs/gdal/vectorgeoprocessing.rst
=> Fix anchor and ID of the "Clip vector by mask layer" algorithm

scripts/create_transifex_resources.sh
- clean and update PO file references (from "scratch")
- use formatting compatible with transifex-github integration
- use more recent tx config mapping command
=> Update the script to generate the transifex config file

docs/user_manual/working_with_vector/editing_geometry_attributes.rst
Update documentation of `circle from 3 tangents` after https://github.com/qgis/QGIS/pull/40702
I'm not sure about the wording.
=> Update circle3Tangents documentation

.github/workflows/doctest.yml, .github/workflows/html.yml, scripts/create_transifex_resources.sh
This is a generated file that has no impact on the build output. Also less noise and bandwidth consumption for Transifex commits.
=> Do not run the tests when the changes are only in locale folder 

Makefile, themes/rtd_qgis/versions.html
=> Prepare 3.16 docs for translation

themes/rtd_qgis/versions.html
Also fix Chinese languages codes mismatch (forward port #6385)
Goal:
Ticket(s): #
=> Update the "translate page" button to use github integration slugs

redirects.txt
=> Add another redirection

docs/user_manual/processing_algs/taudem/basic_grid_analysis_tools.rst, docs/user_manual/processing_algs/taudem/specialized_grid_analysis_tools.rst, docs/user_manual/processing_algs/taudem/stream_network_analysis_tools.rst
closes #4429 with taudem (this is only a formatting switch, eg I do not track the missing parameters ID)
=> Switch taudem algorithms description to table formatting

docs/user_manual/processing_algs/gdal/rasterextraction.rst
Line 18 and line 141 added letter "l"to html to link to the page. Otherwise page 404-errot
=> Added letter "l"to link to html

docs/user_manual/processing_algs/taudem/stream_network_analysis_tools.rst
IF we are to document taudem algs, better fill in some information than just listing the algs. This PR adds algs description (picked from taudem site) and fixes some parameters wrong docs.
=> Add minimal description to taudem algs

docs/pyqgis_developer_cookbook/vector.rst
refs #6421 and fixes doctest build
=> Add a new vector renderer type (mergedFeatureRenderer)

docs/server_manual/getting_started.rst
=> Follow-up fixes to #6351

docs/pyqgis_developer_cookbook/plugins/snippets.rst, docs/user_manual/introduction/general_tools.rst
Closes #1092 (putting emphasis on the feature and removing references to outdated and unavailable blog post)
=> Vector layer properties dialog (including layer styling panel) can show custom tabs 

docs/training_manual/qgis_server/wms.rst
=> Drop another unnecessary old training data link

docs/pyqgis_developer_cookbook/composer.rst
with Nyall's [suggestions](https://github.com/qgis/QGIS-Documentation/pull/3974#issuecomment-509852898) (fixes #3976)
=> Improve the layout code samples

docs/user_manual/working_with_vector/expression_help/Conversions.rst, docs/user_manual/working_with_vector/expression_help/Date_and_Time.rst, scripts/populate_expressions_list.py
Also update to_date(time) functions help
=> Be less greedy when looking for html tag in function help

docs/server_manual/config.rst
=> Remove max_cache_layer because it does nothing

docs/user_manual/print_composer/create_output.rst
=> Add Image compression setting for PDF output

docs/user_manual/preamble/contributors.rst
Added my name to the "Authors" list.
=> Added my name to the authors list

.github/workflows/backport.yml
=> Fix backport bot

docs/user_manual/introduction/qgis_gui.rst
=> Connect zoom tools to their description

docs/user_manual/introduction/qgis_gui.rst
=> Organize Edit and View menus (fixes #6420)

docs/user_manual/working_with_vector/vector_properties.rst
I don't really like the kind of double negation but couldn't find a more obvious alternative. Suggestions or an alternative example for this feature welcome...
=> Fix constraint expression example

docs/user_manual/processing_algs/qgis/vectorgeneral.rst
Added the new processing algoritm "Flatten Relationship" to
user_manual/processing_algs/qgis/vectorgeneral
Fixes #6002
=> Issue#6002 Flatten Relationship

docs/user_manual/processing_algs/qgis/vectorgeneral.rst
Backport #6367 (too old to be picked by the backport bot, I presume)
=> Describe "Flatten relationship" algorithm

docs/pyqgis_developer_cookbook/loadlayer.rst
Switch from geo-solution to demo.mapserver server and fixes doctest build
=> Replace web server for wxs test

docs/documentation_guidelines/cookbook_guidelines.rst, docs/pyqgis_developer_cookbook/authentication.rst, docs/pyqgis_developer_cookbook/crs.rst, docs/pyqgis_developer_cookbook/expressions.rst
Fixes #3635, fixes #3895 (there are a few remaining assert in authentication test codes particularly, but I have no idea
=> Add a basic expression and remove some assert calls

docs/user_manual/managing_data_source/opening_data.rst
=> Explain Oracle DB connection Options parameter

docs/server_manual/config.rst
By commits, easier to review : 
- Reordering alphabetically, not the best but better than a random order ;-)
- Adding missing environment variable (landing page related and log profile, cc @elpaso )
Help strings are a copy/paste from https://github.com/qgis/QGIS/blob/master/src/server/qgsserversettings.cpp
Linked to #6009 
Backport to release 3.16 will be nice
=> Server environment variable

docs/pyqgis_developer_cookbook/server.rst
shorten sentences, fix typos + few nitpicks
=> Misc fixes to server plugins chapter

docs/user_manual/processing/modeler.rst
=> Update list of modeler inputs type

docs/user_manual/working_with_vector/expression_help/Arrays.rst, docs/user_manual/working_with_vector/expression_help/Conditionals.rst, docs/user_manual/working_with_vector/expression_help/General.rst, docs/user_manual/working_with_vector/expression_help/GeometryGroup.rst, docs/user_manual/working_with_vector/expression_help/String.rst, scripts/populate_expressions_list.py
=> (Un)escape backslashes and html formatted characters in expressions

docs/user_manual/working_with_vector/expression_help/Arrays.rst, docs/user_manual/working_with_vector/expression_help/Conditionals.rst, docs/user_manual/working_with_vector/expression_help/General.rst, docs/user_manual/working_with_vector/expression_help/GeometryGroup.rst, docs/user_manual/working_with_vector/expression_help/String.rst, scripts/populate_expressions_list.py
=> Un)escape backslashes and html formatted characters in expression

conf.py
=> Display out of date banner for 3.10

docs/documentation_guidelines/first_contribution.rst
sptecify that it is ithe github user nadm we are talking about.
Goal:
Ticket(s): #
=>  qualify user name with github

docs/training_manual/processing/hydro.rst, docs/training_manual/processing/modeler_hydro.rst, docs/training_manual/processing/modeler_twi.rst
that I came across reading.
I tried to keep the diff as readable as possible, hence did not split long lines if not necessary.
No update of the screenshots and no testing of tools (I don't have SAGA installed), just a reading of texts - It should still be better than the current doc, IMHO.
=>  Format steps in some of the graphical modeler lessons

docs/server_manual/services.rst
=> Defining format is not mandatory for wms getprint

README.md
fix the minimize_translation script link error of README.md
=> fix the readme link error

docs/user_manual/introduction/qgis_configuration.rst
=> Remove unused setting

docs/pyqgis_developer_cookbook/raster.rst
I don't really know if it refers to the same context but let's say: fixes #3064
Also update list of raster renderer types
=> Add example to get raster band name

docs/pyqgis_developer_cookbook/vector.rst
=> Add embeddedSymbol to list of renderers

docs/user_manual/processing_algs/qgis/vectorselection.rst
Fixes https://github.com/qgis/QGIS/issues/42219
=> Swap "select by ..." algorithm method values

docs/user_manual/working_with_vector/functions_list.rst
Goal:
In the variables list table, the first column name should be "Variable", not "Function".
=> Fix variables list table column name

docs/user_manual/processing_algs/qgis/database.rst
This will add necessary description about added parameter for saving only selected features in package layers algorithm introduced by https://github.com/qgis/QGIS/pull/41542.
=> Address saving only selected objects in package layers algorithm

docs/user_manual/processing/console.rst
and hyperlink to method~s~ documented in pyqgis API
=> Add pygment and line numbers to code blocks

docs/pyqgis_developer_cookbook/vector.rst
=> Add new properties to symbol layer

docs/pyqgis_developer_cookbook/vector.rst
=> small typo

.github/workflows/pofiles.yml
Convenient to update/add new files on Transifex before scheduled dates
Goal:
Ticket(s): #
=> Allow to run the pofiles updates on demand

docs/developers_guide/git.rst
and mention why people would have to care about git and alike...
=> There are so easy ways to install git nowadays

docs/training_manual/create_vector_data/create_new_vector.rst, docs/training_manual/online_resources/wfs.rst, docs/training_manual/qgis_server/install.rst, docs/user_manual/introduction/general_tools.rst, docs/user_manual/introduction/qgis_gui.rst, docs/user_manual/print_composer/composer_items/composer_label.rst, docs/user_manual/style_library/label_settings.rst, docs/user_manual/working_with_ogc/ogc_client_support.rst
=> Fixes substitution references

docs/user_manual/working_with_vector/expression_help/Conversions.rst, docs/user_manual/working_with_vector/expression_help/Date_and_Time.rst, docs/user_manual/working_with_vector/expression_help/String.rst, docs/user_manual/working_with_vector/functions_list.rst
=> Update expression and variable list

docs/user_manual/processing/console.rst
It's unclear to me whether the `is_child_algorithm=true` should be added to both algs or only to the one run within. Took option 2.
=> Fix how to run an algorithm as child of another

redirects.txt
=> Trying another formatting for page redirection

docs/user_manual/processing_algs/qgis/vectorgeneral.rst
(refs https://github.com/qgis/QGIS/pull/42824) and make the screenshot bigger and clickable, for a better reading
=> Remove optional attribute of the 'Flatten relationship' algorithm output

docs/pyqgis_developer_cookbook/vector.rst
=> writeAsVectorFormatV2 is deprecated, use V3

docs/user_manual/auth_system/auth_workflows.rst, docs/user_manual/introduction/general_tools.rst, docs/user_manual/plugins/python_console.rst
=> .qgis2 folder is dead, long live user profile

docs/user_manual/working_with_vector/vector_properties.rst
and the widget is also colored
=> Enforced constraint cross is not red but orange

docs/server_manual/services.rst
According to the specifications (and to the current implementation) LAYERS is also required in addition to QUERY_LAYERS.
=> Fix WMS GetFeatureInfo required LAYERS

docs/user_manual/working_with_vector/expression.rst
I don't know if it should be in this general page, in the layout label item page (and/or in the json example in code) but here it's.
=> Add an example of expression to list features in a layout map item

docs/pyqgis_developer_cookbook/geometry.rst
=> Access (multi)parts of geometries

docs/developers_guide/qtcreator.rst, docs/user_manual/processing_algs/qgis/cartography.rst
=> Add "Align points to features" algorithm

docs/user_manual/print_composer/create_output.rst
=> Condition of "Append georeference info" in layout export

docs/user_manual/introduction/qgis_configuration.rst, docs/user_manual/working_with_projections/working_with_projections.rst
=> Grid files for transformation can be stored in user profile folder

docs/user_manual/style_library/style_manager.rst
=> Load style from QGIS repo is possible

docs/pyqgis_developer_cookbook/loadlayer.rst
Should fix current HTML build fail
=> setDatasource has moved to QgsMapLayer

.github/PULL_REQUEST_TEMPLATE.md
=> Change wording from "required" to "requested"

docs/user_manual/processing/standalone.rst
=> Add multiple parameters to qgis_process call

docs/server_manual/services.rst
Fixes some inconsistencies raised by https://github.com/qgis/QGIS/issues/41051.
=> More precise information about BBOX and axis ordering in WMS

docs/server_manual/services.rst
Fixes https://github.com/qgis/QGIS-Documentation/issues/6732.
=> VERSION parameter is mandatory for GetMap in 1.3.0

conf.py, docs/pyqgis_developer_cookbook/communicating.rst, docs/pyqgis_developer_cookbook/composer.rst, docs/pyqgis_developer_cookbook/vector.rst
The renderer is now picky about mapsettings being
valid, since the test layer had only a single point
feature extent was empty and map settings were not
valid.
=> Fix doctests after QGIS commit 3d31477750

docs/server_manual/services.rst
Goal: Make it more clear that HTML pages could be customized. 
From https://github.com/qgis/QGIS/pull/43363#issuecomment-847703200:
> Having the word "Customize" in the title and thereby in the table of content on the left side of the docs page would be good.
Ticket(s): https://github.com/qgis/QGIS/pull/43363
=> Server OAPIF: Make it more clear that HTML pages could be customized

docs/index.rst, docs/user_manual/preamble/contributors.rst
=> Mention for which version the statistics of translation are provided

.github/workflows/translation_statistics.yml
and run it earlier to show best stats
Goal:
Ticket(s): #
=> Limit scope of the "pull translation stats" workflow

docs/user_manual/introduction/qgis_configuration.rst, docs/user_manual/working_with_vector/editing_geometry_attributes.rst
PR to update the vector editing section with all the pending issues.
Fixes #3735 Fixes #3750 Fixes #4332 Fixes #4879 Fixes #4950 Fixes #6565 Fixes #6582 Fixes #2974 Fixes #5560 Fixes #6599 Fixes #5248
=> Editing update

docs/user_manual/introduction/qgis_gui.rst, docs/user_manual/working_with_vector/vector_properties.rst
=>  Mention the Geometry validation panel
