qgis/QGIS-Documentation

source/docs/training_manual/processing/iterative.rst

line 6 : Let's see one of those situation  --->'situation' should be plural 'situations'
line 20 : Yo can run it using the ----> 'Yo' should be 'You'

Two small typos

---

source/docs/training_manual/processing/batch_conversion.rst

line 32 : let's do it just for the first column.  ---> 'column' should here be 'row'. In fact it is the third column but the first row of that :)

One conversion from 'column' to 'row'

---

source/docs/user_manual/processing/scripts.rst

line 187 : algorithms and, epsecially, ---> 'epsecially' should be 'especially'
line 190 :  such as decalring one output ---> 'decalring' should be 'declaring'
line 192 :  forget that your agorithm might ----> 'agorithm'  should be 'algorithm'

Three small typos

---

source/docs/user_manual/processing_algs/otb/feature_extraction/index.rst

line 3 Feature extrcation  ---> should be  Feature extraction

One small typo

---

source/docs/pyqgis_developer_cookbook/network_analysis.rst

line 307 :  'The Whole algorithm' ---->> should probably be 'The whole algorithm'
line 431 : 'not greater that some value' --->>> should probable be 'not greater than some value'

Small typos

---

source/docs/user_manual/introduction/getting_started.rst

I left no mention to the available languages and their codes, since probably this is not the best place to advertise it anyway.

Removed dead link fixes #359

---

source/docs/pyqgis_developer_cookbook/vector.rst

To iterate over selected features, I wouldn't necessarily recommend processing.features(layer) since it's behavior can be changed in the Processing options. This can lead to different results when a script is run on different machines.

Update section on iterating over selected features

---

source/docs/pyqgis_developer_cookbook/loadlayer.rst

added QgisInterface.addVectorLayer(), QgisInterface.addRasterLayer(), and QgsMapLayerRegistry.instance().mapLayers()

Added iface convenience functions

---

source/docs/user_manual/print_composer/print_composer.rst

@junek , I have edited the attribute table item a bit to clarify (I hope) the way it works with atlas features. Please have a look and feel free to correct any mistakes.

Update print_composer.rst attribute table item

---

source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst

also removed trailing spaces in the doc
sorry, it's not very easy to see the changes
I only changed 2 paragraphes:
* Rotate Feature(s)
* Offset Curves

update offset and rotation map tools according to last features

---

source/docs/user_manual/working_with_ogc/ogc_server_support.rst

Add request list supported by QGIS server for each OGC services

---

source/docs/user_manual/processing_algs/qgis/vector_table_tools/refactorfields.rst

Add help file for processing qgis algorithm named "Refactor fields".
Relates to https://github.com/qgis/QGIS/pull/1753.

Add processing refactor fields help file

---

source/docs/user_manual/plugins/core_plugins.rst
source/docs/user_manual/plugins/plugins_index.rst
source/docs/user_manual/print_composer/print_composer.rst
source/docs/user_manual/working_with_ogc/ogc_server_support.rst
source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst
source/docs/user_manual/working_with_vector/field_calculator.rst
source/docs/user_manual/working_with_vector/vector_properties.rst

Yesterday I was working on fixing the build warnings and I saw too late a 2.8 branch was created. I discussed shortly by email the status with Richard Duivenvoorde and he saw there were many build errors indeed. Today I will continue to fix build errors and I want to apply them to master. These should be merged into 2.8.

fixed build errors user manual

---

source/docs/user_manual/plugins/core_plugins.rst
source/docs/user_manual/plugins/plugins_index.rst
source/docs/user_manual/print_composer/print_composer.rst
source/docs/user_manual/working_with_ogc/ogc_server_support.rst
source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst
source/docs/user_manual/working_with_vector/field_calculator.rst
source/docs/user_manual/working_with_vector/vector_properties.rst

fixes the same build errors for branch 2.8 as in master

fix build errors 2.8

---

source/docs/user_manual/processing_algs/qgis/vector_general_tools/mergedatasourcesinvrt.rst

added documention for mergedatasourcesinvrt processing alg just added with https://github.com/qgis/QGIS/pull/2066

added documention for mergedatasourcesinvrt processing 

---

source/docs/user_manual/print_composer/print_composer.rst

line 819 :  'legend..' ---> should be 'legend." (removed one dot at end of sentence)
line 1780  :  ':: note::'   ---> should be   '.. note::'

Corrected two typos

---

source/docs/user_manual/introduction/general_tools.rst
source/docs/user_manual/introduction/getting_started.rst
source/docs/user_manual/introduction/qgis_configuration.rst
source/docs/user_manual/introduction/qgis_gui.rst
source/docs/user_manual/print_composer/print_composer.rst

Checking spelling - American way!

Spell checking

---

source/docs/user_manual/plugins/plugins_metasearch.rst

update MetaSearch link

---

source/docs/user_manual/processing_algs/qgis/vector_general_tools.rst

[processing] add documentation for the new OBBox algorithm

---

source/docs/training_manual/online_resources/wms.rst

The Spatineo Directory search engine is now located at http://directory.spatineo.com/

Updated the Spatineo Directory URL

---

source/docs/user_manual/processing_algs/qgis/vector_geometry_tools.rst

Describe the new checkvalidity processing algorithm.

Add processing checkvalidity

---

source/docs/user_manual/introduction/general_tools.rst

Updates and additions regarding geometry measurement.
This is my first attempt to contribute to the documentation, so I hope I got the formating right.
I am no native speaker, so please check the language!

Measurement and CRS

---

source/docs/user_manual/processing_algs/qgis/vector_general_tools.rst

Update joinattributesbylocation processing algorithm description with geometrypredicate parameter.

Update processsing joinattributesbylocation

---

source/docs/user_manual/processing_algs/qgis/vector_selection_tools.rst

The functions functions  selectbylocation and extractbylocation use a new parameter 'predicates' in 2.8

Update selectbylocation & extractbylocation

---

source/docs/user_manual/processing/scripts.rst

Add missing documentation for the parameters - selection, name and group

Document additional parameter types

---

source/docs/user_manual/working_with_vector/style_library.rst
source/docs/user_manual/working_with_vector/vector_properties.rst

Add option to symbology to prevent clipping of features

---

source/docs/user_manual/processing_algs/qgis/vector_overlay_tools.rst

Updated documentation as part of the South African hackfest arranged by Tim Sutton.

Updated documentation for vector overlay tools

---

source/docs/pyqgis_developer_cookbook/communicating.rst

fixes https://github.com/qgis/QGIS-Website/issues/213

fix messageBar import example

---

source/docs/user_manual/processing/scripts.rst

Fixes partially #568
Add the parameter "extent" to the list of Processing input parameters

Add extent input parameter

---

source/docs/user_manual/working_with_vector/vector_properties.rst

Add autocompleter for ValueRelation edit widget

---

source/docs/pyqgis_developer_cookbook/plugins.rst

Discussed at
http://osgeo-org.1560.x6.nabble.com/How-do-I-specify-multiple-plugin-authors-td5239517.html. Please let me know if I should create a PR against a different branch.

Correct email visibilty information

---

source/docs/user_manual/working_with_vector/vector_properties.rst

Add follow point alignment for multiline labels

---

source/docs/training_manual/introduction/overview.rst

Does this automatically get pushed to Master if accepted in manual_en_v2.8 branch ?

"File" menu is "Project" in 2.8

---

source/docs/pyqgis_developer_cookbook/plugins.rst

Can save headaches for those using Command Prompt/Powershell when they try to run it and discover it is not in PATH.  Not that I would do such a thing ;)

Add note about using pyrcc4 on Windows

---

source/docs/user_manual/introduction/getting_started.rst

Warn on save if last modification date of a loaded project change

---

source/docs/user_manual/processing_algs/qgis/vector_overlay_tools.rst

Title underline too short

---

source/docs/user_manual/print_composer/overview_composer.rst

Complete Items tab description
Splits long lines

Update Items tab description

---

source/docs/training_manual/introduction/overview.rst

See equivalent Master pull request: https://github.com/qgis/QGIS-Documentation/pull/727

actual menu item in 2.8

---

source/docs/user_manual/introduction/general_tools.rst

Made changes to the grammar and style of the Identify Features section. Also corrected minor errors.

Grammar and style changes to Identify Features

---

source/docs/user_manual/working_with_vector/vector_properties.rst

b4e7ed0 has removed some text changes done in 934d725

Get back reverted changes in b4e7ed0 and update path to images

---

source/docs/user_manual/working_with_ogc/ogc_server_support.rst

[SERVER] GetFeature with an other Geometry

---

source/docs/user_manual/working_with_vector/vector_properties.rst

Add options in categorized renderer advanced menu

---

source/docs/user_manual/working_with_vector/vector_properties.rst

* add information about histogram tab (fix #597)
* add information on new field for color vs size method for creating classes.

Add a graphical histogram for graduated renderer

---

source/docs/user_manual/working_with_vector/vector_properties.rst

Made a couple of changes to the wording to be a little clearer, though still wondering if the line about CRS needs update too.

Metadata textual changes to vector_properties.rst

---

source/docs/user_manual/working_with_vector/style_library.rst

Move the Color ramp section under Style manager chapter

Restructure the Symbol Library chapter

---

source/docs/user_manual/working_with_vector/expression.rst

Imho, the current CASE ELSE description lets think that you get a result only when false.

Fix case function description and example

---

source/docs/user_manual/working_with_vector/vector_properties.rst

Added some contents to the metadata section

Updating the metada tab with some content

---

source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst

Added the "zoom to feature" guide, within the "Working with the attribute table" part.
Since this is my first commit, could someone please review it, just to make sure I am doing it properly?
Thank you.

Propose file changes - Adding Zoom to feature

---

source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst

* Fix #600
* Change shorcut to lowercase

Allow pasting of features in attribute table

---

source/docs/user_manual/print_composer/composer_items/composer_items_options.rst

Grammatical and textual changes to clarify some information. Also altered some translation issues which didn't read perfectly.

textual changes to composer_items_options.rst

---

source/docs/training_manual/basic_map/symbology.rst

menu items that correspond to software/screenshot

---

source/docs/training_manual/basic_map/symbology.rst

For it to actually work and match picture.

'Maximum' -> 'Minimum'

---

source/docs/user_manual/working_with_vector/vector_properties.rst

Add cartographic placement description (fix #750, fix #751)

Update point label placement

---

source/docs/user_manual/grass_integration/grass_integration.rst

Minor grammatical and typo issues picked up. Still a few more, will pick up later

Update GRASS integration.rst

---

source/docs/user_manual/working_with_vector/vector_properties.rst

Describe Labels menu --> Rendering tab options

---

source/docs/user_manual/introduction/getting_started.rst

precise labeling step in example and fix formatting

---

source/docs/user_manual/working_with_vector/expression.rst

add new functions

---

source/docs/documentation_guidelines/README.rst
source/docs/documentation_guidelines/substitutions.rst

Following #793, I propose a new draft of the documentation guidelines.
I made it more verbose because for a beginner, it's not really easy to understand how things are imbricated. @mezwor if you think some points might be more explained, feel free to point them, please.
Given that I learnt things by myself (contributing to QGIS doc) I may not be accurate on some theoretical aspects. So rst or sphinx gurus, your corrections and completions are welcome.

popularize guidelines

---

source/docs/user_manual/introduction/qgis_gui.rst

Map canvas is often used  in GUI and docs to identify this space. Might
be worth adding this info here.

Precise that Map view ==Map canvas

---

source/docs/user_manual/grass_integration/grass_integration.rst

Update minor typos and grammar as well as some text & line widths

Fix typos and grammar in GRASS_integration.rst

---

source/docs/user_manual/introduction/qgis_configuration.rst
source/docs/user_manual/working_with_vector/supported_data.rst

Send filter expressions to postgres provider

---

source/docs/user_manual/grass_integration/grass_integration.rst
source/docs/user_manual/introduction/general_tools.rst

Fix the handful of minor typos in general_tools.rst

Fix minor typos general_tools.rst

---

source/docs/user_manual/working_with_vector/vector_properties.rst

fix partially #736 (might be worth adding a screenshot)

Describe "Control feature rendering order" option

---

source/docs/documentation_guidelines/substitutions.rst
source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst

complete and sort the list to easier next contribution
complete substitution list
fix typos

Complete list of tools in attribute table

---

source/docs/user_manual/preamble/whats_new.rst

Remove changelog description and link to changelog main page in QGIS website

Prepare the changelog in doc

---

source/docs/user_manual/plugins/plugins_gdaltools.rst

fix wrong toc in gdal plugins

---

source/docs/user_manual/processing/3rdParty.rst

Fixes #540
Applied the fix proposed by the reporter. I have no knowledge to check if this is the right solution. @volaya ?

Fix typo error

---

source/docs/user_manual/working_with_vector/expression.rst

fix #794 (using an internal reference rather than a "hard-coded" hyperlink)

Fix link to the Cookbook

---

source/docs/user_manual/introduction/qgis_configuration.rst
source/docs/user_manual/working_with_vector/vector_properties.rst

See https://github.com/qgis/QGIS-Documentation/pull/936 for history

Add description for Statistic Summary panel #936 

---

source/docs/user_manual/introduction/qgis_configuration.rst

Add missing icon for Message Panel

---

source/docs/pyqgis_developer_cookbook/plugins.rst

and rather set the note as warning to emphasize on the subject

minor typo fix

---

source/docs/user_manual/introduction/qgis_configuration.rst
source/docs/user_manual/working_with_vector/style_library.rst
source/docs/user_manual/working_with_vector/vector_properties.rst

and replace reference to statistical summary to avoid it being mistakenly translated
(follow up #936)

Fix some typos

---

source/docs/user_manual/working_with_vector/vector_properties.rst

Add concat as another function of concatenation

---

source/docs/user_manual/working_with_vector/vector_properties.rst

Fix partially #981 (move the screenshots under the section of the tab shown inside)

Better place screenshots in the text

---

source/docs/user_manual/working_with_vector/vector_properties.rst

Replace the list of placement by a numbered list

Emphasize on cartographic placement order

---

source/docs/user_manual/working_with_vector/vector_properties.rst

Fixes #616 
Also fixes `labeling` spelling (en-us compliant) and add some hyperlinks

More description for labeling options

---

source/docs/user_manual/introduction/qgis_configuration.rst

Update Settings --> Data sources tab description

---

source/docs/documentation_guidelines/writing.rst

Given that there's no need to be a developer to contribute to doc, and that code blocks can scare people, I think it might be interesting to also add information about what people can do directly in the web interface, without any code.
The PR also reorganises how comments are shown in the code frame

Add not code-based alternative and fix code frame

---

source/docs/user_manual/processing/3rdParty.rst
source/docs/user_manual/processing/batch.rst
source/docs/user_manual/processing/commander.rst

Make grammatical and spelling changes

update 3rd Party.rst

---

source/docs/user_manual/working_with_vector/vector_properties.rst

fix #617, fix #619, fix #620 
@nyalldawson can you check this and let me know if it covers and explains as expected how you have designed this frame, please?
Thanks

Describe the obstacles options of labels

---

source/docs/documentation_guidelines/do_translations.rst

Trying to improve translation guidelines

Complete the rules summary

---

source/docs/user_manual/appendices/appendices.rst

Fix Cosmetics in License

---

source/docs/user_manual/introduction/getting_started.rst

Fix #630 
Add precision on project behavior at opening
Also remove |qg| replacement and trailing spaces + minor fixes

Add recent projects screenshots

---

source/docs/user_manual/working_with_ogc/ogc_server_support.rst

document the caching of the GetCapabilities response

---

source/docs/user_manual/working_with_ogc/ogc_server_support.rst

Fix #737 
@rldhont Could you take a look if it's explicit enough?

Add short name to QGIS Server layers, groups and project

---

source/docs/user_manual/print_composer/composer_items/composer_map.rst

Custom format for grid annotations

---

source/docs/user_manual/introduction/getting_started.rst

Add information about dxf export in command line

---

source/docs/user_manual/print_composer/create_output.rst

Minor fixes for output

---

source/docs/user_manual/introduction/qgis_gui.rst

Move 'Map Legend' to 'Layer Panel'

---

source/docs/user_manual/introduction/qgis_gui.rst
source/docs/user_manual/working_with_raster/index.rst
source/docs/user_manual/working_with_raster/raster_analysis.rst

* Rename file to raster_analysis instead if raster_calculator
* add Align raster feature

Raster Alignment Tool (Fix #610)

---

source/docs/user_manual/print_composer/composer_items/composer_map.rst

Add data-defined preset on map item

---

source/docs/user_manual/print_composer/composer_items/composer_map.rst

fix reference

---

source/docs/user_manual/introduction/getting_started.rst

* Add authdbdirectory and noversioncheck command line options

Add missing command options

---

source/docs/user_manual/working_with_ogc/ogc_server_support.rst

* cleanup
* change QGIS version number tothe correct version
Fix #580

[server] Possibility to set WMS featureInfo tolerance

---

source/docs/user_manual/working_with_ogc/ogc_server_support.rst

This is more a cleanup commit than an integration of the feature.

getMap in dxf format #611

---

source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst
source/docs/user_manual/working_with_vector/style_library.rst
source/docs/user_manual/working_with_vector/supported_data.rst
source/docs/user_manual/working_with_vector/vector_properties.rst

* Removing trailing spaces
* Add substitutions string
* Add informations on data format/feature type support
* Add informations on vector editing chapter
Fix #608 (New geometry classes)

New geometry support

---

source/docs/user_manual/working_with_vector/vector_properties.rst

* Add concentric ring placement mode for displacement renderer
* Move tips at the top of the section
Fix #642

Add new placement mode for displacement renderer

---

source/docs/pyqgis_developer_cookbook/ide_debugging.rst

Change due to proposition from #497

Add url to Eclipse, Aptana and Pydev

---

source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst

Insert screenshot added by https://github.com/qgis/QGIS-Documentation/commit/70cc7be4b96bbe7a4fa2e71063cf7b0962284680 into the description
Also break some long lines

Add the screenshot of conditional formatting

---

source/docs/user_manual/working_with_vector/vector_properties.rst

Support for relative paths in widgets

---

readme.rst

fix indentation and typo

---

source/docs/user_manual/introduction/qgis_gui.rst

paste style to group

---

source/docs/user_manual/working_with_vector/field_calculator.rst

precision on virtual field behavior
index some terms
split long lines

Complete field calculator description

---

source/docs/user_manual/introduction/general_tools.rst
source/docs/user_manual/working_with_vector/vector_properties.rst

* Move Data-defined section into general tools
Fix #629

Data defined style preset for composer maps

---

source/docs/user_manual/introduction/general_tools.rst

Add Z/M coordinate value availability in Identify tool report

---

source/docs/user_manual/working_with_vector/expression.rst

An introduction for expression chapter

---

source/docs/user_manual/introduction/qgis_gui.rst
source/docs/user_manual/working_with_vector/vector_properties.rst

Fix #696, Fix #706, Fix #708, Fix #709, Fix #744, Fix #745
Complete list of options available in context menu
Add description of Styles sub-items

Complete Layers panel context menu description

---

source/docs/user_manual/working_with_vector/supported_data.rst

Add information on how to create an index with gui

---

source/docs/user_manual/introduction/general_tools.rst

Add icons for data overriden

---

source/conf.py
source/docs/documentation_guidelines/substitutions.rst
source/docs/user_manual/working_with_vector/vector_properties.rst

I also change the replacement of renderers: they look too long and could be simplified

Add their icon and an index tag to layer style renderers

---

source/docs/user_manual/introduction/general_tools.rst
source/docs/user_manual/plugins/plugins.rst

Fix #691, first and draft section for #645 
@SrNetoChan see general_tools.rst file in changes tab

Add support to Plugin Manager

---

source/docs/training_manual/processing/index.rst
source/docs/training_manual/processing/r_intro.rst
source/docs/training_manual/processing/r_syntax-table.rst
source/docs/training_manual/processing/r_syntax.rst

New chapter in the Training manual with tables that summarize the input and output option in R Processing syntax style

R Processing syntax summary table

---

source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst

following [guidelines](http://docs.qgis.org/testing/en/docs/documentation_guidelines/README.html#headlines)

Fix headers underlining

---

source/docs/user_manual/working_with_ogc/ogc_server_support.rst

STARTINDEX param in WFS GetFeature Request

---

source/docs/user_manual/print_composer/composer_items/composer_image.rst

Parameterized svg support for composer svg images

---

source/docs/user_manual/introduction/general_tools.rst

Fix #645, thanks to @dakcarto for review.

Rewrite auth. part

---

source/docs/user_manual/working_with_vector/vector_properties.rst

* Fix #706
* Fix #744 (Add color wheel and edit symbol shortcuts to style menu)
* Superseed PR #1072
* Author: andremano

Edit legend symbols directly from layer tree

---

source/docs/user_manual/working_with_vector/supported_data.rst

Fix note title rendering

---

source/docs/user_manual/grass_integration/grass_integration.rst
source/docs/user_manual/working_with_vector/supported_data.rst

* create a new more generic section (open a file) and merge it from shapefile
and mapinfo file
* chnage the structure of the chapter to add the possibility to describe some
specific behaviours like for directory based format, shapefile, etc.
Fix #670

Show filename in layer name

---

source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst

The digitizing environment has evolved in the last releases but it looks like the doc does not really reflect these changes.
This PR is the first step of the refactoring/updating of all this. It focuses on the settings section:
* add some indices to build the index list
* precise some options behaviour
* add tips and note
Review (especially for english) is very welcome

Editing settings and configuration

---

source/docs/pyqgis_developer_cookbook/plugins.rst
source/docs/training_manual/basic_map/symbology.rst
source/docs/training_manual/complete_analysis/analysis_combination.rst
source/docs/training_manual/foreword/preparing_data.rst
source/docs/training_manual/vector_analysis/basic_analysis.rst
source/docs/user_manual/auth_system/auth_considerations.rst
source/docs/user_manual/introduction/general_tools.rst
source/docs/user_manual/working_with_ogc/ogc_client_support.rst
source/docs/user_manual/working_with_raster/raster_analysis.rst

following this [comment](https://github.com/qgis/QGIS-Documentation/pull/1168#discussion_r70163193)

Replace -> by -->

---

source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst

Description of the automatic tracing capability

---

source/docs/training_manual/processing/r_intro.rst
source/docs/training_manual/processing/r_syntax-table.rst
source/docs/training_manual/processing/r_syntax.rst

* Shorten long lines
* organise title underlining sequence according to [doc guidelines](http://docs.qgis.org/testing/en/docs/documentation_guidelines/writing.html#headlines)
* fix typos
* fix some indentation (text and toc)
@ghtmtt

Cleaning R manual rendering

---

source/docs/training_manual/processing/r_intro.rst
source/docs/training_manual/processing/r_syntax-table.rst
source/docs/training_manual/processing/r_syntax.rst

super small change in link at the top of the page, can be merged without problems

link updated in R Scripts Processing

---

source/docs/documentation_guidelines/first_contribution.rst

Fix hyperlink

---

source/docs/user_manual/working_with_vector/attribute_table.rst

Added text to say you can change column width and it will be saved when
next opened.

Added documentation #1110 for column width

---

source/docs/user_manual/grass_integration/grass_integration.rst

fix minor path

---

source/docs/documentation_guidelines/first_contribution.rst

line 86  #. Redo the previous steps for any other file that needs to be updated to fix
line 87  fix the issue.
removed one word "fix"

double word "fix"

---

source/docs/user_manual/working_with_vector/vector_properties.rst

Add no symbols renderer

---

source/docs/training_manual/processing/r_syntax.rst

line 17 ;  specify teh inputs                     ---->  should probably be  'specify the inputs'
line 23 :  specify the all the input types   ---> should probably be; 'specify all the input types'
line 65 :  the extend of an input layer::    ---> should probably be;  'the extent of an input layer::'
line 87 :  pass to it                                   ---> should probably be;  'pass it to'

Several typo's in file

---

source/docs/training_manual/basic_map/symbology.rst
source/docs/training_manual/map_composer/map_composer.rst

Improving "Creating a Custom SVG Fill" description

---

source/docs/training_manual/foreword/preparing_data.rst

Show where and which dem to download

---

source/docs/training_manual/foreword/foreword.rst

Training Manual updated link to download data

Updated link of TM data 2_14

---

source/docs/user_manual/print_composer/composer_items/composer_image.rst
source/docs/user_manual/print_composer/composer_items/composer_items_shape.rst

Also add indices and references and fix typos

Add precision on composer node-based shapes

---

source/docs/training_manual/basic_map/vector_data.rst

Add precision about location of landuse.sqlite file

---

source/docs/training_manual/processing/r_syntax.rst

no big changes, just a small typo

Forget an `s` in the input parameters

---

source/docs/user_manual/introduction/qgis_configuration.rst

as discussed in https://github.com/qgis/QGIS-Documentation/issues/758#issuecomment-215051691
Also fix #952

Move transaction option from Settings to project properties

---

source/docs/training_manual/foreword/foreword.rst
source/docs/training_manual/foreword/preparing_data.rst
source/docs/training_manual/introduction/preparation.rst

New clean PR for the new training data link (master)

Training Manual link for downloading data updated (new repo)

---

source/docs/training_manual/processing/r_intro.rst
source/docs/user_manual/processing/3rdParty.rst

actually 2.14 doc ends up with a link in testing doc (click the link in the [note](http://docs.qgis.org/2.14/fr/docs/training_manual/processing/r_intro.html#use-r-scripts-in-processing) )

Better use dynamic link rather than static

---

source/docs/user_manual/working_with_vector/expression.rst

Add char() function

---

source/docs/gentle_gis_introduction/index.rst
source/docs/training_manual/foreword/foreword.rst

Avoid a link to testing doc in LTR 2.14 doc
Backporting #1259

Better use internal dynamic link rather than static

---

source/docs/user_manual/introduction/qgis_gui.rst

Couldn't find an issue report for this but information is available at http://qgis.org/en/site/forusers/visualchangelog216/index.html#feature-statistics-for-string-and-date-fields

Statistics summary are available for string and date data

---

source/docs/documentation_guidelines/writing.rst

If someone has a better wording???

Add new section level

---

source/docs/user_manual/working_with_vector/expression.rst

Add aggregates functions

---

source/docs/documentation_guidelines/first_contribution.rst

Small addition that explains how to add contribution to other branches (for example LTR 2.14 doc).

New section in doc guidelines

---

source/docs/user_manual/working_with_ogc/ogc_server_support.rst
source/docs/user_manual/working_with_vector/supported_data.rst

I couldn't find at first glance any ``.. attention::``or ``.. important::`` tag, can somebody point me to it if it exists?

Added pg_service file documentation

---

source/docs/user_manual/introduction/general_tools.rst

Hi,
I've added some text explaining the new feature of saving spatial bookmarks in the project file. I couldn't fine a new Feature issue for it. This is the first change I've done, so wanted to do something simple first!
Please let me know if what I've done is right, or I should have done anything differently. By the way, I found the step-by-step guide useful - thanks!
Best wishes,
Nick.

Saving Spatial Bookmarks in the QGIS project file

---

source/docs/documentation_guidelines/first_contribution.rst

Add information that 2.14 is available for fixes
also fix line adornment sequence

More precision on git contribution steps

---

source/docs/user_manual/working_with_vector/expression.rst

Add project function

---

source/docs/user_manual/working_with_vector/vector_properties.rst

Fix #1098 and #1102
* Add Oracle and MSSQL support to save style in DB.
* Add note about the difference between local db and ds database.

[mssql] Save styles to the database in MSSQL

---

source/conf.py

fix a wrong replacement in doc guideline

set 2.14 as current release in 2.14 branch

---

source/docs/user_manual/introduction/general_tools.rst

Improvements to map zooming

---

source/docs/user_manual/working_with_vector/vector_properties.rst

and more info on html option
fix #1105 and somehow (though already closed, fix #1113)

Map tips are persistent over sessions

---

source/docs/user_manual/introduction/qgis_configuration.rst

* Add new unit in the options section
* Move project properties section after the options section
Fix #850

Add km, yards and miles to distance unit options

---

source/conf.py

Remove disclaimer text at the top of 2.14 doc

---

source/docs/user_manual/working_with_vector/vector_properties.rst

* Add capability to rename fields
* Add alias and comment information
Fix #1108

Allow renaming fields

---

source/docs/user_manual/working_with_vector/supported_data.rst

Rephrasing some sentences for Postgis layers

---

source/docs/user_manual/introduction/qgis_configuration.rst
source/docs/user_manual/working_with_vector/attribute_table.rst

Default view can be set for attribute table

---

source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst

Reshape tool extends linestring geometries

---

source/docs/user_manual/working_with_vector/vector_properties.rst

new tabs can be added to layer properties dialog

---

source/docs/user_manual/working_with_vector/attribute_table.rst
source/docs/user_manual/working_with_vector/vector_properties.rst

* hide columns, organize, set with vs autosize
* better index entry
Fix #1111

Add display properties to attribute table

---

source/docs/user_manual/working_with_vector/vector_properties.rst

Widgets constraints

---

source/docs/user_manual/processing/modeler.rst

line 323 : .....Prcoessing  ----> should be Processing

corrected typo

---

source/docs/user_manual/processing_algs/qgis/vector_selection_tools.rst

line 89 ;  ...the precicates..    should be  the predicates

typo corrected

---

source/docs/user_manual/processing_algs/qgis/vector_geometry_tools.rst

Line 35:  Ouput        ---> should be   Output
Line 38:  additionnal ---> should be   additional

typo's corrected

---

source/docs/user_manual/introduction/general_tools.rst

Emphasize on data-defined buttons behaviour

---

source/docs/user_manual/introduction/general_tools.rst

Improve selection tool behavior

---

source/docs/user_manual/processing_algs/qgis/vector_geometry_tools.rst
source/docs/user_manual/processing_algs/qgis/vector_overlay_tools.rst

Description of
1. Dissolve
2. Eliminate sliver polygons
3. Split lines with lines
These were chosen because I either made (2., 3.) or improved them (1.).

Describe processing algorithms

---

source/docs/user_manual/working_with_vector/vector_properties.rst

more coherent and explanatory about what external plugins are.
And not all external plugins are available in our repo.

replace externe hyperlink with reference

---

source/docs/user_manual/auth_system/auth_considerations.rst
source/docs/user_manual/auth_system/auth_overview.rst
source/docs/user_manual/auth_system/auth_workflows.rst
source/docs/user_manual/index.rst
source/docs/user_manual/introduction/getting_started.rst
source/docs/user_manual/introduction/qgis_gui.rst
source/docs/user_manual/plugins/plugins_coordinate_capture.rst
source/docs/user_manual/plugins/plugins_dxf2shape_converter.rst
source/docs/user_manual/preamble/preamble.rst
source/docs/user_manual/processing/scripts.rst
source/docs/user_manual/processing_algs/lidartools/blast2dem.rst
source/docs/user_manual/processing_algs/lidartools/blast2iso.rst
source/docs/user_manual/processing_algs/lidartools/las2dem.rst
source/docs/user_manual/processing_algs/lidartools/las2iso.rst
source/docs/user_manual/processing_algs/lidartools/las2las_filter.rst
source/docs/user_manual/processing_algs/lidartools/las2las_transform.rst
source/docs/user_manual/processing_algs/lidartools/lasgrid.rst
source/docs/user_manual/working_with_vector/attribute_table.rst

in user manual, for consistency
ref #1382

Add |updatedisclaimer| tag at the top of each file

---

source/docs/user_manual/working_with_ogc/ogc_client_support.rst

Are you aware of any other standards that are supported now and should be added?

added CSW & WPS support

---

source/docs/user_manual/introduction/getting_started.rst

- Updates the qgis --help command output to the latest version.
Fixes #1383

Command line Updates Fixes #1383

---

source/docs/user_manual/working_with_ogc/ogc_server_support.rst

to remove figure and description from code sample

Fix indentation

---

source/docs/user_manual/processing_algs/qgis/vector_general_tools.rst

Clean parameters display

---

source/docs/user_manual/working_with_vector/expression.rst

with no table larger than 80 characters.
I have the feeling that tables that are not wider than 80 characters are less (or not) buggy in pdf (still fighting against #1135)
also fix some "too large" code-blocks

Refactor lists of expression functions

---

source/docs/user_manual/working_with_vector/vector_properties.rst

as the prepared section has meanwhile been added at http://docs.qgis.org/testing/en/docs/user_manual/introduction/general_tools.html#use-of-variables-for-dynamic-content

Remove useless comments

---

source/docs/user_manual/introduction/general_tools.rst

Given that code sample is within a code block, |current| is not substituted and the example may not be really clear --> I replace the tag by a value.

fix code sample

---

source/docs/user_manual/introduction/general_tools.rst

(cherry picked from commit 2bef13984d906bb1b42126129779fd50776d5bfa)

fix display typo

---

source/docs/user_manual/preamble/preamble.rst

remove the link to qgis wiki page

Fix link to contribution details

---

source/docs/user_manual/processing_algs/gdalogr/gdal_analysis.rst
source/docs/user_manual/processing_algs/otb/image_filtering.rst
source/docs/user_manual/processing_algs/qgis/vector_selection_tools.rst

minor fix to better display [this](http://docs.qgis.org/testing/en/docs/user_manual/processing_algs/gdalogr/gdal_analysis.html#id15) or [just above that](http://docs.qgis.org/testing/en/docs/user_manual/processing_algs/gdalogr/gdal_analysis.html#id30)

minor rendering fixes

---

source/docs/user_manual/working_with_vector/supported_data.rst

fix #1214 
supersedes #1226 (I completed @nickbearman PR with points discussed there)

Added information on use of CSVT files

---

source/docs/user_manual/introduction/general_tools.rst
source/docs/user_manual/working_with_raster/raster_properties.rst
source/docs/user_manual/working_with_vector/vector_properties.rst

Describe the layer styling dock

---

source/docs/pyqgis_developer_cookbook/loadlayer.rst

@elpaso are you ok with this rendering?
Also standardize indices (at least first letter upper cased for consistency) and move some to the convenient place

Fix text rendering and some indexing

---

source/docs/user_manual/working_with_ogc/ogc_server_support.rst

@elpaso @andreasneumann  Is there a reason not to put this commit on master?
Fix #966

Added information on DEFAULT_DATUM_TRANSFORMATION in QGIS Server

---

source/docs/user_manual/working_with_ogc/ogc_server_support.rst

This reverts commit 43e87356c64d6515f22afcd405b0151f626083cc
as the code is for QGIS >= 2.16

Revert docs on "DEFAULT_DATUM_TRANSFORMATION in Server"

---

source/docs/user_manual/working_with_ogc/ogc_server_support.rst

see twitter discussion: https://twitter.com/geojulien/status/791571013905645568

fix WFS version implemented

---

source/docs/user_manual/introduction/qgis_gui.rst
source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst

Describe the rotate and offset point Symbols tools

---

source/docs/user_manual/working_with_ogc/ogc_server_support.rst

Fix supported version of wfs in 2.14 doc

---

source/docs/user_manual/introduction/general_tools.rst

Emphasize on general behaviour of the dialog and fix some comments that no longer apply

Reorganising measure tools description

---

source/docs/documentation_guidelines/writing.rst

Add rules about doc indexing

---

source/docs/user_manual/introduction/general_tools.rst

Show stats for string & date fields in stats dock

---

source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst

Layers can be set read-only

---

source/docs/user_manual/introduction/qgis_configuration.rst
source/docs/user_manual/introduction/qgis_gui.rst
source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst

Update and complete description of every setting in the Options dialog
Add links from some settings to other chapters that better treats the
setting

Description of the Options dialog

---

source/docs/user_manual/working_with_raster/raster_properties.rst
source/docs/user_manual/working_with_vector/vector_properties.rst

refs #1115  and minor cleanups

Add description of legend menu in properties

---

source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst

with tips and tricks and improve some descriptions (factorize merge tools)

Update editing chapter 

---

source/docs/pyqgis_developer_cookbook/raster.rst

Updated file to reflect setCacheImage() being deprecated.

Reflect setCacheImage being deprecated

---

source/docs/user_manual/working_with_vector/vector_properties.rst

This PR structures and describes features inside Layer properties --> Fields tab (form customization, edit widget). 
fix #1399, fix #944, fix #1313, fix #1415 
ref #705, #1365 
Review welcome...

Describe forms creation and customization

---

source/docs/user_manual/working_with_vector/expression.rst

fixes #1271, fixes #1272 and fixes #1358

Add new expressions

---

source/docs/training_manual/foreword/foreword.rst

Add issue tracker to training materials

---

source/docs/user_manual/working_with_vector/vector_properties.rst

Refs https://github.com/qgis/QGIS-Documentation/issues/1365

Variables can be used in default value

---

source/docs/user_manual/working_with_vector/vector_properties.rst

Add substitute texts list in labeling

---

source/docs/user_manual/introduction/general_tools.rst

fix https://github.com/qgis/QGIS-Documentation/issues/1466

Add append/overwrite options when saving layer

---

source/docs/user_manual/introduction/general_tools.rst

Format the description
Add tip on "identifiable" feature
Also fix #1203

Structure the Identify tool description

---

source/docs/user_manual/preamble/help_and_support.rst

Remove closed lists and mention QGIS User Groups

Update mailing lists

---

source/docs/user_manual/introduction/qgis_configuration.rst

Layers can be set read only

---

source/docs/documentation_guidelines/first_contribution.rst

when using the "Fix Me" shortcut.

Committers directly write to QGIS-Doc master branch

---

source/docs/user_manual/introduction/general_tools.rst

Organize the description of this dialog into subsections
Fix #946 (possibility to select fields to keep)
Also fix #1024 (possibility to select raw/displayed values)

Format and expand the "save as file" dialog description

---

source/docs/training_manual/foreword/preparing_data.rst

Add zoom full icon to help see layer extent

---

source/docs/documentation_guidelines/first_contribution.rst
source/docs/pyqgis_developer_cookbook/authentication.rst
source/docs/pyqgis_developer_cookbook/geometry.rst
source/docs/pyqgis_developer_cookbook/ide_debugging.rst
source/docs/pyqgis_developer_cookbook/plugins.rst
source/docs/pyqgis_developer_cookbook/raster.rst
source/docs/pyqgis_developer_cookbook/snippets.rst
source/docs/pyqgis_developer_cookbook/vector.rst
source/docs/user_manual/plugins/plugins_oracle_raster.rst
source/docs/user_manual/processing/3rdParty.rst
source/docs/user_manual/processing/commander.rst
source/docs/user_manual/processing/console.rst
source/docs/user_manual/processing/scripts.rst
source/docs/user_manual/working_with_ogc/ogc_server_support.rst

This adds highlights to code snippets according to their language (not all -even python ones- were recognised)
Bonus: also highlight code in github preview --> is it worth doing it for all code samples?

Set code-blocks pygments for a better rendering

---

source/docs/user_manual/introduction/general_tools.rst

Layer Styling panel embeds many other dialogs

---

source/docs/user_manual/introduction/general_tools.rst

Fix #1471 
Also create subsection to ease reading
and expand description on restore/save default style behavior

Mention GeoPackage as supported format to save layer style

---

source/docs/user_manual/introduction/qgis_gui.rst
source/docs/user_manual/working_with_vector/attribute_table.rst

Edit attributes of multiple features simultaneously is possible

---

source/docs/user_manual/plugins/plugins_metasearch.rst

supersede #1739 (sorry @tomkralidis for the noise)

Add MetaSearch HTTP Basic Authentication

---

source/docs/developers_guide/codingstandards.rst

Some updates to the coding standards docs - these are guidelines which are well accepted by current core developers, they just aren't documented yet!

Developer guide updates

---

source/docs/user_manual/index.rst

Move the print composer chapter after the Raster one...

Move Print composer chapter

---

source/docs/user_manual/working_with_vector/style_library.rst

Fixes #710, fixes #947, fixes #951, fixes #977, fixes #984, fixes #998, fixes #1015

Overview of the symbol layer types

---

source/docs/user_manual/introduction/qgis_configuration.rst

Replace section title

---

source/docs/user_manual/introduction/getting_started.rst

in the getting started chapter

Mention link to other releases INSTALL file

---

source/docs/user_manual/auth_system/auth_overview.rst

Put it in the text and not as a code-block

Fix path to authentication DB

---

source/docs/user_manual/introduction/general_tools.rst
source/docs/user_manual/working_with_raster/raster_properties.rst
source/docs/user_manual/working_with_vector/vector_properties.rst

@andreasneumann If you want to review...

Highlight the Embed layers and groups feature

---

source/docs/user_manual/plugins/plugins.rst

Fixes #1666 
The description has also been refined in https://github.com/DelazJ/QGIS-Documentation/commit/9b11865a3b5c1687784f4814cfeef85abbb1dd93 (compatible with 2.18)

Plugins can be added from a ZIP file

---

source/docs/user_manual/plugins/plugins_heatmap.rst

The link for the heatmap tutorial is out of date so I updated it to Ujaval Gandhi's tutorial pages at qgistutorials.com

Update heatmap tutorial link in user manual

---

source/docs/user_manual/introduction/qgis_gui.rst

nota: the first commit (DelazJ/QGIS-Documentation@9bccd6b) can be backported to 2.18

Add gui tools

---

source/docs/user_manual/working_with_vector/expression.rst

Documents date, datetime and time subtraction and addition in users manual

---

source/docs/user_manual/working_with_vector/attribute_table.rst
source/docs/user_manual/working_with_vector/vector_properties.rst

* Allow adding a new column to trigger an action to the attribute table
* Allow reordering the attribute table columns
cleanup and adding more missing informations
Fix #1003

New configuration options for attribute table

---

source/docs/user_manual/working_with_vector/supported_data.rst

Basic support for Oracle Workspace Manager

---

source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst

Parse clipboard text so that GeoJSON can be pasted

---

source/docs/user_manual/working_with_gps/plugins_gps.rst

Adds support for GNSS receivers

---

source/docs/training_manual/qgis_server/install.rst
source/docs/user_manual/introduction/general_tools.rst
source/docs/user_manual/working_with_gps/plugins_gps.rst
source/docs/user_manual/working_with_vector/attribute_table.rst
source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst
source/docs/user_manual/working_with_vector/supported_data.rst
source/docs/user_manual/working_with_vector/vector_properties.rst

@pcav @yjacolin please do not forget that we are managing two branches and that changes should be processed in both branches, otherwise we lose information. The earlier the backport is done, I think the best it is.
Opening a PR to ensure Travis stays happy and would like you to check if I caught all your recent changes (_should be the case_). was not easy because @tudorbarascu had backported some changes but might not have seen all the others.

Backport recent changes

---

source/docs/user_manual/working_with_vector/expression.rst

Add few example to expression functions

---

source/docs/user_manual/processing_algs/qgis/vector_geometry_tools.rst

[processing] Algorithm 4 calculating feature bbox

---

source/docs/user_manual/working_with_vector/attribute_table.rst

Add N:M relation editing possibilities

---

source/docs/user_manual/working_with_vector/attribute_table.rst

[BP] Add N:M relation editing possibilities

---

source/docs/user_manual/working_with_vector/supported_data.rst

Add PostGIS Timestamp support (Fix 678)

---

source/docs/user_manual/working_with_vector/supported_data.rst

[BP] Postgres provider: add support for timestamp types

---

source/docs/user_manual/introduction/qgis_configuration.rst

Plugins (refs #1743) and Processing (refs #1744 ) options are available in General Options dialog

New capabilities of the Options dialog

---

source/docs/user_manual/processing_algs/qgis/vector_overlay_tools.rst

[processing] Optimise processing clip algorithm

---

source/docs/user_manual/working_with_vector/expression.rst

Structure the chapter and add links to other sections

Aerate introductory part of Expressions

---

source/docs/user_manual/working_with_vector/style_library.rst

Fixes https://issues.qgis.org/issues/4415

Precision on centroid fill placement

---

source/docs/user_manual/print_composer/composer_items/composer_items_options.rst

Fixes variable level in composer item

---

source/docs/user_manual/processing_algs/qgis/vector_geometry_tools.rst

[processing] New algorithm for geometry boundary

---

source/docs/user_manual/processing_algs/qgis/vector_geometry_tools.rst

[processing] Algorithm for merging connected lines

---

source/docs/user_manual/processing_algs/qgis/vector_geometry_tools.rst

[processing] Point on surface algorithm

---

source/docs/user_manual/working_with_ogc/ogc_client_support.rst

* Fix #957
* cleanup old comments
* removing trailing spaces

[WFS provider] add WFS 1.1 & 2.0 support

---

source/docs/documentation_guidelines/do_translations.rst
source/docs/documentation_guidelines/writing.rst
source/docs/training_manual/database_concepts/adding_data.rst
source/docs/training_manual/database_concepts/data_model.rst
source/docs/training_manual/database_concepts/db_intro.rst
source/docs/training_manual/database_concepts/queries.rst
source/docs/training_manual/database_concepts/rules.rst
source/docs/training_manual/database_concepts/views.rst
source/docs/training_manual/spatial_databases/geometry.rst
source/docs/training_manual/spatial_databases/import_export.rst
source/docs/training_manual/spatial_databases/simple_feature_model.rst
source/docs/training_manual/spatial_databases/spatial_functions.rst
source/docs/training_manual/spatial_databases/spatial_queries.rst
source/docs/user_manual/grass_integration/grass_integration.rst

to have them pygment highlighted

Add code-block directive to code snippets frame

---

source/docs/user_manual/processing_algs/qgis/vector_geometry_tools.rst

Update dissolve algorithm description

---

source/docs/user_manual/working_with_ogc/ogc_client_support.rst

* Fix #957
* cleanup old comments
* removing trailing spaces

[BP] [WFS provider] add WFS 1.1 & 2.0 support

---

source/docs/pyqgis_developer_cookbook/plugins.rst

Fixes https://issues.qgis.org/issues/16062
superseed #1620

Update plugins translation

---

source/docs/documentation_guidelines/writing.rst

Adding special comments rules to guidelines

---

source/docs/pyqgis_developer_cookbook/geometry.rst

following https://github.com/qgis/QGIS-Documentation/pull/1833#pullrequestreview-35465035

Creating a geometry from WKB changed

---

source/docs/user_manual/introduction/general_tools.rst
source/docs/user_manual/working_with_vector/attribute_table.rst

to general tool chapter
Another bit on the way to structure the attribute table dialog (as exposed in #1754)

Improve Features selection by moving some text from attribute table section

---

source/docs/pyqgis_developer_cookbook/ide_debugging.rst

Remove broken link to debug QGIS

---

source/docs/user_manual/working_with_vector/attribute_table.rst

Contextualize the conditional formatting

---

source/docs/user_manual/working_with_vector/attribute_table.rst

This is a work in progress because I have question and need help/.
1/ Because it's no longer about 1-N relation, I rename and restructure the sections to help identify main sections and dependencies. Will look like this
2/ In N-M relation section, instead of using `shop<->product` relation, i opted to use `airport<->airlines` relation, ensuring a kind of continuity with the 1-N relation example (`airports<->regions`). ~~But,~~
- ~~is there a way/place to find data of airlines that may be of interest for us ie list of airlines flying to Alaska airports?~~
- ~~this would help to add more screenshots (that I missed) such as:~~
- ~~Project properties --> relations tab with both relations configured~~
- ~~Form dialog sample~~
- ~~Maybe Layer Properties --> Fields dialog in case it's …

Improve working with relations 

---

source/docs/user_manual/working_with_vector/attribute_table.rst

Allow copying features from QGIS in GeoJSON format

---

source/docs/training_manual/create_vector_data/forms.rst

Using tinyURL does not make sense to me in this case

replaced tinyURL with the real link

---

source/docs/user_manual/working_with_vector/vector_properties.rst

in categorized symbology (follow-up https://github.com/qgis/QGIS-Website/issues/449)
Giving a look to the docs, it isn't obvious the kind of expression you can use to classify data and not easy to explain what is allowed (or what could make sense for the engine).
I fail to find cases one can use a CASE ... ELSE expression in that expression box and to return which classes?
Any ideas @yjacolin @SrNetoChan @nyalldawson and others...?

Trying to explain expression use case for classification

---

qgis-projects/user_manual/drag_n_drop_form_designer.qgs
qgis-projects/user_manual/introduction_qgis_general_tools_annotation.qgs
qgis-projects/user_manual/introduction_qgis_gui_start_up.qgs
qgis-projects/user_manual/macro_example.py
qgis-projects/user_manual/multivariate_example.qgs
qgis-projects/user_manual/working_with_rasters.qgs
qgis-projects/user_manual/working_with_vector_02.qgs
qgis-projects/user_manual/working_with_vector_supported_data.qgs
qgis-projects/user_manual/working_with_vectors_diagrams.qgs
qgis-projects/user_manual/working_with_vectors_relations.qgs

@SrNetoChan I had to do some screenshots and encountered the "handle bad layers" dialog so here is a (extended to folder) fix

Fix path to data and macro indentation

---

source/docs/user_manual/introduction/general_tools.rst
source/docs/user_manual/introduction/qgis_configuration.rst
source/docs/user_manual/managing_data_source/create_layers.rst
source/docs/user_manual/managing_data_source/opening_data.rst
source/docs/user_manual/plugins/plugins_georeferencer.rst
source/docs/user_manual/working_with_ogc/ogc_client_support.rst
source/docs/user_manual/working_with_raster/raster_properties.rst
source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst
source/docs/user_manual/working_with_vector/style_library.rst
source/docs/user_manual/working_with_vector/vector_properties.rst

Prepares the structure to ease doc links from QGIS Desktop, by adding anchors to sections
Also fixes some typos and formatting

Various fixes and add anchors

---

ISSUE_TEMPLATE.md

Trying to avoid unrelated issue reports.
@rduivenvoorde is this "compatible" with the automatic creation of issue reports from QGIS repo?

Create an issue template file

---

source/docs/index.rst

Any reason for the exclamation mark in Table Of Contents?

The right spelling is "Testing" and not "Testing!"

---

source/docs/user_manual/managing_data_source/opening_data.rst

Adding information on DB credentials storage

---

source/docs/user_manual/working_with_ogc/server/index.rst
source/docs/user_manual/working_with_ogc/server/services.rst

This PR update `GetMap` request documentation in QGIS Server.
In the next stage (in another PR), I would like to provide some screenshots for parameters like `BGCOLOR`, `OPACITIES`, ...

Update GetMap documentation

---

source/docs/user_manual/working_with_vector/vector_properties.rst

line 1807:   http://nathanw.net/2011/09/05/....   should be HTTPS now:      https://nathanw.net/2011/09/05/......

Updated link

---

source/docs/developers_guide/codingstandards.rst

Because we want developers to write good API documentation :)

Add notes about comments to the coding standards

---

source/docs/user_manual/introduction/qgis_configuration.rst

Because those options are better described elsewhere.

Connecting chapters

---

source/docs/user_manual/introduction/general_tools.rst

Custom tabs can be added to Layer Styling Panel

---

source/docs/training_manual/processing/r_syntax-table.rst

Fix typo in R syntax table

---

source/docs/training_manual/processing/r_syntax-table.rst
source/docs/user_manual/plugins/plugins_heatmap.rst

A link in the user manual was pointed at an old site.

 Update broken link in user manual

---

source/docs/gentle_gis_introduction/vector_data.rst

Correcting typo

---

source/docs/user_manual/processing_algs/qgis/layer_tools.rst

and not in Parameters' (see http://docs.qgis.org/testing/en/docs/user_manual/processing_algs/qgis/layer_tools.html#extract-layer-extent)

Move the screenshot to the description section

---

source/docs/user_manual/working_with_vector/expression.rst

Fix #1980 - Add array_first and array_list to the array functions on the expressions page

fix #1980 Add array_first and array_last functions

---

source/docs/user_manual/working_with_vector/expression.rst

Fix #2028 - Add array_reverse function to the array functions on the expressions page

fix #2028 Add array_reverse function

---

source/docs/user_manual/working_with_vector/expression.rst

Fix #2032 - Add array_slice function to array functions on expressions page

fix #2032 - Add array_slice function

---

source/docs/user_manual/managing_data_source/create_layers.rst

cherry-picked from #2258  (+ some changes on memory layers)

Some clarification and consistency in Create layers chapter

---

source/docs/user_manual/working_with_vector/expression.rst

Fix #1925 Add create_ramp function to the color functions on the expressions page

fix #1925 - Add create_ramp function

---

source/conf.py
themes/qgis-theme/genindex.html

@rduivenvoorde you disabled the index generation in f60a061cf3f1185ee0058316dcde78596c711733. Is it still valid?

Re-enable index list generation

---

REQUIREMENTS.txt

@rduivenvoorde Build is broken. Is this right?

remove dep which breaks docker image creation

---

source/docs/user_manual/working_with_vector/vector_properties.rst

Very small change to the description of available renderers for polygons.
This can be ported to master

Small fix of polygons renderes description.

---

source/docs/user_manual/introduction/getting_started.rst

Add a little paragraph about `.qgz` format.
Fix #2019
Fix #2020
Fix #2021

Zip format for projects

---

source/docs/user_manual/working_with_vector/attribute_table.rst

Added shortcuts & more consistent headings

---

source/docs/user_manual/working_with_vector/expression.rst

Fix #1981 Add with_variable function to general functions on expressions page.

fix #1981 - Add with_variable function

---

source/docs/user_manual/processing_algs/qgis/vector_selection_tools.rst

Description of all the Vector Selection algorithms of Processing.
No pictures added, descriptions are self explanatory (IMHO). 
Fix #2075 fix #1946 fix #1528 fix #1483

[Processing] vector selection tool chapter

---

source/docs/user_manual/processing_algs/qgis/file_tools.rst
source/docs/user_manual/processing_algs/qgis/index.rst

File tools chapter with single `Download file` algorithm
@Gustry: if you have some detailed example of usage feel free to suggest ;)

[processing] new chapter file tools

---

source/docs/pyqgis_developer_cookbook/vector.rst

Fixes a few typos on the Vectors Cookbook page

Fix vector cookbook typos

---

source/docs/training_manual/database_concepts/rules.rst

As discussed on https://lists.osgeo.org/pipermail/qgis-community-team/2018-January/004966.html

More fitting heading

---

source/docs/user_manual/working_with_ogc/server/getting_started.rst

keeping one place to update (fix https://github.com/qgis/QGIS-Documentation/issues/2246)

Refer to QGIS website for installation instructions

---

source/docs/user_manual/print_composer/create_output.rst

I've been told that the current description does not reflect what is actually done. So trying to reformulate (according to what i experimented) and add precision. If someone gets inspiration...

Describe print composer crop to content option

---

source/conf.py
source/docs/documentation_guidelines/substitutions.rst
source/docs/user_manual/introduction/general_tools.rst
source/docs/user_manual/managing_data_source/create_layers.rst
source/docs/user_manual/print_composer/composer_items/composer_map.rst

This is the first of multiple files that need to be updated to address #1229

Renamed visibility presets to map themes

---

source/docs/user_manual/processing_algs/qgis/vectortable.rst

trying to fix Travis complaining

[processing] generic code block for python calculator

---

source/docs/user_manual/working_with_ogc/server/services.rst

Document GetFeatureInfo FILTER_GEOM

---

source/docs/gentle_gis_introduction/coordinate_reference_systems.rst

Added some text and relatable concepts to the projection topic.

Fixed some changes in the projections document

---

source/docs/user_manual/working_with_vector/vector_properties.rst

following dialog refactoring (refs #2305)
This is just a first step to update that dialog: only section moves are done and for a few number, introduction reviewed to match new name.

Reorganize Vector Properties sections

---

source/docs/user_manual/working_with_projections/working_with_projections.rst
source/docs/user_manual/working_with_raster/raster_properties.rst

following dialog refactoring (fix #2305)

Reorganize raster properties section

---

source/docs/user_manual/processing_algs/qgis/modelertools.rst
source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst

to modeler-only tools group (Fixes #2319)

Move variable distance buffer algorithm

---

source/docs/user_manual/processing_algs/qgis/vectoranalysis.rst

fix wrong algorithm name

---

source/docs/user_manual/working_with_vector/vector_properties.rst

I could not find the new location of the blog

removed dead link and corresponding text

---

source/docs/user_manual/plugins/plugins.rst

Fixes #2169 
Update information on plugins storage
Also mention use of icon on status bar instead of text for updates (fixes #2296)
Fixes #2211, Fixes #2186

Update ZIP install description

---

source/docs/user_manual/processing_algs/qgis/vectorselection.rst

[processing] update Extract by attribute fix #1772

---

source/docs/pyqgis_developer_cookbook/communicating.rst

no big changes, just small correction to new API

[pyqgis] update the communication chapter

---

source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst

[processing] update point on surface

---

source/docs/pyqgis_developer_cookbook/canvas.rst
source/docs/pyqgis_developer_cookbook/loadproject.rst
source/docs/pyqgis_developer_cookbook/network_analysis.rst
source/docs/pyqgis_developer_cookbook/plugins.rst
source/docs/pyqgis_developer_cookbook/server.rst
source/docs/pyqgis_developer_cookbook/vector.rst

My first pull request to the documentation finally ;-)
I will try to update the cookbook with API break that I could noticed.

update from PyQt4 to qgis.PyQt

---

source/docs/developers_guide/git.rst

I fail to see what it's about nor how it could smooth the process...

Remove recommandation to use wiki

---

source/docs/user_manual/working_with_vector/vector_properties.rst

fix #1500
fix #1501
Fix #2203 
fix #2132

 Add more description on fields constraints settings 

---

source/docs/user_manual/introduction/qgis_configuration.rst

Fixes #1681 
Fixes #2221 
Fixes #2223 
refs #2209 
Might be other reports concerned but hard to find...

Updating some settings in Options dialog

---

source/docs/user_manual/introduction/general_tools.rst
source/docs/user_manual/working_with_vector/vector_properties.rst

Fixes #1835 
@yjacolin let me know if it's better

Reword action launching description

---

source/docs/user_manual/introduction/getting_started.rst

Also updated the sample session to the new unified Data Source Manager

Reviewed text for consistency / ease of understanding

---

source/docs/user_manual/introduction/general_tools.rst
source/docs/user_manual/working_with_vector/attribute_table.rst

Adds option to flash features (fixes #2133)
Adds pan to feature option (fixes #1198)
Adds filter options (fixes #2082)
Adds zoom to feature in form view (fix #1591)

Add attribute table options

---

source/docs/user_manual/working_with_vector/expression.rst

and add more description to groups
Fixes #1771 
Fixes #2043 
Fixes #2066 
Fixes #2126 
(maybe there are more...)

 Update list of expression functions 

---

source/docs/user_manual/managing_data_source/supported_data.rst

Trying to advertize geometry type usage + some various fixes

Add some precision to delimited text file

---

source/docs/user_manual/processing/intro.rst

because :guilabel: is mainly about what is shown in the dialog

Fix some label

---

source/docs/user_manual/working_with_vector/expression.rst

Fix #2509, fix #2463, fix #2413, fix #1979, fix #1923, fix #1478

Add more functions

---

source/docs/user_manual/introduction/general_tools.rst

No more context help dialog in QGIS

Help button leads to User manual

---

source/docs/user_manual/introduction/general_tools.rst

(missing bits of #2030 fix) and improve description.

Color picker is available on macOS

---

source/docs/user_manual/processing/history.rst

Double-click the history opens the algorithm dialog pre-filled

---

source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst

Update Snap geometries description

---

source/docs/user_manual/print_composer/overview_composer.rst

Description of layout page properties panel

---

source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst

[processing] Project cartesian algorithm Fix #2370

---

source/docs/user_manual/print_composer/overview_composer.rst

Update layout manager dialog

---

source/docs/user_manual/print_composer/composer_items/composer_image.rst

Updating the layout picture item

---

source/docs/user_manual/print_composer/composer_items/composer_map.rst

Fixes #1628 fixes #1629, fixes #1893, fixes #1894, fixes #1895

Update layout map item description

---

source/docs/user_manual/print_composer/composer_items/composer_attribute_table.rst

Update layout Attribute table item description

---

source/docs/user_manual/print_composer/overview_composer.rst

Update Layout panel description

---

source/docs/user_manual/print_composer/composer_items/composer_legend.rst

Update layout legend item description

---

source/docs/user_manual/print_composer/composer_items/composer_scale_bar.rst

Update layout scale bar item description

---

source/docs/user_manual/print_composer/create_output.rst

Fix #1956 
Build will fail because of reference in #2521

Update layout atlas panel description

---

source/docs/user_manual/introduction/qgis_gui.rst
source/docs/user_manual/print_composer/overview_composer.rst

now that the whole layout chapter is in place

Filling layout tools references

---

source/docs/user_manual/print_composer/composer_items/composer_items_options.rst

Adding more ways to create layout items

---

source/docs/user_manual/print_composer/overview_composer.rst

Adding right-click menus description

---

source/docs/user_manual/print_composer/composer_items/composer_items_options.rst
source/docs/user_manual/print_composer/overview_composer.rst

Adding improvement to Items menu description

---

source/docs/user_manual/working_with_vector/vector_properties.rst

Rename labeling classifier

---

source/docs/user_manual/processing_algs/gdal/rasteranalysis.rst

fixing help path and reorganize parameters order to match algorithms dialog
Fixes #2159 fixes #2160

Add missing GDAL grid algorithms

---

source/docs/user_manual/working_with_vector/vector_properties.rst

Also add Grid placement method (fix #2195)

 Updating the Point Displacement rendering

---

source/docs/user_manual/working_with_vector/vector_properties.rst

"Else" rule can be added through the GUI (fix #2410)

Refine the Rule-based renderer dialog description

---

source/docs/user_manual/working_with_vector/expression.rst

Fixes #2565, fixes #2561, Fixes #2537
Also add wedge_buffer expression (Fixes #2564)

Expression errors are indicated

---

source/docs/user_manual/introduction/general_tools.rst

Update Layers panel contextual menus

---

source/docs/user_manual/introduction/general_tools.rst
source/docs/user_manual/introduction/qgis_gui.rst
source/docs/user_manual/managing_data_source/opening_data.rst
source/docs/user_manual/working_with_gps/live_GPS_tracking.rst
source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst

and add shortcut information (fix #2385)

Rewrite some panels description

---

source/docs/user_manual/processing_algs/gdal/rasteranalysis.rst
source/docs/user_manual/processing_algs/gdal/rasterconversion.rst
source/docs/user_manual/processing_algs/gdal/rasterextraction.rst
source/docs/user_manual/processing_algs/gdal/rastermiscellaneous.rst
source/docs/user_manual/processing_algs/gdal/rasterprojections.rst
source/docs/user_manual/processing_algs/qgis/layertools.rst
source/docs/user_manual/processing_algs/qgis/vectoranalysis.rst
source/docs/user_manual/processing_algs/qgis/vectorcreation.rst
source/docs/user_manual/processing_algs/qgis/vectorgeneral.rst
source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
source/docs/user_manual/processing_algs/qgis/vectoroverlay.rst
source/docs/user_manual/processing_algs/qgis/vectorselection.rst

 Mention default menus for Processing algorithms 

---

source/docs/user_manual/working_with_vector/expression.rst

These functions have been renamed (see https://github.com/qgis/QGIS/blob/master/doc/qgis3_user_changes.dox)

Remove unused functions

---

source/docs/user_manual/introduction/general_tools.rst

 Expression dialog shows Data-defined expected format

---

source/docs/user_manual/introduction/general_tools.rst

Statistic summary can be copied to clipboard

---

source/docs/user_manual/introduction/qgis_configuration.rst
source/docs/user_manual/introduction/qgis_gui.rst

Provide a little introduction to cover the tools and particularly those that are not described elsewhere
Fix #2426 refs #2528

Update project menu items

---

source/docs/user_manual/introduction/general_tools.rst
source/docs/user_manual/introduction/qgis_gui.rst

Update View menu items and add some description

---

source/docs/user_manual/introduction/qgis_configuration.rst

Refs #1913, fix #1932, fix #2375 
@nyalldawson @rduivenvoorde afaics, you are the most prolific on this feature so could one of you give it a look? Thanks
PS: This does not cover the custom configuration of plugins as i do not have time (or heart?) to understand how it works.

Introducing the locator search bar options

---

source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst

Update icons on digitizing related toolbars

---

source/docs/user_manual/processing_algs/qgis/vectorselection.rst

Add selection methods to Select by attribute algorithm

---

source/docs/pyqgis_developer_cookbook/geometry.rst

Update link to geometry specification

---

source/docs/pyqgis_developer_cookbook/authentication.rst
source/docs/pyqgis_developer_cookbook/canvas.rst
source/docs/pyqgis_developer_cookbook/communicating.rst
source/docs/pyqgis_developer_cookbook/compatibility.rst
source/docs/pyqgis_developer_cookbook/composer.rst
source/docs/pyqgis_developer_cookbook/crs.rst
source/docs/pyqgis_developer_cookbook/expressions.rst
source/docs/pyqgis_developer_cookbook/geometry.rst
source/docs/pyqgis_developer_cookbook/ide_debugging.rst
source/docs/pyqgis_developer_cookbook/intro.rst
source/docs/pyqgis_developer_cookbook/loadlayer.rst
source/docs/pyqgis_developer_cookbook/loadproject.rst
source/docs/pyqgis_developer_cookbook/network_analysis.rst
source/docs/pyqgis_developer_cookbook/pluginlayer.rst
source/docs/pyqgis_developer_cookbook/plugins.rst
source/docs/pyqgis_developer_cookbook/processing.rst
source/docs/pyqgis_developer_cookbook/raster.rst
source/docs/pyqgis_developer_cookbook/releasing.rst
source/docs/pyqgis_developer_cookbook/server.rst
source/docs/pyqgis_developer_cookbook/settings.rst
source/docs/pyqgis_developer_cookbook/snippets.rst
source/docs/pyqgis_developer_cookbook/vector.rst

These files were missing in #2645

Adding |updateDisclaimer| on top of Cookbook pages

---

source/docs/user_manual/introduction/getting_started.rst
source/docs/user_manual/introduction/qgis_gui.rst
source/docs/user_manual/managing_data_source/create_layers.rst
source/docs/user_manual/managing_data_source/opening_data.rst

Reorganise project menu

---

source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst

Update export geometry columns algorithmn naming

---

source/docs/user_manual/working_with_vector/expression.rst

Add tip to access function help

---

source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst

from the Advanced digitizing toolbar (refs #1567)

Move the Undo/Redo tools to Digitizing toolbar

---

source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst

fixes #2667 fixes #1289 fixes #1522

Describing the "Move (and copy) features" tools

---

source/docs/user_manual/introduction/qgis_gui.rst

with introduction and new tools
fixes #2457

Updating the Layer menu

---

source/docs/user_manual/introduction/general_tools.rst

Documents behavoir of map theme

---

source/docs/user_manual/introduction/getting_started.rst

add paragraph about saving/loading projects in postgresql

---

source/docs/user_manual/processing_algs/qgis/vectorgeneral.rst

Add some missing types to parameters

---

source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst

Press Shift + click to fill a ring

---

source/docs/user_manual/introduction/general_tools.rst

with tooltip to project file path
Fixes #2681 fixes #2680

Embedded layers and groups show a dedicated indicator

---

source/docs/pyqgis_developer_cookbook/intro.rst

Set path for custom application on Windows

---

source/docs/user_manual/introduction/qgis_gui.rst
source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst

(refs #2179) and move circular string tools to their proper section (refs #1567)
follow-up #2701

Introduce shape digitizing toolbar section

---

source/docs/user_manual/introduction/general_tools.rst

The "Identify features" shows ellipsoidal and cartesian values

---

source/docs/user_manual/managing_data_source/create_layers.rst

Dxf export allows reprojection (fixes #1411) and MTEXT elements (fixes #2237)

Describe more options of the Dxf Export dialog

---

source/docs/user_manual/working_with_vector/expression.rst

Min and max ignore null values

---

source/docs/user_manual/managing_data_source/create_layers.rst

More details on output formats for raster and vector

---

source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst

Add more geometry information

---

source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst

Update the split features tool description

---

source/docs/training_manual/forestry/basic_lidar.rst
source/docs/training_manual/forestry/forest_maps.rst
source/docs/training_manual/forestry/forestry_intro.rst
source/docs/training_manual/forestry/map_georeferencing.rst
source/docs/training_manual/forestry/parameters_calculation.rst
source/docs/training_manual/forestry/results_map.rst
source/docs/training_manual/forestry/stands_digitazing.rst
source/docs/training_manual/forestry/systematic_sampling.rst
source/docs/training_manual/forestry/updating_stands.rst
source/docs/training_manual/processing/batch_conversion.rst
source/docs/training_manual/processing/batch_modeler.rst
source/docs/training_manual/processing/crs.rst
source/docs/training_manual/processing/cutting_merging.rst
source/docs/training_manual/processing/extents.rst
source/docs/training_manual/processing/first_saga_alg.rst
source/docs/training_manual/processing/generalize.rst
source/docs/training_manual/processing/geomorpho.rst
source/docs/training_manual/processing/hooks.rst
source/docs/training_manual/processing/html.rst
source/docs/training_manual/processing/hydro.rst
source/docs/training_manual/processing/interpolation.rst
source/docs/training_manual/processing/warning.rst
source/docs/training_manual/qgis_server/install.rst
source/docs/training_manual/vector_analysis/basic_analysis.rst
source/docs/user_manual/working_with_gps/index.rst

because these are simply unreadable in a text editor, hence hard to review

Split lines too long to be reviewed

---

source/docs/user_manual/processing_algs/qgis/vectorgeneral.rst

Add release version to option

---

source/docs/user_manual/processing_algs/qgis/vectoranalysis.rst
source/docs/user_manual/processing_algs/qgis/vectorgeneral.rst
source/docs/user_manual/processing_algs/qgis/vectortable.rst

* "Optional" is placed next to the parameter instead of below
* use of [combobox], [text], [multiselection] instead of [selection], [string], [multipleinput]
Also add missing release mention for newer options

Fix some inconsistencies with other chapters and guidelines

---

source/docs/training_manual/forestry/updating_stands.rst
source/docs/training_manual/qgis_plugins/plugin_examples.rst
source/docs/training_manual/rasters/data_manipulation.rst
source/docs/training_manual/vector_analysis/basic_analysis.rst
source/docs/user_manual/introduction/general_tools.rst
source/docs/user_manual/introduction/qgis_gui.rst
source/docs/user_manual/plugins/plugins_coordinate_capture.rst
source/docs/user_manual/working_with_ogc/server/getting_started.rst
source/docs/user_manual/working_with_ogc/server/services.rst
source/docs/user_manual/working_with_projections/working_with_projections.rst
source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst

Project properties has been renamed into Properties

---

source/docs/user_manual/processing_algs/qgis/vectortable.rst

Updates autoincremental and unique value algs

---

source/docs/training_manual/qgis_server/install.rst

@DelazJ Not sure how I managed to create this branch without doing a PR...

Fixed a couple of typos in QGIS Server install doc

---

source/docs/user_manual/introduction/general_tools.rst

Update map theme behavior

---

source/docs/pyqgis_developer_cookbook/plugins.rst
source/docs/user_manual/introduction/general_tools.rst
source/docs/user_manual/introduction/qgis_gui.rst
source/docs/user_manual/plugins/plugins.rst
source/docs/user_manual/plugins/plugins_coordinate_capture.rst
source/docs/user_manual/plugins/python_console.rst
source/docs/user_manual/working_with_projections/working_with_projections.rst
source/docs/user_manual/working_with_vector/vector_properties.rst

Nothing strange, just ran the script to update all the paths and icons. Small fix on pyqgis/plugins (last patch made was after the text added by the script and would have been deleted)

Update icons with script

---

source/docs/documentation_guidelines/first_contribution.rst

to help contributors easily find more resources (instead of building a FAQ - fix #1270)
Also update some instructions and add details to some steps.

Add links to online tips and tricks 

---

source/docs/user_manual/introduction/getting_started.rst

This updates the command line options when starting QGIS but this is simply an initial work someone more versed in this area (and with user profile options) should continue. These options are described in next sections (hence, need an update) and it could be nice to link them with the user profile settings.
@rduivenvoorde @elpaso @NathanW2 ...

Update command line options for 3.0

---

source/docs/user_manual/processing_algs/gdal/rasteranalysis.rst
source/docs/user_manual/processing_algs/gdal/rasterextraction.rst
source/docs/user_manual/processing_algs/gdal/rastermiscellaneous.rst
source/docs/user_manual/processing_algs/gdal/vectorgeoprocessing.rst
source/docs/user_manual/processing_algs/gdal/vectormiscellaneous.rst
source/docs/user_manual/processing_algs/qgis/rasteranalysis.rst
source/docs/user_manual/processing_algs/qgis/vectorgeneral.rst
source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
source/docs/user_manual/processing_algs/qgis/vectoroverlay.rst
source/docs/user_manual/processing_algs/qgis/vectorselection.rst
source/docs/user_manual/processing_algs/qgis/vectortable.rst

Adding options for some gdal algorithms
Fixing typo and data type tag

Improve some existing algorithms description

---

source/docs/user_manual/introduction/qgis_configuration.rst

@nyalldawson, @3nids, @andreasneumann (and any other) can any of you give a look to this PR and answer questions inline, please? If i'm not mistaking, you were involved in these changes... 
I plan to tackle projections behavior in 3 so i'll probably make a call again later (if really you were involved). 
Thanks

Update datum transformation description

---

source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst

[Digitizing] Updating the Simplify tool with its new methods

---

source/docs/user_manual/managing_data_source/create_layers.rst

Drag'n'drop layers from layertree to browser dock

---

source/docs/user_manual/managing_data_source/supported_data.rst

Add hstore support to the postgres provider

---

source/docs/pyqgis_developer_cookbook/vector.rst

And enable some sample code highlighting

Fix some reference hyperlinks

---

source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst

with a more exposed note and descriptive parameters

Exploring some vector geometry algorithms

---

source/docs/user_manual/managing_data_source/create_layers.rst
source/docs/user_manual/working_with_vector/vector_properties.rst

and icon updates on vector properties dialog

Update vector layer creation description with new toolbar

---

source/docs/user_manual/processing/console.rst

Continue to update to conform to QGIS 3 behaviour.  Have moved the "No QGIS 3 updates beyond this point (ToDo)" accordingly.

QGIS 3 updates to console.rst (User manual - Processing - Using Processing algs from the Console)

---

source/docs/pyqgis_developer_cookbook/loadproject.rst

Also some minor wording improvements.

Update Loading Projects for QGIS 3 in PyQGIS Cookbook

---

source/docs/user_manual/processing_algs/qgis/vectorgeneral.rst

Rename the "save selected features" algorithm

---

source/docs/user_manual/processing_algs/gdal/vectormiscellaneous.rst

Fixes #2878 
Fill and harmonize description of some SQL functions in the GDAL provider
Also add "fields to include" parameter of the "Export to PostgreSQL" algorithm (fixes #2839)

More "Import into..."/"Export to" algorithms renaming

---

source/docs/user_manual/processing_algs/qgis/vectorcreation.rst

Add details and use same sentences to ease translators work

 Update vector creation algorithms description

---

source/docs/user_manual/processing_algs/qgis/vectorcreation.rst

Add raster pixels to points/polygons algorithms

---

source/docs/user_manual/processing_algs/qgis/database.rst

Add the "PostgreSQL execute and load SQL" algorithm

---

source/docs/user_manual/working_with_vector/expression.rst

Fixes #2881, fixes #2876 fixes #2823, fixes #2858

Update functions list

---

source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst

[processing] update offset line algorithm

---

source/docs/user_manual/working_with_vector/style_library.rst

Each symbol layer can be enabled or disabled

---

source/docs/user_manual/processing_algs/qgis/interpolation.rst
source/docs/user_manual/processing_algs/qgis/vectorcreation.rst
source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
source/docs/user_manual/processing_algs/qgis/vectorselection.rst

Fix labels and default value

---

source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst

[processing] Set z and m values algorithms

---

source/docs/training_manual/introduction/preparation.rst

The main ideas here are:
1. whenever we list steps to do something, we should use a numbered list
1. each point should focus on action(s) to do not to description ie, if the previous action led to something (eg, opens a dialog that needs explanation), such details should be added in the concerned step and not as a new step

Some tweaks to the first loading data lesson

---

source/docs/user_manual/processing_algs/qgis/vectoroverlay.rst

Layer parameter name has been renamed (fixes #2939)

Update and harmonize description of some overlay algorithms

---

source/docs/user_manual/processing_algs/qgis/vectorgeneral.rst

[processing] Join by field value can export unmatched records fixes #2869

---

source/docs/user_manual/processing_algs/qgis/vectorgeneral.rst

[processing] Join by location can export unmatched records

---

source/docs/pyqgis_developer_cookbook/server.rst

I format in list but i'm not sure i really understand what is implied here (are the three classes/ways at the same level?) so a review is more than welcome...

Enumerating ways to use plugins on server

---

source/docs/user_manual/processing_algs/qgis/vectorgeneral.rst

"Extract selected features" alg outputs empty layer

---

source/docs/user_manual/working_with_vector/expression.rst

Fixes #3000, Fixes #3003, Fixes #3004

Add some map and conversion functions

---

source/docs/user_manual/processing_algs/qgis/cartography.rst
source/docs/user_manual/processing_algs/qgis/interpolation.rst
source/docs/user_manual/processing_algs/qgis/vectoranalysis.rst
source/docs/user_manual/processing_algs/qgis/vectorcreation.rst
source/docs/user_manual/processing_algs/qgis/vectorgeneral.rst
source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
source/docs/user_manual/processing_algs/qgis/vectorselection.rst
source/docs/user_manual/processing_algs/qgis/vectortable.rst

* set enumeration list
* add data defined icon when available
* fix some labels, descriptions or (missing) default values

Normalize QGIS vector algorithms description

---

source/docs/user_manual/processing_algs/qgis/rasteranalysis.rst

Defaults the raster band number to 1 instead of a litteral

---

source/docs/user_manual/processing_algs/qgis/rasteranalysis.rst
source/docs/user_manual/processing_algs/qgis/rastertools.rst

(fixes #2689) and a missing parameter for "Convert map to raster"

Add Reclassify raster by layer/table algorithms

---

source/docs/user_manual/processing_algs/qgis/vectorgeneral.rst
source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst

and fix some tags
Fixes #2813 fixes #2593

 Update the "Extend line" and "Define layer projection" algorithms

---

source/docs/user_manual/processing/console.rst

Continuing the updates to processing/console in the user guide.  Processing (toolbox) algorithms.

QGIS 3 updates to processing console - toolbox

---

source/docs/user_manual/introduction/qgis_configuration.rst

Fixes #1724, fixes #1624, refs #2167, refs #1623

Update CRS and measurements settings in Project properties dialog

---

source/docs/user_manual/working_with_vector/attribute_table.rst
source/docs/user_manual/working_with_vector/vector_properties.rst

Add layer scoped actions in Attribute Table

---

source/docs/user_manual/processing_algs/gdal/rasterextraction.rst

(fixes #2991) and fix indentation

Additional creation options for Contour algorithm

---

source/docs/user_manual/introduction/general_tools.rst
source/docs/user_manual/introduction/qgis_configuration.rst
source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst

in Project properties dialog - fixes #2990, fixes #2952

The Identify tab has been merged with Data Sources

---

source/docs/user_manual/processing_algs/gdal/rasterconversion.rst

Tried to fix some missing or outdated parameters of gdal raster conversion algorithms. Contains gaps to fill by someone else as I'm not a raster user. If anyone...

Update GDAL raster conversion algorithms

---

source/docs/user_manual/working_with_vector/style_library.rst

Exploring the different color ramp types

---

source/docs/training_manual/basic_map/symbology.rst

of actions to follow (mainly a formatting changes)

[TM] Number the steps to help better visualize the sequences

---

source/docs/pyqgis_developer_cookbook/vector.rst

Attempt to address #1028 by including the example suggested by @nyalldawson in #1028.

Update vector.rst in the Cookbook to include selectbyexpression (#1028)

---

source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst

Update Dissolve algorithm

---

source/docs/user_manual/introduction/qgis_gui.rst

To make room for the full text of the "Merge Attributes of Selected Features" entry.

Adjust the table for the Edit menu in the GUI description

---

source/docs/user_manual/processing_algs/qgis/database.rst

Using this algorithm I realized that description was wrong (or simply outdated)

Fixes wrong descripion

---

source/docs/user_manual/introduction/qgis_gui.rst

User manual, GUI, menus: Update the menu entries according to the latest master.  Also some reformulations and additional explanation regarding the menu contents dependency on (core) plugins.

Menu updates (in qgis_gui.rst) in the user manual

---

source/docs/user_manual/processing_algs/qgis/vectorcreation.rst
source/docs/user_manual/processing_algs/qgis/vectorgeneral.rst
source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
source/docs/user_manual/processing_algs/qgis/vectoroverlay.rst

If any better wording? note that there's a hyperlink to jump to the concerned feature description.

[Processing] Add a checkbox to mention whether an algorithm allows features in-place modification 

---

source/docs/user_manual/working_with_vector/vector_properties.rst

See https://github.com/qgis/QGIS/pull/8216

Remove comment that ogr based files would not be editable when filtered

---

source/docs/user_manual/processing/console.rst

Updated user_manual/processing/console.rst.

Fixed a misleading class name in an example (user guide, processing)

---

source/docs/training_manual/forestry/parameters_calculation.rst

when chasing "shapefile" use:
* fix again some :kbd: misuse
* use numbered list
(note that i did not check whether the instructions are up to date)

More formatting fixes

---

source/docs/training_manual/grass/grass_setup.rst

Fix shapefiles --> shapeffile folder
Use numbered list to emphasize steps
Fix some :kbd: misuse

Improve grass setup chapter

---

source/docs/user_manual/processing_algs/gdal/rasterextraction.rst

Some tweaks to GDAL clip raster algorithms

---

source/docs/user_manual/managing_data_source/create_layers.rst
source/docs/user_manual/managing_data_source/opening_data.rst
source/docs/user_manual/managing_data_source/supported_data.rst
source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst
source/docs/user_manual/working_with_vector/vector_properties.rst

Because those are kind of steps to follow instead of simple enumeration, it looks better to show them as such.

Move from simple list to numbered list

---

source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst

Also add precision and fixes typos

Formalize some digitizing tools instructions as steps

---

source/docs/documentation_guidelines/first_contribution.rst
source/docs/pyqgis_developer_cookbook/server.rst
source/docs/pyqgis_developer_cookbook/vector.rst
source/docs/training_manual/complete_analysis/raster_to_vector.rst
source/docs/training_manual/introduction/preparation.rst
source/docs/user_manual/introduction/general_tools.rst
source/docs/user_manual/introduction/qgis_configuration.rst
source/docs/user_manual/managing_data_source/create_layers.rst
source/docs/user_manual/managing_data_source/opening_data.rst
source/docs/user_manual/plugins/plugins.rst
source/docs/user_manual/print_composer/composer_items/composer_attribute_table.rst
source/docs/user_manual/print_composer/composer_items/composer_items_options.rst
source/docs/user_manual/print_composer/composer_items/composer_items_shape.rst
source/docs/user_manual/print_composer/create_output.rst
source/docs/user_manual/print_composer/overview_composer.rst
source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
source/docs/user_manual/processing_algs/qgis/vectortable.rst
source/docs/user_manual/working_with_projections/working_with_projections.rst
source/docs/user_manual/working_with_raster/raster_properties.rst
source/docs/user_manual/working_with_vector/attribute_table.rst
source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst
source/docs/user_manual/working_with_vector/style_library.rst
source/docs/user_manual/working_with_vector/vector_properties.rst

even in lists regardless they are bullet list or numbered list.
If not a full sentence, a bullet list item is ended with a semi-colon (unless all the other items do not have any), ie in absence of rules i prefer to have all but the last item end with the same punctuation (usually, semi-colon or nothing) than having a mixed punctuation in the list.
Hoping that i've been consistent in the changes because we have really weirdly shaped lists.

A full sentence begins with capital letter and ends with period

---

source/docs/user_manual/introduction/qgis_configuration.rst

Add details to Locator "af" search option

---

source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst

Fixes #3012 (I'm not sure the option label is self explanatory. what are "anchor nodes"? I fail to understand --and i read the discussion in the PR and btw asked for clarification in the issue report-- So for the end user a better vocabulary is necessary imho... )

Add missing parameter to snap geometries algorithm

---

source/docs/pyqgis_developer_cookbook/composer.rst

You **can** load layouts from template files.
Using "loadFromTemplate()"

Remove outdated statement.

---

source/docs/user_manual/print_composer/create_output.rst

changed informal phrasing to form (bunch to selection)
Coming off Foss4g Oceania and this is my first commit  EVER!!!

Improved phrasing

---

source/docs/user_manual/introduction/qgis_gui.rst
source/docs/user_manual/working_with_vector/expression.rst

A temporary fix... for this kind of rendering

Add spacing at the bottom of tables

---

source/docs/user_manual/managing_data_source/opening_data.rst

rather than the datasource manager dialog, because of speed.
Also fix typo

Prefer adding database tables to canvas from browser panel

---

source/docs/user_manual/processing_algs/qgis/index.rst
source/docs/user_manual/processing_algs/qgis/networkanalysis.rst

This is an initial work to document the network analysis algorithms (fixes #2742). This PR is unfinished but I can't go further (I'm not used to the vocabulary of this discipline nor the concepts) so anyone who knows, feel free to fill the gaps and fix what i might have described wrongly.
To avoid redundant comments because the 5 algs share a lot of common parameters, I only add their unique parameters (depending on context) so that once a description is set and fixed, it will only be a matter of copy paste to the other places.
@ghtmtt @nyalldawson @anitagraser @alexbruy and any other who knows....

Document network analysis algorithms

---

source/docs/user_manual/introduction/qgis_configuration.rst

Remove "QGIS-styled group boxes" checkbox

---

qgis-projects/training_manual/basic_map.qgs
qgis-projects/training_manual/landuse_symbol.svg
qgis-projects/training_manual/symbology.qgs

to easily reproduce training manual screenshots and lessons (instead of having to follow steps from scratch each time)

Add some necessary project files

---

source/docs/user_manual/introduction/qgis_gui.rst
source/docs/user_manual/working_with_vector/vector_properties.rst

Just some wording tweaks from an English native speaker's perspective

English native

---

source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst

Adds a note: activate snapping

Update trim/extend part

---

source/docs/documentation_guidelines/substitutions.rst

as there's no more resources folder

Update icon addition instructions

---

source/docs/documentation_guidelines/writing.rst

First try on how to format lists (start items with capital letter, period as punctuation - only for complex / compound items).  I have also tried to apply the "rules" to this document.
Input appreciated.
See also discussion in #3112.

Documentation guidelines update on the formatting of lists

---

source/docs/documentation_guidelines/first_contribution.rst

@janneke-qgis Here's an update of the step by step chapter with, I hope, more atomic steps. I'm not sure I follow the route you proposed in your msg but think/hope it improves things.
Feedbacks welcome.

 Updating the step by step instructions 

---

source/docs/user_manual/processing_algs/index.rst

Add information about how to find the names of algorithm parameters.
A temporary measure while we are waiting for these names to be included in the algorithm documentation (#2770).

Update index.rst of the processing providers and algorithms section with information about how to find the names of algorithm parameters

---

source/docs/user_manual/preamble/features.rst

- removed unnecessary capitalization (especially initial word of parenthetical phrases which are not standalone sentences)
- some word order improvements
- language simplification

Minor language improvements

---

source/docs/user_manual/introduction/qgis_gui.rst

Final section of this file (ca l.800 to EOF)

Minor language corrections/improvements

---

source/docs/user_manual/introduction/qgis_gui.rst

Complete only up to "Plugins" heading (l. 322) - more to follow

Minor language corrections and improvements

---

source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst

Fix https://issues.qgis.org/issues/20840

Keep n biggest parts of each feature and not layer

---

source/docs/user_manual/introduction/qgis_gui.rst

Plugins section through to line 807.

QGS GUI: minor language corrections/improvements

---

source/docs/pyqgis_developer_cookbook/tasks.rst

Fixing some errors, and improving some code comments.

Update tasks.rst (cookbook)

---

source/docs/user_manual/introduction/qgis_configuration.rst

Reverts qgis/QGIS-Documentation#3407

Revert "Minor language corrections/improvements"

---

source/docs/user_manual/introduction/qgis_gui.rst

update the vector menu (change name to "Check Geometries..." and change the order of the menu items (according to 3.4.4 on Ubuntu).

Update qgis_gui.rst (vector menu)

---

source/docs/user_manual/plugins/plugins_coordinate_capture.rst
source/docs/user_manual/plugins/plugins_geometry_checker.rst
source/docs/user_manual/working_with_gps/plugins_gps.rst

Change "Vector-> GPS-> GPS Tools" to "Vector-> GPS Tools" (#2636).

Update plugins_gps.rst (single entry menus)

---

source/docs/user_manual/introduction/qgis_configuration.rst

Update the general settings of the general tab of project properties. Fixes #2421.

Update qgis_configuration.rst (general settings tab update)

---

source/docs/user_manual/introduction/general_tools.rst

Minor language corrections/improvements

Remaining tweaks to General Tools

---

source/docs/user_manual/introduction/getting_started.rst
source/docs/user_manual/introduction/qgis_configuration.rst
source/docs/user_manual/introduction/qgis_gui.rst
source/docs/user_manual/plugins/plugins.rst

This is an attempt to describe the user profile setting. Given that the QEP is a bit outdated (vs implementation) from my understanding and the discussion in the implementation (as well as the QEP's) seems really developer-speeching oriented, this is mainly based on my experience with this feature and what i've understood here and there.
It fixes #2002, fixes #3440, fixes #2284

Explore User profile settings

---

source/docs/user_manual/print_composer/index.rst

Mention reports on the layout / report index page (#2309, #2358, ...). First step.

Update index of the layouts chapter to mention reports

---

source/docs/user_manual/introduction/qgis_configuration.rst

and remove mention of windows xp or earlier

Enable hyperlink on "user profile" mention

---

source/docs/user_manual/managing_data_source/opening_data.rst

Move less documented formats (gps and grass) in the page to the bottom of the section
Mix two notes in one (too many consecutive notes)

Some minor tweaks

---

source/docs/training_manual/vector_analysis/basic_analysis.rst
source/docs/training_manual/vector_analysis/reproject_transform.rst
source/docs/training_manual/vector_analysis/spatial_statistics.rst

This is a move from bulleted list to numbered list for the chapter 7 (I find numbers better structure the steps). There's (almost) no text modification.

[TM] Chp7 - Use numbered list for instructions

---

source/docs/training_manual/rasters/data_manipulation.rst
source/docs/training_manual/rasters/terrain_analysis.rst

as usual, almost no text modification

[TM] Chp8 - Add more numbered instructions

---

source/docs/user_manual/working_with_vector/attribute_table.rst

refs https://github.com/qgis/QGIS/pull/9267

Adjust field length description and some tweaks

---

source/docs/pyqgis_developer_cookbook/geometry.rst
source/docs/pyqgis_developer_cookbook/vector.rst

Fixes #3466 update Geometry page of developer cookbook to Python 3/Qgis 3.

Update to Geometry Page to Python 3/QGIS 3

---

source/docs/training_manual/grass/grass_setup.rst
source/docs/training_manual/grass/grass_tools.rst

Also add space below screenshot

[TM] Chp13- Use numbered list and fix :kbd: use

---

source/docs/user_manual/working_with_ogc/server/services.rst

This PR suggests to specify in the docs that the GetFeatureInfo parameter `FEATURE_COUNT` is per layer.
Please review.

Provide better documentation for FEATURE_COUNT

---

source/docs/user_manual/working_with_ogc/server/services.rst

Modify documentation to fit with new filter feature https://github.com/qgis/QGIS/pull/9204 - fixes #3464

Update documentation on WMS GetMap filter

---

source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
source/substitutions.txt

superseeds #3496 that has a really dirty merging history (closing it without merging). @DelazJ this PR already includes your review comments. 
fix #3358

[Processing] geodesic split lines algorithm

---

readme.rst

readme updated for 3.4 ref #3507

---

source/docs/user_manual/processing_algs/gdal/rasterextraction.rst
source/docs/user_manual/processing_algs/gdal/rasterprojections.rst
source/docs/user_manual/processing_algs/gdal/vectormiscellaneous.rst
source/docs/user_manual/processing_algs/qgis/cartography.rst
source/docs/user_manual/processing_algs/qgis/database.rst
source/docs/user_manual/processing_algs/qgis/filetools.rst
source/docs/user_manual/processing_algs/qgis/graphics.rst
source/docs/user_manual/processing_algs/qgis/index.rst
source/docs/user_manual/processing_algs/qgis/layertools.rst
source/docs/user_manual/processing_algs/qgis/modelertools.rst
source/docs/user_manual/processing_algs/qgis/networkanalysis.rst
source/docs/user_manual/processing_algs/qgis/rasteranalysis.rst
source/docs/user_manual/processing_algs/qgis/rasterterrainanalysis.rst
source/docs/user_manual/processing_algs/qgis/rastertools.rst
source/docs/user_manual/processing_algs/qgis/vectoranalysis.rst
source/docs/user_manual/processing_algs/qgis/vectorcreation.rst
source/docs/user_manual/processing_algs/qgis/vectorgeneral.rst
source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
source/docs/user_manual/processing_algs/qgis/vectorselection.rst
source/docs/user_manual/processing_algs/qgis/vectortable.rst
source/docs/user_manual/working_with_vector/expression.rst

Not needed anymore after branching 3.4
After the travis is happy the PR will be cherry-picked also for master (leaving 3.6 substitution)

Get rid of all 32 and 34 substitution

---

source/docs/documentation_guidelines/first_contribution.rst
source/docs/user_manual/grass_integration/grass_integration.rst
source/docs/user_manual/preamble/whats_new.rst
source/substitutions.txt

another small replacement of 34 in release_3.4 branch

other 34 updates

---

source/docs/pyqgis_developer_cookbook/authentication.rst

Remove C++ API links from Authentication chapter

---

source/docs/pyqgis_developer_cookbook/loadlayer.rst

see https://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/loadlayer.html?highlight=order%20wrong%20layers#raster-layers and split long lines (no word changed)

Fix wrong indentation of the list

---

source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst

Add more information and cross links to algorithms

---

source/docs/pyqgis_developer_cookbook/processing.rst

Fix #3486 
Linked to https://github.com/qgis/QGIS/pull/9405
CC @nyalldawson

add example how to make a Processing plugin

---

source/docs/pyqgis_developer_cookbook/geometry.rst

- Code snippets are now self-contained and do not rely on layers from other chapters of the tutorial. 
- Minor edits to the non-code text

[geometry.rst] tested and updated geometry.rst of the pyqgis cookbook

---

.dockerignore
.gitignore
Makefile
docker.mk
doctest.dockerfile
readme.rst
source/conf.py
source/docs/pyqgis_developer_cookbook/crs.rst
venv.mk

Based on #3500.
Activate doctest and add make configs to run doctest using venv or docker.

[WIP] Activate doctest

---

.github/PULL_REQUEST_TEMPLATE.md
readme.rst

just an idea of what we had in mind for the discussion at the hackfest. I just added the mandatory fields, not the optional one. I think we can use the PR comments to add other ideas. 
@DelazJ @SrNetoChan @havatv

PR template

---

source/docs/index.rst

Removes the (testing QGIS) from index, which we forgot to do after branching.
Goal:
Ticket: #

Removes (QGIS testing) from index

---

.travis.yml

They are tested as pr build already - @m-kuhn is this worth it (found it when looking for commits to cherry-pick on master)?
(cherry picked from commit 07cba7deb2bdf79084192f03e45df03544f86af9)

Do not test trigger push builds for backports [backport]

---

.gitignore
REQUIREMENTS.txt

Backport various "infrastructure" enhancements

---

source/docs/pyqgis_developer_cookbook/geometry.rst

Goal: Fix wrong indentation of code snippet at https://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/geometry.html
Ticket: #

Fix indentation of code frame

---

source/docs/documentation_guidelines/writing.rst
source/docs/user_manual/processing_algs/qgis/vectoranalysis.rst

Formatting the rendering (https://docs.qgis.org/testing/en/docs/documentation_guidelines/writing.html#documenting-processing-algorithms)
Improving the example used as reference (https://docs.qgis.org/3.4/en/docs/user_manual/processing_algs/qgis/vectoranalysis.html#count-points-in-polygon)

Review of the Processing contribution guidelines

---

source/docs/user_manual/working_with_ogc/server/services.rst

It is possible to request a DXF from QGIS server, but the request which has to be sent is a `GetMap` request with `FORMAT` option.

GetDxf is actually GetMap with FORMAT

---

source/docs/pyqgis_developer_cookbook/intro.rst

Adding hint for finding right  location for startup.py file

default startup.py location hint

---

source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst

Goal: Add details and steps to https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/editing_geometry_attributes.html#rotate-feature-s
Ticket: #

Review the digitizing "Rotate feature(s)" tool

---

source/docs/user_manual/processing/console.rst

Code update to include the #3410 improvement and fix a wrong variable name in the code (BUFFERDIST -> INPUT_BUFFERDIST).

Code update in console.rst

---

source/docs/user_manual/processing/modeler.rst

Update modeler.rst to mention that models will show up in the browser

---

source/docs/user_manual/introduction/general_tools.rst
source/docs/user_manual/introduction/qgis_gui.rst

Update general_tools.rst to mention Layer Definition Files.

---

source/docs/user_manual/working_with_mesh/mesh_properties.rst

Goal: This is a forward port of #3562 
Add havatv suggestions
and reorganise table of contents
Ticket: https://docs.qgis.org/testing/en/docs/user_manual/working_with_mesh/mesh_properties.html

Adding some formatting and review to mesh chapter

---

source/docs/documentation_guidelines/substitutions.rst
source/docs/pyqgis_developer_cookbook/composer.rst
source/docs/pyqgis_developer_cookbook/processing.rst
source/docs/pyqgis_developer_cookbook/tasks.rst
source/docs/user_manual/print_composer/create_reports.rst
source/docs/user_manual/working_with_mesh/mesh_properties.rst
source/docs/user_manual/working_with_vector/attribute_table.rst
source/substitutions.txt

Update substitutions list

---

.travis.yml
docker.mk

Travis doctest docker

---

source/docs/pyqgis_developer_cookbook/crs.rst

Updates the CRS section of the PyCookBook to QGIS 3. Besides it, it also adds doctests
Goal:
Ticket: #3508

Update Pycookbook CRS section and add tests

---

source/docs/documentation_guidelines/cookbook_guidelines.rst

Goal: Add local table of contents into https://docs.qgis.org/testing/en/docs/documentation_guidelines/cookbook_guidelines.html
Ticket: #

Add missing local TOC

---

source/docs/pyqgis_developer_cookbook/expressions.rst

PyQGIS Cook book: expressions.rst

---

source/docs/documentation_guidelines/do_translations.rst

The file used as example no longer exists but, at least let's not mislead people on the |updatedisclaimer| usage
Ticket: see https://docs.qgis.org/3.4/en/docs/documentation_guidelines/do_translations.html#translate-a-file

Remove mention of obsolete use of |updatedisclaimer

---

docker.mk
doctest.dockerfile

And change doctest docker image tag to release-3_4.
Goal:
Ticket: #

Tests Doc 3.4 against QGIS 3.4

---

source/docs/pyqgis_developer_cookbook/expressions.rst

@carolinux I noticed this snippet when I was doing your review.
Are you fine with this change?
It looks much easier and it's much more optimized like this.
Or was it to show some `prepare` statements?
I think so, because the previous PR has been backported.

simplify python expression snippet

---

themes/qgis-theme/page.html

Goal: Shows Transifex link at the bottom of translated pages
Ticket: fix #3559

Enable transifex link in footer

---

source/docs/pyqgis_developer_cookbook/tasks.rst

at https://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/tasks.html
Ticket: #

Add some hyperlinks to qgstask api features

---

source/docs/pyqgis_developer_cookbook/geometry.rst

Goal: some general changes firstly triggered by the line above https://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/geometry.html#geometry-predicates-and-operations 
Ticket: #

Some rendering fixes

---

source/docs/pyqgis_developer_cookbook/expressions.rst
source/docs/pyqgis_developer_cookbook/vector.rst

The warning message just above https://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/vector.html#further-topics is not necessary imho
Ticket: #

Remove obsolete warning

---

source/docs/pyqgis_developer_cookbook/geometry.rst

Goal: Since automatic backport of #3659 fails (no idea why), this a trivial copy-paste from master branch (as far as I can tell, there is no changes between the releases at this moment)
Ticket: #3659

Update the geometry file

---

source/docs/user_manual/processing/batch.rst

line 23 :  Found : "testing changes."  I suspect this frase was a leftover from developers testing. Since it seems to make nog sense in this way, I removed it. If necessary it need to be refrased to avoid confusion.
Goal: Avoid confusion in user documentation

Removed probable leftover from testing

---

source/docs/pyqgis_developer_cookbook/crs.rst
source/docs/user_manual/processing/scripts.rst
source/substitutions.txt

Goal: Make the substitution list in 3.4 coherent with #3645 to avoid possible failure of automatic backport of PRs that update the substitutions list.
Ticket: #

Sort the whole substitutions list

---

source/substitutions.txt

and prepare substitutions for next releases
Goal: Fix eg the mention of 2.18 at https://docs.qgis.org/testing/en/docs/user_manual/preamble/whats_new.html
Ticket: #

Update |current| substitution

---

source/docs/user_manual/introduction/qgis_configuration.rst

Goal:  add environment variable for QGIS startup, deploying QGIS in an organization
Ticket: fix #1714
@NathanW2 @elpaso Can I have a review about this practice?
I got this workaround by talking with my system administrator and we were not very sure about this copy/paste.
* Is it possible to avoid the copy/paste of the default file? We wanted to keep these settings. It doesn't look convenient because they will need to copy/paste again the content of the new default settings file when they will switch to QGIS 3.10 (next LTR).
* ~~Is it possible to avoid the migration QGIS 2 window? In our case we don't want this window. We provide a clean new profile.~~ _Ok, we found how to do that_
Thanks.

 add environment variable for QGIS startup, deploying QGIS in an organization

---

source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst

Goal: users should get detailed information about the usage of the feature
Ticket: #

Digitizing snap to grid

---

source/docs/pyqgis_developer_cookbook/vector.rst

I think we accidentally dropped this argument.

Add missing file format

---

source/docs/user_manual/introduction/qgis_configuration.rst

Added Blend of Gray to UI theme options in user manual, fix #3278

[User Manual] Added Blend of Gray to UI theme options

---

source/docs/documentation_guidelines/substitutions.rst
source/docs/training_manual/create_vector_data/topo_editing.rst
source/docs/training_manual/introduction/preparation.rst
source/docs/training_manual/vector_analysis/spatial_statistics.rst
source/docs/user_manual/auth_system/auth_workflows.rst
source/docs/user_manual/grass_integration/grass_integration.rst
source/docs/user_manual/introduction/general_tools.rst
source/docs/user_manual/introduction/qgis_configuration.rst
source/docs/user_manual/introduction/qgis_gui.rst
source/docs/user_manual/managing_data_source/opening_data.rst
source/docs/user_manual/plugins/plugins_evis.rst
source/docs/user_manual/plugins/plugins_geometry_checker.rst
source/docs/user_manual/preamble/conventions.rst
source/docs/user_manual/print_composer/composer_items/composer_items_options.rst
source/docs/user_manual/print_composer/composer_items/composer_legend.rst
source/docs/user_manual/print_composer/composer_items/composer_map.rst
source/docs/user_manual/print_composer/create_output.rst
source/docs/user_manual/working_with_gps/live_GPS_tracking.rst
source/docs/user_manual/working_with_mesh/mesh_properties.rst
source/docs/user_manual/working_with_projections/working_with_projections.rst
source/docs/user_manual/working_with_raster/raster_properties.rst
source/docs/user_manual/working_with_vector/attribute_table.rst
source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst
source/docs/user_manual/working_with_vector/style_library.rst
source/docs/user_manual/working_with_vector/vector_properties.rst
source/substitutions.txt

Some icons were looking too big next to the text. Fixing most of them.
(applying #3728 compatible changes)
Goal:
Ticket: #

Resize icons

---

source/docs/pyqgis_developer_cookbook/intro.rst

Backport #3727 
Goal:
Ticket: #

Fix startup.py folder

---

source/docs/training_manual/vector_analysis/network_analysis.rst

https://docs.qgis.org/3.4/en/docs/training_manual/vector_analysis/network_analysis.html
Ticket: #

[tm]  Switch to numbered list, aerate and make screenshots more legible

---

source/docs/user_manual/processing_algs/gdal/rastermiscellaneous.rst

Goal:
Ticket: fix #3287
- [ x] Backport to LTR documentation is required

Adding optional tag and new parameters to GDAL miscellaneous algs #3287

---

source/docs/user_manual/processing/console.rst

in order to make the chapter more interactive
@havatv I was a bit lost in the feedback section since methods mentioned there are either from qgsFeedback or qgsProcessingFeedback and the text is not clear when we switch from one to the other. Could you give it a look, please?
Ticket: #

Add more PyQGIS links

---

source/docs/user_manual/processing_algs/gdal/rasterconversion.rst
source/docs/user_manual/processing_algs/gdal/vectorconversion.rst

Fixing indentation

---

source/docs/user_manual/processing_algs/gdal/rasterprojections.rst

documentation source: https://www.gdal.org/gdalwarp.html

Update and complete Gdal warp algorithm description

---

source/docs/user_manual/working_with_vector/expression.rst

Tweak the @parent variable description

---

venv.mk

This adds the python/plugins path to the environment file.
Goal:
This is needed when trying to run doctest on snippets that require importing processing algorithms, like #3403.
Ticket: #

Adds python plugin folder to env file

---

source/docs/user_manual/processing_algs/gdal/rastermiscellaneous.rst

Goal: backport #3744 (creating a dedicated PR to avoid it being blocked by testing failures in #3774)
Ticket: #

Backport some improvements in gdal raster miscellaneous algorithms

---

source/docs/user_manual/working_with_ogc/server/getting_started.rst

Rework the QGIS Server section that describes how to set up QGIS Server with Apache.

Rework the QGIS Server Apache section

---

source/docs/pyqgis_developer_cookbook/cheat_sheet.rst

Display label for cheat sheet sources instead of url

---

source/docs/user_manual/introduction/qgis_gui.rst

line 422: ":guilabel:`Database` menu"  should be:  ":guilabel:`Web` menu"

Wrongfully mentioned menu entry

---

source/docs/pyqgis_developer_cookbook/cheat_sheet.rst
source/docs/pyqgis_developer_cookbook/index.rst

Goal: Backports ~~#3744 and~~ (moved to #3780) #3621 (fix #3773)
Ticket: #

Backports PyQGIS cheat sheet

---

source/docs/pyqgis_developer_cookbook/cheat_sheet.rst

Reorder index, move snippets from sections and pass test
Goal: 
Ticket: #3786

[pyqgis] Fix reorder index QGIS Cheat sheet

---

source/docs/user_manual/processing/scripts.rst

Goal: Tried to fix readability issues (mostly overflowing lines) in https://docs.qgis.org/testing/en/docs/user_manual/processing/scripts.html
Ticket: #

Improve readability

---

source/docs/pyqgis_developer_cookbook/geometry.rst

Added tests for the geometry chapter.
Goal:
Make the pyqgis documentation rock solid ;)

[pyqgis] tests added for geometry chapter

---

source/docs/user_manual/processing/scripts.rst

Goal: backports #3770 
Ticket: #

Improve code readability

---

source/docs/user_manual/introduction/qgis_gui.rst

line 671:  "horizonal" should be "horizontal"

Typo (horizonal = horizontal)

---

source/docs/pyqgis_developer_cookbook/cheat_sheet.rst

Add new snnipets to QGIS Cheat sheets.
Goal:
Ticket: #

[pyqgis] Add new snippets QGIS Cheat sheet

---

source/docs/user_manual/plugins/index.rst

It looks weird to begin this chapter with that. https://docs.qgis.org/testing/en/docs/user_manual/plugins/index.html
Goal:
Ticket: #

Move the Python Console chapter after the Core Plugins

---

source/docs/training_manual/create_vector_data/create_new_vector.rst

The menu selections and dialog windows are entirely different from what is described.  I got a window view (and more), but need to know how to upload and refer to PNG files.  How is an "img" subdirectory created?
Goal:
Ticket: #

Update create new vector to match 3.6

---

source/docs/user_manual/processing_algs/gdal/rasterconversion.rst
source/docs/user_manual/processing_algs/gdal/rasterextraction.rst
source/docs/user_manual/processing_algs/gdal/rasterprojections.rst
source/docs/user_manual/processing_algs/gdal/vectorconversion.rst

description in gdal algorithms
Goal:
Ticket: #

Homogenize raster "additional creation options"

---

source/docs/pyqgis_developer_cookbook/expressions.rst

Goal: explain use of aggregate expressions and necessary context settings, as discussed on the dev list and previously published on https://anitagraser.com/pyqgis-101-introduction-to-qgis-python-programming-for-non-programmers/pyqgis-101-using-expressions-to-compute-new-field-values/
Ticket: #

Add example on aggregate expression

---

source/docs/documentation_guidelines/first_contribution.rst
source/docs/documentation_guidelines/index.rst
source/docs/documentation_guidelines/writing.rst

guidelines chapter, less intimidating than technical writing rules for newcomers. Also it makes it more discoverable.
Goal:
Ticket: #

Move the step-by-step chapter to the beginning of documentation

---

source/docs/pyqgis_developer_cookbook/intro.rst

Minor edits - language, format, ...
Should be trivial, so I will merge soon (if there is no feedback).
Goal:
Ticket: #

Update intro.rst (PyQGIS cookbook)

---

source/docs/documentation_guidelines/cookbook_guidelines.rst
source/docs/pyqgis_developer_cookbook/expressions.rst

Goal: Backports #3769 and #3869
Ticket: #

Backport pyqgis expressions changes

---

source/docs/pyqgis_developer_cookbook/plugins/snippets.rst

review code snippet

---

source/docs/pyqgis_developer_cookbook/cheat_sheet.rst

This aims to fix the problem of doctests using objects from tests in other rst files.
Goal:
Ticket: #

Clean project instance

---

source/docs/user_manual/processing_algs/qgis/vectoranalysis.rst

Add documentation for the Climb along line algorithm.
Fixes #3864
Goal:
Ticket: #

Add the Climb along line algorithm

---

source/conf.py
source/docs/pyqgis_developer_cookbook/cheat_sheet.rst

Goal:
Clear the QGIS project instance in every rst file to avoid problems in docs testing
Ticket: #
- [ x ] Backport to LTR documentation is required

Adds doctest_global_cleanup to clear QgsProject instance

---

source/docs/pyqgis_developer_cookbook/plugins/plugins.rst

Add information for plugin_dependencies metadata

---

source/docs/pyqgis_developer_cookbook/plugins/plugins.rst

We do not have a formatting for .. important:: directive so might be better to use .. note::
Add more spacing at the bottom of the metadata table
Goal:
Ticket: #

Some cosmetics

---

source/docs/user_manual/working_with_vector/expression.rst

Cosmetic rendering

---

source/docs/pyqgis_developer_cookbook/cheat_sheet.rst
source/docs/pyqgis_developer_cookbook/plugins/snippets.rst
source/docs/user_manual/processing_algs/gdal/rastermiscellaneous.rst
source/docs/user_manual/working_with_projections/working_with_projections.rst
source/docs/user_manual/working_with_vector/expression.rst

running the find_set_subst.py script
Goal:
Ticket: #

Update substitutions lists

---

source/docs/pyqgis_developer_cookbook/plugins/snippets.rst
source/docs/user_manual/processing_algs/gdal/rastermiscellaneous.rst
source/docs/user_manual/working_with_projections/working_with_projections.rst

running the find_set_subst.py script

Fix substitutions list

---

source/docs/user_manual/introduction/qgis_configuration.rst

from the help button, because 3.0 does not open testing.
Goal:
Ticket: #

Update default logic of documentation opening

---

source/docs/user_manual/introduction/getting_started.rst

making the experience smoother
Use atomic steps for instructions
Add more details here and there
Goal: improve getting started experience at https://docs.qgis.org/testing/en/docs/user_manual/introduction/getting_started.html
Ticket: #

Adjust and complete the instructions in the "Getting started" chapter

---

source/docs/pyqgis_developer_cookbook/cheat_sheet.rst

Add new samples based on my [answer ](https://gis.stackexchange.com/a/327135/49538)from GIS Stack Exchange.
Goal:
Ticket: #

[pyqgiscookbook] Add new samples to cheat sheet
