qgis/QGIS-Documentation

- source/docs/user_manual/plugins/plugins_metasearch.rst
Per https://github.com/qgis/QGIS/commit/519830e05e9e8793df17e005a6829bdcf63e556e
> [MetaSearch] add docs for OWS connection naming settings

- source/docs/pyqgis_developer_cookbook/composer.rst
The link http://doc.qt.nokia.com/stable/graphicsview.html is dead. Replaced http://doc.qt.io/qt-4.8/qgraphicsview.html. Also added a link to the Python equivalent http://pyqt.sourceforge.net/Docs/PyQt4/qgraphicsview.html
> fixed dead qt link and added pyqt link

- source/docs/pyqgis_developer_cookbook/geometry.rst
As I can see, QgsDistanceArea setProjectionEnable() method no longer works. It was replaced by setEllipsoidalMode()
> Fix reference to enexistent setProjectionEnable()

- source/docs/pyqgis_developer_cookbook/plugins.rst
With version 2 and later, the search directory for Python plugins is `~/.qgis2/python/plugins`.
> Change outdated search path to plugins

- source/docs/user_manual/working_with_vector/expression.rst
reduce line's length to keep function's description more readable 
split long lines into shorter ones
> Fix alignment of some function's description

- source/docs/user_manual/working_with_vector/expression.rst
Adds new functions : fixes #757, fixes #755, fixes #725, fixes #719, fixes #716, fixes #707, fixes #702 , fixes #701, fixes #684
Previously, functions were listed inside a quote and thus, were untranslatable.
Updating the list was also complicated given that a quote item doesn't well handle words;
they could be wrapped anywhere leading to an unreadable description.
Functions are now shown inside a table (which better handles multiline and word wrap --> easy to update). Their description also become translatable.
> Update the list of functions in expression

- source/docs/user_manual/working_with_vector/vector_properties.rst
This commit add two things:
* Typo (click -> clic)
* Add Layer tree as a possible location for the diagram legend (Fix #591)
> Add layer tree for location of the diagram legend

- source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst
The  "zooming and panning" section is now in "General Tools" chapter (c0e0d25) so delete it from this chapter and add a small reference to it.
> Remove "zooming and panning" section to avoid duplication

- source/docs/user_manual/print_composer/managing_composer.rst
It's now possible to select and manage multiple print composers in the Composer Manager (see https://github.com/qgis/QGIS/commit/3c33177910f2324c44613d6829ff1a1a94837658)
> Allows multiple print composers to be opened and deleted in one click

- source/docs/user_manual/working_with_vector/index.rst
- source/docs/user_manual/working_with_vector/virtual_layers.rst
This adds a section explaining what are virtual layers and how to create them
How can I point to other parts of the manual ? Is <pre>:ref:`Field_Calculator_Functions`</pre> the right syntax ?
> Add a section about virtual layers

- source/docs/user_manual/preamble/whats_new.rst
Pointed out the possibility of 
* creating __geometryless__ memory layers (qgis/QGIS#2653) (fixes #746)
* adding and removing fields
and that that all of these changes will be saved to projects/qlr files (qgis/QGIS#2624).
Of course the user would expect these features to be there anyways, but because they were absent in previous versions it might be worth documenting their addition now.
> Updated announcement of memory layers

- source/docs/user_manual/qgis_browser/qgis_browser.rst
* Add subsection for panel and stand-alone application.
* Add information for two icons in QGIS browser widget.
> Add information on QGIS browser widget (Fix #590)

- source/docs/user_manual/working_with_vector/vector_properties.rst
The tab name is Placement and not Position
Add information on z-index option
set the switch advice as a tip instead of note
> fix diagram placement description

- source/docs/user_manual/plugins/plugins.rst
Explanation on how plugin spirit is managed within QGIS project is somehow hidden at the end of the page, in a tip frame. This PR:
- moves this content at the top of the page 
- adds information on plugins (C++ or Python) location...
> Emphasize on different types of plugins and their location

- source/docs/user_manual/print_composer/composer_items/composer_items_options.rst
The blending mode description is no more in this chapter. It has been factorized and moved to an unique [place](http://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/vector_properties.html#blending-modes) so better link to that place.
> Update rendering link and fix some typos

- source/docs/user_manual/plugins/plugins_metasearch.rst
Fix some description : the plugin has now three tabs and not two, the record option has been moved...
Delete the hyperlink associated to the first screenshot and move this screenshot lower in the text
Break lines to around 80 characters
> Update metasearch plugin description

- source/docs/pyqgis_developer_cookbook/plugins.rst
As per http://osgeo-org.1560.x6.nabble.com/plugin-metadata-txt-icon-directive-td5259046.html
> clarify accepted image formats for plugin metadata

- source/docs/user_manual/preamble/whats_new.rst
It's weird to have `what's new in QGIS 2.8` as title while comment is about 2.14.
This commit uses the |version| substitution (set in `conf.py` file) so that this title is automatically updated according to the branch used (testing or numbered) to generate the doc.
> set a dynamic title

- source/docs/documentation_guidelines/do_translations.rst
Following the recent build errors related to translation errors (http://osgeo-org.1560.x6.nabble.com/Qgis-community-team-Translated-websites-td5253677.html) this PR updates the translation rules in order to integrate Transifex process. Thus, it :
- mentions Transifex
- reorders the description so that it fits Qt Linguist and Transifex
- complete the list of rules, according to @rduivenvoorde comment above
- fix some typo errors
I just wonder if I didn't make an excessive use of the \`` character :)
@rduivenvoorde @dassau @yjacolin
> Update translation process and rules description

- source/docs/user_manual/working_with_vector/vector_properties.rst
reorder description of effects (see #994)
apply the ".. only:: html" directive in order to remove `Figure Effects ...` title in the PDF doc
> Fix cosmetics in the "Draw effects" section

- source/docs/pyqgis_developer_cookbook/intro.rst
With recent versions of QGIS (I suppose since the authentication mechanism was added), the original example code resulted in a segmentation fault. I changed the example code based on comments in https://hub.qgis.org/issues/13494 so that it works again.
I also added a subsection for writing standalone scripts. The standalone scripts and custom application sections are very similar, but I thought it better to be explicit about the differences.
I tried to match the original structure as close as possible, but I had a build error when trying to use :const:False (I thought it would work since :const:True was used), so I put it in backticks for inline code instead.
> Update Python Application section example code and add example for standalone script

- source/docs/documentation_guidelines/writing.rst
- source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst
Add rule for writing button label (picked from http://docs.qgis.org/testing/en/docs/user_manual/preamble/conventions.html#gui-conventions e.g., **[OK]**)
Apply the rule to the doc (there was a single mistake in the user manual)
The training manual seems to not follow that rule given that it's full of `:guilabel:OK` or `:guilabel:Apply` and no **[...]**. I'm not sure it's worth fixing this. @pcav @timlinux ?
> Guidelines: Add rule for button labels

- source/docs/pyqgis_developer_cookbook/vector.rst
Try to execute in the Python QGIS console
```python
from qgis.gui import QgsColorButtonV2
btn = QgsColorButtonV2("Color 1")
```
You will get an issue like below:
> Traceback (most recent call last):
>   File "<input>", line 1, in <module>
> TypeError: QgsColorButtonV2(QWidget parent=None, QString cdt="", QgsColorSchemeRegistry registry=None): argument 1 has unexpected type 'str'
It seems previously the string for `QgsColorButtonV2` was the first arg whereas it's not true anymore.
Removing the string `"Color 1"` make the class constructor uses the default parameters.
> Fix QgsColorButtonV2 call in PyQGIS Cookbook

- source/docs/user_manual/introduction/getting_started.rst
Also replace |qg|
remove trailing spaces
> Fix starting and stopping QGIS description on different platforms

- source/docs/user_manual/working_with_vector/vector_properties.rst
* Add a section into `Special tools`
* Not removing the explanation in other part (specifically for size assistant
and composition)
This is a first move to follow #921.
> Data defined properties for font marker Fix #602

- source/docs/user_manual/introduction/qgis_gui.rst
Instead of list of options available in context menu per type of item in Layers panel, regroup them in a table. Avoid repetition.
something like this:
> Structure the lists of options in Layers panel context menu into a table

- source/docs/pyqgis_developer_cookbook/composer.rst
See issue #557 - use QgsRectangle rather than QgsRect (it appears QgsRect was the correct class in much older pre 2.0 QGIS versions).
> Fixing #557 - correct to QgsRectangle class - rebased

- source/docs/user_manual/introduction/general_tools.rst
- source/docs/user_manual/working_with_vector/vector_properties.rst
according to discussion in #629
The PR also fixes some text in order to have a more general oriented comment instead of vector layer oriented.
#1087 is about to move the data defined override section
> Migrate Color selector and blending mode from vector properties to General tools

- source/docs/user_manual/working_with_vector/supported_data.rst
Fix #703 (Text from the QGIS warning).
> Refine warning about estimated metadata

- source/docs/user_manual/introduction/general_tools.rst
- source/docs/user_manual/working_with_vector/supported_data.rst
Fix #682 Allow overide of geometry type in vector save as dialog
> Allow user to save vector and raster file

- source/docs/user_manual/introduction/general_tools.rst
Move up the "Data defined override" section, between "feature selection" and "Identify tools" sections (same context)
Move down, at the end, the "Decoration" section
no change in the text
> Reorder sections sequence in "General tools" chapter

- source/docs/user_manual/introduction/qgis_configuration.rst
- source/docs/user_manual/introduction/qgis_gui.rst
I've been using QGIS under Windows for years and never had a toolbar disappeared magically so I remove that comment that sounds like a bashing. I also remove the manipulation of the registry which imho should not be advised to anybody (an advanced setting) and there are simpler tips to solve that issue
fix #934
> Update restoring toolbar tip

- source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst
The digitizing environment has evolved in the last releases but it looks like the doc does not really reflect these changes.
This PR is the third and last part of the refactoring/updating of all this. It focuses on the advanced digitizing toolbar:
* add some indices to build the index list
* precise some tools behaviour
* add tips and note
* remove |nix| replacement
I didn't touch "Rotate Point Symbols" tool given that I was unable to use it (see http://osgeo-org.1560.x6.nabble.com/How-does-work-the-quot-Rotate-Point-Symbols-quot-tool-in-Advanced-digitizing-panel-td5274111.html)
Review (especially for english) is very welcome
> Update Advanced Digitizing tools description

- source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst
The digitizing environment has evolved in the last releases but it looks like the doc does not really reflect these changes.
This PR is the second part of the refactoring/updating of all this. It focuses on the digitizing toolbar:
* add some indices to build the index list
* precise some tools behaviour
* add new tools such as circular tools and the vertex editor (fix #1159)
* add tips and note
Review (especially for english) is very welcome
> update digitizing tools description

- source/docs/user_manual/working_with_vector/vector_properties.rst
given that the whole chapter has been moved and split and "draw effects" is currently the only survivor
> recontextualize the draw effects section

- source/docs/user_manual/working_with_vector/vector_properties.rst
Move the tip in "single symbol" at the end-of rule-based", after the concerned renderers are described
Insert new tips (trying to link this chapter to Layers panel styles capabilities)
Make human-readable indices and add new index
> Improve vector_properties with tips

- source/docs/user_manual/introduction/general_tools.rst
- source/docs/user_manual/working_with_ogc/ogc_server_support.rst
In dxf export, use can check a checkbox to use title instead of name as dxf layer name in
application and server.
Fix #715
> Add option to use title instead of name

- source/docs/user_manual/introduction/general_tools.rst
reorganise the list of information in something less compact
add mention of vertex radius : no issue report seen but information is available at http://qgis.org/en/site/forusers/visualchangelog216/index.html#feature-show-curve-point-radius-in-info-tool
> Precision on what Identify panel returns

- source/docs/user_manual/working_with_vector/attribute_table.rst
This PR prepares the "Editing attribute values section to insertion of "multi-edit" matters, by structuring it in subsections
It also:
* adds some precision in the text (field width --> field length, hyperlinks to related chapters...)
* cleans index
* and fix a wrong link to a figure, due to insertion of a new figure earlier in the chapter
> Structure the "Editing attribute values" section

- source/docs/user_manual/working_with_vector/expression.rst
fix #950 
I added the fix in a tip frame instead of a block text, hoping that it has more visibility (and actually it's a tip). I wonder if the place it's is the best one. Maybe should it be placed in the introductory section of Function list, before the listing of functions?
> Adding named parameters to functions

- readme.rst
The content of the file sample below was one-line text instead of multiline
> clean file sample rendering

- REQUIREMENTS.txt
Fixes an error when doing pip install -r REQUIREMENTS:
```
from _markerlib import compile as compile_marker
ImportError: No module named _markerlib
```
I tried embedding the markerlib in REQUIREMENTS but for some reasons I get the same error.
If you have better ideas, glad to hear them.
> install markerlib prior to pip install -r

- source/docs/user_manual/introduction/general_tools.rst
- source/docs/user_manual/introduction/getting_started.rst
- source/docs/user_manual/introduction/qgis_gui.rst
At the hackfest we decided to:
* move the panels description into General tools section.
* add a short description as a comment in the header of each file to explain to purpose of the chapter.
* don't change the getting-started or just update the screenshoot if needed
Fix #1334
> GUI vs General tools vs getting_started

- source/docs/user_manual/processing/modeler.rst
Line 285  :  When right-clicking on an algorithm that is not active, you will instead see a
Line 286  :  :guilabel:`Deactivate` menu option that you can use to activate it back.
This seems not correct to me. Expected value for the menu option should be  :guilabel:`Activate`.
Checked the option against a  deactivated model and the option says:  Activate
Please change for this case wording in doc from Deactivate to Activate
> Rename menu-option in doc.

- source/docs/user_manual/working_with_vector/expression.rst
Given that this kind of table seems more powergul, this is a trial to fix table truncation in pdf doc (see #1135 ).
I heard that it won't be easy for me to build pdf doc on Windows so if a linux guy wants to test a build... Otherwise I can merge it (nothing has really changed in the text nor the html rendering) and check at the next daily build of the pdf doc. If successful, will need to be applied on many other tables.
> refactor function's table

- Makefile
This allows much faster build for EN language to preview changes.
It skips internationalization and used rsync to update the static folder.
I also removed the W option so that it does not break on warnings
@rduivenvoorde , @DelazJ and @yjacolin can you please try it out?
> Adds fasthtml job to Makefile

- source/docs/user_manual/working_with_vector/vector_properties.rst
and  print composer legend (fix #975)
Also move the tip to a more appropriate place
> Diagram legend can be added in the layers panel

- source/docs/user_manual/introduction/general_tools.rst
- source/docs/user_manual/introduction/qgis_gui.rst
unlike what is stated, no description of panel is available in [qgis_gui](http://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_gui.html#panels). So this PR moves that comment to [general tools](http://docs.qgis.org/testing/en/docs/user_manual/introduction/general_tools.html#panels) (where some of them are described) and updates the list (and display) of panels.
NB: Travis will fail due to #1423 (waiting for review)
> Update list of panels

- source/docs/pyqgis_developer_cookbook/geometry.rst
As far as I can tell, the ellipsoid needs to be set. Without it, I always get planar results.
> Updated QgsDistanceArea use

- source/docs/pyqgis_developer_cookbook/communicating.rst
The QGIS Message bar example which includes a duration causes a SyntaxError due to one to many double quotes.
> Fix SyntaxError in example

- source/docs/gentle_gis_introduction/map_production.rst
The values in the text for latitude and longitude did not match those on figure_map_graticule. The values needed to be swapped.
[See image](http://docs.qgis.org/2.14/en/_images/map_graticule.png)
> Swapped latitude and longitude values.

- source/docs/user_manual/working_with_ogc/ogc_server_support.rst
better indicate the section itself
> Avoid indirect link that could break easily

- source/docs/user_manual/introduction/general_tools.rst
- source/docs/user_manual/working_with_raster/raster_properties.rst
- source/docs/user_manual/working_with_vector/vector_properties.rst
factorize description in layers properties section with a link to general tools where the option is fully described
fix #878
> Extend description of "scale-dependent visibility" option

- source/docs/pyqgis_developer_cookbook/crs.rst
I was unsuccessful using crs.proj4String() and instead found crs.toProj4() that works in QGIS 2.14.
From: QgsCoordinateReferenceSystem Class Reference (https://qgis.org/api/classQgsCoordinateReferenceSystem.html)
Other function may be obsolete as well, I didn't test them all
> crs.proj4String() not working in QGIS 2.14

- source/docs/pyqgis_developer_cookbook/vector.rst
Those examples that make use of `QVariant` current fail when used in the Python Console with:
NameError: name 'QVariant' is not defined
> Import QVariant in examples that require it

- source/docs/pyqgis_developer_cookbook/composer.rst
Fix #558 :- proposed change to image export example for QgsComposition, so that maps in the exported images are produced at the correct resolution (rather than quite low-res).
> fix for #558: to produce correct-res image outputs

- source/docs/documentation_guidelines/writing.rst
Typo, and Pacific Time isn't always Pacific Daylight Time.
> 2 quick writing.rst fixups

- source/docs/user_manual/index.rst
- source/docs/user_manual/preamble/contributors.rst
- source/docs/user_manual/preamble/preamble.rst
This PR aims to provide a list of docs contributors (writers and translators) as there's a list for the application contributors in the About panel.
The list of writers is a mix of:
- the authors listed in the [preamble chapter](http://docs.qgis.org/testing/en/docs/user_manual/preamble/preamble.html) of the doc (thus removed from this part of the doc)
- [github contributors](https://github.com/qgis/QGIS-Documentation/graphs/contributors) with at least one commit in the current repository.
There are some people I couldn't find their real name. Could you please provide your real name so that we update the list: @andremano @nydydn @mewoch @embelding @badewannencaptain @ajazepk @abusquets @GiordanoPezzola @Icephale ~~@mezwor @DiGro~~ @zstadler ? Thanks
Nobody is currently listed because I …
> Add list of contributors

- source/docs/user_manual/working_with_vector/vector_properties.rst
refs #1273 
This PR also tries to clear a bit this section which was imho a bit full of useless |radiobutton..| tags.
Also tries to describe free and horizontal settings.
**Before**:
**After**:
> Add labels with curved perimeter

- source/docs/training_manual/complete_analysis/analysis_exercise.rst
Fixes #246 and fixes qgis/QGIS-Website#216 (actually the same issues)
The ideal would be to add these data to the QGIS-Training-Data repo but it seems not (yet?) possible due to their size as [reported in the issue](https://github.com/qgis/QGIS-Website/issues/216#issuecomment-238101205) so... meanwhile...
> Add dropbox link to download more_analysis data

- source/docs/documentation_guidelines/substitutions.rst
- source/docs/user_manual/introduction/qgis_gui.rst
- source/docs/user_manual/working_with_projections/working_with_projections.rst
- source/docs/user_manual/working_with_raster/raster_properties.rst
- source/docs/user_manual/working_with_vector/vector_properties.rst
Insert a section to be reached from QGIS application Help button
Fix description
Add tip and note on the behavior of the CRS selection tool (inspired a bit by recent discussion on dev ML - actually a frequent confusion for new users)
> Add precision on CRS selector and OTF reprojection

- source/docs/user_manual/working_with_vector/style_library.rst
Fixes #1712 (with some [backportable](https://github.com/DelazJ/QGIS-Documentation/commit/7fcd7f20b09f518cc22dbf548d38ca8d09c1558a) improvements)
> Use "stroke" instead of outline or pen in symbols dialog

- source/docs/training_manual/basic_map/symbology.rst
- source/docs/training_manual/complete_analysis/analysis_combination.rst
- source/docs/training_manual/complete_analysis/analysis_exercise.rst
- source/docs/training_manual/databases/db_browser.rst
- source/docs/training_manual/databases/db_manager.rst
- source/docs/training_manual/databases/spatialite.rst
- source/docs/training_manual/forestry/forest_maps.rst
- source/docs/training_manual/foreword/preparing_data.rst
- source/docs/training_manual/qgis_plugins/plugin_examples.rst
- source/docs/training_manual/rasters/data_manipulation.rst
- source/docs/training_manual/vector_analysis/spatial_statistics.rst
Because `:guilabel:` doesn't render `-->`
I also found that the training manual is full of sphinx role misuse, particularly `:kbd:` which is used for files and text instead of keyboards commands.
> Display menu selection correctly in Training manual

- source/docs/user_manual/working_with_vector/style_library.rst
Brings altogether svg marker description and note
Aerate geometry generator code sample and `guess`ing the highlight (`sql` renders in github but not in html)
Fix some spelling and indentation
> Improve symbol dialog description

- source/docs/user_manual/working_with_vector/expression.rst
As usual the first commit (@fd50093) is compatible with 2.18
I let some comments because of missing description in the application (and reported the bug on hub)
Fixes #1723, Fixes #1715, Fixes #1649, Fixes #1617, Fixes #1616, Fixes #1615, Fixes #1540, Fixes #1539, Fixes #1521, Fixes #1514, Fixes #1509, Fixes #1486, Fixes #1479, Fixes #1476, Fixes #1475, Fixes #1472, Fixes #1379, Fixes #1348,  Fixes #1304
> Add some expression functions

- source/docs/user_manual/introduction/general_tools.rst
- Add a section on Identify configuration dialog
- Add information on read-only for fields via widget configuration
Fix #937
> Save readonly mode of vector layers in project

- source/docs/user_manual/introduction/general_tools.rst
- source/docs/user_manual/introduction/qgis_gui.rst
Create sub-sections in the Layers panel section because:
* the preset visibility description deserves a more visible and direct link
* groups have been improved in QGIS 3 and will need their own section
* and, there was only one sub-section (which is not nice)
\+ some cleanup
> Structuring the Layers panel description

- source/docs/user_manual/grass_integration/grass_integration.rst
It was pointing to a page that informs the user that the data was moved.
> Fix link to data sample page

- source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst
Extending line is a particular feature of reshape tool and its description was hidden in the "usual" behavior of that tool
> Highlight the reshape tool as line expander

- source/docs/pyqgis_developer_cookbook/geometry.rst
old way didn't work anymore, this works in QGIS 2.18.
The documentation (http://qgis.org/api/2.18/classQgsGeometry.html#ab0e572d06fef008c619651f5a55944f8) mentions that int length must be provided, this is not the case on my machine.
> Creating a geometry from WKB changed

- source/docs/user_manual/introduction/general_tools.rst
- source/docs/user_manual/working_with_vector/supported_data.rst
to avoid a big and a bit heteregeneous note
Also there's no more tip in the postgis chapter the server side execution is no longer experimental.
> Spread the note content in the "save style" sections

- source/docs/user_manual/print_composer/composer_items/composer_attribute_table.rst
- source/docs/user_manual/print_composer/composer_items/composer_html_frame.rst
- source/docs/user_manual/print_composer/composer_items/composer_image.rst
- source/docs/user_manual/print_composer/composer_items/composer_items_options.rst
- source/docs/user_manual/print_composer/composer_items/composer_items_shape.rst
- source/docs/user_manual/print_composer/composer_items/composer_label.rst
- source/docs/user_manual/print_composer/composer_items/composer_legend.rst
- source/docs/user_manual/print_composer/composer_items/composer_map.rst
- source/docs/user_manual/print_composer/composer_items/composer_scale_bar.rst
- source/docs/user_manual/print_composer/create_output.rst
- source/docs/user_manual/print_composer/overview_composer.rst
- replace tab by panel (fix #1716)
- break lines to 80 characters
(ps: backport may not be straightforward)
> Print composer panels are no longer called "tabs"

- source/docs/user_manual/working_with_vector/attribute_table.rst
section to a more visible and introductory place
QGIS handles spatial and non spatial attribute table the same way but most of the descriptions target a spatially enabled layer. A section that concerns non spatial table is somehow hidden in the middle of the attribute table description. This PR moves it to the top of the chapter (_wonder if this sh/wouldn't be a candidate for supported format chapter_).
>  Move "working with non spatial attributes table"

- source/docs/user_manual/working_with_vector/vector_properties.rst
Also:
Introduce labels as a full part of the properties dialog
Differentiate main labeling types (moving rule-based labeling near simple labeling) and labeling options (data-defined and expression based)
Place hyperlink to quickly access sub-tabs
Improve rule-based labeling description
combined with #1960 here is the new toc
> Make the Label chapter match the dialog

- source/docs/user_manual/plugins/core_plugins.rst
- source/docs/user_manual/plugins/plugins_metasearch.rst
- source/docs/user_manual/working_with_ogc/ogc_client_support.rst
- source/docs/user_manual/working_with_ogc/ogc_server_support.rst
- source/docs/user_manual/working_with_vector/vector_properties.rst
because QGIS is en-US compliant (and because of https://github.com/qgis/QGIS/pull/4801)
+ minor spelling fixes
> Replace catalogue by catalog

- source/docs/user_manual/introduction/general_tools.rst
- source/docs/user_manual/introduction/qgis_configuration.rst
- source/docs/user_manual/working_with_vector/attribute_table.rst
The current description mix sections about selection tools and filtering tools. It also ignores working on a form view of attribute table. 
This PR tries to fix things, clearly separating these different needs in a clear structure (Related to #1754 cleanup). Note that it doesn't touch sections relative action on cells or layer creation.
Also fixes #560 about attribute table spatial filtering
> Clean selection and filter sections in attribute table chapter

- source/docs/user_manual/introduction/general_tools.rst
- source/docs/user_manual/introduction/qgis_configuration.rst
I wonder if it is better placed there with other global configuration options (shortcuts are a kind of configuration you do for the application "once for all").
Opinions?
> Move Keyboard Shortcuts from General tools to Configuration chapter

- source/docs/user_manual/working_with_ogc/ogc_server_support.rst
this link (http://linfiniti.com/2010/08/qgis-mapserver-a-wms-server-for-the-masses/) does not exist anymore. I could not find a new location of it ...
> removed dead link

- source/docs/index.rst
The 2.18 doc showed QGIS Testing instead of 2.18.
What would be nice is to have it dynamically updated when a new branch is created (e.g. using its |version| replacement).
Anyone knows how to?
> Set right caption in 2.18 Table Of Contents

- readme.rst
The introduction made too much focus on QGIS Testing Doc than QGIS Doc itself
> Because it's more about QGIS than QGIS Testing

- source/docs/pyqgis_developer_cookbook/server.rst
In http://docs.qgis.org/2.18/en/docs/pyqgis_developer_cookbook/server.html#modifying-the-input the mentioned line 13 is not identifiable so here's a way to show it easily; the relevant commit is https://github.com/DelazJ/QGIS-Documentation/commit/154f3772562958776ec14b4773306bfae24e4f71, the rest is about breaking lines too long to review.
I'd tried to add line numbers to the code sample but the rendering is unfortunately really weird (maybe we need some configurations to set?)
> Better show the mentioned line in code sample

- source/docs/user_manual/working_with_ogc/ogc_client_support.rst
line 226 :  missing colon (:) before  "ref:" ----> corrected
> Typo corrected

- source/docs/training_manual/qgis_plugins/plugin_examples.rst
Should use 'Web -->...' not 'Plugins -->...' to access
'OpenLayers Plugin' functionality.
> Fix menuselection typo in 10.2.2

- source/docs/training_manual/vector_analysis/basic_analysis.rst
In version 2.18 the option is 'Fixed distance buffer' not 'Buffer(s)'
> Fix some text inconsistencies with 2.18 version

- source/docs/user_manual/processing_algs/index.rst
Because we are our own best advocates, let's first show QGIS native algs before other providers at http://docs.qgis.org/testing/en/docs/user_manual/processing_algs/index.html
> Move the QGIS native algorithms at the top of the list

- source/docs/user_manual/working_with_vector/vector_properties.rst
Because people often look for this default value and it might be nice to expand a bit on it (inspired by @m-kuhn [tip](https://gis.stackexchange.com/questions/211120/how-to-set-a-default-value-for-attributes-in-shapefiles/211154#211154)).
Also trying to cover some redundant issue report about missing fields in the expression dialog.
> More details on the default value option

- source/docs/user_manual/plugins/plugins.rst
Resurrecting an old branch of mine that describes the settings tab first and add details on settings ( was written after a message in a forum of someone looking for the default repository link - he might have deleted it - and I found nowhere it was mentioned )
> [Plugins dialog] Move the settings tab upper and add details

- source/docs/user_manual/working_with_raster/raster_properties.rst
Line 334 and 337 : The file landcover.tif does not (longer) exist in the sample set for QGIS. (Alaska)
The file is now named landcover.img.
Changed the extension
> New filename in sample set

- source/docs/user_manual/working_with_vector/expression.rst
Fix #1982 Add get_feature_by_id function to the Record and Attributes functions on the expressions page
> fix #1982 - Add get_feature_by_id

- source/docs/training_manual/create_vector_data/forms.rst
- source/docs/user_manual/working_with_vector/vector_properties.rst
The tutorials of the QGIS trainings manual (https://docs.qgis.org/2.18/en/docs/training_manual/create_vector_data/forms.html#ls-forms) were not referenced before.
Could you please check if I referenced the tutorials correctly (according to Sphinx) ?
> Referenced tutorials

- source/docs/user_manual/index.rst
As a general comment this chapter should be shown before GUI conventions.
> Move up the foreword chapter in the TOC

- source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst
in Options dialog (actually this label no longer exists)
Also move down general tips on setting snap tolerance and search radius, i.e. after all the search radius-only information are provided
> Not only "layer units" is available for search radius

- source/docs/pyqgis_developer_cookbook/vector.rst
Variable is assigned but not used before it is reassigned in the for loop.
> Remove dead code from example, standardise feature variable naming 

- source/docs/user_manual/processing_algs/gdal/index.rst
- source/docs/user_manual/processing_algs/gdal/rasteranalysis.rst
- source/docs/user_manual/processing_algs/gdal/rasterconversion.rst
- source/docs/user_manual/processing_algs/gdal/rasterextraction.rst
- source/docs/user_manual/processing_algs/gdal/rastermiscellaneous.rst
- source/docs/user_manual/processing_algs/gdal/rasterprojections.rst
- source/docs/user_manual/processing_algs/gdal/vectorconversion.rst
- source/docs/user_manual/processing_algs/gdal/vectorgeoprocessing.rst
- source/docs/user_manual/processing_algs/gdal/vectormiscellaneous.rst
- source/docs/user_manual/processing_algs/index.rst
This was missing --> GDAL algs did not open right help pages.
Should SAGA algs also be renamed? (I don't have SAGA enabled on my computer to check how that behaves)
> Rename GDAL algs filename to match groupId

- source/docs/developers_guide/hig.rst
This PR tries to fix this UI/UX issue:
https://github.com/qgis/qgis3_UIX_discussion/issues/43
I used this Qt guidelines:
https://doc-snapshots.qt.io/qtcreator-extending/qtcreator-ui-text.html#ui-text-capitalization
Main changes are in points 2 and 3, the rest is just reordering the numbered list.
I wonder if we want to apply this or not, as it would enforce us to capitalize all group boxes labels and combobox items.
> Document capitalization in HIG

- source/docs/user_manual/working_with_ogc/server/config.rst
- source/docs/user_manual/working_with_ogc/server/getting_started.rst
- source/docs/user_manual/working_with_ogc/server/plugins.rst
I noticed that we're inconsistent when presenting the bash commands.
@pblottiere You prefer the $ in front so that it's recognizable, and we could go that way everywhere.
However, I found it a little bit annoying to copy the commands as double clicking the line with the commands adds the $ and I have to delete it everytime  + this means two characters in plus on the line.
So I would go without the ``$`` in front.
@DelazJ @SrNetoChan @yjacolin @pblottiere Opinions?
> remove the $ in front of bash commands for consistency

- source/docs/user_manual/introduction/qgis_configuration.rst
Fix #2307 and fix some minor changes: move locale tab to general one's (fix #2168) and node
term replacement (fix #2330)
> Reorganize Options dialog

- source/docs/user_manual/working_with_vector/attribute_table.rst
> Relocate cut/copy/paste actions in attribute table

- source/docs/user_manual/introduction/general_tools.rst
- source/docs/user_manual/print_composer/composer_items/composer_attribute_table.rst
- source/docs/user_manual/print_composer/composer_items/composer_html_frame.rst
- source/docs/user_manual/print_composer/composer_items/composer_image.rst
- source/docs/user_manual/print_composer/composer_items/composer_items_shape.rst
- source/docs/user_manual/print_composer/composer_items/composer_label.rst
- source/docs/user_manual/print_composer/composer_items/composer_legend.rst
- source/docs/user_manual/print_composer/composer_items/composer_map.rst
- source/docs/user_manual/print_composer/composer_items/composer_scale_bar.rst
- source/docs/user_manual/print_composer/create_output.rst
- source/docs/user_manual/print_composer/overview_composer.rst
changes due to GUI renaming
This PR is an extraction from #2469; it contains changes related to anchors and fixes some GUI component but nothing big. Combined with #2471 the idea is to lighten #2469 to only the changes about dialog overview.
Will merge once Travis is happy.
> Add some convenient anchors in Layout and apply

- source/docs/user_manual/working_with_vector/vector_properties.rst
> Update list of edit widgets

- source/docs/user_manual/print_composer/overview_composer.rst
This is another step on the road from composer to layout. It does not really describe features but instead focus on the update of [tools listed in Overview section](https://docs.qgis.org/testing/en/docs/user_manual/print_composer/overview_composer.html#menus-tools-and-panels-of-the-print-layout).
Instead of a single table with only the tools listed and then sections describing each menu, I split that table by menus (as done in QGIS GUI chapter, with shortcut, toolbar and reference link) and moved menu description near the table (focusing only on tools that imho are worth it). Grouped this way, information are imho better available and understood (with less repetition).
This PR also adds new icons/substitutions and updates some icons that were too big in github preview.
Meanwhile, it also …
> Update Layout tools overview

- source/docs/pyqgis_developer_cookbook/vector.rst
The ``adding and removing fields`` part is sitting between adding  deleting and modifying features with and without buffer. it should be at the end of the editing chapter so it doesn't interrupt the flow of the editing part.
> move adding and removing fields part after editing features

- source/docs/user_manual/print_composer/overview_composer.rst
in order to present more global and setting-level panels beforehand
> Move the Undo/Redo panel to the bottom

- source/docs/user_manual/print_composer/composer_items/composer_items_options.rst
Under common options (supposed to describe item properties), there was a large section describing interaction with items. This PR really distinguishes those two components and updates some behavior.
Fixes #2150 Fixes #2151 Fixes #2152 Fix #2001
> Improve layout items general behavior

- source/docs/user_manual/introduction/general_tools.rst
- source/docs/user_manual/working_with_vector/vector_properties.rst
Because annotations dialog is almost the same, better group their description at a single place and avoid some repetition. also updates the dialog (refs #1831 , fix #1655, fix #1656) and add some tips and links to other chapters.
> Update annotation tools description

- source/docs/user_manual/managing_data_source/opening_data.rst
> Add "DWG/DXF Import..." description

- source/docs/user_manual/print_composer/composer_items/composer_items_shape.rst
Node-based tool has been improved and got all the capabilities of arrow item so arrow item description has been transfered to node-based tool and the arrow item section is presented as a sub-item (shortcut) of the polyline node tool (fixes #2242)
PS: build will fail (at least) because of references in unreviewed #2494 which is the basement of all items description
> Update layout node-based tool description

- source/docs/user_manual/print_composer/composer_items/composer_items_shape.rst
This PR to avoid big changes in the composer_items_shape.rst file at once (and scare any reviewer?) and split regular shape description from the node-based items one. It updates the description to use #2494 as basement (hence build fail)
> Update the layout regular shape item description

- source/docs/user_manual/introduction/general_tools.rst
in order to:
- have a somehow more (and better?) structure table of content
- group sections by topic (with a kind of red line in the background)
- open room for some old and new features description (map view, introducing 3D, units/fonts/scale(?) widgets...)
This PR does not contain text changes other than adding/renaming some sections titles and necessary blank lines. It's all about moving sections so I'd say there's almost no need to review the text, just comment the following Before -- After screenshot (TOC limited here to two levels for, let's hope, readability)
>  Reorganizing sections in general tools chapter

- source/docs/user_manual/processing/toolbox.rst
- source/docs/user_manual/processing_algs/qgis/rasteranalysis.rst
fix #2345 
**however** the parameter `Reference layers(s)(used for automated extent, cellsize and CRS)` is **not** optional as stated in the GUI. I made some tests and at least one layer has to be chosen, else the algorithm won't run.
@nirvn is this the expected behavior?
> [processing] raster calculator update

- source/docs/user_manual/introduction/qgis_configuration.rst
- source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst
My first PR for the documentation 😃 
I added a small paragraph to document my [PR](https://github.com/qgis/QGIS/pull/6750) for the snapping on (in)visible features. 
Fix #2594
> Default snapping on visible features

- source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
- source/docs/user_manual/working_with_vector/expression.rst
- source/substitutions.txt
This is an attempt to implement a fix that helps readers to identify which algorithms or parameters are newer than the version they use (see [discussion](http://osgeo-org.1560.x6.nabble.com/QGIS-Developer-Documentation-and-algorithm-news-td5358055.html#a5358340))
> Mention release version next to newer algorithms (or parameters)

- source/docs/user_manual/working_with_vector/vector_properties.rst
Fix #1370
Honestly I do not really understand the use case. @mhugo can you please elaborate more on QGIS layer caching. I thought that triggers were acting automatically and will update the layer in QGIS. From what I've experienced (i just use some simple triggers and views), the "resulting" layer was updated as soon as canvas was refreshed.
What's the difference here? Some use case that could help readers to understand when to use this feature?
Thanks
> Add description for dependencies tab

- source/docs/user_manual/introduction/qgis_gui.rst
This is a general update of the recent changes to the status bar. It's also a follow-up to #2598 (hence build is expected to fail as it uses reference that is in that PR) and would close #1913
> Updating the status bar description

- source/docs/pyqgis_developer_cookbook/plugins.rst
Shouldn't be relevant anymore. Probably everyone is using QGIS >= 2.x
> remove obsolete "since QGIS 2.0 and 1.8" parts about metadata.txt

- source/docs/user_manual/working_with_vector/vector_properties.rst
When reaching this section from the diagram's page, it looks weird that the description was mostly focused on symbology and almost never mention diagrams. Should be fairer now.
> Do not hide mention of diagram scaled size legend

- source/docs/user_manual/introduction/qgis_gui.rst
- source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst
Also update tools references: because many tools have recently moved to another toolbar, using the tool's direct reference instead of the toolbar's ensures we will always reach the tool section and not a wrong chapter
> Update Edit menu items

- source/docs/user_manual/introduction/qgis_gui.rst
because not used in other places (eg, layout overview) and it's a hyperlink in a reference column
> Remove redundant "see..." in reference column

- source/docs/user_manual/introduction/general_tools.rst
Fixes #2575 (documentation of 'Move to Top')
Fixes https://github.com/qgis/QGIS/pull/6881 (Documentation of 'Move Out of Group') - somehow it doesn't seems like there is an Issue with this PR have been made, even though it is tagged with 'needs-docs'.
> Documents 'Move to Top' and 'Move Out of Group'

- source/docs/user_manual/introduction/general_tools.rst
From QGIS 3.2. it is possible to zoom to bookmarks in the new locator. This PR add one line regarding this new possibility to the documentation.
The new feature (https://github.com/qgis/QGIS/pull/6418) is not included in any issues in the QGIS documentation GitHub repository.
> Documents new possibility to search for and zoom to bookmarks in the locator

- source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst
Fix #1721: Add a tip about toggling snapping by pressing `S`
> Add keyboard shortcut for toggling snapping

- source/docs/training_manual/basic_map/symbology.rst
- source/docs/training_manual/complete_analysis/analysis_exercise.rst
- source/docs/training_manual/forestry/results_map.rst
- source/docs/training_manual/forestry/stands_digitazing.rst
- source/docs/training_manual/rasters/changing_symbology.rst
- source/docs/training_manual/vector_classification/classification.rst
- source/docs/user_manual/introduction/getting_started.rst
- source/docs/user_manual/working_with_raster/raster_properties.rst
- source/docs/user_manual/working_with_vector/vector_properties.rst
for vector (Fixes #1431) and raster (refs https://github.com/qgis/QGIS/pull/7275)
> Use Symbology instead of Style for layer properties tab

- source/docs/user_manual/working_with_vector/vector_properties.rst
Fixes #2199
Also, currently the comments can not be set or modified in the source
fields tab and are not saved in the project
> Field comment is displayed as tooltip in the form

- source/docs/documentation_guidelines/writing.rst
- source/docs/training_manual/basic_map/symbology.rst
- source/docs/training_manual/create_vector_data/create_new_vector.rst
- source/docs/training_manual/database_concepts/data_model.rst
- source/docs/training_manual/map_composer/map_composer.rst
- source/docs/training_manual/rasters/data_manipulation.rst
- source/docs/training_manual/spatial_databases/spatial_functions.rst
- source/docs/user_manual/introduction/general_tools.rst
- source/docs/user_manual/print_composer/composer_items/composer_items_shape.rst
- source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst
- source/docs/user_manual/working_with_vector/style_library.rst
* remove spaces from key combinations
* change single letter keys to upper case
* special keys capitalised
> Fixes #2743: Standardise the style of keyboard shortcuts

- source/docs/documentation_guidelines/writing.rst
- source/docs/user_manual/processing_algs/qgis/vectorcreation.rst
fix #2432 
@DelazJ @SrNetoChan just to follow up the discussion #2732. This alg wants a `folder` in input and `folder` is not listed in our parameter table. I guess we have to add it, even if not widely used.
> [processing] geotagged photos

- source/docs/pyqgis_developer_cookbook/plugins.rst
Fix a mistaken statement that the email addresses are not visible in the Plugin Manager. A better wording welcome... 
See also:
- https://issues.qgis.org/issues/19239  
- http://osgeo-org.1560.x6.nabble.com/Qgis-community-team-Plugin-author-emails-after-the-GDPR-apocalypse-td5368840.html
- http://osgeo-org.1560.x6.nabble.com/How-do-I-specify-multiple-plugin-authors-td5239517.html
CC @timlinux @pcav @tomchadwin @elpaso
> Update description of the plugin author email metadata tag

- source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
- source/docs/user_manual/processing_algs/qgis/vectortable.rst
This should remove the [fieldsmapping] parameter type (though I did not grep the source to check) and address a point raised in https://github.com/qgis/QGIS-Documentation/pull/2738#issuecomment-400343396 with their removal.
I'm no longer sure it's worth explaining those widgets somewhere else (more than what is done in the parameter section).
> Details the custom widget of the "Refactor Fields" and "Aggregate" algorithms

- source/docs/user_manual/introduction/qgis_configuration.rst
Give more visibility to each tab and generate custom hyperlink for each. Also align with other main tabified dialogs.
No changes done to the content other than indentation.
> Create sections in the Project properties description

- source/docs/user_manual/working_with_vector/expression.rst
* add new variables (refs #2637,  fix #2751)
* add new geometry functions (refs #2591, fix #2592)
Other than the sample sections, a function or variable in the docs gave less information than what is served in the Expression builder help section. This PR proposes to add, when available, a link to the corresponding algorithm, because reading the function description may not be enough while the alg description may contain screenshot and more details. This way, readers can have a visual appreciation of what the (geometric) function does.
> Update list of expression functions

- source/docs/pyqgis_developer_cookbook/authentication.rst
- source/docs/pyqgis_developer_cookbook/canvas.rst
- source/docs/pyqgis_developer_cookbook/communicating.rst
- source/docs/pyqgis_developer_cookbook/composer.rst
- source/docs/pyqgis_developer_cookbook/crs.rst
- source/docs/pyqgis_developer_cookbook/expressions.rst
- source/docs/pyqgis_developer_cookbook/geometry.rst
- source/docs/pyqgis_developer_cookbook/ide_debugging.rst
- source/docs/pyqgis_developer_cookbook/index.rst
- source/docs/pyqgis_developer_cookbook/loadlayer.rst
- source/docs/pyqgis_developer_cookbook/loadproject.rst
- source/docs/pyqgis_developer_cookbook/network_analysis.rst
- source/docs/pyqgis_developer_cookbook/pluginlayer.rst
- source/docs/pyqgis_developer_cookbook/plugins.rst
- source/docs/pyqgis_developer_cookbook/processing.rst
- source/docs/pyqgis_developer_cookbook/raster.rst
- source/docs/pyqgis_developer_cookbook/releasing.rst
- source/docs/pyqgis_developer_cookbook/server.rst
- source/docs/pyqgis_developer_cookbook/settings.rst
- source/docs/pyqgis_developer_cookbook/snippets.rst
- source/docs/pyqgis_developer_cookbook/vector.rst
- source/substitutions.txt
Because people think that information in the Cookbook are already updated and vainly tried the recipes, it could be nice to alarm them on
this. (fixes #2754)
> Add a warning about outdated information in PyQGIS Cookbook

- source/docs/index.rst
Typo: "Trainings"
QGIS in "QGIS Developers Guide" when others do not have that.
Use uppercase as per titles.
> Fix typo and inconsistencies in TOC

- source/docs/pyqgis_developer_cookbook/plugins.rst
- source/docs/user_manual/plugins/plugins.rst
Remove reference to Python 2.7, and __init_.py which is covered later.
> Update plugin paths for QGIS 3 in PyQGIS Cookbook

- source/docs/documentation_guidelines/substitutions.rst
- source/docs/user_manual/introduction/qgis_configuration.rst
with more details on the settings submenus
Also, Project properties is no longer a sub item of Settings menu and is consistently placed on all platforms under Project menu.
> Expand the introduction of Settings menu

- source/docs/pyqgis_developer_cookbook/loadlayer.rst
Using QFileInfo.baseName() is potentially confusing, this is just the
display name.
--
C++ documentation changed here: https://github.com/qgis/QGIS/commit/2a72eda5142b54dde60244b5dab3ec5db8441680
> Simplify creation of QgsRasterLayer() example in PyQGIS Cookbook

- source/docs/pyqgis_developer_cookbook/plugins.rst
- source/docs/pyqgis_developer_cookbook/releasing.rst
- Be clearer in the examples about which files are mandatory.
- Mention the Log Messages Plugins panel.
- Remove references to the Python Plugin Repositories wiki.
- Use https where available.
- Minor wording improvements.
> Update Plugins for QGIS 3 in PyQGIS Cookbook

- source/docs/pyqgis_developer_cookbook/loadlayer.rst
All unsaved changes to the project will be lost on exit. Remove text
that made map layers appear to be a special case.
---
Please check, maybe I missed the point here.
> Simplify description of removeMapLayer() in PyQGIS Cookbook

- source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
- source/docs/user_manual/processing_algs/qgis/vectoroverlay.rst
- source/docs/user_manual/processing_algs/saga/shapes_tools.rst
to reduce translation workload
> Harmonize [vector: line, polygon] vs [vector: polygon, line] type

- source/docs/training_manual/foreword/foreword.rst
- source/docs/training_manual/foreword/preparing_data.rst
- source/docs/training_manual/introduction/preparation.rst
- source/docs/training_manual/qgis_server/wms.rst
- source/docs/user_manual/working_with_ogc/server/getting_started.rst
Because 3.4 data training aims to give a particular place to gpkg
Because 3.4 exercises may not be compatible with 2.18
Because 2.18 users should still be able to train themselves with "working" data
We cannot keep the same branch for the two docs. A new branch is created and linked to.
> Fix link to data training repository

- source/docs/user_manual/print_composer/composer_items/composer_items_options.rst
I'm less convinced by this one; I wonder if I should not simply remove these icons from the repo and skip this description
> using print layout alignment icons

- source/docs/user_manual/print_composer/composer_items/composer_label.rst
QGIS has a lot of functions and variables plus a lot of places where these functions can be combined to endless possibilities. In the user manual, other than stating that an option is data-definable, i think there's a lack of showcase. What can I do? Or how can I write an expression?
This PR would like to introduce a section now in the print layout label item (the easiest) but the idea is to add more section in different chapters with things people can do with variables and expressions (map/legend/scalebar/... item size/placement modification, playing with map theme, playing with symbology....) .
(_Yes, there are some code samples in the Expression chapter but I think while those are desirable, putting the code sample near the feature in which I'd use it is also nice_)
> Add examples of expression in the layout label item

- source/docs/pyqgis_developer_cookbook/vector.rst
Because I don't know how long we'll remember the sections that got updated nor when the earlier sections in the chapter will be updated (so that we move the warning message), this PR places a note so that writers do not lose time on testing what does not need.
> Indicate updated sections to avoid losing time on testing

- source/docs/user_manual/working_with_ogc/server/config.rst
This PR follows up on https://github.com/qgis/QGIS/pull/7814. It documents the new QGIS_SERVER_LOG_STDERR variable, and deprecates QGIS_SERVER_LOG_FILE.
> Document QGIS_SERVER_LOG_STDERR

- source/docs/user_manual/introduction/general_tools.rst
This is the first of a series of pull requests that explore the color widget capabilities. Instead of a big and multi-file PR I opted to small and somehow self-content PRs that should be easier to review.
This PR mainly reorganizes the paragraphs so that color representation is distinct from widgets and makes room for other sub sections.
> Restructure the color selector dialog description

- source/docs/user_manual/processing_algs/gdal/rasterconversion.rst
Fixes #2950 
@nirvn I think I found a bug: once the bands order is modified and the widget closed, if you reopen the band selection widget, the bands you selected are still checked but the order is reset (you lose your custom order). A bug, right?
> Add GDAL Rearrange bands algorithm

- source/docs/training_manual/foreword/foreword.rst
- source/docs/training_manual/foreword/preparing_data.rst
- source/docs/training_manual/introduction/preparation.rst
1. Currently, there are four places where the link to the training manual data is provided. fortunately, they are all the same. With this PR, only a single place remains for the link and the other places are removed or point to it. Easier to maintain.
1. Also, instead of adding a clear link in the text that would be translated, a reference is used, allowing us to freely manage the branches of the data training repo without breaking future translations and still keep the good reference.
1. Downloading the TM data currently creates a `QGIS-Training-Data-QGIS-Training-Data-v2.0.zip` file. Rather ugly name imho. Fixing this by a new `v2.0` branch created in the training data repo and the export file will now be named `QGIS-Training-Data-v2.0.zip`
1. The zip file stores the file under a …
> [TM] Structuring reference to training data download page

- source/docs/user_manual/introduction/general_tools.rst
- source/docs/user_manual/working_with_vector/vector_properties.rst
screenshots not up to date:
* in `user_manual/working_with_vector/vector_properties.html#symbology-properties` the screenshot (https://docs.qgis.org/testing/en/_images/style_combobox.png) should be updated with the new menu (with style categories)
* https://docs.qgis.org/testing/en/_images/categorysymbol_ng_line.png 
actually, it seems that all screen shots present the old "style" tab instead of "symbology".
see https://github.com/qgis/QGIS/pull/7863
> symbology and styles clarifications

- source/docs/pyqgis_developer_cookbook/loadlayer.rst
- source/docs/pyqgis_developer_cookbook/vector.rst
- source/docs/training_manual/complete_analysis/analysis_combination.rst
- source/docs/training_manual/complete_analysis/raster_to_vector.rst
- source/docs/training_manual/introduction/overview.rst
- source/docs/training_manual/introduction/preparation.rst
- source/docs/training_manual/spatial_databases/import_export.rst
- source/docs/training_manual/spatial_databases/index.rst
- source/docs/training_manual/vector_analysis/spatial_statistics.rst
- source/docs/user_manual/grass_integration/grass_integration.rst
- source/docs/user_manual/introduction/getting_started.rst
- source/docs/user_manual/managing_data_source/create_layers.rst
- source/docs/user_manual/managing_data_source/opening_data.rst
- source/docs/user_manual/managing_data_source/supported_data.rst
- source/docs/user_manual/preamble/features.rst
- source/docs/user_manual/processing/3rdParty.rst
- source/docs/user_manual/processing_algs/qgis/vectorgeneral.rst
- source/docs/user_manual/working_with_projections/working_with_projections.rst
- source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst
- source/docs/user_manual/working_with_vector/expression.rst
- source/docs/user_manual/working_with_vector/vector_properties.rst
More than renaming the training manual shapefiles folder into shapefile, this is a review of the use of this term:
* use **S**hapefile when it's about the format itself
* avoid the use of shapefile as synonym of vector layer: shapefile must die, right?
* fix some formatting (:kbd: instead of :file: or ``) and typo
Hoping that i've been constant in my rules...
> Exploring the use of "shapefile"

- source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
A new concave hull algorithm has been added.  It is now documented, and the title of the original concave hull algorithm is changed (Fixes #3018).
> Add concave hull knn and update the name of original concave hull

- source/docs/training_manual/processing/index.rst
It just add an harmless anchor to the Processing TM index page. Useful in some upcoming chapters.
I'm going to merge after Travis is happy, we can revert/change it easily
> [tm] adding an anchor to Processing index

- source/docs/user_manual/working_with_ogc/server/services.rst
This PR updates the WFS service documentation in a similar way than the WMS service.
Moreover, it adds some words on RESULTTYPE parameter to fix https://github.com/qgis/QGIS-Documentation/issues/2171.
> Add documentation for WFS and RESULTTYPE=hits

- source/docs/user_manual/processing_algs/qgis/cartography.rst
> Add "Create categorized renderer from styles" algorithm

- source/docs/user_manual/working_with_ogc/server/getting_started.rst
I just build the master and tested this issue and it now works correctly.
I don't know when this was fixed, I suppose @pblottiere or @elpaso worked on it (thank you guys).
Will also close the relevant https://issues.qgis.org/issues/13703
> remove server relative svg warning as it's fixed

- source/docs/user_manual/working_with_ogc/server/getting_started.rst
Using fcgiwrap results in a much slower set-up than using spawn-fcgi. The changes suggested by this PR make this clear, and recommend spawn-fcgi for production use.
> Improve the QGIS Server with NGINX deployment documentation

- source/docs/user_manual/processing_algs/gdal/rasteranalysis.rst
- source/docs/user_manual/processing_algs/gdal/rasterconversion.rst
- source/docs/user_manual/processing_algs/gdal/rasterextraction.rst
- source/docs/user_manual/processing_algs/gdal/rastermiscellaneous.rst
- source/docs/user_manual/processing_algs/gdal/rasterprojections.rst
- source/docs/user_manual/processing_algs/gdal/vectorconversion.rst
- source/docs/user_manual/processing_algs/gdal/vectorgeoprocessing.rst
- source/docs/user_manual/processing_algs/gdal/vectormiscellaneous.rst
* adds the parent GDAL utility link to almost all algorithms
* places the information on top of alg description instead of as a "see also"
> Add/raise focus on the original algorithm in GDAL docs

- source/docs/user_manual/introduction/general_tools.rst
List the units available in the measurement widget, including the new centimeter and millimeter based units (#1741).
I'm still unclear on a couple of points:
* For the area measurement, should "map units" not properly be called "square map units"?
* I think it would make sense to explain what "map units" refers to. I thought it would be whatever linear units the project CRS uses, but when I tried this out using QGIS 3.2, the measurements were also done in meters with a geographic coordinate system (where I would have expected the linear measurement to be done in degrees). Is this the expected behaviour?
* In the Project Properties and in the Map Tools Options, the centimeter and millimeter units are still missing. Should I open a ticket for this?
> List available measurement units

- source/docs/user_manual/working_with_vector/vector_properties.rst
Make sure that the illustrations for the topology checks in digitizing options are placed with the explaining text by using a table of images (avoid using `.. figure` for these).
> Reorganize topology checks description and images

- source/docs/gentle_gis_introduction/coordinate_reference_systems.rst
- source/docs/gentle_gis_introduction/vector_data.rst
- source/docs/pyqgis_developer_cookbook/loadlayer.rst
- source/docs/training_manual/forestry/map_georeferencing.rst
- source/docs/training_manual/spatial_databases/simple_feature_model.rst
- source/docs/training_manual/spatial_databases/spatial_functions.rst
- source/docs/user_manual/introduction/qgis_configuration.rst
- source/docs/user_manual/managing_data_source/supported_data.rst
- source/docs/user_manual/print_composer/composer_items/composer_label.rst
- source/docs/user_manual/print_composer/composer_items/composer_map.rst
- source/docs/user_manual/processing_algs/lidartools/lastools.rst
- source/docs/user_manual/processing_algs/qgis/graphics.rst
- source/docs/user_manual/processing_algs/qgis/vectorcreation.rst
- source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
- source/docs/user_manual/working_with_ogc/server/services.rst
- source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst
- source/docs/user_manual/working_with_vector/expression.rst
- source/docs/user_manual/working_with_vector/vector_properties.rst
Fixes #3296 (though i don't know it'll be backported - not an issue imho)
> Uppercase "coordinate" letters (x,y,z,m) in description and when done in the GUI

- source/docs/user_manual/working_with_ogc/server/services.rst
the text is at https://docs.qgis.org/testing/en/docs/user_manual/working_with_ogc/server/services.html#extra-parameters-supported-by-all-request-types I don't really know if it's at the wrong place or was leftover by some [other changes](https://github.com/qgis/QGIS-Documentation/blame/master/source/docs/user_manual/working_with_ogc/server/services.rst#L1285). @pblottiere any idea?
> Remove a leftover text

- source/docs/user_manual/working_with_ogc/server/services.rst
This PR adds a section about the feature to add external WMS layers in QGIS Server GetMap and GetPrint requests.
> Document EXTERNAL_WMS feature in QGIS server

- source/docs/user_manual/introduction/getting_started.rst
An attempt to updated the "description" of ``.qgs`` and ``.qgz`` to reflect current behaviour (``.qgz`` is now the default when saving a project in QGIS, so it may be confusing to use the term "default" for ``.qgs``).
> Update getting_started.rst (qgz / qgs)

- source/docs/training_manual/qgis_plugins/plugin_examples.rst
The prepare-data lesson instructs the user to create the training-data.gpkg file, populated with OSM data. For someone who followed that lesson, there's no way he has the sample_points layer in his DB.
Also apply some formatting.
See also https://github.com/qgis/QGIS-Training-Data/pull/19
> Move the dataplotly sample file out of training_data.gpkg

- source/docs/user_manual/introduction/qgis_gui.rst
allowing more space for [reference labels](https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_gui.html#settings) (a single line should look better than two)
> Remove empty columns in the Settings options table

- source/docs/user_manual/index.rst
placed after QGIS GUI --> QGIS Configuration --> Working with projections
As general tools is about the tools and manipulations, I think these chapters showing the GUI and how to understand the settings should have precedence.
I even wonder if it should not move after "Managing data source"...
> Move down the General Tools chapter

- source/conf.py
The issue was raised in #3504, now the master branch of documentation points to the master version of the API and not to 3.4.
Fix #3504
> Changes methods and classes links to point to master API

- source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst
It was commented because of an early merge.
> Allow visibility of the Extend/Trim tools doc

- source/docs/pyqgis_developer_cookbook/vector.rst
The idea is to have the following structure, basically moving the memory provider into the vector creation section (no idea whether it's desirable though)
> Organize sections

- source/docs/documentation_guidelines/cookbook_guidelines.rst
Not having a testoutput when the code snippet has a print() causes the test to fail. This PR tries to clarify the need to add the directive.
> Clarifies when the testoutput is mandatory

- source/docs/user_manual/introduction/qgis_configuration.rst
- source/docs/user_manual/introduction/qgis_gui.rst
to allow cross link between widget and options descriptions
Ticket: http://osgeo-org.1560.x6.nabble.com/locating-layer-td5400310.html (unable to provide a direct link to the feature while answering)
> Add direct link to locator bar description

- source/docs/user_manual/working_with_ogc/server/config.rst
QGIS_SERVER_OVERRIDE_SYSTEM_LOCALE and QGIS_SERVER_SHOW_GROUP_SEPARATOR
Goal:
Ticket: fixes #3633
> QGIS Server: additional ENV vars

- themes/qgis-theme/page.html
because 2.18 is no longer maintained or translated.
Ticket: fixes #3559
> Remove footer fix me links

- source/docs/pyqgis_developer_cookbook/raster.rst
line 167 : there is a missing colon before "meth:`triggerRepaint()" should be: :meth:`triggerRepaint()
Goal: correct the display of the used method in the documentation
> Missing colon before 'meth'

- source/docs/pyqgis_developer_cookbook/expressions.rst
- source/docs/pyqgis_developer_cookbook/vector.rst
and improve readability  (manual backport of #3658)
Goal:
Ticket: #
> Remove obsolete |outofdate| warning

- source/docs/training_manual/forestry/basic_lidar.rst
Line 46:  link for downloading newest version for LAStools seems to have been changed to: https://lastools.github.io/download/LAStools.zip
Goal: presenting correct download link
> Changed download link

- source/docs/pyqgis_developer_cookbook/authentication.rst
Line 53 : It seems there is missing a colon after ":file" in ":file`qgis-auth.db`", should be: ":file:`qgis-auth.db`"
Goal: correct display of used placeholders in documentation
> Missing colon after :file

- source/docs/user_manual/auth_system/auth_overview.rst
Line 231 to 236 : It seems that something went wrong with the formatting. Options are probably inadvertably not formatted right.
First option "Input master password" was correct formatted, but "Clear cached master password" and "Reset master password" were not separately mentioned on the page, but joined together with the first option "Input master password"
Goal: correct display of the mentioned options on the page in documentation
> Error in format page

- source/docs/training_manual/qgis_server/install.rst
line 269 ; ``sudo gedit /etc/hosts`` but I'm removing all "sudo"-s from this page. Should this one remain or should it go ?
I'm on Windows ( yeah, tell the wife :-) ) and my knowledge of Linux is limited
Goal: displaying correct information in documentation
> Remove "sudo" ?  ** NOT SURE ABOUT THIS! **

- source/docs/user_manual/working_with_projections/working_with_projections.rst
Line 54 and 55 :  the icon |option| is not visible in the menu Project next to "Properties" and should be removed
The option for the menu "Project Properties" in Project menu is throughout the application replaced by "Properties" (see also line 116)
Goal: correct display of items of the GUI in the documentation
> Rewording "Project Properties" to "Properties" and removing icon

- source/docs/user_manual/print_composer/create_reports.rst
line 133 :  "::guilabel:`Field Group Section`" contains one colon too many, should be: ":guilabel:`Field Group Section`"
Goal:
Ticket: #
> Superfluous colon

- source/docs/user_manual/print_composer/composer_items/composer_attribute_table.rst
line 110/111:  "the the"  should be "the"
Goal: display grammatical correct documentation
> Double wording "the"

- source/conf.py
to match what is used in [3.4 branch](https://github.com/qgis/QGIS-Documentation/blob/release_3.4/source/conf.py#L48)
The copyright is also mentioned at https://docs.qgis.org/testing/en/docs/user_manual/preamble/preamble.html, stating 
> Copyright (c) 2004 - 2017 QGIS Development Team
Should it be changed? To what (aka, how to make it dynamic if need be?)?
Ticket: #
> Update doc copyright

- source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
Line 168 : "a selected features" should be "a selected feature" since there is only one segment selected.
Goal: Grammatical correct documentation
> Singular instead of multiple

- source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
line 686 : this sentence contains a double reference to ":ref:`qgisbufferbym`" Removed last one.
Goal: correct documentation
> Döuble reference ":ref:`qgisbufferbym` in one sentence

- source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
Line 2236: "Default:*False*" should be *Default: *False*"
Goal: Correct displayed documentation
> Missing space

- source/docs/pyqgis_developer_cookbook/intro.rst
Goal: Solved wrong path for startup.py initialization file.
Ticket: fix #3722
> Modifies wrong path for startup.py initialization file.

- source/docs/user_manual/working_with_vector/style_library.rst
The SVG example was using a wrong parameter name, and would not work properly.
Goal:
Ticket: #
> Fixes SVG customization example

- source/docs/user_manual/working_with_projections/working_with_projections.rst
Update to reflect changes in projection handling since 3.0, and specifically to reflect how QGIS 3.8 and above work when using Proj 6.0.
> Update Working with Projections for 3.8

- source/docs/user_manual/working_with_projections/working_with_projections.rst
This backports the recent improvements/updates to the projection documentation (with removal of the 3.8 specific changes)
> Backport projection updates from master, remove 3.8 additions

- source/docs/pyqgis_developer_cookbook/crs.rst
- source/docs/user_manual/processing_algs/gdal/rastermiscellaneous.rst
- source/docs/user_manual/working_with_mesh/mesh_properties.rst
- source/docs/user_manual/working_with_projections/working_with_projections.rst
- source/docs/user_manual/working_with_raster/raster_properties.rst
- source/docs/user_manual/working_with_vector/vector_properties.rst
Changes references to "proj4" to just "proj". 4 was a version number, not a part of the name!
> Proj4 is no more, rename to 'Proj'

- source/docs/user_manual/introduction/qgis_gui.rst
line 404 : missing colon before "guilabel:"  
"no guilabel:`Database`" should probably be : "no :guilabel:`Database`"
Goal: Display well formed documentation
> Missing colon

- source/docs/training_manual/complete_analysis/analysis_exercise.rst
Line 561 : Superfluous ` disrupts format.
":`guilabel:`X`" should be ":guilabel:`X`"
Goal: Display correct format documentation
> Superfluous `

- source/docs/user_manual/processing_algs/gdal/rastermiscellaneous.rst
Goal:
Fixing creation options in Merge algorithm to refer the GDAL driver options in QGIS configuration
Ticket: #
- [ X] Backport to LTR documentation is required
> fixing edit creation options in raster miscellaneous to align with #3755

- source/docs/documentation_guidelines/cookbook_guidelines.rst
- source/docs/pyqgis_developer_cookbook/expressions.rst
to avoid them changing results in other chapters.
This should fix the failures that from time to time occurred in the build. 
I won't insist anymore on this but we should decide whether we want to use the testing framework, hence make it mandatory for all codes (meaning that instructions and how-to are available, clear and explicit for everyone, we cover all the requirements of QGIS) or continue with old `.. code-block`, with unfortunately the limits it has but it'll spare build failure tracking time for some.
My choice would go for 1 but it's not an area I'm comfortable with...
Ticket: #
> Isolate expressions tests in a group 

- source/docs/training_manual/qgis_server/wms.rst
A tiny typo in example part "Use Filter, Opacities and Filter parameters". There is no "default" style for countries_shapeburst in the demo project. 
Styles are blue or green, and the image is generated with blue style.
cc @pblottiere :wink:
Goal:
Ticket: #
> Fixes example for "Use Filter, Opacities and Filter parameters"

- source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
Add documentation for the point to layer algorithm.
Fixes: #3862
Goal:
Ticket: #
> Add the point to layer algorithm

- source/docs/index.rst
This makes them more discoverable and useful for beginners.
They don't necessarily know what they should read first, so that may help.
Advanced users would just skip and go to the manual they want.
We would end up with
We'd need to reorganize https://www.qgis.org/en/docs/index.html also but I first wanted to know if it sounds good.
Goal:
Ticket: #
> Place the GIS Intro and training manual at the first place in TOC

- source/docs/user_manual/introduction/qgis_configuration.rst
by setting them as subsection titles instead of simple paragraph whose rendering is the same as their text description, hence not easy to find. Incidentally, this also allows to directly link the option when referring to it in a discussion.
Limit the TOC depth at 2 to avoid the tens of options shown in the list.
However I don't quite know what would be the best meaningful display for the title, with or without \``, -- or option
Opinion?
> Improve the discovery of the command line options

- source/docs/user_manual/managing_data_source/create_layers.rst
Adding some information about the GDAL options available when exporting to GeoJSON.
See https://github.com/qgis/QGIS/pull/30272 
And https://github.com/qgis/QGIS/pull/9138
> Exportgeojson for pr30272

- source/docs/user_manual/managing_data_source/create_layers.rst
Follow-up of #3949.  Adding GeoJSON specific export options.
Goal:
Ticket: #
> Update create_layers.rst (adding GeoJSON specific options)

- source/docs/user_manual/working_with_vector/vector_properties.rst
Line 147 :  states: "from the :menuselection:`View` menu" for the option 'Filter…"
however I can't find such an option in the View menu, but there is in the Layer menu.
Am I doing something wrong or should it indeed be "Layer menu"
(for what its worth: I'm on Win10 and QGIS 3.8)
Goal: Display corect documentation
> Wrong menu mentioned ??

- source/docs/user_manual/working_with_vector/vector_properties.rst
Line 800 :  "in the the menu beside the slider." should be "in the menu beside the slider."
Double wording "the", removed one.
> Double wording "the

- source/docs/pyqgis_developer_cookbook/authentication.rst
I have provided a number of changes to allow the examples provide to work with QGIS version 3.4.7 and python 3. The use of str(quri.encodedUri(), "utf-8") appears to make line 284 functional but I remain unclear on which option is being recommended? The sole purpose of this documentation appears to be to show how to use the authentication manager but the comment below the example seems to imply uri(False) should be used instead. Trouble is that I get a "Download of capabilities failed: Protocol "" is unknown" if I use that version.
Goal:
Ticket: #
> Updates for QGIS version 3.4 and above

- source/docs/pyqgis_developer_cookbook/processing.rst
The "processing provider" code block should be rendered aligned with the provider bullet point it belongs to. and not like it's currently https://docs.qgis.org/3.4/en/docs/pyqgis_developer_cookbook/processing.html
Ticket: #
> Indent code block to ease reading at first glance

- source/docs/user_manual/introduction/general_tools.rst
- source/docs/user_manual/print_composer/composer_items/composer_map.rst
The map theme setting in layout map item was moved under another group and the link was not directly pointing to it.
Ticket: #
> Tweak map theme description and fix link

- source/docs/user_manual/managing_data_source/create_layers.rst
- source/docs/user_manual/managing_data_source/supported_data.rst
Backports idea of #4009
Ticket: #
> [3.4] Move the geoJSON parameters section to supported data 

- source/docs/user_manual/managing_data_source/create_layers.rst
- source/docs/user_manual/managing_data_source/supported_data.rst
Because the "supported data" chapter aims to receive details on format specifics (in creation or manipulation) that are not easy to expose elsewhere, it might be better to add the geojson particularities there (next to PG, SpatiaLite...)
@rduivenvoorde ?
Ticket: #
>  Move the geoJSON parameters section to supported data 

- source/docs/user_manual/processing/console.rst
- source/docs/user_manual/processing/scripts.rst
Added QgsProcessingParameterColor (fixes #3925).
Goal:
Ticket: #3925
> Add QgsProcessingParameterColor

- source/docs/user_manual/working_with_ogc/server/services.rst
Goal: this PR documents the WMS GetMap "TILED" parameter that was introduced with https://github.com/qgis/QGIS/pull/30071.
> Document the WMS GetMap TILED parameter

- source/docs/developers_guide/index.rst
- source/docs/developers_guide/processingtesting.rst
This is mainly an rst transcription of https://github.com/qgis/QGIS/blob/master/python/plugins/processing/tests/README.md
Should this go to the [unit testing chapter](https://docs.qgis.org/testing/en/docs/developers_guide/unittesting.html) or be a chapter of its own (like ogc conformance test)? No idea, but since the unit testing one needs a proper review, let's separate things for the moment.
I think/hope moving this doc to dev guides might give it more discoverability (if we come to fix https://github.com/qgis/QGIS-Website/issues/487) and would ease simplification and referencing from #3791
> [dev_guides] Add instructions for Processing algorithms test creation

- source/docs/pyqgis_developer_cookbook/raster.rst
Line 111 : There seems to be a colon missing before "class:".  Added.
> Missing colon before :class:

- source/docs/pyqgis_developer_cookbook/server.rst
Documentation build is broken because QgsMapServiceException is not accessible in master (I can find it in [3.8 pyqgis doc](https://qgis.org/pyqgis/3.8/server/QgsMapServiceException.html) but not in [master'](https://qgis.org/pyqgis/master/search.html?q=QgsMapServiceException&check_keywords=yes&area=default)
I don't know whether it's a bug in pyqgis doc, whether the class has been removed in master, hence description would be out of date(?) or... maybe @elpaso you know better.
This PR intention is to simply fix the build and avoid wrong warning on other PRs.
> Remove hyperlink on QgsMapServiceException class

- source/docs/user_manual/introduction/general_tools.rst
Since the layers combination does not match any map theme, it's not possible to use it to replace **the current** map theme (none is current).
Ticket: #
> It's not possible to replace **the current** map theme

- source/docs/user_manual/processing/scripts.rst
near https://docs.qgis.org/testing/en/docs/user_manual/processing/scripts.html#id2
Ticket: #
> Add spacing between the two alg decorators tables

- source/docs/user_manual/processing_algs/qgis/interpolation.rst
Goal:
Adding parameters Size X and Size Y for interpolations algs. Also, reordering extent, rows and columns to align with the order in dialogs. 
Ticket: Fix #3286
- [x ] Backport to LTR documentation is required
- [ x] The description of this PR is coherent with the manual and does not provide wrong information.
- [ x] This PR passes the checks.
> Fixing "Add cell size parameter to native interpolation algorithms"

- source/docs/documentation_guidelines/first_contribution.rst
Proposal for adding https when cloning both local and remote repository
Goal:
Prevent beginner documenters to get stuck when cloning local and remote qgis repositories.
Cloning using web URL is also recommended in GitHub help
Ticket: #
Fix #4135
- [ x] Backport to LTR documentation is required
- [x ] The description of this PR is coherent with the manual and does not provide wrong information.
- [ x] This PR passes the checks. <!---The results will be reported by travis-ci **after** opening the PR.
> Updating step by step first contribution 

- source/docs/user_manual/processing_algs/qgis/vectorselection.rst
there was an indentation issue at https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/qgis/vectorselection.html#id13
No text changes despite the diff.
Ticket: #
> Fix indentation and line length

- themes/qgis-theme/languageswitch.html
Now you get the right doc but not the right page
Eg `fr/docs/user_manual/introduction/general_tools.html` page currently returns `#fr/docs_user_manual_introduction_general_tools` (all underscored) while Transifex expects `#fr/docs_user-manual_introduction_general-tools` (underscore replaced with hyphen)
Goal:
Ticket: #
> Fix page link generation for Transifex

- source/docs/user_manual/processing_algs/qgis/vectorselection.rst
showing that each "extract by..." algorithm has its "select by..." alter ego (backports #4181)
Ticket: #
> Add links between "select by" and "extract by" algorithms (#4181)

- REQUIREMENTS.txt
- themes/qgis-theme/languageswitch.html
Another attempt to remove fix me button on 2.18 pages (no more fixes on this branch - fix #3559)
Ticket: #
> Hide the fix me button

- source/docs/user_manual/introduction/general_tools.rst
- source/docs/user_manual/introduction/qgis_gui.rst
- source/docs/user_manual/plugins/core_plugins/plugins_evis.rst
- source/docs/user_manual/preamble/contributors.rst
- source/docs/user_manual/print_composer/overview_composer.rst
- source/docs/user_manual/processing/scripts.rst
- source/docs/user_manual/working_with_ogc/server/services.rst
- source/docs/user_manual/working_with_vector/attribute_table.rst
- source/docs/user_manual/working_with_vector/expression.rst
If you have ever downloaded [our user manual](https://docs.qgis.org/3.4/pdf/), you have probably noticed how awful are some tables in the PDF (check the Expressions chapter). Particularly when they are long or have a column really wider than the others. While the rendering is always good in html, in PDF it's another story.
This PR walks through the user manual and fixes each table, using advanced properties to handle and customize tables in Sphinx/LaTeX. 
* Tables are mainly moved to a csv-table format, because it's the format I managed to work with when I looked at this issue. It also has the advantage to ease update, avoiding the whole table reformatting when the new function to add is too long
* Enable columns width control, using smart latex options, resulting in more useful table in …
> Let's put some love into our PDF documentation

- source/conf.py
- source/docs/developers_guide/codingstandards.rst
- source/docs/developers_guide/ogcconformancetesting.rst
- source/docs/developers_guide/processingtesting.rst
- source/docs/documentation_guidelines/substitutions.rst
- source/docs/pyqgis_developer_cookbook/authentication.rst
- source/docs/pyqgis_developer_cookbook/cheat_sheet.rst
- source/docs/pyqgis_developer_cookbook/geometry.rst
- source/docs/pyqgis_developer_cookbook/intro.rst
- source/docs/pyqgis_developer_cookbook/network_analysis.rst
- source/docs/pyqgis_developer_cookbook/processing.rst
- source/docs/pyqgis_developer_cookbook/server.rst
- source/docs/user_manual/plugins/python_console.rst
- source/docs/user_manual/processing/history.rst
- source/docs/user_manual/processing/scripts.rst
When browsing 3.4 document, it's better to point to  pages in code repository, c++ api or pyqgis that are of the same release than master. And when 3.10 is out, the same should apply, as well as when browsing testing --> master.
To avoid manual tracking of these links in the doc, this PR configures and applies an automatic redirection based on the doc version using the [extlinks sphinx extension](https://www.sphinx-doc.org/en/1.6/ext/extlinks.html).
Also applies the same logic to the intersphinx link replacement.
@Gustry it should cover the particular case of https://github.com/qgis/QGIS-Documentation/pull/4237#issuecomment-530794557
> Keep our external links synced with the doc release

- Makefile
- docker-world.sh
Currently when building PDF, you get
```
build succeeded, 47 warnings.
```
These warnings are related to references added in the other parts of the docs that point to the [processing algs](https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/index.html). It does not make the PDF fail but it results in situation like 
where no link is available to click, making these "see also" useless. With this PR, you'd now get
Building with the algs chapter does not result in a big PDF (26Mo -->34Mo) while the training manual is 138Mo. So I might miss the reason why it was excluded from the build. Maybe because many algs were from other projects or ours were outdated/not documented? Anyone knows?
> Allow generation of the Processing Algs chapter in pdf

- source/docs/user_manual/working_with_vector/vector_properties.rst
to avoid a long bulleted list of tab names (https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/index.html)
The idea is to move away from 
for this, more compact
Goal:
Ticket: #
> Introduce the vector layer properties tabs using a table structure

- readme.rst
none of these links is working
@rduivenvoorde are these docs removed (i can see they are not listed at https://docs.qgis.org and I'm fine with that) but thought the link would still work (eg because they are listed in the readme file)
Goal:
Ticket: #
> Remove unavailable document links

- source/docs/user_manual/processing_algs/gdal/vectormiscellaneous.rst
Goal: refs https://github.com/qgis/QGIS/pull/32083
Ticket(s): #
>  Make the A_SRS parameter optional in Export to PG alg

- source/docs/user_manual/introduction/general_tools.rst
- source/docs/user_manual/print_composer/composer_items/composer_map.rst
Goal: Add text for reselect tool to user manual
Ticket(s): fix #4216 
Completed as a part of the FOSS4GUK 2019 code sprint
> Add description of reselect tool

- source/docs/pyqgis_developer_cookbook/authentication.rst
- source/docs/pyqgis_developer_cookbook/tasks.rst
Goal: strings are now unicode by default with Python3
> strings are now unicode by default with Python3

- bootstrap.py
- pavement.py
- readme.rst
With the upgrade to Python 3 and the dependencies as well as the move of the static folder (status), the bootstrap.py file got broken. Which is unfortunate since it was the easiest way for me to build docs when I was using Windows.
With this PR I can successfully build the docs again on ubuntu. The instructions are updated based on my partial knowledge of the ecosystem and my experience.
I didn't test on Windows nor test on a localized branch.
If someone wants to give it a look...
Ticket(s): #
> Update machinery and instructions to build docs with Paver

- source/docs/user_manual/print_composer/composer_items/composer_map.rst
Since I was working in this file, I have also updated the text explaining how to change the grid to a different CRS to the project CRS. 
Goal:
Ticket(s): #
> Clarify text explaining changing to a different CRS for a grid

- source/docs/pyqgis_developer_cookbook/vector.rst
Goal:
Add an example to clarify how to export to ESRI GDB files, which is a common GIS workflow.
> Add text for creating GDBs

- .travis.yml
- themes/qgis-theme/layout.html
- themes/qgis-theme/page.html
- themes/qgis-theme/static/qgis-style.css
- themes/qgis-theme/static/qgis-style.less
References #3452
There's a lot of hardcoding in there.
It will need some sphinx etc. pro to make it translatable et al.
Goal:
Ticket(s): #
> Show "end of life" notice in header bar

- source/conf.py
- themes/qgis-theme/layout.html
- themes/qgis-theme/page.html
- themes/qgis-theme/static/qgis-style.css
- themes/qgis-theme/static/qgis-style.less
Future proof version of https://github.com/qgis/QGIS-Documentation/pull/4273
Adds a new "outdated" option source/conf.py -> html_context
Set that whenever docs are put to the archive to get a nice header bar sending people to the newer version.
> Configurable end of life notice

- source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst
Goal:
There were some commented sections about the extend trim tools that would be only available on 3.4>
Makes no sense to keep them in 3.4 docs, it's just polluting the code.
Ticket(s): #
> Removes commented sections about extend trim feature in 3.4

- source/docs/user_manual/working_with_mesh/mesh_properties.rst
Line 295 : superfluous space causes ref to be broken
":ref:` Mesh" must be ":ref:`Mesh" for ref to work.  Removed space.
Goal: Make correct documentation
> Removed superfluous space

- source/conf.py
- themes/qgis-theme/layout.html
- themes/qgis-theme/page.html
- themes/qgis-theme/static/qgis-style.css
- themes/qgis-theme/static/qgis-style.less
To replace update disclaimer mention and mimicking the outdated doc banner as suggested in PR #4274 - fixes #4295 
Using a soft blue banner ~(no build around yet for a screenshot or check #f3fbfb color)~
> Enable a new banner on top of the testing documentation

- source/docs/pyqgis_developer_cookbook/vector.rst
Move shapefile comment next to related code sample
Fix failure to highlight python code sample due to character encoding issues
> /media/dev/github/QGIS-Documentation/source/docs/pyqgis_developer_cookbook/vector.rst:596: WARNING: Could not lex literal_block as "python". Highlighting skipped.
/media/dev/github/QGIS-Documentation/source/docs/pyqgis_developer_cookbook/vector.rst:616: WARNING: Could not lex literal_block as "python". Highlighting skipped.
Goal:
Ticket(s): #
> Improve vector creation file in Cookbook

- source/docs/pyqgis_developer_cookbook/plugins/plugins.rst
Goal:
Adds the hasProcessingProvider option to the metadata list.
This option is explained later in here:
https://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/processing.html#
Ticket(s): #
> Adds hasProcessingProvider option to metadata list

- source/docs/training_manual/processing/r_intro.rst
Update to reflect that the online collection of R scripts is not available with QGIS 3 and the Processing R Provider plugin.
Goal:
Ticket(s): #
> Update rintro (online collection of R scripts not available)

- source/docs/user_manual/managing_data_source/opening_data.rst
Following on from discussion https://github.com/qgis/QGIS/issues/32648 it seems wise to warn users that primary keys are needed to avoid unexpected results when selecting features. I've proposed a sentence be added to the documentation to help others avoid issues.
Goal:
Ticket(s): #
> Add primary key warning for Oracle spatial layers

- source/docs/user_manual/processing/scripts.rst
A section heading (and an anchor) is added for the input and output processing parameters part. The column sequence of the table has also been changed.
Goal:
Ticket(s): #
> Add a section heading for the input and output processing parameters

- source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
"Ignore ring self intersections" was added in 3.6.
Fixes: #3492
Goal:
Ticket(s): #
> Update the check validity algorithm description with a new parameter

- source/docs/user_manual/processing_algs/qgis/cartography.rst
Moving "Combine style database" in front of Create categorized renderer from styles (alphabetical order, as in the UI).
Goal:
Ticket(s): #
> Update cartography.rst (reorder)

- source/docs/user_manual/processing_algs/qgis/vectorgeneral.rst
for split vector (fixes #4260)
Goal:
Ticket(s): #
> gpkg is no more the single and hard-coded output format

- source/docs/user_manual/processing_algs/qgis/rasteranalysis.rst
Fixes: #3523. Change to table format for parameters (#2770).
Goal:
Ticket(s): #
> Add the new Raster Boolean logical OR/AND algorithms

- source/docs/user_manual/introduction/project_files.rst
- source/docs/user_manual/print_composer/create_output.rst
This is at least a start. Have included a link to the North Road page.
Will try to supplement a bit, but on my Ubuntu boxes I do not have GDAL 3
I don't want to compile, so no GeoPDF support here yet. :-(
Goal:
Ticket(s):  #1892, #3241, #4083, #4084, #4092, #4093, #4094, #4096, #4099, #4104, #4105, #4112
Fixes: #1892, #3241, #4083, #4084, #4092, #4093, #4096, #4099, #4104, #4105, #4112
> GeoPDF export

- source/docs/pyqgis_developer_cookbook/vector.rst
Goal: add geometry less type when we create memory layer
Ticket(s): #
> add geometry less type when we create memory layer

- source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
Added a comma and removed "different" - both for point on surface and centroid.
Goal:
Ticket(s): #
> Update vectorgeometry.rst (trivial edit - added comma; removed "different"; "Centroid" ->"centroid")

- source/docs/pyqgis_developer_cookbook/vector.rst
> Backport to 3.4 of #4443 (add geometry less type when we create memory layer)

- source/docs/user_manual/working_with_ogc/server/services.rst
Missing parameter.
Available since QGIS 3.8.
> Add CODEC to DXF parameters for QGIS server GetDxf

- source/docs/user_manual/processing_algs/gdal/vectorconversion.rst
> Manual backport GDAL vector extracton tables for parameters to 3.4

- source/docs/user_manual/processing_algs/gdal/vectorconversion.rst
Goal: Move Optional to its correct position in a parameter table
Ticket(s): #
> Misplaced "Optional" i GDAL vectorconversion parameter table

- source/docs/user_manual/processing_algs/qgis/database.rst
- source/docs/user_manual/processing_algs/qgis/qgis_algs_include.rst
next: instead of adding link to postgis queries in the "spatialite execute sql" alg description, it would be better someone used to that provider provides corresponding examples for spatialite
> Add seealso to database algs and make the sample codes reusable

- source/docs/user_manual/introduction/general_tools.rst
I feel it's better served to group units that we simply list than letting Inches alone at the end of the list the way it's rendered at https://docs.qgis.org/testing/en/docs/user_manual/introduction/general_tools.html#unit-selector
Btw, let's close #1636
> Move up Inches in the list of supported units

- source/docs/user_manual/processing_algs/qgis/vectorgeneral.rst
Start with including it in Vector general.
New PR to remove from Vector selection.
Goal:
Ticket(s): #
> Move "Delete duplicates by attributes" from QGIS vector selection to QGIS vector general - part 1

- source/docs/user_manual/style_library/symbol_selector.rst
- source/docs/user_manual/working_with_vector/vector_properties.rst
The GUI has changed a bit
Move some notes/tips closer to the features they relate to and fix some minor GUI changes
Add force right-hand rule (fix #3207)
Goal:
Ticket(s): #
> Update symbol selector dialog

- source/docs/user_manual/introduction/general_tools.rst
I find the TOC at https://docs.qgis.org/testing/en/docs/user_manual/introduction/general_tools.html is too long and detailed
> Reduce depth of the "General tools" local TOC as it becomes too long

- source/docs/user_manual/introduction/qgis_configuration.rst
Fix #3219, fix #3216, fix #2815, fix #2814
> SVG and raster images can be embedded in project

- source/docs/user_manual/style_library/label_settings.rst
No new feature and no big text changes as far as I could remember. this is mainly to split [the section](https://docs.qgis.org/testing/en/docs/user_manual/style_library/label_settings.html#rendering-tab) in smaller and identifiable parts and make it a bit airy (following sections at the beginning of the page)
> Aerate the label's rendering settings description

- source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst
A description about the reverse line tool.
Goal:
Ticket(s): #2957
> Inserted reverse line tool

- source/docs/pyqgis_developer_cookbook/authentication.rst
Line 367 <src/providers/postgres/qgspgnewconnection.cpp#L42>`  should probably have a dot at the end,
Next sentence starts with a capital letter.
So; "<src/providers/postgres/qgspgnewconnection.cpp#L42>`"  should probably be:
"<src/providers/postgres/qgspgnewconnection.cpp#L42>`."
<!---
Include a few sentences describing the overall goals for this Pull Request.
> Missing punctuation (dot) at end of sentence

- source/docs/training_manual/map_composer/dynamic_layout.rst
Line 67 : "choose the ``@rg_layout_margin`` variable",  however there is no such variable.
Should probably be the variable @sw_layout_margin which was previously defined
> Wrong name variable

- source/docs/training_manual/map_composer/dynamic_layout.rst
Line 19 and 20 : "a map with the regions of  Alaska."
However, we are loading shapefiles from the sample dataset of the region near Swellendam South-Africa.
If I read through it is probably meant to be Swellendam and not Alaska that we are making the dynamic print layout for.
I suppose/suggest therefore that the sentence should be changed to:  "a map of the region near Swellendam, South Africa."
Greetings
DiGro
<!---
Include a few sentences describing the overall goals for this Pull Request.
> Wrong sample dataset or misused "Alaska" ?

- source/docs/user_manual/processing_algs/qgis/vectoroverlay.rst
Line 586:  " that so not "  should probably be " that do not " given the rest of the sentence
<!---
Include a few sentences describing the overall goals for this Pull Request.
> Probable typo  so -> do

- source/docs/user_manual/processing_algs/qgis/cartography.rst
Line 457 :  " *Balance color assignment**" should be " **Balance color assignment** "
The missing asterisk messes up the formatting of the sentence.
Placing the missing asterisk fixes it.
<!---
Include a few sentences describing the overall goals for this Pull Request.
> Missing asterisk, messes up formatting

- source/docs/user_manual/introduction/project_files.rst
- source/docs/user_manual/working_with_vector/vector_properties.rst
According to https://github.com/qgis/QGIS-Documentation/pull/4579#discussion_r355279346 this option has no influence on exports since export dialogs have their own setting. What it does is only to set the default item of the export dialogs widgets.
Also not only SVG is concerned now.
Goal:
Ticket(s): #
> Tweak the text rendering option in placement engine

- source/docs/training_manual/introduction/overview.rst
Goal: Section 2.2.1.3 says the Toolbars menu is under the Settings menu when it has moved to the View menu.
> Update location of Toolbars menu in Training Manual

- source/docs/training_manual/introduction/preparation.rst
Goal: In the training manual, at the end of section 2.1.1, you are instructed to save the map as `basic_map.qgs` but the dialogue defaults to `.qgz` (at least on Windows). This raises unnecessary questions for a beginner tutorial.
> Update file extension to reflect defaults in v3.10.1

- source/docs/user_manual/processing_algs/qgis/networkanalysis.rst
- source/docs/user_manual/processing_algs/qgis/qgis_algs_include.rst
Goal: Handle the difference in the advanced parameters for the service area
algorithms and the other QGIS network algorithms. The service area algs have
the additional parameter "Include upper/lower bounds points".
Ticket(s): Discussed in #4604
> Add a separate include for the service area QGIS network algorithms

- source/docs/user_manual/processing_algs/qgis/vectortable.rst
Goal: Document the Explode HStore Field algorithm
Ticket(s): Fixes: #3133
> Document the QGIS Explode HStore Field algorithm (#3133)

- source/docs/training_manual/map_composer/dynamic_layout.rst
Fixes `@sw_layout_header` being used when `@sw_layout_height_header` was the variable declared earlier in the exercise.
> Training Manual 5.2: Correct variable name

- source/docs/training_manual/vector_analysis/spatial_statistics.rst
Goal: Radio button substitution was contained in a code block, preventing the substitution from occurring.
Also changed the code block to a `guilabel` block.
It doesn't look right because there's a 15px right margin applied to `<img>` tags within notes (`.admonition` class), but that's a separate issue.
Ticket(s): None
> Training Manual 7.4.6: Fix radio button substitution

- source/conf.py
- source/docs/pyqgis_developer_cookbook/cheat_sheet.rst
Makes it possible to have test objects in the test output:
```
.. testoutput::
:hide:
<qgis._core.QgsLayerTree object at 0x7f068bbc0c18>
[<qgis._core.QgsLayerTreeGroup object at 0x7f068bbc01f8>]
```
> Makes test doc insensitive to object addresses

- source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
Goal: Use tables for algorithm parameters.
The QGIS Vector geometry algorithms from "Rectangles, Ovals, Diamonds (Fixed)" until (and including) "Simplify".
Ticket(s): #4429.   Following up #4629.
> QGIS Vector geometry - tables for alg parameters (part three)

- source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
Goal: Use tables for algorithm parameters.
The QGIS Vector geometry algorithms from "Single sided buffer" to the end of the list
Ticket(s): #4429. Following up #4629 and #4649.
> QGIS Vector geometry - tables for alg parameters (part four)

- source/docs/pyqgis_developer_cookbook/plugins/ide_debugging.rst
This was supposed to add the missing bits from #4669 review and turns into this.
Giving a closer look, it seems that this chapter was at first targeting a Windows audience so we need some structure to help identify what is windows only and what could not be. So changes are:
* Tweak the global configuration note and add a dedicated section for Pyscripter (I think there's something to group with the Eclipse section as configuration but, not an area I'll be efficient)
* Display instructions as numbered list, better to see steps (majority of the changes)
* Move the PyCharm instructions below, to make the reading smoother
Text changes are mainly to connect sections. And I did not check the rightness of what is written so deliberately keep mention of QGIS2, Qt4, Python2... I let that to those …
> More cosmetics and logic in the debugging instructions

- source/docs/user_manual/processing_algs/qgis/rastertools.rst
Goal: Initial documentation (only listing the parameters) of the Generate XYZ tiles algorithms in QGIS Raster tools (introduced in 3.8).
Ticket(s):    https://github.com/qgis/QGIS/pull/9857, fix #3948
> Add the Generate XYZ tiles algorithms

- source/docs/user_manual/processing_algs/gdal/rastermiscellaneous.rst
Goal: Add the GDAL Pansharpening algorithm
Ticket(s): Fixes #3525.
> Add the GDAL Pansharpening algorithm

- source/docs/user_manual/style_library/style_manager.rst
Goal: Users shall be able to copy and paste style items in the tabs of the style manager and also elsewhere in QGIS (symbol and color buttons).
Ticket(s): fix #4032
> Cp paste style in qgis

- source/docs/user_manual/processing_algs/gdal/vectorgeoprocessing.rst
Goal: Add documentation for the remaining algorithms in the GDAL Vector geoprocessing group:
"Buffer vectors", "Offset curve", "One side buffer" and "Points along lines".
Ticket(s): #
> Add the remaining algorithms in the GDAL Vector geoprocessing group

- source/docs/user_manual/processing_algs/gdal/vectorconversion.rst
Goal: Add the remaining algorithms in the GDAL Vector conversion group:
* Rasterize (overwrite with attribute)
* Rasterize (overwrite with fixed value)
Ticket(s): https://github.com/qgis/QGIS/pull/32597
> Add the remaining algorithms in the GDAL Vector conversion group

- source/docs/user_manual/processing_algs/qgis/qgis_algs_include.rst
- source/docs/user_manual/processing_algs/qgis/vectorselection.rst
that were added to the extract/select by location algorithms in #4134 
I think it's too much to be included as part of the `Where the features (geometric predicate)` tiny cell so they are moved to the alg description section.
>  Reintroduce the geometric predicates examples 

- themes/qgis-theme/static/qgis-site.js
Goal:
Substitute a deprecated $(window).load(function(){...}); with $(window).on('load', function(){ ...});
See qgis/QGIS-Website@06d668abc57c56a92582308642d7e3984b2b7b44 (PR qgis/QGIS-Website#579)
Ticket(s): qgis/QGIS-Website#718
> Avoid an "Uncaught TypeError: a.indexOf is not a function"

- source/docs/user_manual/working_with_raster/raster_properties.rst
Goal: Document the contextual menus for changing opacity, colour, ... of selected entries
in the "colour table" for the "singleband pseudocolor" and "paletted/unique values" raster
rendering types.
Ticket(s):
Fixes: #1571
Fixes: #1572
Fixes: #1578
> Document contextual menu for changing symbol properties for paletted and singleband pseudocolor

- source/docs/user_manual/processing/modeler.rst
Line 374 : "can be be executed"  should be "can be executed"
Removed first occurrence of "be"
Goal: Display correct information
> Double wording "be be"

- source/docs/user_manual/processing_algs/gdal/rasteranalysis.rst
Line 555 :  "* - **Smothing**"  should probably be " * - **Smoothing** "
Missing letter "o" added
Goal:  Display correct information
> Typo * - **Smothing**

- source/docs/user_manual/processing_algs/qgis/vectorcreation.rst
Line 1001 : "Input polygon polygon vector layer" should probably be "Input polygon vector layer"
Removed first occurrence of "polygon"
> Double wording "polygon"

- source/docs/user_manual/processing_algs/lidartools/lastools.rst
line 2343  : "- The fouth file to merge"should be "- The fourth file to merge"
> Missing letter in "fouth" = "fourth"

- source/docs/user_manual/processing_algs/lidartools/lastools.rst
line 2028  : "* 3 --- stdeev" should probably be "* 3 --- stddev"
stdeev is not the right abbreviation for the function standard deviation, it is stddev
> Typo in name functie  stddev

- source/docs/user_manual/processing_algs/lidartools/lastools.rst
line 2744  : "       Default: 'xyz " should probably be "       Default: 'xyz' " as in line 1787
Last quote missing
> Missing quote

- source/docs/user_manual/processing_algs/qgis/vectorgeometry.rst
and because that note is already stated in description few lines above (https://docs.qgis.org/3.4/en/docs/user_manual/processing_algs/qgis/vectorgeometry.html#convert-geometry-type)
> Remove the note to make the parameters table more compact

- source/docs/user_manual/working_with_ogc/server/getting_started.rst
Goal:
A few days ago, I quickly followed the documentation with NGINX and I installed `fcgiwrap`. I didn't see the previous note made by @elemoine. The performance is catastrophic :) according to me. It's indeed very slow. So I think we should move `spawn-fcgi` before `fcgiwrap` in the documentation.
fcgiwrap is easy to setup, but very slow.
I also tried to add a systemd file for starting qgis server.
@elemoine I'm clearly not an expert in this area, a review is welcome.
Ticket(s): #
> spawn-fcgi should be the prefered way compare to fcgiwrap

- source/docs/pyqgis_developer_cookbook/plugins/ide_debugging.rst
It is necessary to also import pyqtRemoveInputHook
Goal:
Ticket(s): #
> Add missing import for debugging with command line

- source/docs/user_manual/managing_data_source/opening_data.rst
in order to describe the panel from top to bottom (toolbar then panel items)
Also add subsections to aerate a bit the section, help readers to identify contents and avoid a big chunk of text
>  Move up the Browser panel toolbar description

- .github/workflows/backport.yml
Reverts qgis/QGIS-Documentation#4974 because it doesn't fix the issue but it makes PR fail
> Revert "Use master branch of backport bot"

- source/docs/user_manual/managing_data_source/opening_data.rst
Like on other OSes, connected drives are accessible using the file system browser (nothing special is needed)
> Remove macOS outdated warning

- source/docs/user_manual/working_with_vector/expression.rst
in the right panel (refs changes in #4985)
Goal:
Ticket(s): #
> Fix indentation to move together help and field's values

- source/docs/user_manual/introduction/qgis_configuration.rst
The screenshot about options --> rendering and the description about the default resampling methods were added.
Goal: Users shall be able to set the default resampling method for newly added rasters.
Ticket(s): fix #3878
> Default resampling settings

- conf.py
- themes/rtd_qgis/layout.html
The redirection keeps:
- the language (if not available in latest, we already have a redirection to English in use)
- and the page (if the page does not exist in latest, it will return a 404; we should probably consider setting a redirection ?)
follow-up #5035
> Fix redirection link to the latest docs

- docs/user_manual/processing_algs/gdal/rasterprojections.rst
Line 17 : Double "the"  in sentence. Removed one instance
> Double wording "the the"

- docs/user_manual/working_with_vector/attribute_table.rst
Line 144 :  Was " Attribute table in form view (top) vs table view (bottom)", but the two pictures have             
been flipped.
So, should be " Attribute table in table view (top) vs form view (bottom) "
> Flipped pictures (what was upper is now lower and vice versa)

- conf.py
- themes/rtd_qgis/layout.html
This change adds a 'Last updated + timestamp' sentence ONLY on the frontpage, like we did in the old sites.
This way if some language,rsync or build breaks, it will at least be visible on the frontpage.
I choose to only show it on the frontpage, to minimalize the rsync jobs (else EVERY page will be updated)
> Add generation timestamp ONLY on frontpage

- conf.py
at both the top and bottom of the pages
> Display the previous/next buttons to browse the docs

- themes/rtd_qgis/versions.html
ie, hide "Contribute to docs" section for outdated versions and only display the transifex url for the actually translated version (latest) - like in the previous structure
> Show only the relevant options in the bottom bar

- docs/user_manual/introduction/qgis_gui.rst
reference to image decoration is now OK.
Several substitions have been removed from text but not from local substitions.
Next time you run find_set_subs.py, qgis_gui.rst is complete and will not change!
Goal:
Ticket(s): fix#5140
> Updated reference and local substitutions

- docs/user_manual/introduction/general_tools.rst
as done in QGIS GUI chapter, with small tweak to remove the space in-between
> Indicate submenus in the General Tools chapter with the arrow

- docs/user_manual/managing_data_source/opening_data.rst
The overhead of SSL is that the initial handshake needs additional messages to be exchanged, resulting in more messages being sent around. After that it should be mostly negligible.
Since we use a connection pool for postgres connections the initial added overhead is just paid once on opening the datasource. When working on the datasource after, the pooled connections are used which have already performed the SSL handshake and therefore carry no additional performance penalty.
Since QGIS already sends several queries (e.g. checking postgis version etc.) to the server when loading a layer, these additional SSL handshake messages are compensated in no time.
We should stop encouraging people to disable SSL by promissing "massive speed-ups", because 1. using SSL for transferring data over …
> Do not discourage people from using SSL to access postgres

- docs/user_manual/processing/3rdParty.rst
Updated arrows in menu items which were placed direct after the preceding word.
Removed one superfluous space
> Updated arrows in menu items to --> and removed superfluous space

- docs/user_manual/working_with_raster/raster_properties.rst
Line 77   : moved word "the" to before the icon
Line 159 :  "doint" should be "doing"
Line 651 :  "Properties" should probably be "LegendUrl"  (as in the image)
Goal:
Ticket(s): #
> Small changes

- docs/user_manual/processing_algs/qgis/cartography.rst
Line 52    :  " style items"  should be " style items." since "One of: " is on the same line in display
Line 265  :  " style items"  should be " style items." since "One of: " is on the same line in display
Goal: Display correct information
> Added two periods after end of sentence

- themes/rtd_qgis/layout.html
It seemed that after setting the html_last_updated_fmt param in
conf.py automagically there is a 'last updated' string in the footer
of every page.
Though my aim was also to minimize the number of pages changed
(by only putting it on the frontpage index), I'm fine with this.
Goal:
Ticket(s): #
> Remove the 'Last updated' sentence in the left column

- docs/user_manual/processing_algs/qgis/vectorgeometry.rst
Line 3636  : "layer is the same" should be plural. Calls back on "attributes" not on "layer";  therefore "layer are the same"
Line 6633  : "(buffer) layer One of:" added point (.) after "layer". End of sentence. "(buffer) layer. One of:"
> Two typo's corrected

- docs/user_manual/processing_algs/qgis/vectorgeneral.rst
Line 1081 : Label states "unjoinable" but parameter is called "JOINED_COUNT", so should probably be "joined". The same happened in
Line 1095 : Label states "joined" but parameter is called "UNJOINABLE_COUNT", so should probably be "unjoinable"
Line 1313 : "One or mor of:"  should be "One or more of:"
> Not correct label ? Seems wrong !

- Makefile
I'm not sure this option is necessary. Building without works fine; the errors in building qgisdoc2020 was imho more related to the missing files (due to how we "rebased" the branch) than to the makefile. @rduivenvoorde
> Remove the unnecessary confdir option from Makefile

- conf.py
- docs_conf.yml
- themes/rtd_qgis/theme.conf
- themes/rtd_qgis/versions.html
Currently when switching on items in the bottom bar, regardless where you are in the docs, it opens:
- the main index page if you change language
- the main index page in English if you change version.
Other links are also English-centered.
This PR:
- ensures that it instead keeps the page you are reading and only changes the target language or version (a possible 404 if page does not exist in the other version - need to catch?)
- fixes the "edit on github" buttons (the ones in the bottom bar and at the top of the window) url and make them open the source file in edit mode (like we previously did)
- updates the transifex url--> This still needs a work: replace the pagename with a regex to match transifex file naming (Someone to take this?)
- simplify and aerate the configuration file(s) - …
> Fix links for pages in the bottom bar

- docs/user_manual/working_with_vector/expression.rst
line 416    : "datetime,or" should have a space after the comma. Corrected to "datetime, or"
line 1032 : "sqlite" should be the correct name of the brand, so "SQLite"
line 1172:  ""fullextent_miny", "Minimum x value"  should really be the  "Minimum y value" since variable is "fullextent_miny",
line 1259""renderthe" misses a space before "the",  so corrected to "render the"
> Typo's corrected

- docs/user_manual/working_with_vector/vector_properties.rst
Described which right-click options are available when point, line or polygon is selected in one of three style renderers.
This was a suggested change by @havatv in pull request 5261, which I decided to include.
This is included in the description for three renderers.
Goal:
Ticket(s): #4056
> Describe options depend on geometry

- docs/user_manual/introduction/general_tools.rst
Measurement ellipsoid is set in the "General" tab within "Project --> Properties", not in the "CRS" tab.
> Measurement ellipsoid is set in the "General" tab

- conf.py
and show instead the "view page source" because closed docs are not expected to be edited
> Do not display "Edit on Github" top message for outdated releases

- docs/gentle_gis_introduction/introducing_gis.rst
Goal:
---
Align the second line of the **Digital Data** list item in the
list at the top of the "Introducing GIS" page so that it correctly
shows up as a list of three items, rather than a list with a
partial block quote.
[Before](https://docs.qgis.org/3.10/en/docs/gentle_gis_introduction/introducing_gis.html#overview):
---
After:
---
> Fix list formatting on Introducing GIS page

- docs/developers_guide/unittesting.rst
- docs/gentle_gis_introduction/topology.rst
- docs/gentle_gis_introduction/vector_spatial_analysis_buffers.rst
Fix Sentence Fragment in Topology
The previous section began with a sentence fragment, not a complete sentence. Add a comma to turn this into a compound sentence.
----
Update image caption to correctly say polygon
The image that shows a buffer zone around polygons was incorrectly labeled "A buffer zone around vector polylines." Update it to say polygons.
----
Switch not to no for proper grammar
The previous sentence didn't flow or sound right as is: "not .h file is used"
----
> Fix syntax and grammar in Gentle Introduction to GIS

- docs/pyqgis_developer_cookbook/loadlayer.rst
The provider_options transform_context is passed as the last parameter to uri.setDataSource(), I have checked both in the python console and in the source code and what I find is that the last parameter is for the primary_key of the database table. I only find one overload of this method, so unless there is another on the way, I think this is a mistake in the documentation.
Goal:
Ticket(s): #
> Removed provider_options transform_context

- .github/workflows/html.yml
Could help reviewers and contributors to preview the docs before merge, and exempt them from building locally.
Refs https://github.com/qgis/QGIS-Documentation/pull/5383#issuecomment-622982192
> Allow doc build preview for pull requests also

- docs/user_manual/processing/3rdParty.rst
Escape backslashes in the Microsoft windows path
Goal:
Ticket(s): #
> Fix backslash escaping in 3rdParty.rst

- qgis-projects/user_manual/working_with_vector_02.qgs
Goal: Revert the effect of #4896 
But it turns out that 3.4 "compatibility" of this project file was already lost (Jun 23, 2019):
https://github.com/qgis/QGIS-Documentation/commit/d162200b0d6e232cb862a6d6464c457c297bc7cf#diff-bcdf4885ad1dc8915d717bdb91c85ad3
Should we revert to the version preceding that commit?
Ticket(s): #4891
> Reinstate the version 3.4 project file

- themes/rtd_qgis/versions.html
Goal:
This should fix the "Translate page" link URL in order to point to the right transifex page.
Fixes #5410
Backport to LTR documentation already submitted PR #5462
> Fix "Translate page" link URL

- themes/rtd_qgis/versions.html
When the user hits api, transifex or github urls in the bottom bar, we should still let the user have an access to the docs' current page and open the requested page in a new tab
> Open third-party urls of the bottom bar in a new tab

- docs/user_manual/print_composer/create_reports.rst
line 172  : "Add Item->" - missing space and arrow to short, should be  "Add Item -->"  
line 277 : double comma,  removed one
line 328 : "the atlas feature" should probably be "the report feature" since the subject for documentation is the report
line 358 : "Report->" - missing space and arrow to short, should be "Report -->"
> Corrected typo's

- docs/pyqgis_developer_cookbook/plugins/ide_debugging.rst
Aptana Studio 3 Plugin <www.aptana.com>
becomes
Aptana Studio 3 Plugin <https://www.aptana.com>
> Typo corrected in the link to Aptana website

- docs/pyqgis_developer_cookbook/loadlayer.rst
Manual URI has to be used b/c set methods are written for geometry and not for raster. Therefore a description of the parameters is given.
Goal:
Ticket(s): #
> Load PostGIS raster using manual URI string.

- conf.py
- themes/rtd_qgis/static/css/qgis_topbar.css
Goal:
Adds a custom CSS when a top bar is needed to be shown (for testing or outdated versions).
Ticket(s): #5060
> Fix top bar for testing and outdated versions

- docs/index.rst
- docs/training_manual/index.rst
refs #5543 
I'm not convinced that indices list is worth a place in the bottom left menu
> Move notions' index from training manual to main repo first page

- docs/user_manual/working_with_raster/raster_properties.rst
The paragraph from line 530 to 536 is already mentioned at line 518 to 524.
Deleted the last paragraph (line 530 to 536)
> Double paragraph

- docs/user_manual/print_composer/composer_items/composer_items_options.rst
Line 252 :  says "New item properties dialog" but is in fact the dialog Position and Size. Changed to "Position and Size"
> Rewording caption image Position and Size

- docs/user_manual/auth_system/auth_workflows.rst
I've run the test through debugger but I couldn't make it fail, it's threaded code so I guess that the random failure is just a false positive, I couldn't find a better solution than disabling the test.
Fixes #5398
> Workaround segfault in auth manager test code

- themes/rtd_qgis/static/css/qgis_docs.css
Goal: we discussed this small topic a long ago and actually I don't remember the conclusion (ping @DelazJ @havatv @rduivenvoorde), but given that the *fix* is simple it's more straightforward to make a PR and eventually closing it without merging.
I think that all the white space on the right side of the documentation is *waster*
I just took the same css rule of our big brother https://gdal.org/
Of course the panel is shrinkable on devices etc
> Make the documentation wider

- docs/user_manual/grass_integration/grass_integration.rst
Line 294 :  "text" should be "test", as mentioned in line 288
> Wrong name new mapset

- docs/user_manual/processing_algs/qgis/interpolation.rst
Goal: Add version information, since the line density algorithm was added in 3.12.
Ticket(s): #5593, #4763
> Add version information for the line density algorithm

- docs/pyqgis_developer_cookbook/tasks.rst
Goal:
Be clear that GUI objects *AND* other QObjects that live on the main thread must not be accessed from a task.
> Warn about using QObjects in tasks

- docs/user_manual/processing_algs/qgis/rasteranalysis.rst
Goal: Clean-up (remove trailing blanks) QGIS Raster analysis algs
Ticket(s): #
> Remove trailing spaces - QGIS Raster analysis algs

- docs/user_manual/processing_algs/qgis/vectorgeneral.rst
Line 1975 : mentioned entry for parameter which should have been inside a table.
The same entry inside a table is mentioned at line 1986
> Removed superfluous item of entry for parameter

- conf.py
The canonical link was not working properly and was adding an extra /docs like this:
Goal:
The current canonical URL does not seem to be working properly as it returns an extra /docs folder. Like this:
link rel="canonical" href="https://docs.qgis.org/latest/en/docs/docs/index.html"
One of the effects of this, is that it prevents facebook of showing a proper preview for linked pages
Ticket(s): #
> Try to fix canonical link

- docs/user_manual/introduction/general_tools.rst
Goal: Describe the ctrl-click behaviour for group checkboxes.
Ticket(s): fix #1611
> ctrl-click - group checkbox

- docs/user_manual/processing_algs/qgis/vectorgeneral.rst
Goal: Fix bullet lists for enumerations - QGIS vector general algs
Ticket(s): #
> Fix bullet lists for enumerations - QGIS vector general algs

- conf.py
Goal:
Fix the canonical URL so that the SEOs can get the correct path to a more recent/relevant documentation.
We need to include the language folder, because for the build the language folder is actually the root folder.
Ticket(s): #
> Another try to fix the canonical URL

- themes/rtd_qgis/static/css/qgis_docs.css
With widening the documentation text, we also have make screenshots look bigger. Too much bigger. See for example https://docs.qgis.org/testing/en/docs/user_manual/style_library/label_settings.html#figure-labels-placement-polygon
Here's an attempt to fix that. Why those values? No idea. Need to be tested.
We have  now
vs PR should render something like
> Control image size on bigger screens

- docs/user_manual/introduction/getting_started.rst
Goal:
Make links to Sample Dataset consistent in testing docs.
In the "[Downloading sample data](https://docs.qgis.org/testing/en/docs/user_manual/introduction/getting_started.html#downloading-sample-data)" paragraph of the "Getting Starter" chapter in the "User Guide/Manual" there are separate instructions for Windows and GNU/Linux/macOS.
The current situation is that there are different link for the same sample dataset to download:
_ | Window | GNU/Linux/macOS
-------- | ---------- |------
testing | https://qgis.org/downloads/data/qgis_sample_data.zip | https://github.com/qgis/QGIS-Sample-Data/archive/master.zip
3.10 | https://github.com/qgis/QGIS-Sample-Data/archive/release_3.10.zip | https://qgis.org/downloads/data/qgis_sample_data.zip
3.4 | …
> Make links to Sample Dataset consistent in testing docs

- .travis.yml
Goal:
Trying to Update travis setup to a more recent version of python (3.5 --> 3.7) and ubuntu distribution(Xenial 16.04 --> Bionic 18.04).
Now, that we have moved to a more recent version of Sphinx, we should upgrade the testing infrastructure otherwise we will get problems like testing the usage of the newest libraries. Which is what is happening in here: #5729 
Notice that I don't know much about travis, just giving it a shot.
Ticket(s): #
> Update travis to most recent Python and linux distribution

- docs/training_manual/introduction/mapviewnavigation.rst
Goal: Update TM to reference a GeoPackage data source instead of Shapefile Format data sources
Ticket(s): #5726
> Update TM to reference a GeoPackage data source instead of Shapefile Format data sources

- docs/user_manual/introduction/qgis_gui.rst
- docs/user_manual/managing_data_source/opening_data.rst
- docs/user_manual/plugins/core_plugins/plugins_metasearch.rst
Goal: Update GUI labels for ArcGIS services (and adjust line lengths in the metasearch document).
Ticket(s): Fixes #5610
> Update GUI labels for ArcGIS services

- Makefile
- conf.py
Goal:
Release 3.10 and master building files have diverged a bit. When master gets to 3.16 release, we would need to catch up with everything we "hacked" on 3.10. Besides, we have been changing 3.10 and forward porting to master.
My idea with this PR, is to match the two, living the necessary commented lines to avoid building translations on testing.
This will allow us to work on these files the same way we do with all the others. We change master, and then backport to 3.10 (or in the future 3.16), and not the way around.
Ticket(s): #
> Match Makefile and conf.py to release 3.10

- docs/pyqgis_developer_cookbook/loadlayer.rst
Goal: Since QGIS does is not a fully compliant WFS 2 client, we should use WFS 1.1.0 in the
example requests (`version=1.1.0`).
Ticket(s): #5835
> Add version (1.1.0) to WFS requests

- docs/user_manual/processing/console.rst
Goal:
Fixes a typo in https://docs.qgis.org/testing/en/docs/user_manual/processing/console.html
errata
> To know the available options, you can use the algorithmHelp() command, as above. For instance, the **“native.buffer”** algorithm has an enumeration called JOIN_STYLE:
corrige
> To know the available options, you can use the algorithmHelp() command, as above. For instance, the **native:buffer** algorithm has an enumeration called JOIN_STYLE:
This should be backported to 3.10 branch.
> Fix typo native.buffer -> native:buffer

- docs/user_manual/working_with_vector/vector_properties.rst
The graduated renderer can use the classification mode logarithmic scale. It is useful for data with a wide range of values and represents the low data in detail.
Goal: Users shall be able to use the logarithmic scale classifier for graduated renderer.
Ticket(s): fix #4192
> information logarithmic scale

- docs/user_manual/processing/console.rst
Add the `createAlgorithmDialog` and `execAlgorithmDialog` processing methods to the manual.
p.s. not really really sure that the processing *scripts* section fits in the user manual, we can think to move the entire chapter to the pyqgis cookbook
Ticket(s): fixes #2294
> add doc for createAlgorithmDialog and execAlgorithmDialog

- docs/user_manual/style_library/label_settings.rst
Goal: Users shall be able to find the settings for the overrun feature which is available for line layers.
Ticket(s): fix #4036
> Overrun distance labels

- docs/training_manual/complete_analysis/analysis_combination.rst
Native tools reproject layers if necessary before processing. No need to do your own reprojection.
> Remove obsolete note on projection mismatch

- docs/user_manual/managing_data_source/opening_data.rst
Goal: adds the description of the auth methods to the ogr dataset
Ticket(s): fixes #2227
> Auth config for OGR sources

- docs/user_manual/processing_algs/index.rst
Parameter name for Python use is also displayed in the tables
> Remove obsolete note on algorithm parameters name

- docs/user_manual/plugins/core_plugins/plugins_geometry_checker.rst
Goal: some re-adaptation of the geometry checker plugin. The issue related is already fixed in the repository, but I think having a more bullet list that follows as much as possible the UI of the plugin is better. The content is basically the same (no new explanations added).
Ticket(s): fixes #2182
> Geometry checker chapter revamp

- docs/training_manual/create_vector_data/forms.rst
Line 83    : ":guilabel:`Attribute Form` tab" should probably be  ":guilabel:`Attributes Form` tab", which is the correct name of the  
tab
Line 188  : "Click on the :guilabel:`Fields` tab"  should probably be  "Click on the :guilabel:`Attributes Form` tab" ,
since the `Attribute editor layout` dropdown  is not on the Fields tab, but on the Attributes Form tab
> Corrected typo and switched name to correct tab

- docs/training_manual/map_composer/dynamic_layout.rst
Line 113 : "#. For the first vertical line::" -->> double colon at the end breaks the format of the list that follows it. Removed one instance to correct the format
Line 181 : closing parenthesis is missing. Added
Goal: Display cerrect documentation
> Broken format due to superfluous colon and missing parenthesis

- docs/user_manual/introduction/project_files.rst
Goal: Improving User Guide/Manual by fixing detected typos while studying
Ticket(s): #
> Fix typo in user manual doc (be also be)

- docs/training_manual/create_vector_data/topo_editing.rst
Line 207  :  "inside the polygon.." should probably be  "inside the polygon." 
Removed last instance of the dot (.)
> Removed superfluous dot at end of sentence

- Makefile
Goal:
In case anything goes wrong with one of the PDFs creation, the build will keep going and finish the rest of the jobs.
Ticket(s): #
This needs to be ported to master. I will do it once we confirm that this works with the current problems with JA.
> Allows PDF creation to fail softly without breaking the build

- docs/server_manual/services.rst
GetLegendGraphics request for setting legend labels (RULELABEL) to TRUE or FALSE now also supports AUTO value which is explained with this commit.
fix #5506
> Explain RULELABEL AUTO option in GetLegendGraphics

- docs/user_manual/processing/console.rst
- docs/user_manual/processing/modeler.rst
Goal: first PR of the Processing Model chapter. It just adds the list of the new inputs. Not backportable to 3.10 because of some very new inputs 
Ticket(s): fixes #2316 (I couldn't find other issues)
> Adds missing Processing Model inputs to the list

- docs/training_manual/vector_analysis/basic_analysis.rst
Line  298 ; ":guilabel:`Labe name`  should probably be ":guilabel:`Layer name`", since name of layer is meant, not the name of a label
Goal:  Display correct information
> "Labe name" should be "Layer name"

- docs/user_manual/working_with_vector/vector_properties.rst
Goal: adds a description of remote UI files option and fixes a broken link
Ticket(s): fixes #2622
> Remote UI files and broken link fixing

- docs/user_manual/working_with_vector/expression_help/Aggregates.rst
- docs/user_manual/working_with_vector/expression_help/Arrays.rst
- docs/user_manual/working_with_vector/expression_help/Color.rst
- docs/user_manual/working_with_vector/expression_help/Conditionals.rst
- docs/user_manual/working_with_vector/expression_help/Conversions.rst
- docs/user_manual/working_with_vector/expression_help/Date_and_Time.rst
- docs/user_manual/working_with_vector/expression_help/Files_and_Paths.rst
- docs/user_manual/working_with_vector/expression_help/Form.rst
- docs/user_manual/working_with_vector/expression_help/Fuzzy_Matching.rst
- docs/user_manual/working_with_vector/expression_help/General.rst
- docs/user_manual/working_with_vector/expression_help/GeometryGroup.rst
- docs/user_manual/working_with_vector/expression_help/Layout.rst
- docs/user_manual/working_with_vector/expression_help/Map_Layers.rst
- docs/user_manual/working_with_vector/expression_help/Maps.rst
- docs/user_manual/working_with_vector/expression_help/Math.rst
- docs/user_manual/working_with_vector/expression_help/Processing.rst
- docs/user_manual/working_with_vector/expression_help/Rasters.rst
- docs/user_manual/working_with_vector/expression_help/Record_and_Attributes.rst
- docs/user_manual/working_with_vector/expression_help/String.rst
- scripts/populate_expressions_list.py
by putting them between backticks (fix #5953) and moving from 
to 
Happens that quotes are kept as is within backticks or a code block. When in plain-text, another character code is used, and that one does not work in QGIS.
The only drawback I see is that the sqlite_fetch_increment examples go beyond the "paper" limits but it was already the case with the [hash](https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/expression.html#hash) examples. So not really a new issue.
> Make pasting examples with quotes succesfull

- docs/server_manual/getting_started.rst
I found a mistake in the bash commands used to enable/start the systemd socket/service.
This is directly linked to work made in previous PR [#5941](https://github.com/qgis/QGIS-Documentation/pull/5941)
No backport required
> getting started: fix bash to enable/start systemd socket/service

- scripts/find_set_subst.py
and fix warning 
```
$ python3 scripts/find_set_subst.py 
scripts/find_set_subst.py:31: SyntaxWarning: "is not" with a literal. Did you mean "!="?
while line is not "":
```
> Use string comparison operator

- docs/user_manual/introduction/browser.rst
Line 76   :  "browser panels can"  should probably be  "browser panel can"  Singular, not plural
Line 80   :   "hierarcy"  should be "hierarchy" - missing letter h at the end
Line 115 :  "Favourite"  should be "Favorite" to be consistent with other instances of the word
Line 127 :  ending comma (,) should be a dot (.), since it is at the end of the sentence and the end of the paragraph
Line 389 :  "- open the style manager"  should probably be "- opens the style manager", since pressing "Extract symbols" automagicly opens Style Manager
Line 395 : "menu of a layers offers" should probably be "menu of a layer offers".  Singular, not plural
Line 397 : Should probably have a dot (.) at the end since next sentence starts with capital letter and other items for this list do have a dot at the …
> Several typo's corrected

- docs/server_manual/getting_started.rst
- docs/server_manual/services.rst
Geometries are not added by default to GetFeatureInfo response. Explaining need for WITH_GEOMETRY parameter and related QGIS project setting.
Manual Backport to LTR documentation
> More info on GetFeatureInfo WITH_GEOMETRY parameter

- docs/user_manual/processing_algs/qgis/vectorcreation.rst
Goal: adds the missing parameter introduced by https://github.com/qgis/QGIS/pull/33039 and changes also the algorithm description and the python algorithm name.
Ticket(s): fixes #4492
> [Processing] add missing parameters to random points in extent

- docs/server_manual/config.rst
Goal: Enhance QGIS Server documentation by adding QGIS_SERVER_TRUST_LAYER_METADATA setting environnement description.
Ticket(s): #6013
> QGIS_SERVER_TRUST_LAYER_METADATA setting environnement

- docs/server_manual/config.rst
Goal: Enhance QGIS Server documentation by adding QGIS_SERVER_DISABLE_GETPRINT setting environnement description.
Ticket(s): #6042
> QGIS_SERVER_DISABLE_GETPRINT setting environment

- docs/training_manual/grass/grass_setup.rst
Goal: add a small note on how to open a QGIS session with GRASS available **before** activating it as a plugin
Ticket(s): fix #3331
> Open qgis with grass

- docs/user_manual/working_with_vector/vector_properties.rst
Goal: we have `qmd` file extension for metadata so let's use it ;)
Ticket(s): fix #6034
> change XML to qmd extension metadata

- docs/server_manual/config.rst
- docs/server_manual/services.rst
I complete some missing QGIS Server environment variables.
WFS environment variables were already described [here](https://github.com/qgis/QGIS-Documentation/blob/master/docs/user_manual/working_with_ogc/server/services.rst#configuration-and-settings), but I think it's good to have all in one place, so I move them in **Environment variables** chapter
> Add QGIS Server missing environment variables

- themes/rtd_qgis/versions.html
but not a direct link to the "new issue" page to give people a chance to check whether the issue is not already reported
> Add direct access to issue reports page

- docs/user_manual/introduction/general_tools.rst
- docs/user_manual/introduction/project_files.rst
- docs/user_manual/managing_data_source/opening_data.rst
because the "Handle Unavailable layers" dialog is only shown when opening a project. It's not really the way to open/fix an existing data but a way to fix an existing project. 
Also tweaks some description and fixes #6054
> Move "Handling broken file paths" section to Project files chapter

- REQUIREMENTS.txt
I've been using 3.x versions of sphinx locally for a moment to build , create pot file and pull translation. Issues I encountered were fixed long time ago so it does neither fix anything new, nor afaics brings new issues. But I think it's good we stay close to the new versions to avoid the big gap we had to deal with recently while restructuring docs.
> Upgrade sphinx and sphinx-intl dependencies version

- docs/server_manual/getting_started.rst
- docs/server_manual/services.rst
I went through the code to identify possible undocumented QGIS Server parameters. 
I found some in WMS, none in other services. This PR proposed to document the missing one. 
For the record, I didn't document those one
- **STYLE** : works the same way as STYLES, and it's not in the standard, only here for backward compatilibity I presume
- **WMTVER** : same as VERSION, only here for backwards capability
@signedav SRCWIDTH and SRCHEIGHT are not documented. From what I understand from your [PR](https://github.com/qgis/QGIS/pull/9545) and from the code, they serve the same purpose than HEIGHT/WIDTH on a GetMap but could be used when you want both HEIGHT/WIDTH and SRCHEIGHT/SRCWIDTH on a GetLegendGraphics.
From your PR, you said
> But on a GetLegendGraphics request these parameters (HEIGHT …
> Undocumented WMS parameters

- docs/server_manual/config.rst
- docs/server_manual/getting_started.rst
- docs/server_manual/services.rst
- docs/training_manual/qgis_server/wms.rst
instead of one that points to a "dead-end" table. Also add links to all parameters
When you go to [WMS getfeatureinfo](https://docs.qgis.org/testing/en/docs/server_manual/services.html#getfeatureinfo) and want to read details on its "FILTER" parameter for example, you click the link next to it and it brings you to the [WMS getmap table](https://docs.qgis.org/testing/en/docs/server_manual/services.html#qgisserver-wms-getmap). And the information you get is that it's a "subset of features". Great! But... if you really want details, you have to scroll the page (or Ctrl-F) to find that there's a whole dedicated section. I think this is a poor user experience we provide.
This **draft** PR  proposes to add the minimal description to all parameters and directly link the parameters in the table …
> [WMS] Use direct reference to sections

- docs/developers_guide/ogcconformancetesting.rst
[pyogctest](https://github.com/pblottiere/pyogctest) is now used in QGIS continuous integration (cf the next [PR](https://github.com/qgis/QGIS/pull/38644)) to run OGC tests. Indeed, it allows to run these tests easily and in command line without bothering about the testing environment (Java, Teamengine, OGC test suites, ...).
This PR updates the documentation accordingly. This way, QGIS Server developers will have an entry point to run these tests locally during the development phase.
Opinions are welcome of course :).
> Update documentation on OGC conformance testing

- docs/documentation_guidelines/do_translations.rst
i18n -> locale
Modify the locale directory path in the documentation_guidelines/do_translations.rst.
ex.) /QGIS-Documentation/i18n/en -> /QGIS-Documentation/locale/en
https://docs.qgis.org/3.10/en/docs/documentation_guidelines/do_translations.html
> Modify the locale directory path

- docs/pyqgis_developer_cookbook/cheat_sheet.rst
Goal: OpenStreetMap does use some form of DNS-based load balancing for its tile servers. This should be used in this cheat sheet, as it will end up in a lot of code.
> use tile.openstreetmap.org instead of a.tile.

- docs/server_manual/getting_started.rst
Line 196 : "printing,    you can use :ref:`xvfb <xvfb>`." should be "printing, you can use :ref:`xvfb <xvfb>`."
Line 238 : "0123456789012345678901234567890123456789012345678901234567890123456789" should be removed
> Superfluous whitespace and removed unwanted string

- docs/documentation_guidelines/first_contribution.rst
ex) 1. Fork QGIS-Documentation -> Fork QGIS-Documentation
https://docs.qgis.org/3.10/en/docs/documentation_guidelines/first_contribution.html
Headers' section numbers are attached by Sphinx when it will be rendered. The section number in the header text itself make readers confused.
This change is the same as the branch havatv_numbering_docguide. Since I don't know why the branch has not been merged yet, I create the pull request.
> Remove the section number in the header text

- docs/training_manual/complete_analysis/analysis_exercise.rst
line 235 :  "'Clip Raster by Extent' dialog" should be " 'Clip Raster by Mask Layer' dialog" since that is the algorithm that is used here.
Clip Raster by Mask Layer is also used the first time and should again be used the second time.
> Changed name of used dialog

- docs/server_manual/services.rst
Goal:
map0:, map1: ... has to be specified in GetPrint request to tell which map will get redlining drawn.
Previous PR : https://github.com/qgis/QGIS-Documentation/pull/5897
> Add map0: in GetPrint request with redlining

- docs/pyqgis_developer_cookbook/vector.rst
Goal: add some missing methods to `QgsVectorLayer`
Ticket(s): fixes #1542
> [pyqgis] add methods to QgsVectorLayer

- docs/documentation_guidelines/first_contribution.rst
It is QGIS documentation website (https://docs.qgis.org) which has "Edit on GitHub" link at the top right of each page. It isn't QGIS website (https://qgis.org/xx/site/). It is more confusing because the note says "Though QGIS-Documentation is used to demonstrate the process, all commands and steps shown below also apply to QGIS-Website" above.
https://docs.qgis.org/testing/en/docs/documentation_guidelines/first_contribution.html
> Modify the confusing word

- docs/user_manual/plugins/core_plugins/plugins_db_manager.rst
Goal: add the description of the `Query History` button of DB Manager. I didn't add any screenshot (not worth it IMHO)
Ticket(s): fixes #2607
> add query history DB Manager

- docs/index.rst
Categorize documents into three groups of "For users", "For documentation writers" and "For developers" in the sidebar of the QGIS documentation website in accordance with the description of the documentation area in the [QGIS website](https://qgis.org/en/docs/).
https://docs.qgis.org/testing/en/docs/index.html
> Categorize documents in the sidebar of the QGIS documentation website 

- conf.py
[ Goal ]
* Improve visibility of menu selection
* The more similar appearance of menu selection to the GUI
Before:
After:
[ Problem ]
The default bullet character of menu selection is 'TRIANGULAR BULLET'. This symbol is too small for high visibility.
For example, in Japanese text, a symbol of 'KATAKANA MIDDLE DOT' is often used for a separator of two words, especially foreign words or foreign names. 'Donald John Trump' is written as 'ドナルド・ジョン・トランプ' in Japanese. 'Triangular Bullet' and 'KATAKANA MIDDLE DOT' are so alike that it is almost impossible to tell them apart.
TRIANGULAR BULLET:
KATAKANA MIDDLE DOT:
[ Solution ]
In conf.py, set the BULLET_CHARACTER constant of MenuSelection class into 'BLACK RIGHT-POINTING TRIANGLE'.
ref. https://github.com/sphinx-doc/sphinx/issues/7006
This symbol …
> Make a bullet character of menu selection more visible

- docs/user_manual/processing_algs/qgis/vectorgeneral.rst
Goal: add a description to ``Execute SQL`` Processing algorithm to describe the potential usage of expression and/or variable. I didn't added the description to the parameters itself because it is defined as an unique parameter (`ParameterExecuteSql` basically a String + Expression) used only in this algorithm. 
IMHO it is better to describe what is the general aim of this parameter in the algorithm description
Ticket(s): fixes #2579
> [Processing] describe the use of expression/variable in Execute SQL algorithm

- conf.py
I found a matter with  my already merged pull request “Make a bullet character of menu selection more visible” (#6187). On the iOS operating system, 'BLACK RIGHT-POINTING TRIANGLE' is displayed as a button instead of the right pointing triangle. This is an undesirable result of a lack of similarity to real GUI.
I didn’t realized this because I always worked on the issue using macOS.
According to this website, the problem is only on iOS.
https://www.utf8icons.com/character/9654/black-right-pointing-triangle
Using  'BLACK RIGHT-POINTING POINTER' instead of 'BLACK RIGHT-POINTING TRIANGLE' solves the problem.
On iOS:
On macOS:
On Windows:
I couldn’t test it on Linux and Android because I don’t have them.
Above website doesn’t have images for BLACK RIGHT-POINTING POINTER. …
> Use  'BLACK RIGHT-POINTING POINTER' as MenuSelection.BULLET_CHARACTER

- .github/workflows/doctest.yml
I don't know whether it's better than travis but,  it's faster, and it outputs an artifact of summary for the build a noob like me can find
If approved, the idea would be to remove travis in the next step.
It seems to run fine but I'd very much appreciate some review. Thanks
@elpaso @3nids .... ?
> Check doctest build with GitHub action

- docs/documentation_guidelines/do_translations.rst
Having done some translation cleanup this week-end, there were some missing rules or tips IMHO
> Add precision to translation rules

- docs/user_manual/working_with_vector/editing_geometry_attributes.rst
and also refer to auxiliary storage use
fixes #6210 fixes #6211
> Use click-click for rotate and offset point symbols tools

- docs/user_manual/introduction/qgis_gui.rst
> Update map view color preview modes

- docs/training_manual/complete_analysis/analysis_exercise.rst
Line 449 : "Use the following expression:"  should be "Use the following expression::" to let the expression show as an expression in the built documentation.
At the moment it shows as regular text.
- [x ] Backport to LTR documentation is required
> Added colon to let expression show as expression in build docs

- docs/pyqgis_developer_cookbook/legend.rst
I don't know what has changed in QGIS code or our data but doctest build is failing and outputs that were expected to be of QgsMapLayer type are returned as QgsVectorLayer (eg https://github.com/qgis/QGIS-Documentation/runs/1394492880?check_suite_focus=true#step:6:514). 
Note that the layer ID also changes at each run, something I don't know how to fix it.
Any help is more than appreciated. Thanks
> Doctest build is turning QgsMapLayer into QgsVectorLayer

- docs/pyqgis_developer_cookbook/vector.rst
Goal: revert the revert of https://github.com/qgis/QGIS-Documentation/pull/6040
Sorry for the noise, but the PR was very old and something might have happened.
Ticket(s): fix #2775
> [pyqgis] IndexKDBush index

- docs/server_manual/getting_started.rst
```
systemctl enable service_name && systemctl start service_name
```
has same effect as 
```
systemctl enable --now service_name
```
Source : https://github.com/systemd/systemd/blob/dd95b381b26369c02a3ca03585184cb2ea17295b/NEWS#L3043-L3046
> "systemctl enable", "systemctl disable" and "systemctl mask"
> now support a **new "--now" switch**. If specified the units
> that are **enabled will also be started**, and the ones
>  disabled/masked also stopped.
Require systemd 220 released in 2015-05-22 which is now present in all distributions
Goal:
Ticket(s): #
> Small mod to start service or socket after enable

- docs/user_manual/print_composer/composer_items/composer_map.rst
The map item properties panels were extended by a clipping settings panel
Goal: Precise steps to enable the clipping settings.
Ticket(s): fix #5820 fix #5937
> clipping settings for map items

- docs/user_manual/introduction/general_tools.rst
This is a proposal for explaining the visible rules only option for symbolizing vector tiles. I didn't insert a screenshot. Do we need to mention this information in the vector layer properties, too?
Goal: Users shall be informed that for vector tiles they can work only with the rules that fall inside the current map canvas zoom level
Ticket(s): fix #6085
> mention visible rules only

- docs/user_manual/introduction/qgis_configuration.rst
- docs/user_manual/working_with_vector/editing_geometry_attributes.rst
The tracing tool was extended. The user can now trance on curved geometries.
Goal: The user shall be able to use the tracing of curved geometries while digitizing.
Ticket(s): fix #6287
> tracing on curved geometries

- docs/training_manual/complete_analysis/raster_to_vector.rst
Line 49 :  " :kbd:`suitable` has the value of :kbd:`1`." should probably be " :guilabel:`suitable` has the value of ``1``." to look the same as the previous paragraph (line 38)
Line 50/51 : "as :kbd:`exercise_data/residential_development/` as
:kbd:`suitable_terrain.shp`.  should probably be "under :file:`exercise_data/residential_development/` as
:file:`suitable_terrain.shp`." to look the same as earlier paragraph (line 33/34)
Line 60 "":kbd:`suitable_terrain.shp`" should probably be ":file:`suitable_terrain.shp`" since it refers to a file, not to something to enter.
All changes used to have the tag :kbd: instead of the more appropriate tags :guilabel: and :file:
> Updated format to express as previous/earlier paragraph

- docs/user_manual/print_composer/composer_items/composer_legend.rst
The feature was already there but not necessarily visible for readers
> More visibility for legend items expression capabilities

- docs/user_manual/working_with_vector/vector_properties.rst
when a relation exists (fix #1493)
> Relation reference widget is applied by default

- docs/user_manual/processing_algs/qgis/vectorgeneral.rst
This algorithm now allows to merge vector layers with mixed attribute types.
Goal: Users shall be able to use the updated merge vector layers algorithm.
Ticket(s): fix #6008
> updated merge vector layers

- docs/user_manual/plugins/core_plugins/plugins_metasearch.rst
This PR adds a section on possible configuration errors for CSW servers that a user may be trying to work with in MetaSearch, pointing to the pycsw FAQ for a deeper discussion.  This will e useful for those testing their CSW server in MetaSearch.
> [MetaSearch]: add section on CSW Server Errors

- .github/workflows/pofiles.yml
This PR adds an action that automatically generates and commits the translation .po files. It aims to help us automate the push/pull of files from/to Transifex. This should happen at every night whenever the 3.16 branch has got a change on an rst file.
In its current shape, it (seems to) work(s).
Review and feedback welcome...
> Add an action to update English PO files when rst files change

- docs/user_manual/print_composer/composer_items/composer_table_items.rst
Goal: Correct typo. Close the relevant issue.
Ticket(s): fix #5867
> fixed typo

- REQUIREMENTS.txt
- conf.py
- redirects.txt
* Add [sphinxext-rediraffe](https://github.com/wpilibsuite/sphinxext-rediraffe) extension to redirect HTML pages
* Add the extension to REQUIREMENTS.txt file to consolidate the build
* Add a set of pages redirection
It wouldn't solve issues with moving section from a page to another (to keep tracking the help button from QGIS application - #1926) but when a whole file is renamed or moved to another directory (eg the server manual reshuffle) we can still catch the right page. Gives also more sense to the top banner of outdated pages that sends to the latest version (and sometimes a 404).
Bonus: the redirection is tested by the HTML build which fails if a target page is missing.
@rduivenvoorde @mbernasocchi we were looking for something like this in …
> Enable pages redirection using the sphinxext-rediraffe extension

- themes/rtd_qgis/versions.html
Ideally we should set the outdated status to True but I fee the top banner would be confusing to people since 3.10 is still active code-wise. We should do that in February.
> Disable translations for 3.10 documentation

- Makefile
- scripts/minimize_translation.sh
using the --mode onlytranslated option
Also add a script that cleans the folder from unnecessary downloaded files (transifex still pulls files with untranslated strings, only their header)
Sphinx is smart enough to build the translated docs so we don't need to pull in target PO files, the English strings if untranslated. [Using this method](https://github.com/qgis/QGIS-Documentation/commit/0c20b7ddd8ab4b93cc9436f19d6059b3a80d5d6e), we fall down from 22k files (450MB) to 8k files (77MB). The 57 languages are downloaded in almost 1h from scratch here.
> Only pull translated parts of files from Transifex and not the whole files

- .github/workflows/doctest.yml
- .github/workflows/html.yml
- scripts/create_transifex_resources.sh
(cherry picked from commit 662c886d9e3ee5551ed55828020987f51482ca69) Backports #6393
And use full lower case for slugs.
> Do not run the tests when the changes are only in locale folder (#6393)

- docs/user_manual/style_library/label_settings.rst
Line 487 : "`Parallel`: draws "  -->> is missing a space between the colon and "draws".  Placed one space in between
Line 570 : "to force the force" -->>  double wording. Removed "the force"
> Missing space and double wording corrected

- redirects.txt
- Redirect old single "server manual" page
- Remove unnecessary comma
- Group pages by manual
Fixes #4325 (3.4 is no longer maintained but manually changing version in the mentioned URL will now lead to an existing page in recent versions)
> Update list of pages redirection

- docs/server_manual/getting_started.rst
- docs/training_manual/qgis_server/install.rst
Move training_manual/qgis_server/install.rst sections to server_manual/getting_started.rst 
Try to do the best merge by replacing less detailed content of server_manual/getting_started.rst with training_manual/qgis_server/install.rst. Add references in training_manual to server_manual.
See ticket #6031
Goal:
Ticket(s): #
> Merge duplicated explainations about QGIS server installation with Apache

- docs/user_manual/working_with_vector/vector_properties.rst
to connect labels and features
> Mention that label callout can be used next to geometry generator symbol layer

- docs/server_manual/getting_started.rst
As per the environmental variables section, PROJECT_FILE is not listed
Would be good if one of the QGIS Server gurus can confirm that this change is correct....
> Replace references to PROJECT_FILE with QGIS_PROJECT_FILE

- docs/training_manual/map_composer/dynamic_layout.rst
The original expression is `@layout_pagewidth - @sw_layout_margin * 2 - 78`, which makes the picrure item not x-aligned with the label just created in previous section, and is conflict with the north arrow created in following context.
> correct the expression for picture item's X

- Makefile
- conf.py
- docs/gentle_gis_introduction/coordinate_reference_systems.rst
- docs/gentle_gis_introduction/data_capture.rst
- docs/gentle_gis_introduction/map_production.rst
- docs/gentle_gis_introduction/vector_attribute_data.rst
- docs/pyqgis_developer_cookbook/network_analysis.rst
- docs/server_manual/containerized_deployment.rst
- docs/server_manual/services.rst
- docs/training_manual/appendix/preparing_data.rst
- docs/training_manual/database_concepts/data_model.rst
- docs/training_manual/forestry/basic_lidar.rst
- docs/training_manual/forestry/forestry_intro.rst
- docs/training_manual/spatial_databases/geometry.rst
- docs/training_manual/spatial_databases/index.rst
- docs/training_manual/spatial_databases/spatial_functions.rst
- docs/training_manual/vector_analysis/reproject_transform.rst
- docs/user_manual/appendices/qgis_r_syntax.rst
- docs/user_manual/introduction/qgis_gui.rst
- docs/user_manual/preamble/help_and_support.rst
Running `make linkcheck` to find them and browsing the web for a replacement. The idea is to close #4182
Missing fixes for:
1. Qt [qdatetime::fromstring]( https://docs.qgis.org/3.16/en/docs/user_manual/working_with_vector/functions_list.html#expression-function-date-and-time-to-datetime): underway at https://github.com/qgis/QGIS/pull/40908
1. the http://apps1.gdr.nrcan.gc.ca/cgi-bin/worldmin_en-ca_ows link used in [training manual answers](https://docs.qgis.org/3.16/en/docs/training_manual/answers/answers.html#moderate-finding-a-wms-server). Any suggestion for a good replacement would be more than welcome.
> Fixes broken URLs in the documentation

- docs/user_manual/introduction/general_tools.rst
Added more complete documentation about zooming and panning.
> Zooming and panning

- docs/training_manual/answers/answers.rst
- docs/training_manual/online_resources/wms.rst
- docs/user_manual/introduction/general_tools.rst
- docs/user_manual/introduction/qgis_gui.rst
Edited the documentation for the new behavior of Zoom to Layer, Zoom to Selection and Pan Map to Selection (QGIS/QGIS#40460 and QGIS/QGIS#40857) that will be in release 3.18
Fixes #6406
> Zooming and panning for 3.18 (fixes #6406)

- docs/user_manual/processing/standalone.rst
line 31 :    - `--json`  should be  - ``--json`` to have the same format as the rest of the list. Without it is showed as italic text
> Fix format item in list

- .github/workflows/backport.yml
Merged pull-requests do not backport changes to 3.16 anymore (https://github.com/qgis/QGIS-Documentation/actions?query=workflow%3ABackport). And the report is `Unexpected input(s) 'bot_token_key', valid inputs are ['bot_username', 'bot_token', 'github_token'] `. So let's try to follow...?
> Use ubuntu-latest for backport github action

- docs/user_manual/processing/3rdParty.rst
line 233  :  `http://cran.at.r-project.org/`  changed to HTTPS : `https://cran.at.r-project.org/`.  Checked and works
> Updated HTTP to HTTPS

- docs/pyqgis_developer_cookbook/cheat_sheet.rst
PyQGIS - Use the API to get the sublayer separator, instead of hardcoded string
> PyQGIS - Use the API to get the sublayer separator

- .github/workflows/pofiles.yml
Create the files to pull by Transifex once a week instead of every day. Reduces files traffic and the frequency of files modification for translators (and I'm personally not convinced that it's necessary to load changes every day). Once per week is already far better than the previous once in a while.
> Delay the PO files generation

- docs/user_manual/processing_algs/qgis/rasteranalysis.rst
and update the docs to mention the difference of behavior
If you are using 3.12 or 3.14 and you hit help button of the zonal statistics alg, it won't bring you to the alg section but to the top of the page, because the anchor has changed. Moreover the description does not match the behavior which may look confusing. This fixes these issues.
> Keep older zonal statistics anchor for 3.12 and 3.14

- docs/training_manual/processing/cutting_merging.rst
Goal:
In the **_17.15. Clipping and merging raster layers_** chapter is currently mentioned the "GDAL Merge" algorithm.
Previously, the mentioned algorithm was "Merge raster layers", but it was incorrectly replaced in the documentation by "GDAL Merge" https://github.com/qgis/QGIS-Documentation/commit/265ae574567d15a979c640d1901b37f93e54523d.
Anyway the correct replacement for the "Merge raster layers" algorithm is the SAGA "Mosaic raster layers" algorithm (https://github.com/qgis/QGIS/pull/1636 - https://github.com/qgis/QGIS/commit/62302377db1990485f7821f1ccef4ff6ef4d07d9#diff-aad3ad85caa27c517e2934f3aa74fc25021fe41164fdd74e808b0920d3243cf8).
See also http://osgeo-org.1560.x6.nabble.com/gdal-merge-td5456099.html
> Fix Merge algorithm name

- REQUIREMENTS.txt
I think we should follow dependencies upgrade and stick to a version only if there are issues with the newer releases.
We already use no version for the GitHub workflow and Transifex also seems to rely on a more recent version (eg, babel 2.9 vs 2.8) so this PR aligns them all...
> Use latest release for dependencies

- themes/rtd_qgis/static/css/qgis_docs.css
Prevents situation where text is out of the table (like https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/functions_list.html#sqlite-fetch-and-increment) by adding a scroll bar within the table.
Fix suggested in a [french forum](https://georezo.net/forum/viewtopic.php?pid=340191#p340191)
> Avoid table content overflow

- scripts/fix_versions.sh
This is a follow-up to https://github.com/qgis/QGIS-Documentation/pull/5833#issuecomment-656047018, providing a script to run on the server side to update the list of versions in the bottom left panel of outdated releases, when a new release is out. (To be run on 3.4 folder).
It's probably not academically written or optimized, but it works well as far as I could test locally, and is based on the [pyqgis script](https://github.com/qgis/pyqgis/blob/gh-pages/fix-versions.sh). 
Probably supersedes #5833 
@rduivenvoorde (as server father 😄 ) @agiudiceandrea @SrNetoChan ?
> Add a script to update versions list in outdated releases

- docs/user_manual/print_composer/composer_items/composer_html_frame.rst
Goal: Documents unexpected behavior of scaling when adding HTML frames. 
Ticket(s): #
Fixes #6387
> Add HTML scaling control documentation

- conf.py
Download a pdf doc and you get this kind of paragraph (note the arrow replacement in the menu path)
> ![image](https://user-images.githubusercontent.com/7983394/109927782-00473400-7cc5-11eb-8bc5-b091fec588a2.png)
This is like this since #6212 (4 months ago). Wonder how nobody reports this if there are any PDF user .
I don't know what is the proper/elegant fix but the changes here display the arrow now instead of interrogation mark (in English build)
> ![image](https://user-images.githubusercontent.com/7983394/109931634-60d87000-7cc9-11eb-8791-5177aa7afc05.png)
> Display :menuselection: arrow in PDF output using unicode format

- conf.py
avoiding accumulation of screenshots at the end of exercises, making them almost useless (iow download the training manual in pdf and try to understand any logic in the screenshot - I really wonder if there are people using the PDF...)
> Place the images in PDF where they are expected in the rst

- docs/user_manual/print_composer/composer_items/composer_legend.rst
Looks more legible and understandable than concat (with its isolated brackets)
_/me nitpicking_
> Use format function for an example

- .github/workflows/pofiles.yml
- scripts/create_transifex_resources.sh
Avoids pushing to transifex strings that were replaced and no longer exist in the rst file (translators already have enough to do)
> Do not keep old strings in generated po files

- docs/server_manual/services.rst
The WMS 1.1.0 protocol is not strictly implemented. Instead, we implement the 1.1.1 version and currently, the fallback to 1.1.1 when `VERSION=1.1.0` is not always respected (it's a WIP).
> WMS version set to 1.1.1

- .github/workflows/builds.yml
Currently the github action to create html and pdf artifacts takes 12/13mn to proceed. Too long.
Instead of building formats one after the other, we now build them in parallel and it takes less than 8mn (in which the command to generate the PDF files takes 6mn).
If you know another way to improve the situation...
> Parallel jobs to decrease docs builds time

- docs/server_manual/config.rst
Goal:
Update Logging information:
- `QGIS_SERVER_LOG_FILE` is deprecated
- `QGIS_SERVER_LOG_PROFILE` is not mentioned
> Update Logging information

- docs/server_manual/getting_started.rst
Goal:
Provide a working Apache `qgis.demo.conf` for setups where no X environment is available.
If there's no X environment, the current use of the `DISPLAY` parameter results in an _Internal Server Error_.
There's no information lost with this PR, the use of the `DISPLAY` parameter is explained later in the manual:
https://github.com/qgis/QGIS-Documentation/blob/master/docs/server_manual/getting_started.rst#with-apache
> Remove DISPLAY parameter from Apache qgis.demo.conf

- .github/workflows/pofiles.yml
We shouldn't (try to) update these files on user repo (noisy when it fails, diverging history when it succeeds, so nothing good)
> Run PO files update workflow only on upstream repo

- docs/server_manual/config.rst
- docs/server_manual/getting_started.rst
Remove QGIS_SERVER_LOG_FILE and QGIS_DEBUG from code snippets
@elpaso What do you think ?
If I'm not wrong, people running a debug build are just a few (geeks compiling QGIS ?). So these people should just read the table of available environment variable #6492 
So if QGIS_DEBUG doesn't have an effect for the majority of people, we shouldn't provide it in code snippets, as usually people do a copy/paste from here.
Backport to 3.16
> Remove QGIS_SERVER_LOG_FILE and QGIS_DEBUG from code snippets

- docs/developers_guide/git.rst
* Remove mention of patches: let's stick to pull request which is the simplest and advised way to contribute
* Remove some unnecessary information
* Update instructions for docs issues generation
This part really needs some more work (still refers to pr as being assigned a reviewer, and eg mentions Marco Hugentobler). It echoes the current discussion regarding help on pr queue and I hope someone will later summarize main decisions to make things clear for all
> Update information on pull request submission

- docs/developers_guide/git.rst
* Align terms (origin, upstream) with the GitHub help. Fixes https://github.com/qgis/QGIS-Website/issues/359
* Reorder instructions to avoid repetition, and make the learning process smoother
* Remove confusing instructions regarding core devs: let's target the contributor lambda and explain the situations he may face. And I hope that before someone is given write access to the repo, we ensure he has enough knowledge and practice with git.
This is just a cleanup. There might be more details to provide to (first time) contributors for a better onboarding: tests, backport process, review...
> Walk through instructions on how to develop using git

- docs/training_manual/spatial_databases/spatial_functions.rst
Updated PostGIS installation instructions as per https://github.com/qgis/QGIS-Documentation/issues/6511
I updated the installation instructions. I have tested those (PG 13 + PostGIS 3) myself on Ubuntu 18.04 and used several times with different distros. I also modified the Windows instructions a bit.
Goal:
Make life easier for QGIS users who want to install PostGIS
Ticket(s): #
Fixes https://github.com/qgis/QGIS-Documentation/issues/6511
> Update PostGIS installation instructions in training manual

- docs/user_manual/working_with_raster/georeferencer.rst
Rewrote transformation type section to remove some erroneous info on projective transformation, and more importantly provide better guidance on differences between the types and when to choose each one. This section has been source of some confusion to the user base, e.g. https://gis.stackexchange.com/questions/367659/differences-between-different-georeferencing-transformation-algorithms-in-qgis
> Rewrite section of georeferencer.rst

- docs/server_manual/getting_started.rst
The documentation refers to `C:\xampp\apache\httpd.conf` which doesn't exist. Instead I found it at `C:\xampp\apache\conf\httpd.conf`.
> Update QGIS Server doc with new conf location

- docs/server_manual/getting_started.rst
The existing documentation is confusing about what to expect when running `/usr/lib/cgi-bin/qgis_mapserv.fcgi` for the first time.  Since QGIS 3.16.x, the server will produce a 400 response that suggests it is not working, when in fact it is.  See my answer here: https://gis.stackexchange.com/a/394171/181982
Goal:
Ticket(s): #
> Update section on running qgis_mapserv.fcgi for the first time

- docs/user_manual/introduction/general_tools.rst
- docs/user_manual/introduction/qgis_configuration.rst
- docs/user_manual/style_library/label_settings.rst
- docs/user_manual/style_library/symbol_selector.rst
With more and more (raster, 3D) features being "embeddable" in the project,
it looks weird to point to an SVG dedicated section (in config docs).
Let's make a generic section any data type could point to.
> Dedicate section for embedded file selector

- docs/user_manual/processing_algs/qgis/rasteranalysis.rst
Goal:
Specify that the "Output extent" parameter for Raster calculator (qgis:rastercalculator) algorithm is optional.
See: https://github.com/qgis/QGIS/blob/ac6732db42e8f0db8305b00a616430bd310c0360/python/plugins/processing/algs/qgis/RasterCalculator.py#L87-L89
> "Output extent" parameter for Raster calculator (qgis:rastercalculator) algorithm is optional

- docs/user_manual/processing/standalone.rst
https://github.com/qgis/QGIS/pull/34617#issuecomment-703939137 shows this is unclear for users, especially since the qgis processing GUI doesn't show the command line to use, so including this in the documentation would be helpful for users.
not required, but it could be
> Update qgis_process documentation to show how arrays may be passed

- docs/server_manual/services.rst
and VERSION parameter is mandatory for GetMap in 1.3.0
Backports fixes in #6733 and #6730
> More precise information about BBOX and axis ordering in WMS

- Makefile
- conf.py
- docs/index.rst
- docs/user_manual/introduction/qgis_configuration.rst
with some details on what QGIS is, how to contribute and what to expect from the docs
This is highly inspired from the godot-engine project: see [en](https://docs.godotengine.org/en/stable/index.html) vs [fr](https://docs.godotengine.org/fr/stable/index.html) vs [latest](https://docs.godotengine.org/en/latest/index.html). You don't get the same text depending on what version or language you are reading.
Feedback are more than expected
> Expand and customize the introduction of QGIS documentation

- scripts/load_tx_stats.py
when the number of target languages is not a multiple of the number of columns. Ensures a valid rst table.
> Fill the generated table with empty cells

- docs/user_manual/processing_algs/gdal/rasterextraction.rst
The ``gdal:cliprasterbymasklayer`` algorithm has one of its paramaters named wrong in the documentation.
This PR replaces the "EXTENT" with the correct "MASK" parameter name.
> fix wrong parameter name in gdal:cliprasterbymasklayer

- docs/index.rst
Goal: Fix broken link: current link to testing docs (https://docs.qgis.org/en/testing) appears to be broken – https://docs.qgis.org/testing/en/ appears to be the correct link.
Ticket(s): n/a
> Fix broken link to testing docs

- docs/user_manual/processing/configuration.rst
Goal:
Add `Results group name` parameter to Processing Configuration section.
This parameter is available since QGIS 3.16 (see https://github.com/qgis/QGIS/pull/37595) .
> Add 'Results group name' parameter to Configuration section

- docs/user_manual/processing/standalone.rst
Display the help output and move some related sections close together
Fixes #5283, fixes #5931, fixes #5803
> Refactor qgis_process documentation

- docs/user_manual/introduction/browser.rst
Instead of repeating texts for each of the supported database in the Browser panel (see from [this section](https://docs.qgis.org/3.16/en/docs/user_manual/introduction/browser.html#geopackage)), this PR suggests to display their contextual menu in a matrix, so no repetition but ability to compare what is available, where...
Remove the DB2 entry
Still looking for help to fill MSSQL, Oracle and SAP HANA that I do not have available. Maybe @stefanuhrig @troopa81 @vcloarec ?. Thanks
Fixes #4406
> [Browser] Turn lists of database contextual menus into a table

- docs/pyqgis_developer_cookbook/authentication.rst
- docs/pyqgis_developer_cookbook/canvas.rst
- docs/pyqgis_developer_cookbook/cheat_sheet.rst
- docs/pyqgis_developer_cookbook/communicating.rst
- docs/pyqgis_developer_cookbook/composer.rst
- docs/pyqgis_developer_cookbook/crs.rst
- docs/pyqgis_developer_cookbook/expressions.rst
- docs/pyqgis_developer_cookbook/geometry.rst
- docs/pyqgis_developer_cookbook/intro.rst
- docs/pyqgis_developer_cookbook/legend.rst
- docs/pyqgis_developer_cookbook/loadlayer.rst
- docs/pyqgis_developer_cookbook/loadproject.rst
- docs/pyqgis_developer_cookbook/network_analysis.rst
- docs/pyqgis_developer_cookbook/pluginlayer.rst
- docs/pyqgis_developer_cookbook/plugins/ide_debugging.rst
- docs/pyqgis_developer_cookbook/plugins/plugins.rst
- docs/pyqgis_developer_cookbook/plugins/releasing.rst
- docs/pyqgis_developer_cookbook/plugins/snippets.rst
- docs/pyqgis_developer_cookbook/processing.rst
- docs/pyqgis_developer_cookbook/raster.rst
- docs/pyqgis_developer_cookbook/settings.rst
- docs/pyqgis_developer_cookbook/tasks.rst
- docs/pyqgis_developer_cookbook/vector.rst
Display table of contents for all, and only in html docs
Highlight the page testcode and place it after the page title and before the inline TOC (Currently it's sometimes before the page title, or just after or after the toc). things are now harmonized and predictable. refs #3561
> Harmonize Cookbook chapters beginning

- docs/user_manual/introduction/qgis_configuration.rst
Goal:
Substitutes "QSettings" with "Settings" in QGIS Configuration chapter:
https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html#customization
https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html#system-settings
Ticket(s): #
> Substitute "QSettings" with "Settings" in QGIS Configuration chapter

- docs/user_manual/processing_algs/qgis/vectorgeneral.rst
Goal:
Fix some Vector general tools Algorithm IDs, from qgis: to native:
Ticket(s): #
> Fix Vector general tools Algorithm IDs

- docs/user_manual/introduction/general_tools.rst
- docs/user_manual/working_with_mesh/mesh_properties.rst
- docs/user_manual/working_with_raster/raster_properties.rst
- docs/user_manual/working_with_vector/vector_properties.rst
- docs/user_manual/working_with_vector_tiles/vector_tiles_properties.rst
instead of within the vector layer chapter and point to it.
Also adds/updates metadata and information tabs for these layer types (raster, vector, vector tile, mesh - fixes #6705).
This also makes room for layer notes...
> Move the layer metadata tab description to a more generic place

- docs/user_manual/processing_algs/gdal/rasteranalysis.rst
- docs/user_manual/processing_algs/gdal/rasterconversion.rst
- docs/user_manual/processing_algs/gdal/rasterextraction.rst
- docs/user_manual/processing_algs/gdal/rastermiscellaneous.rst
- docs/user_manual/processing_algs/gdal/rasterprojections.rst
- docs/user_manual/processing_algs/gdal/vectorconversion.rst
- docs/user_manual/processing_algs/gdal/vectorgeoprocessing.rst
- docs/user_manual/processing_algs/gdal/vectormiscellaneous.rst
- docs/user_manual/processing_algs/qgis/cartography.rst
- docs/user_manual/processing_algs/qgis/database.rst
- docs/user_manual/processing_algs/qgis/filetools.rst
- docs/user_manual/processing_algs/qgis/interpolation.rst
- docs/user_manual/processing_algs/qgis/layertools.rst
- docs/user_manual/processing_algs/qgis/networkanalysis.rst
- docs/user_manual/processing_algs/qgis/plots.rst
- docs/user_manual/processing_algs/qgis/qgis_algs_include.rst
- docs/user_manual/processing_algs/qgis/rasteranalysis.rst
- docs/user_manual/processing_algs/qgis/rastertools.rst
- docs/user_manual/processing_algs/qgis/vectoranalysis.rst
- docs/user_manual/processing_algs/qgis/vectorcreation.rst
- docs/user_manual/processing_algs/qgis/vectorgeneral.rst
- docs/user_manual/processing_algs/qgis/vectorgeometry.rst
- docs/user_manual/processing_algs/qgis/vectoroverlay.rst
- docs/user_manual/processing_algs/qgis/vectorselection.rst
- docs/user_manual/processing_algs/qgis/vectortable.rst
The Processing output parameter has got some improvements over the years, namely:
- ability to save to any database type and not only to PostGIS (#5160)
- append results to an existing layer (#5241)
Instead of trying to update each individual alg output with correct options/text, this first-step PR proposes to rely on the sphinx `.. include::` role, ie set the (variants of)text in [one place](https://github.com/qgis/QGIS-Documentation/compare/master...DelazJ:processingOutputtypes?expand=1#diff-2e852d3e2a90789ba4798c61b3b1aafc7e9c49f251ba5d82c488917089a64a3a) and call them in the algs. This way, descriptions are harmonized, can be easily extended/updated and doing this helped fix some incoherence.
~~Only covered the PostGIS --> DB rename. A follow-up PR for the Append.~~ Both covered now.
> Factorize the Processing output types list description

- docs/user_manual/processing_algs/qgis/vectorgeometry.rst
Goal:
Fixes Convert geometry type, Lines to polygons, Polygonize and Polygons to lines tools documentation.
Ticket(s): https://github.com/qgis/QGIS/issues/44779
> Fix some geometry conversion tools

- docs/pyqgis_developer_cookbook/cheat_sheet.rst
- docs/pyqgis_developer_cookbook/plugins/snippets.rst
Remove examples that do not necessarily belong to plugin development (and which are better served in other place)
This "Plugin development" chapter deserves more fixes/updates to current best practices... "knowers"...?
> Simplify the plugins snippets page

- docs/server_manual/services.rst
TEMPLATE parameter is required : https://docs.qgis.org/3.16/fr/docs/server_manual/services.html#getprint
It should be backported.
> template parameter is required for GetPrint request

- docs/server_manual/config.rst
The following ENV vars had wrong default values in the docs
QGIS_SERVER_LANDING_PAGE_PROJECTS_PG_CONNECTIONS
QGIS_SERVER_LANDING_PAGE_PROJECTS_DIRECTORIES
QGIS_SERVER_LOG_PROFILE
> Fix some server ENV variables default values

- docs/user_manual/working_with_vector/functions_list.rst
until we find how to render the list in multicolumns instead of a single long one (and we usually do not display local toc).
Fixes this kind of rendering (do not check the array's or geometry's)
> Hide the list of functions in the PDF build

- docs/user_manual/processing_algs/qgis/interpolation.rst
This is just a quick fix of the algorithm ID for the Line Density algorithm. The algorithm is native - not a python implementation. 
Goal: fix the broken algorithm ID of Line Density
> fix Line Density algorithm ID

- docs/user_manual/print_composer/composer_items/composer_map.rst
Fixes #5454
also remove left-over from old GUI in the Extents group
> Expose the layout map item's temporal range properties

- docs/documentation_guidelines/writing.rst
Goal:
Specify the indentation behaviour of QGIS documentation. This had me confused for some time while working on my own derived tutorial. I may have over-done it a little bit, and am willing to shorten :)
Ticket(s): None yet
> added section on indentation/whitespace

- docs/user_manual/working_with_vector/editing_geometry_attributes.rst
Attempt to write clearer documentation for the stream digitizing and digitize with curve (fixes #7044)
https://github.com/qgis/QGIS-Documentation/issues/7044#issuecomment-963819748
Goal:
Ticket(s): #
> Update curve and stream digitizing tools description

- Makefile
possible now that the PyQGIS 3.22 docs is released
reverts 017c31f2
> [release_3.22] Reinstate nitpicking checks for docs build

- docs/user_manual/introduction/qgis_configuration.rst
(it's not part of the API section) and use a less complex URL
> Fix indentation for github access token feature

- docs/user_manual/processing_algs/qgis/vectorgeneral.rst
Goal:
Fixes the "Delete duplicates by attribute" (https://github.com/qgis/QGIS/commit/4e9da6f1906c6ba6076742e9aa3d49bebd1965b6 - https://github.com/qgis/QGIS/pull/8355) algorithm ID.
The correct algorithm ID is "removeduplicatesbyattribute".
See https://github.com/qgis/QGIS/blob/22c16f206778b80571479985e59f44c34b1ae0a7/src/analysis/processing/qgsalgorithmremoveduplicatesbyattribute.cpp#L22-L30
This PR needs to be backported to 3.16 and 3.22 branches.
> Fix "Delete duplicates by attribute" algorithm ID

- docs/user_manual/processing_algs/qgis/vectorgeneral.rst
Goal:
Fixes the "Detect dataset changes" algorithm ID. The correct algorithm ID is "detectvectorchanges".
See [master](https://github.com/qgis/QGIS/blob/47fde44198727f8145551ccf5ec0cced802ad248/src/analysis/processing/qgsalgorithmdetectdatasetchanges.cpp#L24-L32), [3.16](https://github.com/qgis/QGIS/blob/release-3_16/src/analysis/processing/qgsalgorithmdetectdatasetchanges.cpp#L24-L32), [3.22](https://github.com/qgis/QGIS/blob/release-3_22/src/analysis/processing/qgsalgorithmdetectdatasetchanges.cpp#L24-L32).
This PR needs to be backported to 3.16 and 3.22 branches.
> Fix "Detect dataset changes" algorithm ID

- docs/user_manual/managing_data_source/opening_data.rst
Wanted to upgrade the XYZ tab, but was up to date, just the
"tilePixelRatio" in the .xml File was missing (for the TileResolution).
I guess we can close #5284 ?
Goal:
Ticket(s): #
> XYZ - added tilePixelRatio to xml

- docs/user_manual/working_with_mesh/mesh_properties.rst
Introduce the different types of mesh structure, stating that QGIS supports any of them
Remove the outdated list of supported formats
Update mesh symbology with 1D mesh particularities (fixes #4988, fixes #5343)
> Update mesh description with 1D mesh particularities

- docs/user_manual/introduction/getting_started.rst
fixed the name of projection Alaska Alber<b><strike>t</strike></b>s
Ticket(s): #
> Fix typo in Getting Started

- docs/user_manual/working_with_raster/raster_properties.rst
Goal:
Fixes the "Input downscaling" default value in Raster Properties Dialog - Raster Symbology - Contours rendering, changing it from `1.0` to `4.0`.
See https://github.com/qgis/QGIS-Documentation/pull/6538#discussion_r771754355
See https://github.com/qgis/QGIS/blob/6fbb4e8c88e283ad46036e8d90857d7b2c8bf0ea/src/ui/qgsrastercontourrendererwidget.ui#L130-L140
Ticket(s): #
> Fix Input downscaling default value in Raster Properties Dialog - Raster Symbology - Contours rendering

- docs/user_manual/managing_data_source/opening_data.rst
fixes #6174
The open options also work with raster layers, so expanded the
note-information.
Didnt documented the URI Options yet. Thought about documenting it in: https://docs.qgis.org/3.16/en/docs/pyqgis_developer_cookbook/loadlayer.html
?
Goal:
Ticket(s): #
> GDAL open options

- docs/user_manual/managing_data_source/create_layers.rst
To prevent further confusing in regards to the use of the parameter, here is a proposal to improve the doc.
Fix #7282
> [Export layer] document extent parameter

- docs/user_manual/managing_data_source/supported_data.rst
Added a Tip to the PostGIS layers section.
It is documented in the "Working with Project Files" section (
https://docs.qgis.org/testing/en/docs/user_manual/introduction/project_files.html
) that one can save projects to a postgresql database, but i felt like
if the user is looking for postgis data information, its good to know
that you can also save project files there and that it is unlikely that
one will also check the "working with Project Files"-section in that
process.
Thoughts?
Goal:
Ticket(s): #
> Save QGIS project in PostgreSQL

- docs/user_manual/processing_algs/qgis/rasteranalysis.rst
Line 1735 : "feature the highest value," should probably be "feature the lowest value," since the algorithm is "lowestpositioninrasterstack" and not "highestpositioninrasterstack"
Ticket(s): #
> Error corrected

- docs/user_manual/introduction/browser.rst
- split different options into rows, with label fix
Before:
After
- allows better columns display for the PDF output
Before
After
> Formatting of tables in browser chapter

- conf.py
because the versions have diverged a lot and opening an unexpected/modified page (if still existing) can be confusing
> Do not open master branch when trying to update from 3.16

- .github/workflows/auto-label.yml
Issue reports created from the code repo are not automatically assigned a version label. Seems that Naturalclar/issue-action has modified its syntax sometime ago (https://github.com/Naturalclar/issue-action#example)
> Use correct syntax for the issue auto-label script

- docs/pyqgis_developer_cookbook/server.rst
Update QgsServerFilter documentation according to https://github.com/qgis/QGIS/pull/45158
Also fix some errors about how QgsServerFilter callbacks are called during the processing of the response.
> Fix/Update QgsServerFilter cookbook documentation

- docs/training_manual/complete_analysis/analysis_exercise.rst
Goal: Update instructions for aligning rasters in training manual exercise 8.4. Instruct users to use the Warp (reproject) tool rather than 'save>export' from the ToC.
Ticket(s): fix  #7342
> update instructions for aligning rasters

- docs/user_manual/style_library/symbol_selector.rst
- docs/user_manual/working_with_vector/vector_properties.rst
- static/common/rendererMergedFeatures.svg
Fixes #6421 Fixes #6571 Fixes #6692 Fixes #6715 Fixes #6790  Fixes #6948
Proposal to update the vector symbology sections. 
Images still need to be added.
> Vector symbology batch update

- docs/user_manual/style_library/symbol_selector.rst
> Add back the option to control point pattern fill rotation

- docs/training_manual/create_vector_data/forms.rst
Line 38:  "|options| sup:`Identify Settings` menu." should be: "|options| :sup:`Identify Settings` menu." Placed colon before "sup:" to let the proper format reflect on the page.
> Typo prevents proper format

- docs/user_manual/introduction/qgis_gui.rst
Line 837 : ":menuselection:`-->` :guilabel:`Toogle Selected Layers Independently`" ==>  should probably be: ":menuselection:`-->` :guilabel:`Toggle Selected Layers Independently`"
Line 2134 :  "and |zoomIn| :sup:`Zoom Out`"  ==> should probably be : "and |zoomOut| :sup:`Zoom Out`"  (|zoomIn| used two times )
Line 2279 :  "This is useful is" ==> should probably be: "This is useful if"
Line 2293:  "Using the close |refresh| button" ==> should probably be : "Using the refresh |refresh| button"
line 2321 : "Keeping the |refresh| :sup:`Loop` button pressed" ==> should probably be : "Keeping the |unchecked| :sup:`Loop` box checked", because this "button" seems to be a "checkbox" instead
Line 2769 : "Keeping the :guilabel:`Loop` button checked will" ==> should probably be : 
""Keeping the …
> Some typo's and display

- docs/server_manual/services/wms.rst
Line 180 :  ":menuselection:`OWS Server --> WMS capabilities` menu" ===> should probably be ":menuselection:`QGIS Server --> WMS` tab"
> Changed menu name

- docs/pyqgis_developer_cookbook/plugins/plugins.rst
Explain where those plugin names come from, since a dev could be confused on where to get them from (metadata.txt's name field vs. plugin's Python module name).
See how confusing is this at: https://lists.osgeo.org/pipermail/qgis-developer/2022-March/064643.html
> More details on how to declare plugin dependencies

- docs/server_manual/plugins.rst
* Improve the documentation about QGIS Server plugins
* Mention qgis-plugin-manager, is this tool ok in the official documentation ? It's not hosted/developed under the GitHub QGIS repository.
> Server plugins - improve the plugin section and mention a CLI helper tool

- docs/user_manual/working_with_vector/vector_properties.rst
Line 3193 : "by the :guilabel:`Start expression` and :guilabel:`End expression` "  ==>> should probably be: "by the fields :guilabel:`Start expression` and  :guilabel:`End expression` "
--->
> Typo, added "fields" to sentence

- docs/index.rst
Another manual change that we missed.
I wonder if the version number is really necessary here...
> Display correct version of docs

- docker-world.sh
- docs_conf.yml
Currently:
1. If you click on "zh_Hans" in the bottom left menu of https://docs.qgis.org/3.22/en/docs/index.html, it should open https://docs.qgis.org/3.22/zh_Hans/docs/index.html (as shown when hovering over the entry), but it instead opens https://docs.qgis.org/en/docs/index.html. This is because on the server, "zh_Hans" (with underscore) is  not listed among served languages and redirects to default "en"
1. If you instead write https://docs.qgis.org/3.22/zh-Hans/docs/index.html (note the hyphen), you get the correct url page (because the server exposes "zh-Hans" language) but the docs appears in English. I assume it's because the build folder is not filled with correct strings (an issue with symlink?)
Considering that https://docs.qgis.org/3.22/zh-Hans/docs/index.html was providing …
> Fixing Simplified Chinese build (take 2)

- docs/user_manual/working_with_vector/editing_geometry_attributes.rst
Line 1341 : "the longest line feature the largest polygon" should probably have a comma in it between "feature"and "the" and should probably read: "the longest line feature, the largest polygon"  (added comma}
> One tiny typo

- docs/user_manual/processing_algs/qgis/rasteranalysis.rst
Line 338 : "cell stack percentrank from raster layer" should be "Cell stack percentrank from raster layer"as it addresses the title of the algorithm
> Capital C instead of lower case

- docs/user_manual/working_with_vector/vector_properties.rst
Line 3192 : ":guilabel:`Sart`" should be:  ":guilabel:`Start`"
> Missing letter "t"

- docs/user_manual/introduction/qgis_configuration.rst
Line 1313 : "at the same place" --> misses a dot at the end of the sentence. Added the dot, so it reads: "at the same place."
Line 1634 : "The guilabel:`Customization` dialog" missed a colon before "guilabel:" so it broke formatting. Added the missing colon, so all should be fine now with "The :guilabel:`Customization` dialog"
> Missing dot and colon

- docs/developers_guide/qtcreator.rst
I think this is the right link. Although It is a gitub .md file and not html like the original link. fix https://github.com/qgis/QGIS-Documentation/issues/7490
Goal:
Ticket(s): #
> Broken link fix

- docs/user_manual/processing_algs/qgis/vectorgeometry.rst
Goal: Add Missing Edit in place documentation for Affine, Covert To Curved Geometries, Extract Specific Vertices, Extract Vertices, Force Right Hand Rule, Geodesic Line Split at antimeridian and, Split by max length.
Ticket(s): fix #7487
> Edit in place missing checkboxes and text

- docs/user_manual/processing_algs/qgis/vectoroverlay.rst
Adding supported geometry types to edit in place text in the vector overlay tools.
Goal:
Ticket(s): #
> Vector Overlay Edit in Place Updates

- conf.py
- docs_conf.yml
First step towards a single list of languages as requested in #7452; at least now we can simply copy-paste from one variable to the other(s).
*Question*: Should I align the version list to this? mainly for homogenization purpose (for the list and the split call)
> Separate the supported_languages list with space instead of comma

- docs/user_manual/processing_algs/gdal/rasterextraction.rst
Goal:
The "[Clip raster by extent](https://docs.qgis.org/3.22/en/docs/user_manual/processing_algs/gdal/rasterextraction.html#clip-raster-by-extent)" algorithm is derived from the GDAL translate utility, not from the GDAL warp utility as currently stated in the docs.
See: https://github.com/qgis/QGIS/blob/2d1aa68f0d044f2aced7ebeca8d2fa6b754ac970/python/plugins/processing/algs/gdal/ClipRasterByExtent.py#L117
Ticket(s): #
> Fix "Clip raster by extent" algorithm docs

- docs/user_manual/processing_algs/algs_include.rst
- docs/user_manual/processing_algs/qgis/vectoroverlay.rst
so that we can reuse the full warning text in algs instead of pointing to a not working URL. The URL is indeed not operational in translated documentation (try [en](https://docs.qgis.org/3.22/en/docs/user_manual/processing_algs/qgis/vectoroverlay.html#warning-difference) vs [fr](https://docs.qgis.org/3.22/fr/docs/user_manual/processing_algs/qgis/vectoroverlay.html#warning-difference), clicked from any "see warning" url in the page).
>  Move the overlay algs "attributes modification warning" to the include file

- conf.py
- docs/pyqgis_developer_cookbook/cheat_sheet.rst
Fix the crash locally, note that the root cause of the crash was a serious bug recently introduced in QGIS.
This is the third time that a failure in the doctests helped to discover a crash in QGIS.
> Workaround for https://github.com/qgis/QGIS/issues/48670

- docs/user_manual/introduction/general_tools.rst
- docs/user_manual/introduction/qgis_gui.rst
> Using right term: embedding layers from external projects #7428

- docs/user_manual/processing_algs/algs_include.rst
The algs_include file "is not published" in the docs, so there is no point in translating unnecessary strings (those are there to help file editors and catch the include calls)
Goal:
Ticket(s): #
> Comment out cosmetic strings to avoid them in Transifex

- docs/user_manual/processing_algs/qgis/vectorgeneral.rst
Goal:
The `FILE_TYPE` parameter of the "Split vector layer" (`native:splitvectorlayer`) algorithm is optional: see [[needs-docs] add optional parameter for output file type to the vector split algorithm](https://github.com/qgis/QGIS/commit/b99fe4e51f2cd79ad8922e765ad4d7125216259e) and [[processing] Fix FILE_TYPE parameter of the "Split Vector Layer" native algorithm](https://github.com/qgis/QGIS/pull/48781).
What is the best way to specify that the default for the `FILE_TYPE` parameter when the algorithm is executed from the GUI is 'gpkg' and when the algorithm is executed using Python it is the "Default output vector layer extension" set by the user in the Processing settings if available or it fallback to 'gpkg'?
Ticket(s): #
> Fix FILE_TYPE parameter in "Split vector layer"

- README.md
Goal: The correct package for otf fonts is fonts-freefont-otf but the original doc had a spelling error with font-freefonts-otf. This has been corrected
Ticket(s): #
> Correct spelling font-freefonts-otf to fonts-freefont-otf

- docs/user_manual/processing_algs/qgis/vectorgeometry.rst
Goal:
Adds the "Offset" parameter to the "Drape (set Z value from raster)" (`native:setzfromraster`) and "Set M value from raster" (`native:setmfromraster`) processing algorithms.
Ticket(s): https://github.com/qgis/QGIS/pull/48772
Fixes https://github.com/qgis/QGIS-Documentation/issues/7641.
> Add "Offset" parameter to the "Drape" algorithms

- docs/server_manual/services/wfs.rst
@pblottiere https://github.com/qgis/QGIS-Documentation/commit/1906446b35efc776ff3138d3ed5cd6d09eb0fce5
This commit should be backported.
> Server - Use "none" instead of "bash" for GEOMETRYNAME

- docs/pyqgis_developer_cookbook/loadproject.rst
As mentionned this is a quick PR to add information about flag usage when reading a project in pyqgis.
This might not be common, but I think it's good to have it out here.
Fixes #7634
> add flag info

- docs/user_manual/introduction/general_tools.rst
Goal: Fixes #7171
Ticket(s): #
> Allow text buffer size, shadow offset and radius to be set in "percentage" units

- docs/user_manual/processing/toolbox.rst
Replace "allow" (allows) for "allowing..."
> Rephrase to cover a typo in Processing-->Toolbox page

- docs/user_manual/style_library/symbol_selector.rst
Marker/hash line: allow offset along line in percent, and negative offsets along line  (fixes #7207):
Text updated
Goal:
Ticket(s): #
> Marker/hash line: allow offset along line in percent, and negative offsets along line  #7207

- docs/pyqgis_developer_cookbook/plugins/plugins.rst
@Gustry @m-kuhn @3nids  Following the qgis-plugin-ci nice presentation today, I propose to add it to the documentation tips and tricks next to the minimal plugin and qgis3 builder. 
Does it look goo to you?
> adds qgis-plugin-ci to plugins tips and tricks

- docs/server_manual/containerized_deployment.rst
Deeper update than #7719
- Switch to Debian Bullseye (buster is oldstable)
- Do not use apt-key which will be deprecated in next Debian release.
- Add comment for qgis version (LTR, nightly, master, ...)
- Update tiny version
> Update Dockerfile for containerized deployment of qgis-server

- docs/server_manual/getting_started.rst
> Use link to NGINX docs page instead

- docs/user_manual/processing_algs/qgis/rasterterrainanalysis.rst
Goal:
The "Slope" QGIS algorithm has the following line in the description:
`In the following picture you can see to the left the DTM layer with the elevation of the terrain while to the right the calculated slope:`
Anyway, the picture only shows the slope and not the DTM.
I propose to remove the whole line. Alternatively the line could be rewritten as:
`In the following picture you can see the calculated slope:`
Ticket(s): #
> Fix the "Slope" QGIS algorithm map description

- docs/user_manual/introduction/general_tools.rst
- docs/user_manual/introduction/qgis_configuration.rst
- docs/user_manual/introduction/qgis_gui.rst
moving duplicate global rendering options in general tools to configuration page and removing outdated options
Also adjust list formatting as well as the map rendering features on the status bar
While a step towards #7811 this pr mainly starts the cleanup of the [working with map canvas](https://docs.qgis.org/testing/en/docs/user_manual/introduction/general_tools.html#working-with-the-map-canvas) section
> Expand description of the global rendering settings

- docs/training_manual/foreword/foreword.rst
The contact addresses in the foreward are old and no longer relevant. @DelazJ maybe we should rework this forward - it is nice to keep the history but it would be good to acknowledge others who have contributed to the manual too.
> Fix email addresses

- docs/user_manual/working_with_mesh/mesh_properties.rst
refs #6883, refs qgis/QGIS#45140
Completes #7729
> Explain how Z values are asssigned to mesh elements

- docs/user_manual/processing_algs/qgis/cartography.rst
Goal:
Fixes the capitalisation of the `FORCE_RASTER` parameter description in the "Export print layout as PDF", "Export atlas layout as PDF (multiple files)" and "Export atlas layout as PDF (single file)" processing algorithms and the the `FORCE_RASTER` parameter Type in the "Export print layout as PDF" processing algorithm.
Ticket(s): #
> Fix some typos in the FORCE_RASTER parameter (Export print/atlas layout as PDF)

- docs/user_manual/expressions/expression_help/Arrays.rst
- docs/user_manual/expressions/expression_help/GeometryGroup.rst
- docs/user_manual/expressions/expression_help/img/images_list.json
and fully fix array_get syntax (#7814)
Goal:
Ticket(s): #
> Add more images to expressions examples

- docs/user_manual/style_library/symbol_selector.rst
Goal:
It is possible to specify a Raster image marker or an SVG marker as a base64 string (in the form `base64:` followed by the base64 encoded imgage).
This is useful when the user wants to use an image/svg stored in a BLOB field as a Raster image / SVG marker just using the Data Defined Override expression `'base64:' || to_base64("blob_image_field")`.
See thread at https://github.com/qgis/QGIS-Documentation/pull/4641/files#r1000413560.
Ticket(s): #
> Base64 string for Raster image marker and SVG marker symbologies

- docs/user_manual/introduction/general_tools.rst
- docs/user_manual/introduction/qgis_gui.rst
Simplifies instructions, removing columns with all rows checked
One more step towards #7811 
Goal:
Ticket(s): #
> Merge map canvas navigation descriptions into the "map view" section

- docs/pyqgis_developer_cookbook/vector.rst
Fixes HTML build after https://github.com/qgis/QGIS/pull/50854
> Fix mapTipTemplate class name

- docs/pyqgis_developer_cookbook/raster.rst
Fixes doctest build (https://github.com/qgis/QGIS-Documentation/actions/runs/3752875442/jobs/6375530260#step:6:571), probably an api change
> Fix raster type output

- docs/user_manual/working_with_ogc/ogc_client_support.rst
For future reference: explanations from @jef-n:
* The tile size limits the request size.  the wms provider splits bigger requests into smaller ones of that size (to meet the wms server non-advertised limits).  by default there is no limit.   raster iterators produce requests (not only for wms) of 2000x2000 by default - and you can change that for wms to something higher to reduce cutting labels (as in redmine #16182 aka gh #24092)
* tile size just make the wms provider split the request.  and step size changes the default for the iteratators (not sure if those do overlapping requests)
* The iterator was written by Marco Hugentobler back in 2012
Goal:
Ticket(s): #
> Explain WMS request step size, fixes #1703

- docs/pyqgis_developer_cookbook/composer.rst
- docs/user_manual/print_composer/create_output.rst
* Mention automatic predefined layouts validity checks (fixes #3350)
* Add code samples for running various layout validity checks (fixes #3351, fixes #3291)
> Running Validity checks when exporting layout

- .github/workflows/pofiles.yml
- REQUIREMENTS.txt
- conf.py
Goal:
Add the [sphinx_copybutton](https://sphinx-copybutton.readthedocs.io/en/latest/index.html) extension in order to facilitate the code copy of the cookbook.
> Add sphinx_copybutton extension

- docs/user_manual/style_library/label_settings.rst
refs qgis/QGIS#50848
Goal:
Ticket(s): #
> Superscript and subscript HTML tags are also supported

- docs/user_manual/preamble/help_and_support.rst
The section in the documentation about help and support links to the IRC channel at Freenode, a network that doesnt exist anymore. 
I see on https://qgis.org/en/site/forusers/support.html that the channel has moved and the documentation should be updated
> Update help and support - IRC section

- .github/workflows/builds.yml
- .github/workflows/doctest.yml
- .github/workflows/pofiles.yml
- .github/workflows/translation_statistics.yml
Fixes warnings like the following:
https://github.com/qgis/QGIS-Documentation/actions/runs/4003246598
> [gh-actions] Update actions/setup-python for workflows

- docs/pyqgis_developer_cookbook/plugins/plugins.rst
e.g. moved section on resource files to less prominent section since they are not mandatory.
These doc pages are still missing information about different plugin types, such as Processing algorithm provider plugins vs. regular plugins with toolbar button and/or dialog/panel. 
Goal:
Ticket(s): #
> Restructuring plugin dev docs

- Makefile
If you look at https://docs.qgis.org/3.22/pdf/ja/, you'll notice that Japanese PDF builds are broken. I don't know the root cause but switching the compiler to the default one (https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-latex_engine) fixes the issue (see [GitHub action output](https://github.com/DelazJ/QGIS-Documentation/actions/runs/4158642826))
> Replace platex with uplatex for japanese PDF build

- docs/user_manual/processing_algs/qgis/vectorgeneral.rst
Goal:
The OPERATION parameter of the "Reproject layer" algorithm (native:reprojectlayer) is an advanced parameter.
Ticket(s): #
> [Processing] "Reproject layer" alg: OPERATION is an advanced parameter

- docs/pyqgis_developer_cookbook/server.rst
I think something is wrong in the structure of the sections of the [server page in Cookbook](https://docs.qgis.org/3.28/en/docs/pyqgis_developer_cookbook/server.html). I tried to fix based on my understanding but I'm not sure whether the "Exception" section should be part of the "Writing" one.
Also, if anyone has a suggestion to lower the number of levels in the TOC, it would be really great!!!
Left (before), right (PR)
> Adjust the table of content and fix some texts

- docs/developers_guide/unittesting.rst
- docs/training_manual/create_vector_data/actions.rst
- docs/training_manual/foreword/foreword.rst
- docs/user_manual/working_with_vector/vector_properties.rst
Add "submit url ..." action types (refs https://github.com/qgis/QGIS/pull/46384)
Add "form" scope (fixes #7624)
Use macOS instead of Mac, MacOS or Mac OS X (partly refs https://github.com/qgis/QGIS/pull/51484)
and various formatting cleanup
> More update and cleanup for vector layer actions

- docs/user_manual/preamble/translation_stats.rst
- scripts/load_tx_stats.py
to avoid having to translate them at every iteration
Every week we pull percentage of translation of each language from Transifex to display in docs. Because these values regularly change, they generate new strings to translate in Transifex. For languages that have already reached 100% of translation (kudos to nl, es and it) it is a bit unfortunate IMHO to have to retranslate every time these numbers (or their stats regress).
This PR proposes to use substitutions instead of numbers. We "translate" substitutions, and the values changing is transparent for us. The only thing I see is that numbers will be displayed for all with English locale, but not a big deal IMHO.
@DiGro, opinions?
Goal:
Ticket(s): #
> Store translation statistics inside substitutions

- docs/training_manual/forestry/forest_maps.rst
removes misused :kbd:, reference to page printing
This is an unfinished work as the screenshots need update (from 2.x period) and some actions can be better achieved today with newer/dedicated tools. But the branch went stale a couple of times so better share the basic improvements than keeping old misleading/confusing instructions
> [TM] Update formatting and instructions in forest_maps exercise

- docs/user_manual/style_library/label_settings.rst
The table showing the difference between text and label settings was not correct.
Goal:
Ticket(s): #
> Shadow not Mask part of Text

- .github/workflows/translation_statistics.yml
It used to fail due to branch protection; let's then create a pr and auto-merge it to master
There might be a straighter approach but this one might work also (kind of tested on my repo)
> Auto-pull translation statistics to master branch

- docs/user_manual/map_views/map_view.rst
There is a |refresh| button on temporal navigation panel but for different use. _Loop_ is a checkbox.
> Fix Loop checkbox in temporal navigation

- .github/workflows/auto-label.yml
- .github/workflows/backport.yml
- .github/workflows/builds.yml
- .github/workflows/doctest.yml
- .github/workflows/pofiles.yml
- .github/workflows/pull_minimized_translations.yml
- .github/workflows/stale.yml
- .github/workflows/translation_statistics.yml
[Apply security best practices to actions (inspired by https://github.com/qgis/QGIS/pull/49188 and done using https://app.stepsecurity.io/)
- Restrict permissions for GITHUB_TOKEN
- Add security agent for Github hosted runner
- Pin actions to a full length commit SHA
- I had to guess and apply some changes in backport and autolabel workflows as the actions we relied on are unknown by the service
Also raise Python version in actions to 3.9 and various cleanup.
Not 100% understanding (nor did I test) all the changes here so we'd need to monitor the repo behavior after this is merged. And of course, feedback/review welcome.
> Consolidating github actions with best practices

- conf.py
Fixes #8244 (based on [html_last_updated_fmt](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_last_updated_fmt))
Goal:
Ticket(s): #
> Indicate time zone offset next to page build time

- docs/training_manual/spatial_databases/spatial_queries.rst
Goal: The main purpose of this pull request is to fix an error in the QGIS training manual. The error is that the manual refers to a PostGIS function called ```TOUCHES```, but there is no such function. The correct function is ```st_touches```.
Ticket(s): #
> 📝 corrected postgis function

- docs/user_manual/processing/3rdParty.rst
Goal: remove references the the OTB plugin "Activate" option: it no longer exist since QGIS 3.22: https://github.com/qgis/QGIS/commit/f3d494abe6854ab498834b012a6f8f4efb1c2807#diff-50e42408a88dce497dd6358366d0144127d91500a98241528472e56b230490c2L54
Ticket(s): #
> OTB plugin: remove references to the "Activate" option

- Makefile
#8181 reminds me of this branch I worked on some time ago to simplify PDF make commands. It should output same structure as today, just in a fewer lines.
I'd appreciate double-checks. @rduivenvoorde @SrNetoChan ?
(Ideally we should use the one-line [-M latexpdf](https://www.sphinx-doc.org/en/master/usage/builders/index.html#sphinx.builders.latex.LaTeXBuilder) call but I locally failed to have clean output with Japanese - maybe did I not have all the dependencies? I didn't find such a detailed page on the dependencies at that time).
Goal:
Ticket(s): #
> Simplify makefile instructions for PDF outputs

- conf.py
Avoids redundant QGIS string in some docs output file name (QGIS-testing-**QGIS**ServerUserGuide-en.pdf instead of QGIS-testing-ServerUserGuide-en.pdf)
complements #8189 
Goal:
Ticket(s): #
> Normalize pdf output file name by removing QGIS prefix

- docs/server_manual/services/ogcapif.rst
Describe undocumented behaviour of OGC API Features:
- add prefix that is typically used: `/wfs3`
- mention the existence of CRUD functionality
> QGIS Server: OGC API Features updates

- docs/training_manual/complete_analysis/analysis_exercise.rst
Fixes #8317
Goal:
Ticket(s): #
> [TM] Line, not fill, for linestring features symbology

- docs/user_manual/processing/modeler.rst
follow-up https://github.com/qgis/QGIS-Documentation/pull/8349
> "Reorder Output Layers..." is only located in the "Model" menu

- docs/server_manual/services/wms.rst
It is FORMAT_OPTIONS not FORMAT-OPTIONS
Goal:
Ticket(s): #
> Fix typo in WMS GetMap parameter

- docs/user_manual/processing_algs/qgis/rastertools.rst
Goal: Add documentation for qgis/QGIS/pull/53674 (fixes #8370)
(retake of #8365 )
> Add antialias setting to raster tile processing plugin

- docs/documentation_guidelines/substitutions.rst
- docs/user_manual/introduction/qgis_gui.rst
- docs/user_manual/map_views/elevation_profile.rst
- docs/user_manual/map_views/index.rst
- docs/user_manual/working_with_mesh/mesh_properties.rst
- docs/user_manual/working_with_point_clouds/point_clouds.rst
- docs/user_manual/working_with_raster/raster_properties.rst
- docs/user_manual/working_with_vector/vector_properties.rst
* Restructure the elevation profile chapter, fixing typos and duplicates and following this sequence (left: current, right: PR)
* Move up the Elevation chapter in the index as a transitional chapter between 2D and 3D views
* Add connections to the other chapters that should reference the profile tool
* Report icons to the guidelines substitutions
Goal: Fixes #7485, fixes #7500, fixes #7507, fixes #7523, fixes #7531, fixes #7544, fixes #7546
Ticket(s): #
> More updates to the Elevation Profile view

- docs/user_manual/introduction/project_files.rst
In my opinion term ''Georeferencing'' can be misleading in this chapter. Georefernce information seems like a better choice of words/terms.
> Term Georeferencing replaced with Georeference information in section 6.3.

- docs/user_manual/introduction/project_files.rst
In chapter Working with Project Files section 6.1. updated database implementation ( added Oracle, GeoPackage where they were missing).
> Added missing databased Implementation in section 6.1.

- docs/user_manual/introduction/qgis_gui.rst
- docs/user_manual/processing/modeler.rst
Goal:
Continuation of #8418 now that the processing menu entry called "Graphical Modeler..." has been changed to "Model Designer..." in https://github.com/qgis/QGIS/pull/54015
NO BACKPORTING to 3.28 branch
Ticket(s): #
> Rename processing menu to model designer

- .github/workflows/translation_statistics.yml
PAT only valid for a year, it's not possible to create a longer one
Goal:
Ticket(s): #
> Use bot with PAT to update statistics

- docs/user_manual/map_views/elevation_profile.rst
- docs/user_manual/map_views/map_view.rst
I think it will make these videos more visible in the docs (only rendered in HTML version). Example for the elevation profile
Opinions welcome...
> Also display reference videos inside a frame

- docs/server_manual/services/ogcapif.rst
- docs/user_manual/working_with_ogc/ogc_client_support.rst
fixes #8398 Added support for edition capabilities (OGC API Features Part 4). Is this paragraph added in the right position in a document?
> Added support for edition capabilities for issue #8398

- docs/pyqgis_developer_cookbook/geometry.rst
After d3b7b6047c9156d4fe7138f06385f0a0bd76ca7f by @SrNetoChan and @arongergely, only the distance is calculated.
Another approach would be to add the bearing calculation.
https://docs.qgis.org/3.28/en/docs/pyqgis_developer_cookbook/geometry.html#:~:text=Alternatively%2C%20you%20may%20want%20to%20know%20the%20distance%20and%20bearing%20between%20two%20points.
Goal:
Ticket(s): #
> Fix geometry.rst

- docs/user_manual/processing_algs/gdal/rasteranalysis.rst
- docs/user_manual/processing_algs/qgis/cartography.rst
- docs/user_manual/processing_algs/qgis/modelertools.rst
- docs/user_manual/processing_algs/qgis/rasteranalysis.rst
- docs/user_manual/processing_algs/qgis/vectoranalysis.rst
- docs/user_manual/processing_algs/qgis/vectorcreation.rst
- docs/user_manual/processing_algs/qgis/vectorgeneral.rst
- docs/user_manual/processing_algs/qgis/vectorgeometry.rst
The idea is to move from left to right (as done for expression functions), hopefully leading to a more usable/readable TOC and less scrolling
Groups that have more than 10 algorithms available have their algs list split
> Split long local list of algorithms into columns

- docs/server_manual/config.rst
* Fix https://github.com/qgis/QGIS-Documentation/issues/8147 `QGIS_SERVER_CAPABILITIES_CACHE_SIZE`
* Linked to https://github.com/qgis/QGIS-Documentation/issues/8168 `QGIS_SERVER_APPLICATION_NAME`, I'm not sure if we describe other part of this PR. But at least, the server part is done. I think it's OK like this, it's quite an advanced usage.
Follow up previous PR #8237 which was closed by the stale bot.
> Add 2 new env variables about QGIS server

- README.md
For me the instructions `## Build on Linux` are not working. I didn't searched why but I noticed that the `Linux & MacOs` instruction are working.
So I thought it makes sense to put them first in the README as they are more generic.
Maybe the "Linux only" way of building can be completely removed as it is redundant? Or it bring some more value?
> Put more generic build instructions first

- docs/user_manual/processing_algs/qgis/vectorgeneral.rst
Goal:
In https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/qgis/vectorgeneral.html#assign-projection and https://docs.qgis.org/3.28/en/docs/user_manual/processing_algs/qgis/vectorgeneral.html#assign-projection the OUTPUT parameter is incorrectly described as "Specify the output layer containing only the duplicates."
Ticket(s): #
> Fix Assign Projection alg description of OUTPUT parameter

- docs/server_manual/containerized_deployment.rst
Goal: Fix non-working examples for containerized deployment of QGIS Server.
The current documentation on containerized deployment includes some steps that if followed, will not work. Such as:
- `kubectl apply -k` will expect to have a kustomization.yaml file that is nowhere present in the documentation. The way of applying the deployments in this case would be `kubectl apply -f`.
- I have also added a ConfigMap for the NGINX configuration. In the current version, the nginx.conf file would not be accessible if the deployment is done outside of a local cluster.
> QGIS server containerized deployment

- docs/user_manual/working_with_vector/vector_properties.rst
It looks weird to have those information appear far away, next to quite different widgets
Goal:
Ticket(s): #
> Move tip on attachment widget close to the widget description

- docs/user_manual/style_library/symbol_selector.rst
Adds the missing documentation for the stroke and fill opacity parameters
> Add fill/stroke opacity parameters for SVG parameters

- docs/user_manual/working_with_vector/vector_properties.rst
Given that not all the options are in groups and only groups are put as subsection, the [Rendering section](https://docs.qgis.org/3.28/en/docs/user_manual/working_with_vector/vector_properties.html#rendering-properties) structure can be misleading (e.g. is "force layer to render" an option of "simplify geometry"?). Let's use bullet points instead of subsections. Almost no text changes, mainly indentation and sentence split.
Also reorder options to match the GUI.
> Remove subsections from Vector Rendering properties section

- docs/user_manual/print_composer/composer_items/composer_map.rst
> Clarify what the grid interval type refers to

- docs/user_manual/processing_algs/qgis/modelertools.rst
> Calculate expression added to modeler tools

- docs/server_manual/getting_started.rst
Ticket(s): #
Goal:
In current installer for server default path for Windows C:\OSGeo4W\ instead of C:\OSGeo4W64, it may be a bit confusing to config server for new user, fixed to actual C:\OSGeo4W\
> fixed default install path

- docs/user_manual/working_with_vector/editing_geometry_attributes.rst
Goal:
Fixes the "Circle by a center point and another point" tool name.
https://github.com/qgis/QGIS/blob/5cde6a9349f4b2c6d431859cb9ec9755bcd172fb/src/app/maptools/qgsmaptoolshapecirclecenterpoint.cpp#L33
Ticket(s): #
> Fix "Circle by a center point and another point" tool name

- docs/user_manual/plugins/core_plugins/plugins_metasearch.rst
fixes #2961 
@DelazJ I'm not sure my description is correct; I looked it up in Default Services, but I didn't find a dataset that enabled the "Add GIS File" action.
> Add GIS File added to metasearch plugin

- docs/user_manual/print_composer/overview_composer.rst
Fixes #8381 and update general description of layout overview (mention 3D map view, elevation profile items)
Goal:
Ticket(s): #
> Add multiselection from layout Items panel

- docs/user_manual/introduction/qgis_configuration.rst
- docs/user_manual/map_views/map_view.rst
Removes duplicate lists of measure units and unnecessary comments
Adds missing inches unit, connection between the sections
Lines length
Goal:
Ticket(s): #
> Measurement tools configs and cleanups

- docs/training_manual/spatial_databases/index.rst
Perhaps these links just need to be removed? I can rewrite this to adjust for that change.
- May need to just remove them since the links are broken
- Boundless Spatial, Inc. was acquired in 2019 by Planet Labs PBC to become Planet Federal
- Soon thereafter these websites were shutdown
Fixes #8235
> Fix broken links in PostGIS documentation

- docs/user_manual/processing_algs/gdal/rasteranalysis.rst
- docs/user_manual/processing_algs/gdal/rasterconversion.rst
- docs/user_manual/processing_algs/gdal/rasterextraction.rst
- docs/user_manual/processing_algs/gdal/rastermiscellaneous.rst
- docs/user_manual/processing_algs/gdal/rasterprojections.rst
- docs/user_manual/processing_algs/gdal/vectorconversion.rst
- docs/user_manual/processing_algs/qgis/rasteranalysis.rst
- docs/user_manual/processing_algs/qgis/vectorcreation.rst
- docs/user_manual/processing_algs/qgis/vectorgeometry.rst
Goal: Harmonize NoData spelling and capitalization.
Ticket(s): fix #8656
> NoData Harmonization

- docs/server_manual/services/wfs.rst
- Add example how to filter a WFS by polygon in QGIS Server.
> Server: Add example how to filter WFS by polygon

- docs/developers_guide/unittesting.rst
As it is stated some paragraphs after in the same document.
> All our test methods are implemented as private slots.
-----------
@timlinux, could you please check this minor change?
> Unit tests section: All test methods should be 'private' (not 'public')

- docs/user_manual/processing_algs/gdal/rastermiscellaneous.rst
refs qgis/QGIS#50586
Goal:
Ticket(s): #
> Add extent option to GDAL Raster Calculator algorithm

- docs/user_manual/introduction/project_files.rst
- docs/user_manual/introduction/qgis_gui.rst
fixes #8501 
does this PR also fixes #8496?
> Right-click menu for Recent projects update

- docs/user_manual/processing_algs/qgis/vectorgeneral.rst
> Save vector feature to file alg update

- docs/pyqgis_developer_cookbook/vector.rst
The doctest is failing and reports another result for the symbol layer properties, mainly modifying the color output. I copy pasted the suggestion but I have no idea if that is the new "formatting of the color properties" or a bug in code repo...
@nyalldawson @elpaso @nirvn (I saw a PR from you playing with colors)
> Update vector symbol layer properties output

- docs/user_manual/map_views/map_view.rst
Makes the reading smoother as we go into details later, at feature level
_no changes to text, except the section title_
> Move up the annotation layer properties section

- Makefile
Seems required by new Sphinx versions
Combined with https://github.com/qgis/QGIS-Website/pull/1135/, supersedes #8782 and #8783
> export LC_ALL variable to C.UTF-8 in Makefile

- docs/server_manual/containerized_deployment.rst
As per https://wiki.debian.org/DebianReleases Debian Bullseye will reach EOL in about 6 months, so it's time to move on to the newer shinier thing
This commit updates the suggested Dockerfile example to use Debian bookworm-slim instead of bullseye-slim
> Update base image from Bullseye to Bookworm

- docs/user_manual/style_library/label_settings.rst
Fixes #7926
Goal: to explain what the label mask is and how it works 
Ticket(s): #7926
> Added explanation of label masking

- docs/user_manual/working_with_raster/georeferencer.rst
Fixes #3335
Goal: Clarify the Configure Georeferencer settings, in particular the ability to dock the window
> Edits to clarify Configure Georeferencer settings

- docs/user_manual/managing_data_source/opening_data.rst
This PR addresses requested changes from [this discussion](https://github.com/qgis/QGIS-Documentation/pull/8780). 
I referred to the following sources for information:
- [video](https://freegistutorial.com/how-to-open-ms-sql-server-spatial-table-on-qgis/)
- [gis.stackexchange](https://gis.stackexchange.com/questions/351214/connecting-to-microsoft-sql-server-from-qgis)
If anyone has additional insights regarding the functionality of the 'Test Connection' button, please share.
> MS SQL server connection fix

- docs/user_manual/introduction/general_tools.rst
- docs/user_manual/introduction/qgis_gui.rst
The idea is to replace in [QGIS GUI](https://docs.qgis.org/3.34/en/docs/user_manual/introduction/qgis_gui.html#layer)
by
> Aerate the References cell of "layer properties" entry in Layer menu

- docs/user_manual/processing_algs/qgis/vectorgeometry.rst
Goal:
Both "Filter vertices by M value" and "Filter vertices by Z value" algs will accept any spatial vector layer as input since QGIS 3.36
Fixes https://github.com/qgis/QGIS-Documentation/issues/8884.
Ticket(s): #
> Update "Filter vertices by M value" and "Filter vertices by Z value" algs docs

- docs/user_manual/introduction/qgis_configuration.rst
- docs/user_manual/working_with_gps/plugins_gps.rst
I am halved here. Once the description of the different tools are fixed, the idea is to have move anything relating to GPS to the "working with GPS data" chapter, and if possible just have a single page.
Not sure how/if this is a good idea. Opinions?
> [GPS] 4 - Move GPSBabel instructions to loading from GPS devices section

- docs/user_manual/working_with_vector/attribute_table.rst
This tool is not in the attribute table itself so it may look weird to start with it. It is an accompanying tool for viewing attribute data, so let's expose it as such. Also add a ref to the tool.
follow-up #8864
> Move down the Identify features section in vector attribute table page

- conf.py
One nice thing added in recent versions of sphinx is a substitution evaluating [percentage of the active page](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#substitutions). Let's then use it to show readers (and potential translators) how much English remains in the page they are about to read.
Only display the warning when using a language other than English, with html builds. Test on 3.28 branch below
https://github.com/qgis/QGIS-Documentation/assets/7983394/074ffa2f-b888-4390-82eb-0383b934939a
I don't think it is worth a backport to 3.28 as it will require some tweaks on Transifex, and we are one week left. Better invest those efforts on 3.34.
Do you agree with showing this info? as a warning or an info? Suggestions of wording? 
@rduivenvoorde @agiudiceandrea …
> Add a message on translation progress at the top of the pages

- docs/user_manual/introduction/general_tools.rst
- docs/user_manual/working_with_raster/raster_properties.rst
Fixes #8500 
I believe that such 'small details' should be mentioned in the 'Working with Raster' chapter, but I'm not sure how to incorporate them into that chapter. I would like to hear suggestions and opinions on this.
> Show raster row/column of clicked point in identify results

- docs/user_manual/map_views/3d_map_view.rst
Press |checkbox| == Check |checkbox|
Nothing to press on, just to select  :-)
<!---
Ticket(s): #
> Corrected wrong wording

- docs/user_manual/expressions/functions_list.rst
- docs/user_manual/expressions/text_include.rst
Some groups contain tens of functions that, despite the multicolumns split, still take a lot of vertical scrolling space. Let's reduce that using a collapsible widget (as for training manual answers). Available only on html, for now.
A video showing the current situation and the proposed one
https://github.com/qgis/QGIS-Documentation/assets/7983394/211a2432-8df3-45df-8655-74a3103760a4
Any feedback?
> Put Expressions groups table of contents in a collapsible widget

- docs/user_manual/processing/scripts.rst
Cherry-picks d910f61e0d7ba410ec60f54bedeeb370ad1d4fb7
Goal:
Ticket(s): #
> Processing scripts: Improve distinction between alg.INT and alg.NUMBER

- docs/pyqgis_developer_cookbook/plugins/ide_debugging.rst
- substitutions.txt
Fixes #8851
It is the only page in which that message is shown (other occurrences were removed during the cookbook update), it has been there for years with almost nobody caring about, and the text is not inline with that specific chapter.
@agiudiceandrea ?
> Update and make translatable the warning on outdated info in IDE debugging chapter

- docs/user_manual/style_library/3d_symbols.rst
Fixes #8776
@nyalldawson I have no clear idea what this is so if you think there's a better explanation we could provide, I'd be thankful.
Also the Qt docs (and others) mention that metalness and roughness values are between 0 and 1 but I can see that in QGIS, the limit is 1000. Expected?
> Add "Metal roughness" as shading mode

- docs/user_manual/processing/scripts.rst
I don't know if that is the most meaningful way to present the data types, but it seems to build again...
> Fix build error due to attributes moved to qgis enums

- docs/user_manual/introduction/general_tools.rst
Goal:
In https://docs.qgis.org/testing/en/docs/user_manual/introduction/general_tools.html#data-defined-override-setup.
Fixes https://github.com/qgis/QGIS-Documentation/issues/8927.
Ticket(s): #
> Data defined override: use middle-click to open the Expression Builder dialog window

- docs/user_manual/working_with_vector/attribute_table.rst
Goal:
A proposal to clarify the sorting of the rows.
https://docs.qgis.org/3.34/en/docs/user_manual/working_with_vector/attribute_table.html#sorting-columns
Ticket(s): #
> [attribute table] Clarify rows sorting

- docs/user_manual/working_with_gps/live_GPS_tracking.rst
Goal: Add missing capturePolygon action to https://docs.qgis.org/3.34/en/docs/user_manual/working_with_gps/live_GPS_tracking.html#gps-toolbar
Ticket(s): #
> Add capturePolygon to live_GPS_tracking

- docs/user_manual/processing_algs/qgis/rastertools.rst
backports #9005
and fix algorithm reference
Goal:
Ticket(s): #
> [3.34] Detail how to be able to fill options for input layers in the "raster aligns" algorithm

- docs/user_manual/working_with_vector/attribute_table.rst
Weirdly, the badges are green in the readme file while both should be red. Fixing the docs build one.
> Fixes typo in reference

- docs/training_manual/appendix/preparing_data.rst
That chapter targets people willing to adapt the lessons and teach QGIS to others so I hope they are good enough to cover all the levels of difficulties in the manual (or not worry about)
Moreover, I think we shouldn't go into details that way in the chapter. They are assumed to know how to do it (btw, QuickOSM we rely on no longer has that interface), we should instead mention the main points they should pay attention to.
Last but not least, we would avoid, in the training manual top page 👇🏿
> Delete exercice levels in the preparing data chapter

- themes/rtd_qgis/static/css/qgis_docs.css
can be convenient when you don't have a mouse and need to go to a section that is not visible in the side bar.
The fix also ensures the clicked item in the side bar is kept visible and identifiable instead of being hidden under the testing banner
before and after (with scrollbar while hovering over the side bar)
> Add scrollbar to left menu and ensure the search top frame is always visible

- docs/training_manual/appendix/contribute.rst
- docs/training_manual/basic_map/mapviewnavigation.rst
- docs/training_manual/databases/db_manager.rst
- docs/training_manual/processing/log.rst
Let's adjust the training manual contributing instructions after #8916, clarifying instructions formatting, removing the 80 chars limitation, killing some :kbd: misuse, fixing typos
> [TM] Adjust contributing instructions

- docs/user_manual/introduction/qgis_gui.rst
Fixes #8853 (forward ports #8857)
(cherry picked from commit fb5f8cb8c847b8822a8d155408efd62f04fbbc70)
@agiudiceandrea @3nids (I still don't know if the tools removal was accidental or intentional - afaict it appears nowhere in the various discussions that introduced the PR)
> Remove Shape digitizing menus from the main Edit menu

- docs/user_manual/working_with_vector/vector_properties.rst
> Corrected typo

- docs/training_manual/rasters/terrain_analysis.rst
Added extension to filenames for consistency and as to avoid confusion
Goal: Display good documentation
> Naming files by extension.

- docs/developers_guide/qtcreator.rst
This step is no longer necessary.
Goal: Improve instructions for building QGIS with QtCreator
Ticket(s): #
> Remove `make -jX`  step in qtcreator instructions

- docs/training_manual/processing/log.rst
- docs/user_manual/processing/console.rst
> Clarify and adjust use of runAndLoadResults method

- docs/user_manual/working_with_mesh/mesh.rst
> Keep the string as a whole to not mislead readers and translators

- docs/user_manual/introduction/qgis_configuration.rst
refs https://github.com/qgis/QGIS/issues/58586
This may be helpful when you inadvertently remove the entry and don't remember how it was constructed
> fix: Mention the default URL to open user manual pages from QGIS Desktop

- docs/user_manual/processing_algs/qgis/vectortable.rst
- "Field calculator" native:fieldcalculator
- "Advanced Python field calculator" qgis:advancedpythonfieldcalculator
- "Add field to attributes table" `native:addfieldtoattributestable`
Unfortunately the order of the field types' list is different in "Field calculator" form "Advanced Python field calculator" and "Add field to attributes table"
Fixes https://github.com/qgis/QGIS-Documentation/issues/9261.
Fixes https://github.com/qgis/QGIS-Documentation/issues/9260.
Goal:
Ticket(s): #
> Fix field type list for "Field calculator", "Advanced Python field calculator" and "Add field to attributes table" algs

- docs/user_manual/introduction/qgis_configuration.rst
> Added project properties: vertical CRS

- docs/training_manual/basic_map/symbology.rst
fix #9267 
-->
Goal:
Ticket(s): #
> Documentation on Border line style changed from "Pen" to "Line"

- docs/user_manual/processing_algs/qgis/pointcloudconversion.rst
- docs/user_manual/processing_algs/qgis/pointclouddatamanagement.rst
- docs/user_manual/processing_algs/qgis/pointcloudextraction.rst
Goal:
Add a note about the minimum PDAL version needed for the Point Cloud processing algorithms to be available.
See https://github.com/qgis/QGIS/pull/52182/.
Ticket(s): #
> Add a note for Point Cloud algorithms availability

- docs/pyqgis_developer_cookbook/plugins/plugins.rst
- docs/pyqgis_developer_cookbook/plugins/releasing.rst
Fixes #9192 : 
* add reference to required LICENSE file
Goal: clarify required files for validation in the official plugin repository
Ticket(s): #9192
> Update plugin structure requirements for upload to directory

- README.md
These should currently show as
Fixes #9179
> Fix actions badges

- themes/rtd_qgis/versions.html
The new website is language agnostic so let's not use that variable in constructing the URL
> Remove language from QGIS Website url

- docs/user_manual/processing/parameters.rst
- docs/user_manual/processing_algs/qgis/interpolation.rst
- docs/user_manual/processing_algs/qgis/mesh.rst
- docs/user_manual/processing_algs/qgis/rasteranalysis.rst
- docs/user_manual/processing_algs/qgis/rastercreation.rst
- docs/user_manual/processing_algs/qgis/rasterterrainanalysis.rst
- docs/user_manual/processing_algs/qgis/rastertools.rst
- docs/user_manual/processing_algs/qgis/vectoranalysis.rst
Fixes #9151, fixes  #9166, fixes #9161
> Updates a few algorithms

- .github/workflows/builds.yml
- .github/workflows/doctest.yml
- .github/workflows/pofiles.yml
- .github/workflows/translation_statistics.yml
Raised to 3.12. New sphinx versions (v8) dropped Python 3.9 (and very soon 3.10).
> Homogenize Python version in use across github workflows

- docs/documentation_guidelines/do_translations.rst
- docs/documentation_guidelines/first_contribution.rst
- docs/documentation_guidelines/index.rst
- docs/index.rst
- docs/server_manual/containerized_deployment.rst
- docs/server_manual/getting_started.rst
- docs/training_manual/qgis_server/install.rst
- docs/user_manual/grass_integration/grass_integration.rst
- docs/user_manual/preamble/contributors.rst
- docs/user_manual/preamble/help_and_support.rst
- docs/user_manual/preamble/preamble.rst
The QGIS website refactoring replaces and deletes some information we were linking to in the docs. This PR tries to fix the issues
> Replace broken old-fashion URLs of QGIS website

- docs/user_manual/working_with_vector/editing_geometry_attributes.rst
Adds additional Offset Curve Documentation including from background layers.
This is in conjunction with https://github.com/qgis/QGIS/pull/59438 
Goal:
Ticket(s): #
> Add additional Offset Curve Documentation

- docs/training_manual/spatial_databases/spatial_queries.rst
- The geometry field is named 'geom' (and not 'the_geom') in .shp files and so are they in the resultant tables after import.
> update spatial_queries.rst - Wrong fieldnames in queries related to 'region', 'road' and 'building' tables.

- cronjob.sh
- docker-run.sh
- docker-world.sh
- release_process.md
These commands are meant to be run on our servers to build the different releases (master and release_x.y branches). Instead of manually adjusting them at every new release (at the risk of forgetting one or making a mistake), let's automatize using the target release as variable.
@rduivenvoorde opinions?
> Base docker build commands on their target docs version

- docs/user_manual/expressions/functions_list.rst
format_date provides a direct preview of the formatting syntax these function rely on
refs https://github.com/qgis/QGIS/issues/32027#issuecomment-2502939376
Goal:
Ticket(s): #
> Reach format_date function from to_date/datetime/time functions

- docs/training_manual/spatial_databases/geometry.rst
- docs/training_manual/spatial_databases/simple_feature_model.rst
- docs/training_manual/spatial_databases/spatial_queries.rst
- docs/user_manual/managing_data_source/supported_data.rst
the_geom is not used for years, let's abandon it also. This si simply a search and replace; we should consider investigating the geometry_columns calls also.
Goal:
Ticket(s): #
> Replace "the_geom" with "geom" in PostGIS lessons

- docs/gentle_gis_introduction/vector_attribute_data.rst
Goal: The example table shows the years, not the months.  This PR corrects the sentence describing the table.  Also, in the listing of other potential attributes the example of year is changed to month.
> Fix references to month/year in example attributes

- docs/pyqgis_developer_cookbook/canvas.rst
- docs/pyqgis_developer_cookbook/cheat_sheet.rst
- docs/pyqgis_developer_cookbook/expressions.rst
- docs/pyqgis_developer_cookbook/loadlayer.rst
- docs/pyqgis_developer_cookbook/vector.rst
Fixes #9255
This is an attempt to fix the flaky doctests behavior, only actual workflow runs on the Github agent will provide certainty.
Primary changes
- Use the airports dataset from data/data.gpkg (EPSG:4326) instead of the Alaska scoped airports.shp (EPSG:2964) and remove the warning string as expected test output. We do not simply reproject the layer, because the Alaska airports crs is mentioned multiple times in the cookbook and streamlining the whole cookbook is out of scope for this PR.
Secondary changes
- Prefer usage of geopackage instead of shapefile in the spirit of slowly fading out .shp hopefully.
- Minor refactoring of documentation along the way.
> Attempt to fix doctests by using airports layer in epsg4326 instead of epsg2964.

- release_process.md
The formatting of the [releases container](https://hub.docker.com/r/qgis/qgis/tags)
name has changed, moving from the branch name to simply the release number
Refs #9433 and #9434
Goal:
Ticket(s): #
> Update formatting of the Docker container to pull from

- docs/user_manual/map_views/elevation_profile.rst
> Tolerance for lines and polygons - elevation profile

- docs/pyqgis_developer_cookbook/processing.rst
Follow up from my previous PR #9465. Sorry, I'm giving a PyQGIS training these days... ;-)
* Remove `args` and `kwargs` from the example, we do not need them, it makes the function signature easier
* Adding Python annotations, similar as in QGIS recently https://github.com/qgis/QGIS/pull/59811 and https://github.com/qgis/QGIS/pull/59812
> Add Python annotations and remove args kwargs from Python methods

- docs/user_manual/print_composer/composer_items/composer_tables.rst
Fixes #9232 and fixes #4782
Goal:
Ticket(s): #
> Update the layout fixed table item properties

- docs/user_manual/introduction/general_tools.rst
Fixes #9216
Goal:
Ticket(s): #
> Add custom expression for numbers formatting

- docs/user_manual/processing_algs/algs_include.rst
- docs/user_manual/processing_algs/qgis/vectorgeometry.rst
- docs/user_manual/processing_algs/qgis/vectortable.rst
in Aggregate and Refactor fields algorithms
Fixes #3666
@selmaVH1 @nyalldawson @agiudiceandrea may I request your feedback, please? I found from the log panel that Int/Int64/Double lists share the same `type` enum and there is an additional sub_type parameter to differentiate them (which of course is not exposed in the GUI). I'm not sure of how to clearly explain this to the users. this is what I came to (I also don't keep the order in which the types are displayed in the drop-down widget). Any ideas? Thanks
> Field types

- docs/user_manual/style_library/label_settings.rst
Fixes #9279, Fixes #9246, fixes #9264
Goal:
Ticket(s): #
> Add some more HTML tags and CSS properties for labels

- docs/user_manual/style_library/label_settings.rst
Fixes #9401, fixes #9376, fixes #9372
Goal:
Ticket(s): #
> Some more CSS properties for HTML-enabled labels

- Makefile
- REQUIREMENTS.txt
- conf.py
- docs_conf.yml
and adapt the changes to repo and tools contexts
Fixes #7619 
Actually, the issue is already fixed (I locally build and pushed to server). This PR is to align the branch with the necessary changes...
Because 3.10 is an old version, it wasn't possible to build it as it was (without setting a compatible environment). The fix here is to instead replace the old libraries and commands with the ones used in master and build 3.10 docs with them.  Focus was put mainly on the HTML build.
> Backport some of the HTML and PDF build configuration from recent versions

- docs/user_manual/style_library/label_settings.rst
Fixes https://github.com/qgis/QGIS-Documentation/issues/9201
Moreover this PR actually reformats the description of this section moving away from a list based items to a IMHO clearer tabular formatting, i.e.
**BEFORE** 
**AFTER**
Goal:
Ticket(s): #
> Add end point marker to label's callout, and format the section as a table

- docs/user_manual/introduction/qgis_configuration.rst
e.g. when QGIS crashes at startup
_This would probably help some bug reporters that have crash at startup and may not know how to effectively restart QGIS cleanly_
Goal:
Ticket(s): #
> Add ways people can run QGIS under a new user profile

- docs/user_manual/working_with_vector/editing_geometry_attributes.rst
Goal: refs qgis/QGIS#59806
Ticket(s): #
> "Split features" keeps original feature and assigns biggest geometry

- docs/user_manual/introduction/qgis_configuration.rst
Fixes #9544 
@domi4484 @agiudiceandrea may I request feedback? Thanks
Goal:
Ticket(s): #
> Add py-args and -- as command line parameters

- docs/developers_guide/codingstandards.rst
Following approval of https://github.com/qgis/QGIS-Enhancement-Proposals/pull/314, we now use a formal QEP to describe coding conventions which must be followed in the QGIS code.
As a result this duplicate information should be removed from the documentation and replaced with a link to QEP 314
> Link coding standards to QEP 314, remove duplicate content

- docs/developers_guide/hig.rst
- the use**r is**...
- e.**g.,**
- i.**e.,**
- layman'**s** equivalent...
Goal:
see:
https://www.merriam-webster.com/dictionary/layman#examples
and:  
https://www.merriam-webster.com/dictionary/e.g.#examples
Ticket(s): #
> docs: fix grammar and punctuation in hig.rst

- docs/developers_guide/git.rst
- c**h**ecks
- Develo**p**er
- sent to **us**
- other**s'** pull requests
- e.**g.,**
Goal:
Ticket(s): #
> docs: fix spelling and punctuation in git.rst

- docs/user_manual/working_with_vector/editing_geometry_attributes.rst
fixes https://github.com/qgis/QGIS-Documentation/issues/8658
Also update an old fix me and describe "add ring" how-to
> Indicate vertices order orientation in polygon part and ring geometries

- docs/user_manual/introduction/qgis_configuration.rst
- column~s~ names
- contro**ll**ed
- e.**g.,**
- i.**e.,**
Goal:
Ticket(s): #
> docs: fix punctuation and spelling in qgis_configuration.rst

- .github/workflows/auto-label.yml
- .github/workflows/backport.yml
- .github/workflows/builds.yml
- .github/workflows/doctest.yml
- .github/workflows/pofiles.yml
- .github/workflows/pull_minimized_translations.yml
- .github/workflows/stale.yml
- .github/workflows/translation_statistics.yml
taken from actions outputs.
I don't know what these really do (or if worth it) but this is an old todo so let's solve it...
> [GH Actions] Add recommended configuration to harden the runner

- docs/developers_guide/localization.rst
- the other~s~ ...
- e.**g.,**
Goal:
Ticket(s): #
> fix: grammar and punctuation in localization.rst

- docs/user_manual/expressions/expression_help/Conversions.rst
- docs/user_manual/expressions/expression_help/String.rst
refs https://github.com/qgis/QGIS/pull/60479
Goal:
Ticket(s): #
> Add precision to to_string function

- .github/workflows/pofiles.yml
- .tx/config
- conf.py
- locale/en/LC_MESSAGES/sphinx.po
- scripts/create_transifex_resources.sh
- themes/rtd_qgis/breadcrumbs.html
- themes/rtd_qgis/layout.html
making every user-facing strings in the docs really translatable.
This is a backport of #9624 with an additional commit that applies the changes and generates the new strings to translate (see sphinx.po file).
Any objections to merging this so close to 3.34 EOL? Afaict at worst it adds new strings to Transifex but these strings are already visible in English in the docs, regardless the locale. So no harm if not translated, other than lowering translation ratio 😄  On the contrary, if translated, the red banner for outdated docs would now display translated.
> [3.34] Make strings in the themes folder also translatable

- docs/user_manual/style_library/label_settings.rst
Added explanation about 0° angle pointing direction and rotation direction definition for Data defined Rotation under Placement. This is not common between different software's so it should be documented.
Goal:
Ticket(s): #
> Update label_settings.rst - definition for Data defined rotation

- docs/user_manual/introduction/general_tools.rst
Goal: Add info to the docs to inform Mac users of how to remove features from a selection using the Select Feature(s) tool.
Ticket(s): #
> Remove features from selection with Cmd-drag on Mac. Also typo fixes.

- docs/user_manual/expressions/functions_list.rst
Also connect replace and array_replace functions
Goal:
Ticket(s): #
> Mention array_to_string as alternative for string concatenation functions

- docs/developers_guide/git.rst
QEP 323 is now the definitive, dynamic source for these policies
> Update pull request merge criteria to point to QEP 323

- .envrc
- .gitignore
- clean.sh
- scripts/clean_unused_images.sh
- scripts/countsubs.sh
- scripts/create_transifex_resources.sh
- scripts/minimize_translation.sh
- scripts/populate_expressions_list.py
- scripts/rstcleanup.sh
- shell.nix
- vscode.sh
Hi @DelazJ 
We are soon going to be moving a bunch of QGIS infrastructure over to new servers and build / packaging systems. These are all NixOS based and I want to establish the workflows for building the docs under NixOS early in the process. Currently the requested changes are non-invasive, just adding a few environment files to the source tree.
Later on, if you are available, I would like to hop into a call with you to explain our infrastructure roadmap and how it impacts the documentation publishing process.
For now, I humbly request that you accept these changes and subsequent changes relating to NixOS where they do not impact your existing workflows.
Thanks
Tim
cc @xpirix @ivanmincik
> Nixos build support

- docs/user_manual/processing_algs/qgis/vectorgeometry.rst
Goal:
1) Figure is obviously previously replaced, but figure description isn't, so I've fixed it.
2) Other than that one-line fix, my VSCode setup automatically cleaned all extra white-spaces (right trim) - that's why there are so many changes (I hope that this is OK)
old:
new:
Ticket(s): #
> fix figure description

- docs/documentation_guidelines/writing.rst
Goal:
- There was no `Tables` in TOC so I pushed it one level up...
- This is my proposal, other good option could be to rename [`Figures and Images`](https://docs.qgis.org/3.40/en/docs/documentation_guidelines/writing.html#figures-and-images) to `Figures, Images and Tables`
before:
new:
Ticket(s): #
> change level for tables section

- scripts/strings_fixer.sh
A probably ugly, but working, script that helps replace broken or redirected urls found by Linkcheck (used to fill #9676).
It will also be called on translated po files to avoid broken translated strings due to modified urls. Morever, it is designed for fixing a number of common translation errors related to Sphinx text formatting.
Goal:
Ticket(s): #
> Add a script to easily replace strings in rst or po files

- docs/developers_guide/ogcconformancetesting.rst
I recently published `pyogctest` on PyPI, so I suggest updating the OGC conformance chapter to use it directly from there, rather than installing the package from sources.
See https://github.com/qgis/QGIS/pull/61013.
> Install pyogctest from PyPI instead of the GitHub repository

- .github/workflows/pofiles.yml
- .github/workflows/pull_minimized_translations.yml
- .github/workflows/translation_statistics.yml
- scripts/fix_versions.sh
(cherry picked from commit c29dc74b1d9f5973d0547efb8bc7a26f8602108c)
Backport #9683
I thought actions files in the master branch were the ones that have priority, but ... Should fix the actions not running for 3.40
Goal:
Ticket(s): #
> Preparing github actions for 3.40 LTR

- docs/user_manual/processing_algs/qgis/cartography.rst
- docs/user_manual/processing_algs/qgis/networkanalysis.rst
- docs/user_manual/processing_algs/qgis/vectoranalysis.rst
- docs/user_manual/processing_algs/qgis/vectorcreation.rst
- docs/user_manual/processing_algs/qgis/vectorgeneral.rst
- docs/user_manual/processing_algs/qgis/vectorgeometry.rst
- docs/user_manual/processing_algs/qgis/vectoroverlay.rst
- docs/user_manual/processing_algs/qgis/vectorselection.rst
- docs/user_manual/processing_algs/qgis/vectortable.rst
(cherry picked from commit f361fdf789c570817f3fea77553b17ace31803d1)
Backports #9743
Goal:
Ticket(s): #
> Add warning to algorithms that drop primary keys or FID values

- docs/user_manual/style_library/symbol_selector.rst
Sentence is not translated in the lokalised Dutch version. Only difference I see with other sentences in the same paragraph was a missing period at the end of the sentence.
Maybe this will fix it
Goal: Delivering good documentation
> Added one period at end sentence. Update symbol_selector.rst

- docs/training_manual/create_vector_data/topo_editing.rst
Goal: Add more specified steps for set snapping options in QGIS Training Manual in 5.2.1 chapter.
Ticket(s): #
> Add more specified steps for set snapping options

- docs/user_manual/managing_data_source/opening_data.rst
While Oracle and MS SQL refer to PG connection description section as a first place to discover their options, they actually list ALL their options instead of showing the additional/custom ones.
This PR removes those references to PG and create a PG section instead of the supposedly "common section".
> Stop mentioning the PostgreSQL connection section as reference for other databases

- docs/user_manual/expressions/expression_help/GeometryGroup.rst
refs https://github.com/qgis/QGIS/pull/61786
Goal:
Ticket(s): #
> Fix concave hull function description

- docs/user_manual/working_with_raster/raster_properties.rst
because the expected embedded .gif file was not embedded and was then trying unsuccessfully to build in PDF
> Fix ".. only:: html" role misalignment breaking PDF build

- docker-run.sh
- docker-world.sh
This is unnecessary given that we have the translated strings already in the repository and we do not download them anymore at build time. 
This then allows more simplification of the docs structure by moving the builds command in the docker-world.sh file and remove the docker-run.sh one. 
Goal:
Ticket(s): #
> Remove copy of transifexrc file in build dir in order to build docs with docker

- docs/user_manual/expressions/expression_help/GeometryGroup.rst
Complements #9951
@bsaglio2001 we forgot to do the last step, I.e., regenerate the difference function help with the image, either running the Python function or, like done here, copy-paste a figure block and adapt filename and caption
Goal:
Ticket(s): #
> Add the difference expression function screenshot to the help

- docs/user_manual/introduction/general_tools.rst
We add brief description to each tab and move details on the profiler tab to their dedicated section
> Adjust introduction of tabs in the Development Tools panel

- docs/user_manual/style_library/label_settings.rst
Goal:
See https://github.com/qgis/QGIS/pull/45887 and https://github.com/qgis/QGIS/pull/45946 and https://gis.stackexchange.com/questions/491719/stretch-ratio-option-missing-in-qgis-3-40-5-label-settings-windows-11/491723.
Not sure if "Only available on some systems." is enough or should it be "Requires Qt 6.3+, or Qt 5.15 using KDE's fork and the cmake HAS_KDE_QT5_SMALL_CAPS_FIX switch defined during build" and "Requires Qt 6.3+, or Qt 5.15 using KDE's fork and the cmake HAS_KDE_QT5_FONT_STRETCH_FIX switch defined during build".
Ticket(s): #
> Update label_settings.rst for some options' availability

- conf.py
- docs/documentation_guidelines/first_contribution.rst
It is expected to behave the same as the one in the bottom left menu
> Make the top "Edit on Github" button actually switch file to edit mode instead of simply display the file

- docs/pyqgis_developer_cookbook/loadlayer.rst
Goal: When you add a geopackage layer with `addMapLayer`, the relationships are not automatically built (unlike when this is done via the GUI). I therefore propose to explain how to do this if you want to automatically build relationships in addition to adding one or more layers from a geopackage.
> loadlayers: add information to build relations from gpkg

- docs/user_manual/processing_algs/qgis/checkgeometry.rst
> Check geometry: Duplicated geometries ---> Add explanation for added fields

- docs/user_manual/processing_algs/qgis/checkgeometry.rst
> Check geometry: Holes---> Add explanation for added fields

- docs/user_manual/processing_algs/qgis/checkgeometry.rst
> Check geometry: Self-intersections---> Add explanation for added fields

- docs/user_manual/processing_algs/qgis/fixgeometry.rst
> Fix geometry: Delete features---> Add explanation for added fields

- docs/user_manual/managing_data_source/supported_data.rst
- docs/user_manual/working_with_vector/editing_geometry_attributes.rst
Fixes #4780
There is no specific place in the docs we mention what geometry types can be edited depending on the data provider but this PR kind of adds Oracle among the ones with curved geometry support.
> Mention somehow that Oracle Spatial curve geometries can be edited and saved as curved
