- docs/user_manual/managing_data_source/create_layers.rst
Fixes #6691
@roya0045 does this reflect the main info? Thanks
> Layer metadata can be transferred when exporting a layer

- docs/user_manual/processing/modeler.rst
> Fix misaligned screenshot

- docs/user_manual/processing_algs/gdal/vectorconversion.rst
> Add "burn value..." to rasterize algorithm

- .github/workflows/translation_statistics.yml
> Do not unnecessarily fetch translation stats after every changes

- docs/user_manual/processing_algs/qgis/vectorgeometry.rst
Goal:
Fix a formatting typo:
and add descriptions for `BEHAVIOR` options taken from https://github.com/qgis/QGIS/blob/5e62599c30a8f17376630f021b7d71c3b5296656/src/analysis/vector/qgsgeometrysnapper.h#L48-L58
```
//! Snapping modes
enum SnapMode
{
PreferNodes = 0, //!< Prefer to snap to nodes, even when a segment may be closer than a node. New nodes will be inserted to make geometries follow each other exactly when inside allowable tolerance.
PreferClosest, //!< Snap to closest point, regardless of it is a node or a segment. New nodes will be inserted to make geometries follow each other exactly when inside allowable tolerance.
PreferNodesNoExtraVertices, //!< Prefer to snap to nodes, even when a segment may be closer than a node. No new nodes will be inserted. …
```
> Some fixes in Vector geometry tools docs

- docs/user_manual/style_library/label_settings.rst
> Label background shapes rely on fill symbols properties

- docs/user_manual/introduction/qgis_gui.rst
Interactions with and rendering of the 3D Map view depend on settings user selected so let's expose these settings first
> Move up the 3D Configuration section

- docs/user_manual/print_composer/composer_items/composer_label.rst
> Dynamic layout label can be turned into static

- docs/user_manual/working_with_vector/vector_properties.rst
Added JSON View to the edit widgets list, related to #6709
> Added JSON View to the edit widgets list

- docs/user_manual/introduction/browser.rst
- docs/user_manual/introduction/qgis_configuration.rst
Fixes #6714, Fixes #6731, fixes #6735, fixes #6029
> Update folders description in the Browser panel

- docs/user_manual/working_with_vector/functions_list.rst
Add clarity re custom paper sizes, aligning with https://github.com/qgis/QGIS/commit/dc338476c75807d4df3680cfd776c88f8885301d
> Fix layout_pageheight and width description

- docs/server_manual/containerized_deployment.rst
Closes #6603
Goal:
Ticket(s): #
> Provide note for adding Advertised URL in sample project.

- docs/user_manual/working_with_vector/expression_help/Files_and_Paths.rst
- docs/user_manual/working_with_vector/expression_help/GeometryGroup.rst
- docs/user_manual/working_with_vector/functions_list.rst
refs #6705, qgis/QGIS#37568 and qgis/QGIS#44081
> New variables and functions

- docs/user_manual/processing/standalone.rst
> More details on qgis_process tool

- docs/pyqgis_developer_cookbook/loadproject.rst
> Update path preprocessor details

- docs/user_manual/working_with_vector/vector_properties.rst
Some options are not self explaining so a little more documentation is needed on this
> [JSON widget] Some information about configurable options

- docs/user_manual/introduction/browser.rst
> [Browser]Use a table to display available context menus for tiles and web service

- docs/user_manual/style_library/label_settings.rst
- docs/user_manual/working_with_vector/vector_properties.rst
Provide description of properties of the various callout types, following structure suggested in https://github.com/qgis/QGIS/pull/43356
Also update labels toolbar items
> Detail callout properties 

- docs/user_manual/introduction/general_tools.rst
- docs/user_manual/plugins/core_plugins/plugins_offline_editing.rst
@signedav you introduce this in qgis/QGIS#39527 but I'm unable to understand what it actually indicates. Can you provide a simple, end-user explanation of this indicator, please? Thanks.
> Add offline Indicator to layers

- docs/user_manual/introduction/general_tools.rst
- docs/user_manual/introduction/qgis_configuration.rst
Fixes #6706, fixes #6708
I think I got the features but it may be interesting to provide more education regarding datum ensemble/crs static vs dynamic, inaccuracies... (and I'm not enough skilled for this).
@nyalldawson may I ask for your help/review, please? Thanks
> Warn for CRS inaccuracies

- docs/user_manual/working_with_raster/raster_properties.rst
and format into a table like in vector properties documentation
> Update list of raster properties tab

- docs/user_manual/managing_data_source/opening_data.rst
> Load mesh layers within a multi mesh file

- docs/user_manual/processing_algs/qgis/vectoranalysis.rst
- docs/user_manual/processing_algs/qgis/vectorcreation.rst
- docs/user_manual/processing_algs/qgis/vectoroverlay.rst
> More basic/advanced separation for algorithm parameters

- docs/user_manual/processing_algs/qgis/vectortable.rst
- docs/user_manual/working_with_vector/vector_properties.rst
> Refactor field algorithm can show field constraints

- docs/user_manual/processing_algs/qgis/vectoranalysis.rst
> Document the ST-DBSCAN clustering algorithm

- docs/user_manual/processing_algs/qgis/vectorgeometry.rst
> Document Convert to curved geometries algorithm

- docs/user_manual/style_library/symbol_selector.rst
Fixes #6606, fixes #6604, fixes #5819, fixes #5712
> Update symbol layer properties

- docs/user_manual/processing_algs/qgis/rasteranalysis.rst
- Switching to basic/advanced GUI sections
- using "native:" when available
- completing/updating parameters
> General update of the current algorithms of raster analysis group 

- docs/user_manual/processing/3rdParty.rst
> Switch formatting of R-package listing

- docs/user_manual/processing_algs/qgis/rasteranalysis.rst
> Add "Raster layer properties" algorithm

- docs/server_manual/containerized_deployment.rst
Goal:
Followup https://github.com/qgis/QGIS-Website/commit/7831f972025d4599a122c573a654d6dde4e548a9 and https://github.com/qgis/QGIS-Website/commit/72e19904804066da0ab55552c0df6f532c38122b
See https://github.com/qgis/QGIS/issues/44622
Note: 
It might be possible to avoid the fingerprint update just changing:
```
&& wget -O - https://qgis.org/downloads/qgis-2021.gpg.key | gpg --import \
&& gpg --export --armor 46B5721DBBD2996A | apt-key add - \
```
to
```
&& wget -O - https://qgis.org/downloads/qgis-2021.gpg.key | apt-key add - \
```
> Update QGIS gpg key and fingerprint in "Containerized deployment" chapter

- docs/user_manual/processing_algs/qgis/rastertools.rst
> Describe "Fill NoData cells" algorithm

- docs/user_manual/processing_algs/qgis/database.rst
- docs/user_manual/processing_algs/qgis/qgis_algs_include.rst
Remove the database example from the general include file.
Its scope is the database chapter so let's move it there.
> Relocate the database algs include text

- docs/training_manual/basic_map/symbology.rst
> Clarify how to load layer style onto a layer

- docs/pyqgis_developer_cookbook/raster.rst
> Allow raster data modification

- docs/pyqgis_developer_cookbook/intro.rst
> Add FDL to cookbook, explicitly say it applies to code snnippets.

- docs/server_manual/getting_started.rst
> add missing parameters to WMS request

- docs/user_manual/plugins/core_plugins/plugins_offline_editing.rst
> Offline editing plugin converts list into string

- docs/user_manual/working_with_vector/editing_geometry_attributes.rst
> More description of the digitizing tools

- docs/user_manual/processing_algs/gdal/rasteranalysis.rst
- docs/user_manual/processing_algs/gdal/rasterconversion.rst
- docs/user_manual/processing_algs/gdal/rasterextraction.rst
- docs/user_manual/processing_algs/gdal/rastermiscellaneous.rst
- docs/user_manual/processing_algs/gdal/rasterprojections.rst
- docs/user_manual/processing_algs/gdal/vectorconversion.rst
> Additional creation options use in batch mode

- docs/user_manual/expressions/functions_list.rst
- docs/user_manual/processing_algs/gdal/rasterextraction.rst
- docs/user_manual/processing_algs/gdal/vectorconversion.rst
- docs/user_manual/processing_algs/qgis/layertools.rst
- docs/user_manual/processing_algs/qgis/rasteranalysis.rst
- docs/user_manual/processing_algs/qgis/vectoranalysis.rst
- docs/user_manual/processing_algs/qgis/vectorcreation.rst
- docs/user_manual/processing_algs/qgis/vectorgeneral.rst
- docs/user_manual/processing_algs/qgis/vectorselection.rst
- docs/user_manual/processing_algs/qgis/vectortable.rst
- docs/user_manual/working_with_vector/attribute_table.rst
- docs/user_manual/working_with_vector/vector_properties.rst
- docs_conf.yml
- scripts/fix_versions.sh
- substitutions.txt
> Prepare release of 3.22 docs

- docs/pyqgis_developer_cookbook/geometry.rst
since the underlying method has changed (should fix doctest build)
> Fix area calculation test output

- docs/user_manual/expressions/expression_help/Arrays.rst
- docs/user_manual/expressions/expression_help/Color.rst
- docs/user_manual/expressions/expression_help/GeometryGroup.rst
- docs/user_manual/expressions/expression_help/Maps.rst
- docs/user_manual/expressions/expression_help/Math.rst
- docs/user_manual/expressions/functions_list.rst
Fixes #7007 fixes #7008 fixes #7010 fixes #6987 fixes #6986, fixes #7024
refs #7019
> Update list of functions

- docs/user_manual/processing_algs/gdal/rasteranalysis.rst
> Indicate the advanced parameters in the GDAL Raster Analysis Algs chapter

- docs/user_manual/expressions/functions_list.rst
> Make the index operator use with map and array more explicite

- docs/user_manual/processing_algs/qgis/filetools.rst
as an advanced parameter (fixes #6917)
> Add POST method to the download file algorithm

- docs/user_manual/processing_algs/qgis/vectorgeneral.rst
- docs/user_manual/processing_algs/qgis/vectorselection.rst
refs https://github.com/qgis/QGIS/pull/45652
> Reorder the join by location ... algorithms

- docs/user_manual/introduction/general_tools.rst
fixes #5024
Goal:
Ticket(s): #
> New option to group layers in layer panal 

- docs/user_manual/working_with_mesh/mesh_properties.rst
in mesh layer properties, and correct the "reset to defaults" button behavior
> Add contextual menu from the "Available datasets" group box

- docs/user_manual/introduction/general_tools.rst
- docs/user_manual/introduction/qgis_gui.rst
Move annotations tools to the dedicated toolbar (fixes #6936)
> Mention Annotations and mesh digitizing toolbars

- docs/user_manual/processing_algs/gdal/rastermiscellaneous.rst
> Add GDAL viewshed algorithm

- themes/rtd_qgis/static/css/qgis_docs.css
> Enlarge :kbd: annotations font size

- docs/user_manual/processing/console.rst
- docs/user_manual/processing/modeler.rst
more digestible and useful
Also turn into table the list in Console page (no update of the list)
> Update and turn the long list of modeler inputs into a table with links to PyQGIS class docs

- docs/user_manual/introduction/qgis_gui.rst
> Active layer prefix in locator is f and not af

- docs/user_manual/introduction/qgis_gui.rst
fixes #4562
Goal:
Ticket(s): #
> pan distance and direction is shown in the status bar

- docs/user_manual/managing_data_source/create_layers.rst
> Add date and date time fields to spatiaLite layer creation dialog

- docs/user_manual/working_with_vector/vector_properties.rst
> Mention "invert selection" tool in Drag-and-drop designer

- docs/user_manual/expressions/expression.rst
- docs/user_manual/expressions/functions_list.rst
> Fix expression output

- redirects.txt
> Redirect the supported_data.rst file from old releases

- redirects.txt
> Sort entries in the redirect.txt file

- docs/pyqgis_developer_cookbook/geometry.rst
- doctest.dockerfile
> Use QGIS 3.22 to run doctest builds on 3.22 docs

- docs/user_manual/introduction/general_tools.rst
fixes #5418
Not sure if it's the right place for the documentation... but couldnt
find a better place.
Goal:
Ticket(s): #
> Allow drag/drop from layer panel

- docs/user_manual/working_with_vector/editing_geometry_attributes.rst
Fixes #6937 and put basic usage of the panel into numbered list (steps)
> Add Z and M entries to the digitizing panel

- docs/user_manual/introduction/browser.rst
fixes #6835
Goal:
Ticket(s): #
> added "delete" and "rename" to browsers capabilities

- docs/user_manual/introduction/general_tools.rst
fixes #6851
Goal:
Ticket(s): #
> Updated Identify Tool

- docs/user_manual/introduction/qgis_gui.rst
- docs/user_manual/processing/modeler.rst
Fix #7156
See: https://github.com/qgis/QGIS/pull/46212
> Add Project-->Models menu item

- docs/user_manual/style_library/symbol_selector.rst
fixes #6992
Goal:
Ticket(s): #
> Angle for point pattern fill

- docs/user_manual/processing/modeler.rst
fixes #5202
Goal:
Ticket(s): #
> ModelBuilder - colors for comments

- docs/user_manual/print_composer/composer_items/composer_image.rst
fixes #5300
Goal:
Ticket(s): #
> Pasting Images into Layout

- docs/user_manual/style_library/label_settings.rst
fixes  #6921
Goal:
Ticket(s): #
> added data defined label rotation

- docs/user_manual/working_with_vector/vector_properties.rst
> Refining the symbology rule-based renderer description

- docs/user_manual/managing_data_source/supported_data.rst
fixes #4063
Goal:
Ticket(s): #
> PostgreSQL foreign tables

- docs/user_manual/introduction/project_files.rst
fixes #2187
fixes #2196
fixes #2194
Goal:
Ticket(s): #
> Add right click project options on welcome page

- qgis-projects/user_manual/introduction_qgis_gui_map_legend.qgs
- qgis-projects/user_manual/working_with_rasters.qgs
These were getting conflicted in #7022 and #7023
> Update project files with temporal references

- docs/user_manual/plugins/core_plugins/plugins_db_manager.rst
fixes #3305
I am not sure if this issue really needs documentation.
Took a look into the db manager section and the postgresql documentation
and its just a normal option for creating database objects.
Nevertheless added a draft how to doccument it.
Thoughts?
Goal:
Ticket(s): #
> Add comment option for postgis tables

- docs/user_manual/working_with_mesh/mesh_properties.rst
> Explain mesh contours resampling methods

- .github/workflows/auto-label.yml
for security reasons (fixes #7236) and remove 3.16 reference
> Bump auto-label action dependencies version

- docs/user_manual/working_with_raster/raster_analysis.rst
> Create on-the-fly raster with calculator

- docs/user_manual/style_library/3d_symbols.rst
> Add description for 3d polygon symbols

- redirects.txt
to make browsing between testing and latest as easy as replacing the version number
> Redirecting expressions chapters

- .github/workflows/backport.yml
> Bump backport action's version

- docs/user_manual/processing_algs/qgis/index.rst
- docs/user_manual/processing_algs/qgis/vectortiles.rst
Couldn't find issue reports. Refers to https://github.com/qgis/QGIS/pull/36099
Review more than welcome...
> Add Vector Tiles related algorithms

- docs/user_manual/processing_algs/qgis/index.rst
- docs/user_manual/processing_algs/qgis/vectortiles.rst
> [3.16] Add vector tiles algorithms

- docs/pyqgis_developer_cookbook/plugins/ide_debugging.rst
Goal: minor change in Eclipse .bat startup file, so that Eclipse opens without the terminal window.
> Minor change in eclipse .bat startup file

- docs/user_manual/processing_algs/gdal/rastermiscellaneous.rst
- docs/user_manual/processing_algs/qgis/vectorgeneral.rst
> Minor processing alg description fixes

- docs/training_manual/complete_analysis/analysis_combination.rst
- docs/user_manual/introduction/getting_started.rst
The answer should be collapsed at https://docs.qgis.org/3.22/en/docs/training_manual/complete_analysis/analysis_combination.html#moderate-ty-refining-the-analysis
> Collapse "Refining the analysis" exercice answer by default

- docs/user_manual/style_library/style_manager.rst
fixes #3359
Goal:
Ticket(s): #
> Add list view for style manager

- docs/user_manual/expressions/functions_list.rst
refs https://github.com/qgis/QGIS/pull/46959
> Update zoom_tile and vector_tile_zoom variables

- docs/user_manual/introduction/general_tools.rst
fixes #3457
Goal:
Ticket(s): #
> Add Cartesian option to measure dist / area

- docs/user_manual/working_with_vector/vector_properties.rst
fixes #4358
Thought about placing it in the postgres section, but since it also
works for gpkg and spatiallite, thought its better to keep it in the
value relation section.
Goal:
Ticket(s): #
> Restore missing Value Realtion

- docs/user_manual/processing_algs/qgis/modelertools.rst
> Display warnings in the modeler chapter

- docs/server_manual/services/wms.rst
> BBOX Required for the WMS GetMap request

- docs/server_manual/services/wfs.rst
Fixes https://github.com/qgis/QGIS-Documentation/issues/7329
Fixes https://github.com/qgis/QGIS-Documentation/issues/7309
> Add example for EXP_FILTER and FILTER WFS parameters 

- docs/user_manual/managing_data_source/opening_data.rst
Added the ArcGIS REST Server into the "Opening Data" section.
Not adding any images or xml files, since i dont have a service to share
(found a free one, but dont want to link it in the documentation without
permission) and i think empty images dont realy help.
Goal:
Ticket(s): #
> ArcGIS REST Server section

- docs/user_manual/processing_algs/qgis/index.rst
- docs/user_manual/processing_algs/qgis/mesh.rst
This is an initial walk through the mesh algorithms. I'm not a user of this type of data and probably lack some knowledge so there are some blank cells in the description
Let's say that it fixes #4341 (and more unreported)
> Introducing mesh algorithms

- docs/pyqgis_developer_cookbook/intro.rst
- docs/server_manual/introduction.rst
> Add license to Server manual and align cookbook's

- docs/user_manual/working_with_vector/attribute_table.rst
fixes #5500
Goal:
Ticket(s): #
> Delete cascade on composition relations

- docs/user_manual/processing_algs/gdal/vectorconversion.rst
Goal:
The EXTENT ("Output extent") parameter is optional.
See https://github.com/qgis/QGIS/pull/47205.
Ticket(s): #
> Update "Rasterize (overwrite with fixed value)" GDAL algorithm docs

- docs/pyqgis_developer_cookbook/authentication.rst
Should fix doctest build per https://github.com/qgis/QGIS-Documentation/runs/5115898054?check_suite_focus=true#step:6:801
> Fix authentication test output

- docs/user_manual/introduction/qgis_gui.rst
- docs/user_manual/processing/configuration.rst
> Explore Processing settings

- docs/user_manual/introduction/qgis_gui.rst
> Reference the Debugging panel

- docs/user_manual/expressions/expression_help/Aggregates.rst
- docs/user_manual/expressions/expression_help/Arrays.rst
- docs/user_manual/expressions/expression_help/Color.rst
- docs/user_manual/expressions/expression_help/Map_Layers.rst
- docs/user_manual/expressions/expression_help/Rasters.rst
- scripts/populate_expressions_list.py
sometimes raising errors when files are touched
> Remove blank spaces in expression function

- .github/workflows/auto-label.yml
unlike the action README
The action is still failing to label issue (https://github.com/qgis/QGIS-Documentation/runs/5246100020?check_suite_focus=true#step:2:11)
> [Auto-label]Remove quote from parameters

- docs/user_manual/style_library/symbol_selector.rst
- docs/user_manual/working_with_vector/vector_properties.rst
> Various vector symbology fixes

- docs/user_manual/introduction/qgis_gui.rst
> Do not render gif file in PDF output

- Makefile
- docs_conf.yml
Hungarian translation of docs has reached 5%.
> Add Hungarian to conf

- docs_conf.yml
I took a threshold of 5% to build. So now, we have Hungarian and Lithuanian and lose Bulgarian, Finnish, Indonesian, Turkish and Chinese traditional
> Add list of languages to build and display in the bottom left corner

- .github/workflows/pofiles.yml
- .github/workflows/translation_statistics.yml
> Target 3.22 for automated scripts

- conf.py
> 3.16 docs should now be closed

- transifex.yml
Makes it easier to integrate github with transifex (details at https://docs.transifex.com/transifex-github-integrations/github-tx-ui#linking-a-specific-project-with-a-github-repository)
> Add Transifex configuration file

- docs/user_manual/working_with_vector/editing_geometry_attributes.rst
Fixes #7411
Goal:
Ticket(s): #
> Add Ctrl modifier to Offset Curves tool

- substitutions.txt
> Remove substitutions whose image does not exist

- docker-world.sh
> Use proper languages for Chinese builds

- docs/user_manual/working_with_vector_tiles/vector_tiles_properties.rst
fixes #6076
Also altered one heading, since it deals with symbology and label and
dont think that it is necessary to have a chapter for symbology and
label.
Goal:
Ticket(s): #
> MapBox GL Json for vector tile layers

- docs/pyqgis_developer_cookbook/vector.rst
I propose a improvement of the python code : instead of using a loop `for` with a `break`, we can use the method `next`.
> More pythonic code

- docs/pyqgis_developer_cookbook/vector.rst
> Mention Animated symbol marker

- docs/user_manual/introduction/general_tools.rst
Documentation for QGIS feature introduced here: qgis/QGIS#47477
Documentation issue fixes #7416
Within user_manual > introduction > general_tools.rst:
Added detail under "The Identify Results dialog" header (for its context menu), explaining what the "select features by attribute value" command does, and that it exists
All changes done under updated-identify-results-panel-documentation-fix-#43757 branch
Let me know if you have any questions!
> updated identify results panel documentation as per fix #43757

- docs/documentation_guidelines/first_contribution.rst
> Introduce github branch update instructions

- conf.py
- docs_conf.yml
This is a forward port of #7495
> Fix supported languages list display

- docs/user_manual/plugins/python_console.rst
fixes #6131
Goal:
Ticket(s): #
> Using gist to share snippets instead of codepad

- docs/server_manual/getting_started.rst
According to https://httpd.apache.org/docs/2.4/upgrading.html#run-time mixing options from Apache 2.2 and 2.4 should be avoided.
Also raise version number in code sample
> Remove unwanted options from server conf file

- docs/user_manual/working_with_vector/vector_properties.rst
and emphasize the "description" option role (refs #6715)
> Update label's "Edit rule" dialog

- docs/user_manual/processing_algs/qgis/gps.rst
- docs/user_manual/processing_algs/qgis/index.rst
Fixes #6849 fixes #6838
Again, not something I have thoroughly tested so review more than welcome
> Add GPS related algorithms

- docs/server_manual/services/ogcapif.rst
- docs/user_manual/working_with_ogc/ogc_client_support.rst
refs https://github.com/qgis/QGIS-Documentation/pull/6213#issuecomment-1035977980
@elpaso I made an almost blind replacement. Except for images and QGIS_SERVER_API_WFS3_MAX_LIMIT
> Replace "WFS3" with "OAPIF"

- docs/server_manual/config.rst
> Add QGIS_SERVER_LANDING_PAGE_PREFIX env variable

- docs/server_manual/getting_started.rst
with some more clarification and code emphasis
This PR only addresses the Apache section. For the nginx part, see #7519.
> Make the Server "getting started" section on Linux more step-through

- docs/user_manual/introduction/browser.rst
- docs/user_manual/managing_data_source/opening_data.rst
Fixes #6832 fixes #6857
supersedes #7114
> Add "Show in Files" and Update some browser functions

- docs/gentle_gis_introduction/vector_spatial_analysis_buffers.rst
Goal: Fix minor language errors in A Gentle Introduction to GIS > Vector Spatial Analysis (Buffers)
Ticket(s): #
> Fix minor language errors

- docs/server_manual/services/wms.rst
> Add new WMS Highlight parameters 

- release_process.md
A number of changes have to be taken care of when we release a new release. This PR writes them down (for the ones I could remember) in order to share the knowledge as well as the workload when necessary.
At the end of the instructions, an improvement section is added to highlight some development needs concerning this release process. I'm not skilled enough to fix them so if any taker...
> Document the release process

- docs/user_manual/introduction/project_files.rst
> Fixing plural

- docs/user_manual/processing_algs/qgis/rasteranalysis.rst
> Fix rasterlayerstatistics "provider"

- docs/user_manual/style_library/label_settings.rst
> Indicate better text format options vs label settings'

- conf.py
- docs/pyqgis_developer_cookbook/pluginlayer.rst
- run_single_test.sh
> Skip crashing tests and introduce single test runner

- docs/user_manual/processing/scripts.rst
and tweak description
Goal:
Ticket(s): #
> Add more processing parameters for point cloud

- docs/user_manual/style_library/symbol_selector.rst
It also makes room for new features addition
Goal:
Ticket(s): #
> Detail some properties of fill symbol layer types

- docs/user_manual/style_library/symbol_selector.rst
Backports #7614 
Goal:
Ticket(s): #
> Detail some fill symbol layer types

- .github/workflows/builds.yml
- .github/workflows/doctest.yml
- .github/workflows/pofiles.yml
- .github/workflows/translation_statistics.yml
> Upgrade dependencies version for github actions

- docs/user_manual/appendices/qgis_desktop_network_connections.rst
Goal:
- "New version check": change the server url from `www.qgis.org` to `version.qgis.org` (see https://github.com/qgis/QGIS/blob/cd7b64cc2327b89a82b79b7ddba62822de9081df/src/app/qgsversioninfo.cpp#L28-L32)
- "QGIS Feed": add `QGIS version` to "Information sent to server" and add `QGIS version, OS and IP are aggregated and used to collect some statistics` to "Information stored on server"
@anitagraser @timlinux
For reference: https://github.com/qgis/PSC/issues/55, https://github.com/qgis/QGIS-Documentation/pull/7178 and https://github.com/qgis/QGIS-Documentation/pull/7434, https://github.com/qgis/QGIS/pull/46090
Ticket(s): #
> Update "QGIS Application Network Connections" appendix

- docs/user_manual/introduction/general_tools.rst
To make it more clear, information taken from https://github.com/qgis/QGIS/issues/26749#issuecomment-926934514.
> Add information regarding calculation of "Meters at Scale"

- docs/user_manual/preamble/features.rst
and a bit of cleanup/detailing
Goal:
Ticket(s): #
> Mention 3D view and OAPIF as features

- docs/user_manual/introduction/project_files.rst
Completes #7588 
Goal:
Ticket(s): #
> Mention that 3D map views are saved in project

- docs/user_manual/processing_algs/qgis/cartography.rst
> Add "Export atlas layout as PDF (multiple files)" alg

- docs/pyqgis_developer_cookbook/canvas.rst
fix some errors about `QgsWkbTypes ` in `QgsRubberBand`
Goal:
Ticket(s): #
> Fix QgsWkbTypes in QgsRubberBand

- docs/user_manual/processing_algs/qgis/vectoroverlay.rst
Goal: Update - Somehow didn't get updated when we made all the changes.
Ticket(s): #
> Fix MultiUnion Union image description

- docs/user_manual/processing_algs/qgis/vectorgeometry.rst
> Fix version for the drape algorithm offset parameter

- docs/pyqgis_developer_cookbook/loadproject.rst
> Fix flag name and doctest build

- docs/user_manual/processing/batch.rst
> Add subtle properties of the Processing batch outputs

- docs/user_manual/preamble/contributors.rst
Goal: update the list of "Authors" in https://docs.qgis.org/testing/en/docs/user_manual/preamble/contributors.html.
https://github.com/qgis/QGIS-Documentation/graphs/contributors?from=2016-10-31&to=2022-06-26&type=c
The committers without a real name in GitHub: @muranamihdk, @MorriganR.
Ticket(s): #
> Update the list of authors

- docs/user_manual/processing/standalone.rst
Fixes #7239, fixes #7237
Ticket(s): #
> qgis_process accepts json input parameters

- docs/user_manual/expressions/expression.rst
> Update the custom function help and add the context parameter

- docs/user_manual/processing_algs/qgis/cartography.rst
Fixes #7260 
@nirvn may I have your review, please? I'm not sure whether I  got key points and I have no idea what the DPI option is intended for. Thanks.
> Add "Extract labels" algorithm

- docs/pyqgis_developer_cookbook/tasks.rst
Goal:
Add missing module on Task example
> Add missing module on Task example

- docs/training_manual/forestry/map_georeferencing.rst
- docs/user_manual/introduction/qgis_gui.rst
- docs/user_manual/preamble/features.rst
- docs/user_manual/working_with_raster/georeferencer.rst
This PR does not address vector layers georeferencing. It is simply about updating the tool location.
> Make the Georeferencer tool more discoverable

- docs/user_manual/processing_algs/qgis/cartography.rst
Goal:
fixes the "Export print layout as PDF" algorithm name, from "Export print layout as pdf" to "Export print layout as PDF".
See https://github.com/qgis/QGIS/blob/8d25fe973fc5f889daceb05f7175dbee42d430bf/src/analysis/processing/qgsalgorithmlayouttopdf.cpp#L27-L35
Ticket(s): #
> Fix "Export print layout as PDF" alg name

- docs/user_manual/introduction/qgis_gui.rst
Fixes #7279 
Goal:
Ticket(s): #
> Implement 3D map viewers manager #7279

- docs/server_manual/services/wms.rst
Fixes #7596 
If someone can check... @uprel @mhugent ?
Goal:
Ticket(s): #
> Add opacity to external layers in WMS

- docs/server_manual/services/wms.rst
- docs/user_manual/introduction/qgis_gui.rst
- docs/user_manual/working_with_mesh/mesh_properties.rst
> Various fixes and tweaks

- docs/user_manual/introduction/qgis_gui.rst
Fixes #7586
Goal:
Ticket(s): #
> "Terrain elevation offset" is now labeled "Offset"

- docs/user_manual/style_library/label_settings.rst
Fixes #7612, fixes #7396, fixes #7045
> Describe more features of labels settings items

- docs/user_manual/introduction/qgis_configuration.rst
> Reorder sections to match Options dialog

- docs/user_manual/introduction/project_files.rst
I came across situations where people didn't try to apply changes after bad layers are resolved, so let's tell them.
> Tell people to apply changes

- docs/user_manual/introduction/qgis_configuration.rst
Fixes #7306
~~**Todo:** explain all items~~
There are options I'm really unsure what they do or at which level they take place (seems obvious but...) so I'd need some help here.
@antoniolocandro have you got some more details since? Maybe @agiudiceandrea you have some idea? Thanks
> Describe environment custom variables

- docs/server_manual/config.rst
Fixes #7469
@dmarteau mind giving a look please? Thanks.
> Add strategies to refresh project cache on server

- docs/server_manual/plugins.rst
Goal: Server - Add note about useful plugins on server
Some plugins can bring issues if the plugin is used on production and people install them blindly following the documentation.
> Server - Add note about useful plugins on server

- docs/pyqgis_developer_cookbook/plugins/plugins.rst
- docs/user_manual/introduction/qgis_gui.rst
> Add methods to put plugins under Mesh menu

- docs/user_manual/processing_algs/qgis/cartography.rst
to "print layouts to PDF" algorithms (fixes #7653)
> Add FORCE_RASTER and IMAGE_COMPRESSION parameters

- docs/user_manual/print_composer/composer_items/composer_tables.rst
> Layout attribute table follows layer conditional styling rules

- Makefile
- conf.py
I think these are the necessary bits on GitHub side.
@rduivenvoorde ?
> Generate PDF for the "Gentle Introduction to GIS" document

- docs/user_manual/processing/batch.rst
> Detail "Add files by pattern option"

- docs/pyqgis_developer_cookbook/plugins/plugins.rst
- docs/pyqgis_developer_cookbook/plugins/snippets.rst
Fixes #4232
And thanks to @Guts for the icons reuse tip (https://static.geotribu.fr/articles/2021/2021-01-19_pyqgis_utiliser_icones_integrees/ - sorry, in French)
> Add tips and good practice for plugins developers

- docs/user_manual/processing/toolbox.rst
> Add small note for 'Change Parameters' button

- docs/user_manual/introduction/qgis_gui.rst
- docs/user_manual/working_with_mesh/mesh_properties.rst
- docs/user_manual/working_with_vector/editing_geometry_attributes.rst
FYI, I added captions to a few that were on my way. so if someone wants to track and update the remaining ones :clap:
> Properly add caption to tables, allowing them to be numbered, same as figures

- docs/user_manual/print_composer/composer_items/composer_scale_bar.rst
Goal:
Update **Fit segments width** section to be clearer. 
Question: scalebar or scale bar?
I added a bug report with this as well. https://github.com/qgis/QGIS/issues/49095
It might make sense to wait on the discussion there before adding this. 
Ticket(s): #
> [WIP] Scalebar Fit segments width

- docs/user_manual/processing_algs/qgis/rastertools.rst
Goal:
"[Convert map to raster](https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/qgis/rastertools.html#convert-map-to-raster)" algorithm is a "native" (C++) algorithm since 3.12.
Ticket(s): #
> "Convert map to raster" algorithm is "native"

- docs/user_manual/working_with_vector/editing_geometry_attributes.rst
> Address digitizing tools refactoring

- docs/user_manual/working_with_vector/editing_geometry_attributes.rst
> Describe logic of digitizing vector with z or m

- docs/user_manual/introduction/general_tools.rst
Add Mesh and point cloud layers and reorder columns
also add title to a few tables
> Update layers contextual menu

- docs/user_manual/processing/configuration.rst
> [processing] Add option to show feature count for vector outputs

- docs/server_manual/services/ogcapif.rst
Goal: 
Add missing custom template function:
https://github.com/qgis/QGIS/blob/1d9495b8a946c3a64758807a8f4c9ee4003ee208/src/server/qgsserverogcapihandler.h#L221
https://github.com/qgis/QGIS/blob/1d9495b8a946c3a64758807a8f4c9ee4003ee208/src/server/qgsserverogcapihandler.cpp#L375-L380
> Add missing custom template function

- docs/server_manual/config.rst
> Document QGIS_SERVER_ALLOWED_EXTRA_SQL_TOKENS

- docs/server_manual/services/ogcapif.rst
Goal:
Document custom template function "starts_with"
-> https://github.com/qgis/QGIS/pull/50139
> Document custom template function "starts_with"

- docs/user_manual/processing_algs/qgis/vectorgeometry.rst
> Add repair method to Fix geometries algorithm

- docs/user_manual/expressions/expression_help/GeometryGroup.rst
- docs/user_manual/expressions/expression_help/Record_and_Attributes.rst
- docs/user_manual/expressions/functions_list.rst
Fixes #7773
Goal:
Ticket(s): #
> Update expression functions and variables docs

- docs/server_manual/config.rst
Fix #7777
CC @rldhont 
@elpaso The list is ordered alphabetically so I have updated your latest entry ;-)
> Server - Add the new read only environment variable

- docs/pyqgis_developer_cookbook/intro.rst
Add ``--code`` param and add more information here and there
> Add --code and --py-args param to startup.py docs

- docs/user_manual/working_with_vector/vector_properties.rst
Use a numbered list to emphasize steps and options, as for other renderers
Add some precision in description
Add "label distance factor" option (fixes #3597)
> Update point displacement and point cluster renderers

- docs/server_manual/getting_started.rst
making instructions easier to decrypt and fix fastCGI/fcgid typo
Fix #7749 
Goal:
Ticket(s): #
> Use numbered list for steps to configure server on Linux

- .github/workflows/stale.yml
when request for feedback is ignored
> Create action to stale and close issue reports and PR

- docs/user_manual/introduction/qgis_gui.rst
> No more plugins update info on status bar

- docs/user_manual/working_with_mesh/mesh_properties.rst
This is the first of a series of PR that address issues related to mesh digitizing. Because it resulted in a big document and to make it reviewable :crossed_fingers: I split the work into "thematically" self-contained PRs that you can pick and review easily. Despite the hours spent on reading, testing and writing, I'm not a mesh user so other pairs of eyes are still welcome.
The main structure [in the docs](https://docs.qgis.org/testing/en/docs/user_manual/working_with_mesh/mesh_properties.html) is as follow:
Some of the next PRs are expected to fail because they have links to other PRs but that shouldn't refrain from reviewing... 
If ever you are looking for mesh data, you might find at https://github.com/lutraconsulting/MDAL/tree/master/tests/data
> Introduce the mesh editing tools

- docs/user_manual/working_with_mesh/mesh_properties.rst
Fixes #6918, fixes #6932
Completes #7729
> Add "Transform mesh Vertices" tool

- docs/user_manual/working_with_mesh/mesh_properties.rst
refs #6883, fixes #6882, refs qgis/QGIS#45040, refs qgis/QGIS#44835
Completes #7729
> Describe ways to select mesh elements

- docs/user_manual/introduction/qgis_gui.rst
- docs/user_manual/working_with_mesh/mesh_properties.rst
> Reindex faces and vertices

- docs/user_manual/introduction/qgis_configuration.rst
> No more debugging section in global Rendering Options

- docs/user_manual/expressions/expression_help/Operators.rst
- docs/user_manual/expressions/functions_list.rst
- scripts/populate_expressions_list.py
refs https://github.com/qgis/QGIS/pull/50322
> Update between and not between functions documentation

- docs/user_manual/processing/configuration.rst
Extracted from #6886 to stop blocking that PR and in the hope that this one will get a feedback (see https://github.com/qgis/QGIS-Documentation/pull/6886#discussion_r692112201)
> Describe output folder related settings for Processing

- .github/workflows/translation_statistics.yml
- conf.py
- docs/user_manual/preamble/contributors.rst
- docs/user_manual/preamble/preamble.rst
> Only recommend latest LTR and hide translation stats in testing docs

- docs/user_manual/expressions/functions_list.rst
For any layer in the project, it is possible to display connected fields, should they be stored in the layer, joined, virtual, auxiliary
Refs https://github.com/qgis/QGIS/pull/46505
> All fields are available in expression dialog functions tree

- docs/pyqgis_developer_cookbook/plugins/snippets.rst
> Allow key shortcuts customization for plugin actions

- docs/user_manual/working_with_mesh/mesh_properties.rst
Fixes #6883, refs qgis/QGIS#45140
Completes #7729
> Describe some mesh edits processes

- conf.py
- docs/user_manual/preamble/contributors.rst
- docs/user_manual/preamble/preamble.rst
> [3.22] Only recommend latest LTR and hide translation stats in testing docs

- docs/user_manual/working_with_vector/vector_properties.rst
> Introduce vector profile chart appearance section

- docs/pyqgis_developer_cookbook/geometry.rst
Fixes #3221, fixes #3222
Goal:
Ticket(s): #
> Direct access to parts of a geometry collection

- release_process.md
> Update actions for releasing a new version docs

- docs/user_manual/working_with_vector/editing_geometry_attributes.rst
> Clarify behavior and steps of trim/extend tool

- release_process.md
> Memo for other repos we depend on for release

- docs_conf.yml
- scripts/fix_versions.sh
> Say "Bye" to some old versions

- docs/pyqgis_developer_cookbook/canvas.rst
Fixes #5842 
Thanks to @jakimowb for the code snippet
> Add entries to map canvas contextual menu

- redirects.txt
> Redirect old core plugins pages

- docs/user_manual/preamble/features.rst
Just link to the man page here. I think this should be sufficient
> Add pointer to prlimit, fixes #6012

- .github/workflows/stale.yml
a PR for testing the bot
Ticket(s): #
> Readjusting the stale action options

- docs/user_manual/style_library/3d_symbols.rst
fixes #2139
Goal:
Ticket(s): #
> Add supported model formats

- docs/user_manual/expressions/expression_help/Maps.rst
- docs/user_manual/expressions/expression_help/Rasters.rst
refs #7887 (partial fix)
Goal:
Ticket(s): #
> Add raster maptip related expression functions

- docs/developers_guide/localization.rst
- docs/developers_guide/processingtesting.rst
- docs/developers_guide/unittesting.rst
- docs/documentation_guidelines/do_translations.rst
- docs/gentle_gis_introduction/authors_and_contributors.rst
- docs/training_manual/processing/more_backends.rst
- docs/user_manual/grass_integration/grass_integration.rst
- docs/user_manual/introduction/getting_started.rst
- docs/user_manual/managing_data_source/supported_data.rst
> Fix various broken URL reported by make linkcheck

- docs/developers_guide/codingstandards.rst
> Improve coding standards with various connections to source code

- docs/user_manual/expressions/expression_help/GeometryGroup.rst
- docs/user_manual/expressions/functions_list.rst
> Add coordinate extractors functions and link the deprecated ones to newer

- docs/user_manual/managing_data_source/supported_data.rst
refs https://github.com/qgis/QGIS-Documentation/issues/478#issuecomment-1322193483
> More descriptive steps for restoring layer styles in PG database

- docs/user_manual/processing_algs/qgis/vectoroverlay.rst
Fixes #7891 
Goal:
Ticket(s): #
> Split features with polygons

- docs/server_manual/services/basics.rst
A typo I think.
@pblottiere mind giving a look, please? Thanks
Goal:
Ticket(s): #
> Fix parameter name

- docs/server_manual/config.rst
Fixes #6653
Goal: add documentation about service URL
Ticket(s): #
> Add service URL documentation

- docs/server_manual/config.rst
> [Backport] Add service URL environment variables

- docs/user_manual/introduction/qgis_configuration.rst
> Predefined scales are used in more than the status bar widget

- docs/documentation_guidelines/substitutions.rst
- docs/training_manual/forestry/stands_digitazing.rst
> Minor cleanup while running find_set_subst script

- docs/user_manual/expressions/expression_help/Record_and_Attributes.rst
- docs/user_manual/expressions/functions_list.rst
- docs/user_manual/working_with_vector/vector_properties.rst
> Add is_attribute_valid and is_feature_valid functions

- docs/user_manual/working_with_vector/vector_properties.rst
cherry-pick 96b39963d
Goal:
Ticket(s): #
> Use soft and hard constraints vocabulary

- docs/user_manual/processing_algs/qgis/database.rst
- docs/user_manual/processing_algs/qgis/vectoranalysis.rst
- docs/user_manual/processing_algs/qgis/vectoroverlay.rst
Package layers (fixes #7713)
Add Grid size parameter to Overlay algorithms (fixes #7778)
> Add new parameters for Processing algorithms

- README.md
> Update URL of transifex-github integration page

- docs/user_manual/expressions/expression_help/Record_and_Attributes.rst
- docs/user_manual/expressions/functions_list.rst
Fixes #7955 
Goal:
Ticket(s): #
> Add feature_id function and connect related functions

- docs/server_manual/services/wfs.rst
> Add an example to the WFS maxfeatures parameter

- docs/user_manual/introduction/qgis_gui.rst
- docs/user_manual/working_with_vector_tiles/vector_tiles_properties.rst
Add missing menu actions, references or shortcuts
Avoid duplicate list of panels and toolbars
Add missing captions to the tables
> Updates QGIS GUI chapter

- docs/user_manual/working_with_mesh/mesh_properties.rst
Fixes #7967 
and a few lines formatting
> Vertices of a new face can be added with single click

- docs/user_manual/processing_algs/qgis/rastertools.rst
Document three new optional advanced parameters (QGIS 3.30), ref https://github.com/qgis/QGIS/pull/51522.
Also: Remove duplicated output entries.
> [rastertools/tilesxyzdirectory] Document new parameters

- .github/dependabot.yml
To get automatically pull request for version bumps like in https://github.com/qgis/QGIS/pull/51348.
ref. https://github.com/qgis/QGIS-Documentation/pull/7994
> Activate depandabot for github-actions

- REQUIREMENTS.txt
> Remember to update requirements for servers

- docs/user_manual/map_views/map_view.rst
- docs/user_manual/processing_algs/qgis/cartography.rst
To clarify what kind of annotations are expected to be transferred
> Add hyperlink to layer annotation from dedicated algorithm

- docs/user_manual/processing_algs/qgis/rastertools.rst
> Add the version of xyz directory alg advanced parameters

- docs/user_manual/processing_algs/qgis/rastertools.rst
> Missing details in XYZ directory algorithm

- docs/user_manual/processing_algs/gdal/vectorconversion.rst
Goal: Add missing "Additional command-line parameters" advanced parameter
Ticket(s): #
> Fix "Rasterize (vector to raster)" docs

- docs/user_manual/introduction/qgis_gui.rst
- docs/user_manual/map_views/map_view.rst
> Update anchor to match dialog help URL

- docs/user_manual/processing_algs/algs_include.rst
- docs/user_manual/processing_algs/gdal/rasteranalysis.rst
- docs/user_manual/processing_algs/gdal/rasterconversion.rst
- docs/user_manual/processing_algs/gdal/rasterextraction.rst
- docs/user_manual/processing_algs/gdal/rastermiscellaneous.rst
- docs/user_manual/processing_algs/gdal/rasterprojections.rst
- docs/user_manual/processing_algs/gdal/vectorconversion.rst
- docs/user_manual/processing_algs/qgis/rasteranalysis.rst
> Use an include for raster data type lists

- docs/user_manual/processing_algs/qgis/rasteranalysis.rst
> Swap Indices for Int32 and UInt32 raster data types

- docs/user_manual/processing_algs/gdal/rasterextraction.rst
> Add missing blank line

- docs/user_manual/expressions/expression_help/String.rst
Goal: Fixes #8033
Ticket(s): #
> Update format_number function

- docs/user_manual/working_with_ogc/ogc_client_support.rst
The first limitation no more exists. How about the second one?
> Remove outdated WMS client limitations

- docs/user_manual/working_with_vector/vector_properties.rst
follow-up #8041
Goal:
Ticket(s): #
> GUI label cosmetics

- docs/user_manual/working_with_vector/vector_properties.rst
Partial backport of #8025 
Goal:
Ticket(s): #
> Mention the other widgets

- docs/user_manual/managing_data_source/supported_data.rst
and not a subsection of PG data. I'd consider this closes #1911 and suggest opening a new report for improvements regarding raster or other tools. Opinions @SrNetoChan ?
> Make the "Crossing 180° longitude line" a section of its own

- docs/pyqgis_developer_cookbook/plugins/plugins.rst
follow-up https://github.com/qgis/QGIS-Documentation/pull/7958#discussion_r1071293923
before vs after:
Goal:
Ticket(s): #
> Move up and raise level of the "Share your plugin" section

- .github/workflows/pofiles.yml
- REQUIREMENTS.txt
- conf.py
Backports #7972
Goal:
Ticket(s): #
> Add sphinx_copybutton extension

- .github/workflows/builds.yml
- .github/workflows/doctest.yml
- .github/workflows/pofiles.yml
- .github/workflows/translation_statistics.yml
(cherry picked from commit ffd66434f02183d6a983086ea86c5abe40dec3ea)
Backports #7616
Goal:
Ticket(s): #
> [3.22] Upgrade dependencies version for github actions

- .github/workflows/builds.yml
- .github/workflows/doctest.yml
- .github/workflows/pofiles.yml
- .github/workflows/translation_statistics.yml
backports #7994 
Goal:
Ticket(s): #
> Update actions/setup-python for workflows

- docs/pyqgis_developer_cookbook/plugins/snippets.rst
Fixes #1115
credits to @rduivenvoorde
https://qgis.nl/2019/02/14/about-layer-tree-embedded-widgets-and-have-your-wmts-always-crispy-sharp/?lang=en
> Add embedded layer tree widget

- docs/pyqgis_developer_cookbook/geometry.rst
- docs/pyqgis_developer_cookbook/network_analysis.rst
> code samples are failing due to changes in WkbTypes outputs and some geometry calculation method(?)

- release_process.md
> Remove duplicate instruction

- docs/developers_guide/git.rst
Fixes #8000 
Goal:
Ticket(s): #
> No, Marco does not manage PR queue

- docs/pyqgis_developer_cookbook/network_analysis.rst
partial backport of #8072 
Goal:
Ticket(s): #
> Remove boolean from QgsRubberband creation parameters

- docs/user_manual/processing/toolbox.rst
This was an outdated limitation
> Fix inaccuracy in vector layer description

- docs/server_manual/getting_started.rst
Goal:
Replace the line
`sh -c "echo '127.0.0.1 qgis.demo' >> /etc/hosts"``.`
with
`sh -c "echo '127.0.0.1 qgis.demo' >> /etc/hosts"`
Ticket(s): #
> Fix QGIS Server installation Getting Started

- docs/user_manual/working_with_vector/editing_geometry_attributes.rst
An attempt to make it more obvious that 3D features can be edited (refs and should somehow close
https://github.com/qgis/QGIS-Documentation/issues/3675#issuecomment-482476412)
> More mention of 3D features as digitizable

- .github/workflows/pull_minimized_translations.yml
- README.md
- release_process.md
- scripts/minimize_translation.sh
Fixes #7827 (_finally!!!_)
Goal:
Ticket(s): #
> Add action to automatically pull unfinished translated files twice a month

- REQUIREMENTS.txt
Fixes #8024
Supersedes #8034 
Would be easier to maintain if website requirements change...
Goal:
Ticket(s): #
> Let's fully depend on QGIS-Website requirements

- .github/workflows/pull_minimized_translations.yml
> tx not found

- conf.py
> Say "Bye bye" to 3.22 LTR

- docs/documentation_guidelines/substitutions.rst
- docs/gentle_gis_introduction/introducing_gis.rst
- docs/training_manual/appendix/preparing_data.rst
- docs/training_manual/basic_map/overview.rst
- docs/training_manual/complete_analysis/analysis_exercise.rst
- docs/training_manual/map_composer/dynamic_layout.rst
- docs/user_manual/print_composer/overview_composer.rst
- docs/user_manual/style_library/symbol_selector.rst
and some minor changes
Goal:
Ticket(s): #
> Replace "File" menu with "Project"

- docs_conf.yml
- scripts/fix_versions.sh
> Remove 2.8 and 2.14 from bottom menu

- docs/user_manual/processing_algs/qgis/vectorcreation.rst
Small documentation update to cover the change in #8123 
Upstream change is https://github.com/qgis/QGIS/pull/51973
> mention importphotos additional supported formatsi (#8123)

- docs/user_manual/processing_algs/gdal/rasterconversion.rst
Doc for PR [#52187](https://github.com/qgis/QGIS/pull/52187)
Fixes #8127
> gdal2xyz skipnodata and src/dstnodata param docs

- scripts/load_tx_stats.py
Also take into account the _notranslate_ strings tagged in Transifex (stats show what people actually translate...)
Goal:
Ticket(s): #
> Simplify the load translation script using functions

- docs/user_manual/expressions/expression_help/GeometryGroup.rst
- docs/user_manual/expressions/expression_help/Operators.rst
- docs/user_manual/expressions/expression_help/Record_and_Attributes.rst
> [3.28] Update expression functions help

- scripts/create_transifex_resources.sh
Otherwise it is not possible to pull unfinished translated files from Transifex
Goal:
Ticket(s): #
> Update scripts to generate .tx/config file formatting

- .tx/config
- scripts/create_transifex_resources.sh
allowing us to pull translation from Transifex, and update the config file accordingly
Goal:
Ticket(s): #
> [3.28] Update scripts to generate .tx/config file formatting

- .github/workflows/auto-label.yml
Removes obsolete naturalclar/issue-action in favor of custom script
Add step to assign milestone (fixes #7828)
Goal:
Ticket(s): #
> Improve automatic labeling and milestoning of generated issues

- Makefile
- README.md
- conf.py
- docs/index.rst
- docs/pyqgis_developer_cookbook/plugins/plugins.rst
- release_process.md
- scripts/minimize_translation.sh
> A bit of cleanup around transifex urls

- docs/user_manual/working_with_vector/attribute_table.rst
Fix https://github.com/qgis/QGIS-Documentation/issues/7395 .
> Added documentation about horizontal scrolling with shift

- docs/server_manual/services/wms.rst
> Server - Add the feature display name to the WMS GetFeatureInfo

- docs/training_manual/online_resources/wms.rst
Uses working MapServer demo WMS as example answer in training manual
Fixes https://github.com/qgis/QGIS-Documentation/issues/6455
> Use MapServer demo WMS as example answer

- docs/documentation_guidelines/substitutions.rst
> Tweak instructions on substitutions addition

- docs/documentation_guidelines/substitutions.rst
- docs/server_manual/plugins.rst
- docs/user_manual/print_composer/composer_items/composer_map.rst
- docs/user_manual/working_with_mesh/mesh_properties.rst
- docs/user_manual/working_with_vector/editing_geometry_attributes.rst
- substitutions.txt
> Fixing various substitutions

- .github/workflows/translation_statistics.yml
> Modify logic of stats reports and fix broken action

- docs/documentation_guidelines/writing.rst
> Use github repo for sample dataset instead of download.qgis.org

- conf.py
- themes/rtd_qgis/versions.html
Fixes #8195 
Goal:
Ticket(s): #
> Update way to reach Transifex pages

- docs/user_manual/working_with_ogc/ogc_client_support.rst
no more "build query" button
Goal:
Ticket(s): #
> Update add WFS layer dialog and the filtering process

- docs/server_manual/getting_started.rst
- docs/server_manual/services/wcs.rst
- docs/server_manual/services/wms.rst
> Add separate example for each type of installation process

- .github/CONTRIBUTING.md
- docs/documentation_guidelines/first_contribution.rst
to make use of github contributing page
Goal:
Ticket(s): #
> Replace the "easy fix" label with "good first issue"

- docs/training_manual/vector_classification/attribute_data.rst
Fixes #8241 
Goal:
Ticket(s): #
> Provider clearer way to find tools for attribute table

- docs/documentation_guidelines/do_translations.rst
- docs/documentation_guidelines/index.rst
fixes #8228 
Goal:
Ticket(s): #
> Update process for (publishing) translations

- docs/user_manual/map_views/index.rst
> Fix "Visualizing maps" chapter is not generated in PDF

- .github/workflows/pull_minimized_translations.yml
- scripts/minimize_translation.sh
make the script more permissive to not lose actual translation (and hopefully run in a more reasonable time)
Also fix and simplify the corresponding github action
refs https://github.com/qgis/QGIS-Documentation/issues/8228#issuecomment-1533681723
> Update script to pull optimized translated strings

- docs/user_manual/introduction/qgis_gui.rst
Fixes #8269 
Goal:
Ticket(s): #
> Remove unnecessary and misleading message on toolbars

- docs/user_manual/processing_algs/qgis/rastercreation.rst
refs https://github.com/qgis/QGIS/pull/52855
Goal:
Ticket(s): #
> Update default PIXEL_SIZE for create raster algorithms

- .github/workflows/translation_statistics.yml
> Temporarily disable automerge to check why PR tests do not start upon opening

- docs/user_manual/introduction/qgis_gui.rst
- docs/user_manual/working_with_ogc/ogc_client_support.rst
Fixes https://github.com/qgis/QGIS-Documentation/issues/8290.
> Change "Add WFS Layer" to "Add WFS / OGC API - Features Layer"

- docs/training_manual/vector_analysis/basic_analysis.rst
Fixes #8255
Goal:
Ticket(s): #
> macOS asks to overwrite the gpkg upon saving a new layer

- docs/user_manual/processing_algs/algs_include.rst
- docs/user_manual/processing_algs/gdal/rastermiscellaneous.rst
Also align gdal raster calculator data types to other algs'
refs https://github.com/qgis/QGIS/pull/51755
> Add int8 raster data type to Processing algorithms

- docs/training_manual/qgis_server/install.rst
> The debian package is now named python3-qgis

- docs/user_manual/working_with_point_clouds/point_clouds.rst
namely draw order  (fixes #7291) and 2d eye dome lighting (fixes #7754)
@NedjimaBelgacem @uclaros (and BTW if I can get feedback on #8223 ...). Thanks
Goal:
Ticket(s): #
> Add more Point cloud Symbology Layer rendering options

- docs/user_manual/processing_algs/gdal/rasteranalysis.rst
- docs/user_manual/processing_algs/gdal/rasterextraction.rst
- docs/user_manual/processing_algs/gdal/rastermiscellaneous.rst
- docs/user_manual/processing_algs/gdal/rasterprojections.rst
- docs/user_manual/processing_algs/gdal/vectorconversion.rst
Fixes #8243
note: I did not test. Just assumed based on the widget type and #8095
@SrNetoChan ?
Goal:
Ticket(s): #
> Add mention of pipe usage when adding GDAL creation options in modeler

- docs/user_manual/preamble/foreword.rst
My first pull request, while lerning working on QGIS documentation with Tim.
> Update preamble mention Android and iOS.

- docs/documentation_guidelines/first_contribution.rst
> Remove unnecessary hyphen

- docs/user_manual/processing_algs/qgis/vectorgeneral.rst
- docs/user_manual/processing_algs/qgis/vectortable.rst
- docs/user_manual/working_with_vector/vector_properties.rst
* Add "Convert curved geometries" to reproject layer algorithm (fixes #8148)
* Add field comment and alias parameters to Processing algorithms (fixes #8190 and fixes #8213)
> Misc algorithm parameters

- docs/user_manual/print_composer/composer_items/composer_map3d.rst
- docs/user_manual/print_composer/composer_items/index.rst
- docs/user_manual/print_composer/composer_items/layout_elevation_profile.rst
- docs/user_manual/print_composer/overview_composer.rst
Fixes #8361
Goal:
Ticket(s): #
> Add layout elevation profile item description

- docs/user_manual/working_with_vector/editing_geometry_attributes.rst
> Snapping and floater options in Advanced digitizing panel

- docs/user_manual/introduction/qgis_gui.rst
Oracle database option was missing from Project Menu
> Added Oracle in Project menu section 7.1.1.

- docs/user_manual/introduction/qgis_gui.rst
"Add SAP HANA Spatial Layer" was missing from Layer menu.
> Added SAP HANA item to Layer menu

- docs/user_manual/working_with_vector/vector_properties.rst
and add some widget properties (makes room for recent changes description)
Supersedes #7705
Goal:
Ticket(s): #
> Update container's creation and configuration

- docs/user_manual/introduction/qgis_gui.rst
- docs/user_manual/processing_algs/qgis/rasterterrainanalysis.rst
> Adjust outputs of the raster terrain analysis algorithms

- docs/user_manual/map_views/map_view.rst
> Center align the annotation video frame

- docs/user_manual/processing_algs/qgis/vectorgeneral.rst
> Update output destination list for vector general algorithms

- docs/user_manual/print_composer/overview_composer.rst
Fixes #7959 Added Keyboard shortcuts in the print layouts.
> Shortcut manager added in the Print layout interface #7959

- docs/user_manual/print_composer/overview_composer.rst
> Add url reference for layout marker item

- docs/user_manual/processing_algs/qgis/vectorgeneral.rst
refs qgis/QGIS#54344
Goal:
Ticket(s): #
> Make "convert curved geometries" parameter optional

- docs/user_manual/introduction/qgis_configuration.rst
also refs https://github.com/qgis/QGIS-Documentation/pull/4695#issuecomment-571035341
Goal:
Ticket(s): #
> Provide more info for the "planimetric measurement" option

- docs/user_manual/processing/console.rst
- docs/user_manual/processing/modeler.rst
- docs/user_manual/processing/scripts.rst
- docs/user_manual/processing_algs/qgis/vectortiles.rst
Also update Processing parameter types lists
Fixes #8275, fixes #8161
Goal:
Ticket(s): #
> Add "Download vector tiles" algorithm

- docs/user_manual/processing_algs/qgis/rasterterrainanalysis.rst
Fixes #8401 
Goal:
Ticket(s): #
> Add DTM filter (slope-based) algorithm

- docs/user_manual/processing_algs/qgis/vectorgeometry.rst
> Fix plural

- docs/user_manual/managing_data_source/opening_data.rst
> Make it obvious that metadata search panel is for layer loading

- docs/server_manual/services/wms.rst
This is an attempt to fix #8292 
It assumes I understand what it is about because of the various points I already raised at https://github.com/qgis/QGIS/pull/52799#issuecomment-1614265126. I could have put it in draft mode but considering that I can't do anything more, better have it reviewed by those who actually know, and fill the `???` gaps in the PR.
@mhugent ?
> Add Server pdf format options

- docs/training_manual/complete_analysis/analysis_exercise.rst
- docs/training_manual/forestry/parameters_calculation.rst
- docs/training_manual/grass/grass_setup.rst
- docs/user_manual/processing_algs/gdal/vectormiscellaneous.rst
- docs/user_manual/processing_algs/qgis/rasteranalysis.rst
by tmiyoshi
Goal:
Ticket(s): #
> Fix misc issues reported in Transifex

- docs/user_manual/preamble/translation_stats.rst
Manually run given that the automated action no longer runs at all 😢 
Goal:
Ticket(s): #
> Add translation statistics

- docs/user_manual/working_with_vector/vector_properties.rst
Fixes #8515 
Goal:
Ticket(s): #
> Harmonize tabs icon placement

- docs/user_manual/working_with_raster/raster_properties.rst
> Move down Elevation section to align with the Raster properties dialog

- docs/pyqgis_developer_cookbook/tasks.rst
Goal:
- clarify a few things on tasks
> 1 warning, 1 info on tasks

- docs/pyqgis_developer_cookbook/tasks.rst
to avoid this rendering
I don't know if instance is the correct word, here. anyone? @why-not-try-calmer ?
> Fix text in italic

- docs/user_manual/processing_algs/qgis/vectorgeometry.rst
> Add details on "bounding boxes" algorithm output

- docs/user_manual/introduction/general_tools.rst
* Add some `guilabels:` into the RST to highlight these buttons
It can be backported if possible.
Is-it a good way to go ?
> Review the SVG button explainations

- docs/user_manual/map_views/elevation_profile.rst
> Option Add layers added to elevation profile

- docs/user_manual/map_views/elevation_profile.rst
> Export elevation profiles option added

- docs/user_manual/working_with_vector/attribute_table.rst
> Add info to attribute table conditional formatting

- docs/user_manual/working_with_vector/editing_geometry_attributes.rst
refs https://github.com/qgis/QGIS/issues/54746 (or should I say "fixes"?)
> Explain how to enable/use shape digitizing tools

- docs/user_manual/working_with_vector/vector_properties.rst
Fixes #8199 and update scope of map tips across projects
> Mention "Enable map tips" checkbox

- docs/user_manual/introduction/general_tools.rst
> Identify tool for raster layer added #8503

- docs/user_manual/map_views/elevation_profile.rst
Fixes #8279, refs #8296 
Goal:
Ticket(s): #
> Expand the Options' drop-down menu in Elevation Profile toolbar

- docs/user_manual/introduction/qgis_configuration.rst
found during translation operation
Goal:
Ticket(s): #
> Fixes typos

- docs/user_manual/working_with_mesh/mesh_properties.rst
- docs/user_manual/working_with_raster/raster_properties.rst
- docs/user_manual/working_with_vector/vector_properties.rst
(fixes #8282) and harmonize descriptions
Goal:
Ticket(s): #
> Adding elevation Fill Above properties

- docs/user_manual/processing_algs/qgis/3dtiles.rst
- docs/user_manual/processing_algs/qgis/index.rst
- docs/user_manual/processing_algs/qgis/modelertools.rst
Fixes #8473, fixes #8577
Goal:
Ticket(s): #
> Add 3D Tiles algorithms

- release_process.md
taking into account various recent improvements
Goal:
Ticket(s): #
> Update the release process notes

- .github/workflows/pofiles.yml
The action is already run after PR so there is [nothing to work with later](https://github.com/qgis/QGIS-Documentation/actions/workflows/pofiles.yml?query=event%3Aschedule), and we have the workflow_dispatch if necessary
Goal:
Ticket(s): #
> Remove noisy, failing and unnecessary scheduled job

- docs/user_manual/processing/standalone.rst
@nyalldawson @m-kuhn Ignoring the status of the different solutions you planned in the mentioned issue report, here is a PR with the suggested hint. Let me know if it is still necessary or not. Thanks.
Goal: Fixes #7947
> Add hint for qgis_process usage on systems without window manager

- docs/server_manual/services/wms.rst
> SERVER: add getlegendgraphics SHOWRULEDETAILS

- docs/user_manual/style_library/symbol_selector.rst
Add note about SVG parameters
from https://gis.stackexchange.com/questions/469042/parameterizing-svg-text-rotation-in-qgis/469439#469439
> note for SVG parameters

- docs/user_manual/map_views/map_view.rst
Fixes #8482 
Goal:
Ticket(s): #
> Scale bar decorations follow project distance unit

- docs/server_manual/services/wms.rst
Picked from #8584 
Goal:
Ticket(s): #
> Tweaks wms services description

- docs/server_manual/services/wms.rst
Available since https://github.com/qgis/QGIS/pull/37068
Goal:
Ticket(s): #
> Document the WEBP format for GetMap

- docs/user_manual/introduction/qgis_configuration.rst
Fixes #8629
Goal:
Ticket(s): #
> Use correct image for elevation settings

- docs/server_manual/services/wms.rst
Fixes #8647 
Goal:
Ticket(s): #
> Add PDF format to WMS GetMap requests

- docs/user_manual/working_with_point_clouds/point_clouds.rst
> Better indentation of filtered layers tip for point clouds

- docs/user_manual/processing_algs/qgis/rasteranalysis.rst
Goal: Document other values that can be used in reclassify by table. 
Ticket(s): fix #8650
- [ x] Backport to LTR documentation is requested
> Add -inf inf and nan

- docs/user_manual/processing_algs/qgis/vectorgeometry.rst
Update Concave Hull, Delaunay triangulation and Voronoi polygons
Delete deprecated Concave hull (k-nearest neighbor) algorithm
Fixes #8548
> Update vector geometry algorithms

- docs/user_manual/managing_data_source/opening_data.rst
Add note about QGIS server in PG Service section
> Add note about QGIS server in PG Service section

- docs/user_manual/working_with_vector_tiles/vector_tiles.rst
Describe the items for rules creation
Add Layer rendering options and a reference to layer style options
completes #8639
An update of the screenshot would be welcome when we find a more verbose vector tile
Goal:
Ticket(s): #
> Exploring the Symbology and Labels tabs of vector tiles

- docs/index.rst
- docs/user_manual/expressions/expression_help/Map_Layers.rst
- docs/user_manual/grass_integration/grass_integration.rst
- docs/user_manual/introduction/qgis_configuration.rst
- docs/user_manual/map_views/map_view.rst
- docs/user_manual/preamble/contributors.rst
- docs/user_manual/processing_algs/qgis/rastertools.rst
and update version references and expression help.
> [3.34] Indicate the version in which the align rasters algs were introduced

- docs/user_manual/working_with_3d_tiles/3d_tiles.rst
> layer rendering options added

- .mailmap
Highly inspired by https://github.com/qgis/QGIS/pull/55547. Thanks @gacarrillor
> Create a mailmap file for committers

- docs/pyqgis_developer_cookbook/settings.rst
Goal: fixes the global settings filename. @elpaso could you please have a look?
Ticket(s): #
> PyQGIS Developer Cookbook: fix qgis_global_settings.ini file name

- docs/documentation_guidelines/substitutions.rst
- docs/user_manual/introduction/browser.rst
- docs/user_manual/introduction/general_tools.rst
- docs/user_manual/managing_data_source/opening_data.rst
- docs/user_manual/working_with_3d_tiles/3d_tiles.rst
- docs/user_manual/working_with_projections/working_with_projections.rst
- substitutions.txt
> Substitutions list cleanup running find_set_subst.py script

- docs/user_manual/working_with_ogc/ogc_client_support.rst
> Load and save buttons added to OGC server connection

- docs/user_manual/working_with_ogc/ogc_client_support.rst
to connection creation instructions (followup #8723).... on second reading
@selmaVH1 what do you think about this?
Goal:
Ticket(s): #
> Mention Load and Save connections buttons closer

- docs/user_manual/print_composer/composer_items/composer_map.rst
Fixes #5843
Goal:
Ticket(s): #
> Use text format capabilities for layout map grid text

- docs/user_manual/introduction/qgis_configuration.rst
- docs/user_manual/processing/toolbox.rst
fixes #8502
Goal:
Ticket(s): #
> Default values can be set for alg parameters in INI file

- docs/server_manual/config.rst
> Add example for pointing a QGIS Project on a Geopackage

- docs/user_manual/style_library/symbol_selector.rst
> Add height setting for raster fill symbol layer type

- docs/user_manual/working_with_gps/live_GPS_tracking.rst
I just adjust sections titles and levels, and instruct to use the new interface tools
BUT I don't really know if those instructions are still necessary in 2024, or worth it.
> [GPS] 5 - Simplify TOC for GPS devices connection examples

- docs/user_manual/processing/standalone.rst
> Add skip-loading-plugins to qgis_process

- docs/user_manual/map_views/3d_map_view.rst
Fixes #8759 
The build is expected to fail as this PR needs #8761 to be merged first.
> Add shortcut to set 3D extent on map canvas

- docs/user_manual/managing_data_source/opening_data.rst
> Local XYZ tiles options

- docs/server_manual/services/wms.rst
Fixes #8794
@pathmapper TBH I have no idea whether this is the correct information for describing the changes. Your input will be appreciated...
> Add HTML_FI_ONLY_MAPTIP value to GetFeatureInfo WITH_MAPTIP parameter

- docs/user_manual/expressions/functions_list.rst
Fixes #8769
Goal:
Ticket(s): #
> Update layer_cursor_point variable

- .github/dependabot.yml
- release_process.md
> Allow automatic backport of dependabot changes to other branches

- docs/user_manual/managing_data_source/opening_data.rst
Fixes #8001
Just a small tip added, most of the diff being paragraphs moved in the section in order to make a better room for the tip
> Loading XYZ tiles without creating a connection

- docs/server_manual/config.rst
Ticket(s): Linked to PR https://github.com/qgis/QGIS/pull/56213
> Update doc about QGIS_SERVER_PROJECT_CACHE_CHECK_INTERVAL

- docs/server_manual/services/wms.rst
LAYERATTRIBUTES (singular LAYER)
> Fix typo in server's LAYERATTRIBUTES

- docs/server_manual/services/wms.rst
Added more information about how several layers should be configured.
Goal:
Ticket(s): #
> LAYERATTRIBUTES many layers

- docs/user_manual/introduction/qgis_gui.rst
from at least 3.28 docs (refs #8853)
Goal:
Ticket(s): #
> Remove unavailable Edit submenus

- docs/user_manual/managing_data_source/opening_data.rst
> Sublayer selection checkboxes added

- docs/training_manual/rasters/data_manipulation.rst
Clarified the wording in the exercise
> Clarify wording in virtual raster training exercise

- docs/user_manual/processing_algs/qgis/rastertools.rst
Goal:
See https://github.com/qgis/QGIS/pull/54321.
Ticket(s): #
> [processing] The "Generate XYZ tiles" algs have been ported to C++

- .github/workflows/builds.yml
- .github/workflows/doctest.yml
> Auto-cancel running builds on PRs when pushing a new commit

- docs/user_manual/processing_algs/gdal/rasteranalysis.rst
Goal:
Removes the NO_MASK parameter.
Fixes https://github.com/qgis/QGIS-Documentation/issues/8871.
Ticket(s): #
> [processing] Fill NoData: remove the NO_MASK parameter (Fix #8871)

- docs/user_manual/introduction/general_tools.rst
At the beginning this was about fixing some confusing terms used in the docs and emphasize that this tool is not only about vector (regardless of its name). This has become a "deeper refactoring", describing the GUI from bottom to top, given that the interface as well as available tools of this dialog depend on the choice you made at the bottom of the dialog.
Also expands a bit more on how identification works since the process depends on the selected tool/format.
Note: This PR covers the interactive tools and the results panel behavior. Specific results outputs, dependent on data formats, as discussed in #8764, are not touched.
> Updating the "Identify features" tool

- conf.py
> Say Bye to 3.28, marking it as outdated

- .github/workflows/pofiles.yml
- .github/workflows/pull_minimized_translations.yml
- .github/workflows/translation_statistics.yml
- Makefile
- docker-world.sh
- docs_conf.yml
- release_process.md
- scripts/fix_versions.sh
> Make 3.34 the new LTR

- .github/workflows/pofiles.yml
- .github/workflows/pull_minimized_translations.yml
- .github/workflows/translation_statistics.yml
- docs_conf.yml
- release_process.md
- scripts/fix_versions.sh
> Prepare branch for releasing 3.34 as LTR

- docs/user_manual/working_with_mesh/mesh.rst
> Fix wrong indentation

- docs/user_manual/working_with_vector/vector_properties.rst
Fow example == For example
:guilabel'Form == :guilabel:'Form
-->
Ticket(s): #
-->
--->
> Corrected two small typo's

- docs/user_manual/processing/scripts.rst
Closes: https://github.com/qgis/QGIS-Documentation/issues/8905
> scripts: Document DATE and TIME

- scripts/minimize_translation.sh
taking into account "notranslate"-tagged strings on Transifex for (now) reusing source string for translation, when appropriate. This is necessary to get meaningful and correct translation progress stats displayed at the top of each page.
Goal:
Ticket(s): #
> Consolidate script to pull translations

- .gitignore
Some new files added to .gitignore as a support for working on the docs on NixOS. 
@timlinux
> Add new files and update .gitignore

- docs/user_manual/working_with_vector/vector_properties.rst
fixes #8128 
I've left out details about advanced settings to avoid potential confusion for average users.
> Relation Reference - limit number of entries

- docs/user_manual/processing/parameters.rst
follow-up 4131324aa2
Goal:
Ticket(s): #
> Various adjustments to algs table

- docs/user_manual/managing_data_source/opening_data.rst
>  Add Prefix to ArcGIS REST Servers

- .gitignore
- docs/user_manual/working_with_vector/vector_properties.rst
> Widget stretch

- docs/pyqgis_developer_cookbook/intro.rst
Affects https://docs.qgis.org/3.34/fr/docs/pyqgis_developer_cookbook/intro.html#the-code-parameter
Goal: readability
> fix intro.rst typo

- .github/workflows/builds.yml
- .github/workflows/doctest.yml
- .github/workflows/pofiles.yml
- .github/workflows/pull_minimized_translations.yml
- .github/workflows/translation_statistics.yml
manual backport of #8991 and #8993
> [Backport 3.34] Update actions dependencies

- docs/user_manual/working_with_vector/vector_properties.rst
> Fixed Interval added to graduated render

- docs/user_manual/processing_algs/qgis/rastertools.rst
refs https://github.com/qgis/QGIS/issues/57096#issuecomment-2044612464
> Detail how to be able to fill options for input layers in the "raster aligns" algorithm

- docs/user_manual/working_with_vector/vector_properties.rst
> [3.34] Widget stretch

- docs/user_manual/processing/batch.rst
> Add Toggle advanced mode to batch interface

- docs/user_manual/working_with_vector/attribute_table.rst
mainly adding information on editing tools, detail some options, remove out of context description, toc and rendering fixes...
> Various updates to vector attribute table contents

- docs/user_manual/working_with_vector/attribute_table.rst
Fixes #8926
Goal:
Ticket(s): #
> Explaining how to create and edit virtual fields

- docs/pyqgis_developer_cookbook/network_analysis.rst
Add missing strategy call
Fixes https://github.com/qgis/QGIS-Documentation/issues/9010
> Fix crashing test

- docs/user_manual/expressions/expression.rst
(trying to address a recurring request)
Also replace some $-based functions with corresponding variable
Goal:
Ticket(s): #
> Add expressions to select features based on spatial relationship with another layer 

- docs/user_manual/map_views/elevation_profile.rst
Fixes #8293
Goal:
Ticket(s): #
> Explore the export options of the profile tool

- docs/user_manual/print_composer/composer_items/layout_elevation_profile.rst
Fixes #8296
Goal:
Ticket(s): #
> Add unit properties of layout elevation profile item

- docs/training_manual/rasters/terrain_analysis.rst
Helps clarify, and avoids people keeping an inappropriate format
Fixes #9069
Goal:
Ticket(s): #
> Add file format to algorithm outputs

- docs/user_manual/introduction/general_tools.rst
> Show broken layers only added to Filter Legend

- docs/user_manual/introduction/qgis_configuration.rst
refs  "Additional context of https://github.com/qgis/QGIS/issues/57262#issue-2266782531"
Goal:
Ticket(s): #
> Make new profile button more obvious

- docs/user_manual/print_composer/composer_items/composer_map.rst
> Elevation range - print layout

- docs/training_manual/forestry/forest_maps.rst
- docs/training_manual/forestry/systematic_sampling.rst
Fixes #9112
Goal:
Ticket(s): #
> Replace @rownum with @row_number variable

- conf.py
There is no need to look for source files in this repository.
> conf: Ignore .github directory

- .gitignore
- Makefile
- docs/pyqgis_developer_cookbook/canvas.rst
- docs/pyqgis_developer_cookbook/crs.rst
- docs/pyqgis_developer_cookbook/expressions.rst
- docs/pyqgis_developer_cookbook/geometry.rst
- docs/pyqgis_developer_cookbook/loadlayer.rst
- docs/pyqgis_developer_cookbook/raster.rst
- docs/pyqgis_developer_cookbook/vector.rst
- doctest.dockerfile
Goal: Trying to fix gh doctests
> Fixing doctests in gh workflow

- docs/user_manual/expressions/functions_list.rst
refs #8999, #8979 and qgis/QGIS#57302
> Add more expression variables

- docs/user_manual/working_with_3d_tiles/3d_tiles.rst
- docs/user_manual/working_with_mesh/mesh.rst
- docs/user_manual/working_with_point_clouds/point_clouds.rst
- docs/user_manual/working_with_raster/raster_properties.rst
- docs/user_manual/working_with_vector/vector_properties.rst
- docs/user_manual/working_with_vector_tiles/vector_tiles.rst
> Custom properties added to the Information tab - "working with..." chapters

- docs/user_manual/introduction/qgis_configuration.rst
refs https://github.com/qgis/QGIS/issues/58253#issuecomment-2254154107
@agiudiceandrea @MatzFan hoping that I understand that (I agree with you) weird behavior...
> Describe behavior of user-agent

- conf.py
- docs/pyqgis_developer_cookbook/vector.rst
> Backport fixes to build 3.34 docs

- docs/user_manual/processing/parameters.rst
- docs/user_manual/processing_algs/qgis/rastertools.rst
Should fix build errors at https://github.com/qgis/QGIS-Documentation/actions/runs/10572711995/job/29290883240#step:7:677-684
Goal:
Ticket(s): #
> Fix references to processing classes moved to core

- docs/user_manual/introduction/qgis_configuration.rst
> Add missing space to display user-agent example

- docs/developers_guide/git.rst
In order to cleanup the CONTRIBUTING.md of Qgis project, some file contents were remove and the `git.rst` of this repo updated.
Linked to https://github.com/qgis/QGIS/pull/58472
> Add proper formatting section and add commit convention link

- docs/user_manual/working_with_mesh/mesh.rst
fixes #9086 
I added an additional explanation for activating vector properties, as it took me a few minutes to figure out where to activate it.
> Wind barb rendering for mesh vector datasets

- docs/training_manual/foreword/foreword.rst
> fix: We use ReadTheDocs sphinx theme

- conf.py
Fixes #9234
Goal:
Ticket(s): #
> fix: Use correct URL for translation process

- docs/user_manual/processing_algs/qgis/filetools.rst
> Add new algorithm "Processing open url or file"

- docs/user_manual/auth_system/auth_overview.rst
Describe the QGIS_AUTH_DB_URI env variable and expand the documentation of the new credentials storage abstraction.
> Describe QGIS_AUTH_DB_URI after implementation of QEP #248

- docs/user_manual/working_with_vector/vector_properties.rst
> Data defined control over heatmap radius and maximum value

- docs/user_manual/processing_algs/qgis/vectoroverlay.rst
Goal:
https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/qgis/vectoroverlay.html#extract-clip-by-extent
Ticket(s): #
> Fix "Extract/clip by extent" algorithm

- docs/user_manual/style_library/label_settings.rst
> Maximum distance setting for point labels

- docs/user_manual/managing_data_source/opening_data.rst
> Move open options description close to where they show

- docs/server_manual/getting_started.rst
Less readable for curious users but would avoid pasting a broken link due to spaces in it (refs https://lists.osgeo.org/pipermail/qgis-user/2024-October/054889.html)
Goal:
Ticket(s): #
> One liner command for URL in browser

- docs/user_manual/print_composer/create_output.rst
> Print composer: PDF file size - tip

- release_process.md
Due to the QGIS website refactoring and some changes in the way the PyQGIS docs is generated, we need to update some details
Goal:
Ticket(s): #
> Update instructions for releasing a new docs version

- .github/dependabot.yml
- docs_conf.yml
- substitutions.txt
Prepare master branch for release 3.40
Goal:
Ticket(s): #
> Prepare master branch for release 3.40

- release_process.md
> Clarify when the new branch is created and its updates

- docs_conf.yml
> Release 3.34 version list update

- release_process.md
> Also update docs URL in the new branch's Readme

- docs/user_manual/preamble/preamble.rst
> Update latest "released" docs version

- docs/user_manual/processing_algs/qgis/vectorgeneral.rst
- docs/user_manual/processing_algs/qgis/vectorgeometry.rst
Fixes #9165
@lbartoletti as mentioned in the issue report, it is unclear to me what you wanted to [get documented](https://github.com/qgis/QGIS/pull/58046#pullrequestreview-2168018924). Feel free to adjust/update/fix/clarify....
> No geometry validity checks for some algorithms

- docs/user_manual/processing_algs/qgis/index.rst
- docs/user_manual/processing_algs/qgis/vectorcoverage.rst
- docs/user_manual/processing_algs/qgis/vectorgeometry.rst
> Add Vector coverage algorithms

- docker-run.sh
PS: This is the kind of oversight #9323 is meant to avoid
> Fix docker run name for 3.40

- docs/developers_guide/git.rst
Captures https://github.com/qgis/QGIS-Enhancement-Proposals/issues/304 and other existing procedures
[X] Backport to LTR documentation is requested
> developers_guide/git.rst: add a 'Pull Requests merge criteria' section

- docs/training_manual/vector_analysis/spatial_statistics.rst
> Clarify settings to use in matrix distance dialog

- docs/user_manual/processing_algs/qgis/vectorgeometry.rst
> "buffer" alg: Do not direct to deprecated "Variable distance buffer" algorithm

- docs/user_manual/introduction/qgis_configuration.rst
mainly picked in the buffer alg description and remove GEOS 3.3 (QGIS requires 3.9 minimum)
> Detail Offset curve tool options

- docs/user_manual/managing_data_source/opening_data.rst
> Credential options for OGR vector and GDAL raster

- doctest.dockerfile
> Use correct container for 3.40

- docs/training_manual/qgis_plugins/plugin_examples.rst
and merge QuickOSM entries as a single in the TOC
The idea is to avoid listing twice QuickOSM in the TOC
> Add sub level item in QuickOSM lesson

- docs/developers_guide/git.rst
depends on https://github.com/qgis/QGIS/pull/59522
> Adapt developer guides with pre-commit use

- docs/user_manual/processing_algs/gdal/vectormiscellaneous.rst
refs https://github.com/qgis/QGIS/pull/59581
Goal:
Ticket(s): #
> Remove obsolete description

- docs/pyqgis_developer_cookbook/processing.rst
According to the directory structure, imports seems broken.
Small fix, parenthesis are not needed when not parent class are involved.
> Fix import in the Processing provider example

- docs/user_manual/processing_algs/gdal/vectorconversion.rst
- docs/user_manual/processing_algs/gdal/vectormiscellaneous.rst
- docs/user_manual/processing_algs/qgis/cartography.rst
- docs/user_manual/processing_algs/qgis/rastertools.rst
- docs/user_manual/processing_algs/qgis/vectoranalysis.rst
- docs/user_manual/processing_algs/qgis/vectorcreation.rst
- docs/user_manual/processing_algs/qgis/vectorgeneral.rst
- docs/user_manual/processing_algs/qgis/vectorgeometry.rst
> Remove Optional flag from algs' Boolean parameters

- docs/user_manual/processing_algs/gdal/vectormiscellaneous.rst
Fixes #9307
Also completes description of some parameters
Goal:
Ticket(s): #
> Add makevalid parameter to GDAL "Export to PostgreSQL" algorithms

- docs/index.rst
- docs/user_manual/grass_integration/grass_integration.rst
- docs/user_manual/managing_data_source/opening_data.rst
- docs/user_manual/preamble/contributors.rst
- docs/user_manual/working_with_raster/raster_properties.rst
- docs/user_manual/working_with_vector/vector_properties.rst
> Fix references to substitution

- docs/user_manual/style_library/label_settings.rst
Resurrects #9249, addressing comments on the Qt docs link
Fixes https://github.com/qgis/QGIS-Documentation/issues/9245
> Restructure html label section and add word-spacing

- docs/user_manual/processing_algs/qgis/vectorgeometry.rst
Fixes #6623
Goal:
Ticket(s): #
> Mention first_value and last_value functions in Aggregate algorithm

- docs/user_manual/introduction/qgis_configuration.rst
Fixes #9252
Goal:
Ticket(s): #
> Mention that angle are concerned by Ellipsoid selection

- scripts/load_tx_stats.py
> Adjust variable name

- docs/user_manual/style_library/symbol_selector.rst
Fixes https://github.com/qgis/QGIS-Documentation/issues/9191
Goal:
Ticket(s): #
> Add buffer to marker symbols

- docs/user_manual/introduction/general_tools.rst
> Vertical Datum in Identify results

- docs/user_manual/introduction/browser.rst
and a few more items for Oracle
Completes #9543 and fixes #9206
Goal:
Ticket(s): #
> Mention "Duplicate connection" entry for database

- docs/user_manual/map_views/elevation_profile.rst
fixes #9224 
Goal:
Ticket(s): #
> Elevation Profile Name

- docs/user_manual/working_with_mesh/mesh.rst
> Fix sentences

- docs/user_manual/working_with_mesh/mesh.rst
Fixes #9533 
Goal:
Ticket(s): #
> Mesh editing delaunay refinement

- docs/user_manual/working_with_vector/vector_properties.rst
Fixes #8004
Goal:
Ticket(s): #
> Add audio and video types to the form attachment widget

- docs/user_manual/processing_algs/qgis/rasteranalysis.rst
fixes #9371 
Goal:
Ticket(s): #
> Processing alg - Raster min/max

- docs/user_manual/processing/configuration.rst
> fix(user_manual/processing/configuration): typo

- docs/gentle_gis_introduction/introducing_gis.rst
- e.**g.,**
- GIS Software le**ts**...
- ~Raster data **is** stored~
- to **the** environment...
- these type**s**...
Goal:
Ticket(s): #
> docs: fix spelling grammar and punctuation in introducing_gis.rst

- .github/workflows/auto-label.yml
- .github/workflows/backport.yml
- .github/workflows/builds.yml
- .github/workflows/doctest.yml
- .github/workflows/pofiles.yml
- .github/workflows/pull_minimized_translations.yml
- .github/workflows/stale.yml
- .github/workflows/translation_statistics.yml
backports #9604, #9603, #9601
Goal:
Ticket(s): #
> Backport dependencies

- themes/rtd_qgis/breadcrumbs.html
- themes/rtd_qgis/static/css/qgis_docs.css
explaining how people could contribute.
I read somewhere that people didn't know they could contribute to the project , reason why they didn't. Let's make it more obvious.
Goal:
Ticket(s): #
> Add a button at the top of the pages to reach the "Get involved" page

- docs/user_manual/introduction/qgis_configuration.rst
> Add link to Elevation Controller section

- .github/workflows/auto-label.yml
- .github/workflows/backport.yml
- .github/workflows/builds.yml
- .github/workflows/doctest.yml
- .github/workflows/pofiles.yml
- .github/workflows/pull_minimized_translations.yml
- .github/workflows/stale.yml
- .github/workflows/translation_statistics.yml
(cherry picked from commit d79d697bf432e05838ec9f2454c20401e22dfe33)
backports #9609
Goal:
Ticket(s): #
> [GH Actions] Add recommended configuration to harden the runner

- docs/user_manual/style_library/symbol_selector.rst
follow-up c336a4e
Goal:
Ticket(s): #
> Also mention "Extent buffer" in symbols properties

- .github/workflows/pofiles.yml
- conf.py
- scripts/create_transifex_resources.sh
- themes/rtd_qgis/breadcrumbs.html
- themes/rtd_qgis/layout.html
making every user-facing strings in the docs really translatable
Goal:
Ticket(s): #
> Make strings in the themes folder also translatable

- .github/workflows/pofiles.yml
> Update po files also when template files are updated

- docs/developers_guide/codingstandards.rst
> Fix Hyperlink formatting

- docs/user_manual/map_views/map_view.rst
fixes #9071 
Goal:
Ticket(s): #
> Elevation Filter Updates

- docs/documentation_guidelines/cookbook_guidelines.rst
- useful~l~ to use...
see:
https://www.merriam-webster.com/dictionary/usefull
Goal:
Ticket(s): #
> Fix spelling of the word useful in cookbook_guidelines rst

- docs/user_manual/working_with_vector/editing_geometry_attributes.rst
Fixes #9274 
Is there a need for a screencast?
Goal:
Ticket(s): #
> Advanced Digitizing - Construction Guides

- docs/gentle_gis_introduction/map_production.rst
- **as** a little box ...
- real wo**rld**
Goal:
Ticket(s): #
> Fix spelling in map_production rst

- docs/user_manual/processing_algs/qgis/database.rst
refs https://github.com/qgis/QGIS/pull/60337
Goal:
Ticket(s): #
> Update parameter in SpatiaLite Execute SQL algorithm

- docs/user_manual/style_library/label_settings.rst
and kind of mention "over point" option (fixes #9087)
Goal:
Ticket(s): #
> Clarify cartographic placement for labels using DD button

- docs/user_manual/processing_algs/gdal/rasteranalysis.rst
refs https://github.com/qgis/QGIS/pull/60607
> Update the GDAL Slope and Proximity algs parameters

- .gitignore
> Ignore _build folder

- conf.py
Translations from the Transifex
> conf.py changes

- docs/user_manual/processing_algs/qgis/vectorgeneral.rst
Fixes #9455
Goal:
Ticket(s): #
> Add parameter for adding source layer info to "Merge vector layers" algorithm

- redirects.txt
> Add missing files to redirect

- Makefile
- docker-world.sh
- docs_conf.yml
> Update list of 3.40 languages

- .tx/config
> Add configuration file for Transifex

- docs/user_manual/processing_algs/gdal/vectorgeoprocessing.rst
> Fix text indentation

- docs/server_manual/getting_started.rst
> fix(server_manual): add "a2enmod rewrite" in Apache section

- docs/user_manual/managing_data_source/create_layers.rst
- docs/user_manual/print_composer/composer_items/composer_tables.rst
> Rollback some typo fixes

- .github/workflows/auto-label.yml
- .github/workflows/backport.yml
- .github/workflows/builds.yml
- .github/workflows/doctest.yml
- .github/workflows/pofiles.yml
- .github/workflows/pull_minimized_translations.yml
- .github/workflows/stale.yml
- .github/workflows/translation_statistics.yml
- docs/developers_guide/codingstandards.rst
- docs/documentation_guidelines/do_translations.rst
- docs/server_manual/getting_started.rst
- docs/user_manual/managing_data_source/create_layers.rst
- docs/user_manual/map_views/elevation_profile.rst
- docs/user_manual/plugins/plugins.rst
- docs/user_manual/print_composer/composer_items/composer_tables.rst
- docs/user_manual/processing/toolbox.rst
- docs/user_manual/processing_algs/qgis/vectortable.rst
- docs/user_manual/style_library/symbol_selector.rst
- docs/user_manual/working_with_mesh/mesh.rst
- docs/user_manual/working_with_vector/vector_properties.rst
> [3.40] Backport recent dependencies and typo fixes

- README.md
- release_process.md
and syntax highlight to code samples (adds coloring in the Readme file, either in github preview or local editing).
Goal:
Ticket(s): #
> Add details on transifex-client activation

- docs/user_manual/processing_algs/qgis/mesh.rst
> Surface to polygon - mesh alg

- docs/documentation_guidelines/writing.rst
- docs/user_manual/map_views/elevation_profile.rst
see #9726 comments
Goal:
Ticket(s): #
> Small fixes: elevation profile and docs guidelines

- docs/user_manual/processing_algs/qgis/vectortable.rst
Fixes #9746
Goal:
Ticket(s): #
> Fix name and anchor for the "Add x/y fields to layer" algorithm

- .github/workflows/builds.yml
- .github/workflows/doctest.yml
- .github/workflows/pofiles.yml
- .github/workflows/translation_statistics.yml
backports #9756 #9755 #9754 
Goal:
Ticket(s): #
> Backports dependencies updates

- docs/user_manual/processing_algs/qgis/networkanalysis.rst
and some missing default values
Fixes #9029
Goal:
Ticket(s): #
> Add "maximum point distance from network" parameter

- docs/user_manual/processing_algs/qgis/plots.rst
> Plots - advanced parameters

- docs/user_manual/processing/modeler.rst
line 640:  Edit..  =  Edit…
Goal: Create good documentation
> Missing period, replaced by ellipsis

- docs/server_manual/getting_started.rst
Line 879 : mutiple -->> should be multiple
Goal: Making good documentation
> Corrected typo mutiple = multiple

- docs/user_manual/processing/configuration.rst
- docs/user_manual/processing_algs/gdal/index.rst
Fixes #9453
Goal:
Ticket(s): #
> Document built-in algorithm providers settings

- docs/user_manual/processing_algs/gdal/rasteranalysis.rst
- docs/user_manual/processing_algs/gdal/rasterconversion.rst
- docs/user_manual/processing_algs/gdal/rasterextraction.rst
- docs/user_manual/processing_algs/gdal/rastermiscellaneous.rst
- docs/user_manual/processing_algs/gdal/rasterprojections.rst
- docs/user_manual/processing_algs/gdal/vectorconversion.rst
- docs/user_manual/processing_algs/gdal/vectorgeoprocessing.rst
- docs/user_manual/processing_algs/gdal/vectormiscellaneous.rst
- docs/user_manual/processing_algs/qgis/interpolation.rst
- docs/user_manual/processing_algs/qgis/mesh.rst
- docs/user_manual/processing_algs/qgis/rasteranalysis.rst
- docs/user_manual/processing_algs/qgis/rastercreation.rst
- docs/user_manual/processing_algs/qgis/rasterterrainanalysis.rst
- docs/user_manual/processing_algs/qgis/rastertools.rst
Fixes #9802
I don't know if the note in parentheses is required, but we could let it until the next docs release...
Goal:
Ticket(s): #
> [Processing] Harmonize GDAL creation options parameter naming

- docs/user_manual/managing_data_source/opening_data.rst
Fixes #2556
Goal:
Ticket(s): #
> Add schema restriction option in Oracle DB connection

- docs/user_manual/processing_algs/qgis/vectoranalysis.rst
- docs/user_manual/processing_algs/qgis/vectorgeometry.rst
refs https://github.com/qgis/QGIS/pull/61622 and https://github.com/qgis/QGIS/pull/61584
Goal:
Ticket(s): #
> Fix "Check validity" and "Climb along line" algorithms ID

- docs/user_manual/processing_algs/gdal/rasteranalysis.rst
- docs/user_manual/processing_algs/gdal/rasterconversion.rst
- docs/user_manual/processing_algs/gdal/rasterextraction.rst
- docs/user_manual/processing_algs/gdal/rastermiscellaneous.rst
- docs/user_manual/processing_algs/gdal/rasterprojections.rst
- docs/user_manual/processing_algs/gdal/vectorgeoprocessing.rst
- docs/user_manual/processing_algs/gdal/vectormiscellaneous.rst
- docs/user_manual/processing_algs/qgis/mesh.rst
- docs/user_manual/processing_algs/qgis/vectorgeometry.rst
- docs/user_manual/processing_algs/qgis/vectoroverlay.rst
I wondered if I should just remove them but thought that stating that it is not set is a clearer and more informative. Opinions welcome.
> Harmonize the parameters default value when not set, using label in GUI

- docs/user_manual/processing_algs/qgis/rastercreation.rst
- docs/user_manual/processing_algs/qgis/vectorcreation.rst
Fixes #9844
Thanks @DiGro 
Goal:
Ticket(s): #
> Fix superfluous brackets

- docs/user_manual/processing_algs/gdal/rastermiscellaneous.rst
- docs/user_manual/processing_algs/gdal/rasterprojections.rst
- docs/user_manual/processing_algs/gdal/vectorconversion.rst
- docs/user_manual/processing_algs/gdal/vectorgeoprocessing.rst
Followup  #9804
Goal:
Ticket(s): #
> Update some more numerical parameters label

- docs/documentation_guidelines/first_contribution.rst
- docs/documentation_guidelines/writing.rst
There are a few changes GitHub made to the process, so let's adjust them.
Also add instructions for loading an image file to the docs.
May be helpful for upcoming community on-boarding days...
> Update the step-by-step contribution guide

- .github/workflows/auto-label.yml
- .github/workflows/backport.yml
- .github/workflows/builds.yml
- .github/workflows/doctest.yml
- .github/workflows/pofiles.yml
- .github/workflows/pull_minimized_translations.yml
- .github/workflows/stale.yml
- .github/workflows/translation_statistics.yml
> [Gh Actions] Update Harden runner

- conf.py
> Harmonize casing for PDF Document file name

- docs/user_manual/introduction/qgis_configuration.rst
- docs/user_manual/working_with_projections/working_with_projections.rst
fixes #4696?
Goal:
Ticket(s): #
> Fix wrong description when switching project CRS

- .tx/config
> Update config file to have references match 3.40 source files

- Makefile
- docker-world.sh
- docs_conf.yml
It is almost translated at 15%
Goal:
Ticket(s): #
> Allow to build documentation in Polish

- README.md
There was stil a command from the Pico editor included from previous solution. I removed it so now it makes sense.
Goal: make the instruction clear
Ticket(s): #9931
> Update README.md improve fix for macOS

- docs/user_manual/introduction/general_tools.rst
> add hint for smaller contextmenu on multiselect

- README.md
> Syntax highlight for code sample

- docs/user_manual/expressions/expression_help/img/images_list.json
- scripts/populate_expressions_list.py
Merge img et alg_img keys into a single entry for providing image file name
Goal:
Ticket(s): #
> Simplify process for adding image for expression function

- docs/user_manual/processing_algs/qgis/vectorcreation.rst
- docs/user_manual/processing_algs/qgis/vectorgeometry.rst
Goal: Document new fields added by processing algorithm
Ticket(s): #9847
> add info about added fields

- docs/user_manual/processing/batch.rst
fixes #9735  
Goal:
Ticket(s): #
> Batch - temporary layer

- docs/user_manual/processing/batch.rst
> Adjust button label

- docs/user_manual/processing_algs/qgis/vectoranalysis.rst
Adds method and reference to existing Kmeans alg description, as implemented in qgis/QGIS#61756
> Add method to Kmeans algorithm

- docs/user_manual/introduction/qgis_configuration.rst
> Add link to Processing Options dialog

- docs/user_manual/print_composer/composer_items/composer_tables.rst
fixes #9975
Goal:
Ticket(s): #
> Double-click opens layout fixed table editor dialog

- docs/user_manual/processing_algs/qgis/vectorgeometry.rst
> Documentation for special case in oriented minimum bounding box: singlepart point features

- docs/user_manual/working_with_vector/editing_geometry_attributes.rst
- docs/user_manual/working_with_vector/vector_properties.rst
fixes #9766
Goal:
Ticket(s): #
> Merge policies - vector properties

- docs/user_manual/managing_data_source/opening_data.rst
refs https://github.com/qgis/QGIS/pull/62624
> Detail more options in the MS SQL connection dialog

- docs/user_manual/introduction/browser.rst
- docs/user_manual/managing_data_source/create_layers.rst
- docs/user_manual/managing_data_source/opening_data.rst
Fixes #9965 
Goal:
Ticket(s): #
> Add tip: Rename PostgreSQL table fields directly from the Browser Panel

- docs/user_manual/introduction/browser.rst
Fixes #9964 
Goal:
Ticket(s): #
> Add info about Move table to another schema for PostgreSQL

- docs/user_manual/processing_algs/qgis/database.rst
- docs/user_manual/processing_algs/qgis/interpolation.rst
- docs/user_manual/processing_algs/qgis/networkanalysis.rst
- docs/user_manual/processing_algs/qgis/vectoranalysis.rst
- docs/user_manual/processing_algs/qgis/vectorcreation.rst
- docs/user_manual/processing_algs/qgis/vectorgeometry.rst
- docs/user_manual/processing_algs/qgis/vectortable.rst
Refs unreported fixes like https://github.com/qgis/QGIS/pull/62629, https://github.com/qgis/QGIS/pull/62583, https://github.com/qgis/QGIS/pull/62437
> Add various details to Processing algorithms

- docs/user_manual/processing_algs/qgis/vectorgeometry.rst
> Move information on the singlepart point feature's bounding box to the right algorithm

- docs/user_manual/introduction/qgis_configuration.rst
> Mention how to keep units synced with project CRS unit

- docs/user_manual/introduction/qgis_configuration.rst
>  Fix indentation and placement of a .. note:: block

- docs/user_manual/processing_algs/qgis/rasterterrainanalysis.rst
> Add "Fill sinks (Wang & Liu)" Processing algorithm

- docs/documentation_guidelines/substitutions.rst
- substitutions.txt
> Add |layers| to displayed substitutions

- docs/user_manual/introduction/general_tools.rst
Fixes #10068 
Goal:
Ticket(s): #
> Add info about copy paste grouped style categories

- Makefile
- docker-world.sh
- docs_conf.yml
> Add Swedish to candidates for docs builds

- Makefile
- docker-world.sh
- docs_conf.yml
as they reach 100% of translation
Goal:
Ticket(s): #
> Allow to build documentation in Swedish

- README.md
i.e., what versions we do target for translation and how to use them.
Fixes #10110
Goal:
Ticket(s): #
> Clarify how the translation process works

- docs/user_manual/processing_algs/qgis/vectorselection.rst
Goal:
`qgis:extractbyattribute` -> `native:extractbyattribute`
`qgis:extractbyexpression` -> `native:extractbyexpression`
`qgis:extractbylocation` -> `native:extractbylocation`
`qgis:randomextract` -> `native:randomextract`
`qgis:selectbylocation` -> `native:selectbylocation`
Ticket(s): #
> Update algorithms' id in "Vector selection" qgis: -> native:

- locale/sv/LC_MESSAGES/sphinx.po
This is the for Sphinx part of the translation. Not part of the Transifex
> Adding Swedish sphinx.po

- transifex.yml
refs #10136 
Goal:
Ticket(s): #
> Move up to parent folder in order to catch sphinx.po files for Transifex

- docs/user_manual/working_with_vector/vector_properties.rst
The geometry widget from PR https://github.com/qgis/QGIS/pull/51863 was missing.
> Added information on geometry widget type

- docs/user_manual/processing_algs/qgis/checkgeometry.rst
> Check geometry: Dangle-end lines ---> Add explanation for added fields

- docs/user_manual/introduction/browser.rst
- docs/user_manual/introduction/project_files.rst
- docs/user_manual/managing_data_source/opening_data.rst
- docs/user_manual/processing/modeler.rst
> Backport 10176 to release 3.40

- docs/user_manual/expressions/expression.rst
Follow-up #10215 (and refs #10243)
Fix indentation issue and reword characters usage
> Adjust formatting and text for comments in expression

- docs/user_manual/expressions/functions_list.rst
refs https://github.com/qgis/QGIS/pull/63130
> Additional expression variables for plots and charts

- docs/user_manual/print_composer/composer_items/composer_legend.rst
Fixes #10178 
Goal:
Ticket(s): #
> Mention that layers can be excluded using the checkbox in the legend tab

- .github/workflows/auto-label.yml
- .github/workflows/backport.yml
- .github/workflows/builds.yml
- .github/workflows/doctest.yml
- .github/workflows/pofiles.yml
- .github/workflows/pull_minimized_translations.yml
- .github/workflows/stale.yml
- .github/workflows/translation_statistics.yml
> Backport dependabot changes

- docs/server_manual/getting_started.rst
Fixes #9968 
Goal:
Ticket(s): #
> Docs for set group wms data
